### ISSUE TITLE
Renaming an enum member results in invalid serialization and deserialization methods.

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/autorest.csharp#1004]
I have some auto-generated enums where I need to rename the members.  I am following the instructions here - https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#renaming-an-enum-member

I am able to rename the enum members just fine, but the result in invalid serialization methods that don't reflect the new enum member names.

Swagger:
https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2020-06-12/blob.json#L457

The new enum after I renamed the members:
https://github.com/seanmcc-msft/azure-sdk-for-net/blob/feature/storage/migrateBlobNewGenerator/sdk/storage/Azure.Storage.Blobs/src/Models/SkuName.cs

The invalid generated serialization/deserialization methods:
https://github.com/seanmcc-msft/azure-sdk-for-net/blob/feature/storage/migrateBlobNewGenerator/sdk/storage/Azure.Storage.Blobs/src/Generated/Models/SkuName.Serialization.cs

Note that the member rename I am trying to do is:
- SkuName.StandardL**RS** -> SkuName.StandardL**rs**
- SkuName.StandardG**RS** -> SkuName.StandardG**rs**
- SkuName.StandardZ**RS** -> SkuName.StandardZ**rs**
- SkuName.PremiumL**RS** -> SkuName.PremiumL**rs**

I have to make this change to comply with our existing public API contract.

I am also facing this issue with several other public enums.

**Comment by pakrym** [comment]
We talked offline and found that `[CodeGenMember(...)]` attributes that are required to rename enum members were missing.
