### ISSUE TITLE
Adding values to an enum do not show up in xxxExtensions methods

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/autorest.csharp#1012]
I added "None" as a value for `PublicAccessType`.  It is not appearing in `PublicAccessTypeExtensions.ToSerialString()` and `.ToPublicAccessType()`

Swagger:

https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2020-06-12/blob.json#L871

Hand-written enum:
https://github.com/seanmcc-msft/azure-sdk-for-net/blob/feature/storage/migrateBlobNewGenerator/sdk/storage/Azure.Storage.Blobs/src/Models/PublicAccessType.cs

Generated extensions class:
https://github.com/seanmcc-msft/azure-sdk-for-net/blob/feature/storage/migrateBlobNewGenerator/sdk/storage/Azure.Storage.Blobs/src/Generated/Models/PublicAccessType.Serialization.cs

Note that neither method includes support for the new value, "None".

**Comment by pakrym** [comment]
This is by design.
