### ISSUE TITLE
Generation Behavior Change in C#

### ISSUE THREAD

**Issue by chadlevn** [Azure/autorest.csharp#1035]
After updating to 3.0.6373 overall code generation behavior in C# is vastly different. We now only see a single Client file generated and it is internal instead of public. Our Models now also include .Serialization files and the csproj is updated to use Azure.Core.

```
autorest --v3 --input-file={folder}/swagger.json --output-folder={folder} --csharp --namespace=API.Client --add-credentials --override-client-name=APIClient --sync-methods=all --skip-csproj
```

**Expected behavior**
Previously when generating it would build a code-model-v1 file, an interface with a public implementation and an extensions file. I would like to have it generate a public client that can then be packed and used for deployment.

**Comment by ShivangiReja** [comment]
Hi @chadlevn, we’ve recently switched the default generator to the new version V3. [Here](https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#default-autorest---csharp-generator-change) we mentioned some side effects.

If you want the previous behaviour, you can add `--legacy` to the command line.

**Comment by ShivangiReja** [comment]
Hi @chadlevn, we’ve recently switched the default generator to the new version V3. [Here](https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#default-autorest---csharp-generator-change) we mentioned some side effects.

If you want the previous behaviour, you can add `--legacy` to the command line or if you want to use the updated version and would like to generate public client you can pass `save-inputs: true` to the command line.

**Comment by ShivangiReja** [comment]
Hi @chadlevn, we’ve recently switched the default generator to the new version V3. [Here](https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#default-autorest---csharp-generator-change) we mentioned some side effects.

If you want the previous behaviour, you can add `--legacy` to the command line or if you want to use the updated version and would like to generate public client you can pass `public-clients: true` to the command line.

**Comment by chadlevn** [comment]
That's exactly what I needed, thank you!
