### ISSUE TITLE
Remove extra method generated by "x-ms-pageable" custom nextlink operation

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#1056]
For example we have [this](https://github.com/Azure/autorest.testserver/blob/master/swagger/paging.json#L532-L573) customize next link operation `NextFragment` defined in the swagger. It generates [NextFragment()](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/paging/Generated/PagingRestClient.cs#L1113) operation which is correct but it also generates [NextFragmentNextPage()](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/paging/Generated/PagingRestClient.cs#L2200) operation which I think is not needed. We can consider removing it if there is no usecase of this extra operation.

**Comment by AlexanderSher** [comment]
Fixed by https://github.com/Azure/autorest.csharp/pull/1303
