### ISSUE TITLE
Generating csharp client: ´ClientDiagnostics´ is inaccessible due to its protection level

### ISSUE THREAD

**Issue by KristofferStrube** [Azure/autorest.csharp#1071]
**Describe the bug**

I used this command:
```bash
- AutoRest --namespace=Elmah.Io.Client --add-credential --csharp --output-folder=Elmah.Io.Client --input-file=https://api.elmah.io:443/swagger/docs/v3
```
With following versions:
```bash
AutoRest code generation utility [cli version: 3.1.2; node: v14.15.5, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      'C:\Users\hhhha\.autorest\@autorest_core@3.0.6374\node_modules\@autorest\core\dist' (3.0.6374)
   Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210303.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.17.0->4.17.0)
```
It generated classes for my endpoints but had `ClientDiagnostics` as an argument for the constructor for each class.
It can't access this as it is defined as internal:
```csharp
internal sealed partial class ClientDiagnostics : DiagnosticScopeFactory
```
Other problems that I'm having (that might be unrelated) are that it uses the types `RawRequestUriBuilder` and `IUtf8JsonSerializable` in the generated code. I don't know which packages these should come from and I can't see any references for them

**Expected behavior**
It should generate code that can be built by adding references to the packages that are defined as being used in each of the generated classes. A helpful addition might be to define which versions of these packages need to be used.

**Additional context**
The input is in Swagger 2.0

**Comment by NelsonLamprecht** [comment]
Experienced same end result with a input file that is a version "openapi": "3.0.1"

**Comment by KristofferStrube** [comment]
hey, @NelsonLamprecht I also tried with OpenAPI 3.0 first but found that it is not fully supported yet.
Related Tweet: https://twitter.com/lmazuel/status/1367193999027572736?s=20

**Comment by NelsonLamprecht** [comment]
> hey, @NelsonLamprecht I also tried with OpenAPI 3.0 first but found that it is not fully supported yet.
> Related Tweet: https://twitter.com/lmazuel/status/1367193999027572736?s=20

Thank you @KristofferStrube  I was experimenting with both autorest and nswag and while I would prefer to use autorest, it looks like their may not be a plan to allow non azure consumers?: https://github.com/Azure/autorest.csharp/issues/1044

**Comment by NelsonLamprecht** [comment]
> > hey, @NelsonLamprecht I also tried with OpenAPI 3.0 first but found that it is not fully supported yet.
> > Related Tweet: https://twitter.com/lmazuel/status/1367193999027572736?s=20
> 
> Thank you @KristofferStrube I was experimenting with both autorest and nswag and while I would prefer to use autorest, it looks like their may not be a plan to allow non azure consumers?: #1044

Maybe the same thing which indicates they are working on it?: https://github.com/Azure/autorest.csharp/issues/960

**Comment by KristofferStrube** [comment]
@NelsonLamprecht interesting insight. 😀 Looking forward to hearing from the devs what their plans are.

**Comment by NelsonLamprecht** [comment]
> @NelsonLamprecht interesting insight. 😀 Looking forward to hearing from the devs what their plans are.

The answer is in: no plan for autorest outside the azure space: (https://github.com/Azure/autorest.csharp/issues/1044#issuecomment-797146304)
:(

**Comment by NelsonLamprecht** [comment]
> @NelsonLamprecht interesting insight. 😀 Looking forward to hearing from the devs what their plans are.

@KristofferStrube:
No plans for autorest usage outside the Azure ecosystem:
https://github.com/Azure/autorest.csharp/issues/1044#issuecomment-797146304

For me, I'm going to move to NSwag...

**Comment by ShivangiReja** [comment]
@NelsonLamprecht and @KristofferStrube:

> https://github.com/Azure/autorest.csharp/issues/1044#issuecomment-797146304

I meant we depend on Azure.Core and we don't have any plan to support Microsoft.Rest.ClientRuntime(non Azure) library.

>Confirming that this package is now only for consuming azure rest services and not any rest services?

You can use this package for non-azure services as well. For more details please add comment to [this](https://github.com/Azure/autorest.csharp/issues/1044#issuecomment-799643898).

**Comment by ShivangiReja** [comment]
@NelsonLamprecht and @KristofferStrube:

> https://github.com/Azure/autorest.csharp/issues/1044#issuecomment-797146304

I meant we depend on Azure.Core and we don't have any plan to support Microsoft.Rest.ClientRuntime(non Azure) library.

>Confirming that this package is now only for consuming azure rest services and not any rest services?

You can use this package to generate code for non-azure services as well. For more details please add comment to [this](https://github.com/Azure/autorest.csharp/issues/1044#issuecomment-799643898).

**Comment by esbenbach** [comment]
Any updates to this, im facing the same issue that it references ClientDiagnostics (which is internal). Pretty difficult to work around :(

**Comment by KristofferStrube** [comment]
@esbenbach I no longer have this issue after having updated to version 3 of Autorest. Have you tried that?

**Comment by esbenbach** [comment]
Running 3.1.4 and still have the same issue. Might be because i need to
target a newer net SDK. Currently targeting netstandard2, will try changing
that tomorrow.

**Comment by KristofferStrube** [comment]
@esbenbach you need to include the following in your project which the generator also creates:
```xml
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <IncludeGeneratorSharedCode>true</IncludeGeneratorSharedCode>
    <RestoreAdditionalProjectSources>https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20210401.4" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.11.0" />
  </ItemGroup>
```

**Comment by ShivangiReja** [comment]
@esbenbach [Here](https://github.com/ShivangiReja/AutorestCSharpConsoleApp) I created a console application using autorest c# V3 generator and [here](https://github.com/ShivangiReja/AutorestCSharpConsoleApp/blob/master/AutorestCSharpConsoleApp.csproj) is generated .csproj. Please take a look.

**Comment by esbenbach** [comment]
Apparently I was blind when merging in the changes to the csproj, I forgot to add the Autorest.CSharp package ref. It works now. Thanks a bunch!

**Comment by KristofferStrube** [comment]
I am closing this issue now as it was solved in the newest version of autorest.

**Comment by lobbo232** [comment]
@KristofferStrube  I am getting this issue again on the latest version of AutoRest using Azure.Core v1.18.0.
The generated csproj already has the property group and item group config you posted above.

**Comment by KristofferStrube** [comment]
@lobbo232 you might need a newer version of the specified packages. Try to update to the newest for all of these.

**Comment by lobbo232** [comment]
Thanks, this worked for me. 
For the record / anyone else who needs help;
Azure.Core: 1.19.0
Azure.Identity: 1.4.1
Microsoft.Azure.AutoRest.CSharp: 3.0.0-beta.20210604.3

@KristofferStrube Now that is resolved, it's highlighted a second issue. The generated code is resulting in two cases in a switch statement with the same label value of '200'. Is this issue raised anywhere else? I haven't been able to find it.
![image](https://user-images.githubusercontent.com/17614851/132339030-5f773c6d-71d9-4f49-b376-a06f17e68867.png)

**Comment by KristofferStrube** [comment]
I would think that this is because the OpenAPI definition that you build from has two return types for the same status code response. That is not allowed.

**Comment by KotanaSai21** [comment]
I'm facing same issue and getting two switch cases with same label. Checked my swagger json and didn't find two return types.

Figured out the switch cases is being generated from this code and removing below API call everything works fine.

```
      "/v1.0/myorg/groups/{groupId}/reports/{reportId}/exports/{exportId}/file": {
            "get": {
                "tags": [
                    "Reports"
                ],
                "summary": "Returns the file from the [Export to File In Group](/rest/api/power-bi/reports/export-to-file-in-group) job for the specified report from the specified workspace.",
                "description": "\n## Permissions\n\nThis API call can be called by a service principal profile. For more information see: [Service principal profiles in Power BI Embedded](/power-bi/developer/embedded/embed-multi-tenancy).\n\n## Required Scope\n\nReport.ReadWrite.All or Report.Read.All\n<br><br>",
                "operationId": "Reports_GetFileOfExportToFileInGroup",
                "consumes": [],
                "produces": [
                    "application/*",
                    "image/*",
                    "text/csv",
                    "text/xml",
                    "multipart/related"
                ],
                "parameters": [
                    {
                        "name": "groupId",
                        "in": "path",
                        "required": true,
                        "description": "The workspace ID",
                        "type": "string",
                        "format": "uuid"
                    },
                    {
                        "name": "reportId",
                        "in": "path",
                        "description": "The report ID",
                        "required": true,
                        "type": "string",
                        "format": "uuid"
                    },
                    {
                        "name": "exportId",
                        "in": "path",
                        "required": true,
                        "description": "The export ID",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "schema": {
                            "type": "file"
                        },
                        "description": "The exported file"
                    }
                },
                "deprecated": false
            }
        },
```

Not sure what we need to modify in swagger json in order to eliminate the duplicate switch cases
