### ISSUE TITLE
React to Operation<T> pattern change

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#1088]
There is a chance that a non-generic Operation class would be added to Azure.Core to represent operations without a return value.

We should react to it in the generator and move away from using Operation<Response> as a base type.
 https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Output/Models/Requests/LongRunningOperation.cs#L56

https://github.com/Azure/azure-sdk-for-net/pull/19607

*NOTE* This has a public API impact and should be done sooner than later.

@chamons

**Comment by pakrym** [comment]
`sdk/core/Azure.Core/src/Shared/Operation.cs ` should be removed when this is done.

**Comment by m-nash** [comment]
[This PR](https://github.com/Azure/autorest.csharp/pull/1203) should take care of the autorest side of the changes, we still need to remove the [Operation class from azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/Operation.cs) and then this issue can be closed
