### ISSUE TITLE
Generated ClientOptions fails static analyzer

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1089]
The generated `ContainerRegistryClientOptions` type causes the following error from one of our .NET static analyzers:

> AZC0009	ClientOptions constructors should take a ServiceVersion as their first parameter.  Default constructor should be overloaded to provide ServiceVersion.	

The generated file is as follows:
**ContainerRegistryClientOptions.cs**
```C#
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Azure.Containers.ContainerRegistry
{
    /// <summary> Client options for ContainerRegistryClient. </summary>
    public partial class ContainerRegistryClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V2019_08_15_preview;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "2019-08-15-preview". </summary>
            V2019_08_15_preview = 1,
        }
    }
}

```

**Comment by chamons** [comment]
Hey @annelo-msft  - Was this data plane or LLC?

Could you point me to the swagger and/or project?

I'm seeing this working for [LLC](https://github.com/Azure/autorest.csharp/blob/feature/v3/samples/Azure.AI.DocumentTranslation/Generated/AzureAIDocumentTranslationClientOptions.cs#L28) and [Data Plane](https://github.com/Azure/autorest.csharp/blob/feature/v3/samples/CognitiveServices.TextAnalytics/Generated/CognitiveServicesTextAnalyticsClientOptions.cs#L27).

**Comment by chamons** [comment]
It has been over 2 weeks without the needed feedback. 

Please reopen with details if this is still an issue.
