### ISSUE TITLE
Incorporate new autorest build to address transient pipeline failures

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1092]
This issue tracks resolution of a [transient failure in autorest](https://github.com/Azure/autorest/issues/3968).

We'll need to move the CSharp code generator to the new autorest build to take advantage of that modification.

**Comment by annelo-msft** [comment]
@chamons FYI

**Comment by chamons** [comment]
Hey @annelo-msft - We just bumped [here](https://github.com/Azure/autorest.csharp/commit/be0c50dbd91a7ae7bdcd85c347f0a1d0af3c474c), does that resolve this?

**Comment by chamons** [comment]
Given that it's been a month after our bump, I'm going to assume this is fixed. Please reopen with an explanation if not.
