### ISSUE TITLE
autorest v3 is not generating as expected.

### ISSUE THREAD

**Issue by yifan-zhou922** [Azure/autorest.csharp#1094]
Hi, I am trying using autorest v3 to generate csharp SDK. However autorest v3 does not generate the expected files.

This is the command line I used.
![image](https://user-images.githubusercontent.com/78060542/112085143-f11d1d00-8bc4-11eb-8934-deece01e1838.png)

The left side is the files generated using v3 and the right side is the files generated using v2. It seems that autorest@v3 only generates parts of the files.
![image](https://user-images.githubusercontent.com/78060542/112085347-5244f080-8bc5-11eb-92de-0e5890ff815e.png)

Many thanks in advance.

**Comment by yifan-zhou922** [comment]
Hi, any updates for how to solve this issue? Many thanks.

**Comment by chamons** [comment]
Hey @yifan-zhou922 - Those files match the expectations of the V3 generator. Can you attach your csproj, or at least what dependencies you are pulling in. Are you pulling in a new enough Azure.Core?

Having a sample project would be exceptionally helpful here.

**Comment by yifan-zhou922** [comment]
Hi, many thanks for your help. Colleagues from other team will take over the work from my side. The issue can be closed.
