### ISSUE TITLE
Low Level Client Feedback

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1104]
This is the collected feedback from initial APIViews on LLC code.

- [x] Generated a ServiceVersion enum for apiVersion instead of a string param
- [x] Update visibility on CreateFooRequest to `protected`
- [x] `RequestContent body` -> `RequestContent requestBody`
- [x] Generate required enums outside of Models namespace?
- [x] `protected HttpPipeline Pipeline`

**Comment by ellismg** [comment]
> Generate required enums outside of Models namespace?

Would it be possible to not generate the type and instead just use something like `string` or `int` (i.e. the backing type for the enum) in places where it was required or does that break something in some subtle way?

**Comment by ellismg** [comment]
I think we also want to add a `protected` property of type `HttpPipeline` named `Pipeline` to ever client, based on @KrzysztofCwalina's prototype.

**Comment by chamons** [comment]
Not a bad idea, let me give that a spin...

**Comment by chamons** [comment]
4 are done in #1109 . The ServiceVersion one requires discussion, which I will start.

**Comment by chamons** [comment]
ServiceVersion work was completed awhile ago.
