### ISSUE TITLE
Generated code does not match the documentation how to use it

### ISSUE THREAD

**Issue by alrabe** [Azure/autorest.csharp#1155]
**Describe the issue or request**
In the docs you can read how to [Initializing Your Client](https://github.com/Azure/autorest.csharp/blob/feature/v3/docs/client/initializing.md).
`const string endpoint = "http://localhost:3000";
var client = new PetsClient(endpoint);`

But when I generate the code my client constructor looks totally different:
`public MyRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)`

This constructor seems pointless to me as it doesn't require an Uri but forces instead to provide some other parameters. I'm not sure if that's the case because the documentation is outdated or because I missing an option. 

**Describe your ideas for solutions**
Please update the documentation how to generate a client which can be instantiated like shown in the documentation. Or provide an example how to use this constructor.

**Comment by chamons** [comment]
Could you please post your autorest configuration (the readme or command line invocation).

Some options change the generated output.
