### ISSUE TITLE
[LLC] Top level client parameters should be generated as client ctor arguments

### ISSUE THREAD

**Issue by christothes** [Azure/autorest.csharp#1157]
Example : The [ledgerBaseUrl](https://github.com/Azure/azure-rest-api-specs/blob/92d7355cccd7d503234f6f7a9866a2d17c4d0df5/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/preview/0.1-preview/confidentialledger.json#L14) is generated as an argument to each service operation rather than a ctor argument.

**Comment by ellismg** [comment]
I think we already support this, the swagger just does not denote this is what is wanted.  

Can you try adding

```
"x-ms-parameter-location": "client",
```

To the the swagger for the `ledgerBaseUrl` and then re-generate the client?

**Comment by chamons** [comment]
@christothes - Could you take a look at ^ and let me know if this is still an issue?

**Comment by christothes** [comment]
Not an issue, you can close it out - thanks!
