### ISSUE TITLE
Default property values in OpenAPI 3

### ISSUE THREAD

**Issue by disophisis** [Azure/autorest.csharp#1168]
The OpenAPI Spec has an example spec containing a Cat schema which contains a property `huntingSkill`, and a default for that property:

```
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "discriminator": {
          "propertyName": "petType"
        },
        "properties": {
          "name": {
            "type": "string"
          },
          "petType": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "petType"
        ]
      },
      "Cat": {
        "description": "A representation of a cat. Note that `Cat` will be used as the discriminator value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "properties": {
              "huntingSkill": {
                "type": "string",
                "description": "The measured skill for hunting",
                "default": "lazy",
                "enum": [
                  "clueless",
                  "lazy",
                  "adventurous",
                  "aggressive"
                ]
              }
            },
            "required": [
              "huntingSkill"
            ]
          }
        ]
      },
      "Dog": {
        "description": "A representation of a dog. Note that `Dog` will be used as the discriminator value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "properties": {
              "packSize": {
                "type": "integer",
                "format": "int32",
                "description": "the size of the pack the dog is from",
                "default": 0,
                "minimum": 0
              }
            },
            "required": [
              "packSize"
            ]
          }
        ]
      }
    }
  }
```

In looking through issues on the OpenAPI spec github:
https://github.com/OAI/OpenAPI-Specification/issues/1543

The best I can glean is that this is intended to allow you to specify a default property value within the request, but I haven't actually seen it work with AutoRest.  The generated Cat request model shows as follows:

```
        internal Cat(string name, CatHuntingSkill huntingSkill) : base(name)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }

            HuntingSkill = huntingSkill;
            PetType = "Cat";
        }
```

I would expect the default would add a default value to the parameter in the constructor.  I have tinkered around with removing the requirement for that property and also adding an x-ms-enum extension that sets modelAsString to false just to see how the behavior changes, but haven't noticed a change.

Is `default` supported by AutoRest in this way?  Or am I misunderstanding the purpose of that property?

**Comment by chamons** [comment]
So my reading of the linked discussion is different. In particular:

> **default documents behavior when a field is absent. It does not cause the default value to be written in to an instance**

So, in your example, if you send a `Cat` without `huntingSkill` set at all (not null, no key of that name at all), the service is stating it will accept it as if you set the `lazy` enum value server side.

If I'm reading it correctly, setting a required default value property does not make a lot of sense. You are stating what happens if it is unset but then forbidding it from being unset.

If you want to use default then don't use required and let the json go to the server, which should honor default if done on their end correctly.

If I've misunderstood this, please feel free to reopen with additional details.
