### ISSUE TITLE
C# ClientOptions partial method Initialize

### ISSUE THREAD

**Issue by pavelprystinka** [Azure/autorest.csharp#1173]
**Is your feature request related to a problem? Please describe.**
We are using Autorest to generate C# client. It also generates Azure.Core.ClientOptions.
We need to have some functionality add to the constructor of ClientOptions (add headers to diagnostict)

**Describe the solution you'd like**
Class to have a partial method partial void Initialize(); (or similar name)
and constructor to call it

**Describe alternatives you've considered**
We can bypass this now by creating subclass of ClientOptions and providing that to the Client class. That will not work if we will use generated client.

Thanks!

**Comment by chamons** [comment]
This is a reasonable enough feature request, though I don't know of other places we use the Initialize pattern, it would save the creation of a derived class.

It'll get added to the backlog of features. If you want to take a stab at implementing it yourself, the relevant code lives [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ClientOptionsWriter.cs#L52).

**Comment by AlexanderSher** [comment]
ClientOptions support customization similar to other generated types:
```cs
[CodeGenClient("SomeClientOptions")]
public partial class SomeClientOptions
{
    public SomeClientOptions(ServiceVersion version = LatestVersion)
    {
        // Custom implementation
    }
}
```
