### ISSUE TITLE
Question : How to call RestClient with V3 ?  migrate v2 to v3

### ISSUE THREAD

**Issue by auriou** [Azure/autorest.csharp#1181]
hello 

I was using Autorest.csharp to generate my client libraries from an AzureDevOps pipeline. 

I am on version 2, I wanted to upgrade to version 3.

But I don't understand how to use the library, as the client classes are internal, and the client class constructor has techinqual objects like ClientDiagnostics, or HttpPipeline that I can create.

Do you have an example for calling autogenerated lib ?

Thx

**Comment by chamons** [comment]
The general pattern is to either use public-clients option or wrap them in a higher level "convenience layer", such as [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClient.cs).
