### ISSUE TITLE
Argument checks for required parameters are not generated when a new optional property is added to a type

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/autorest.csharp#1193]
**Describe the issue or request**
On adding a new optional property to a type, a new constructor is generated that does not check the non-nullability of the required existing parameters. This bypasses the checks in the existing constructor for those parameters and users are able to create objects with required properties not being set to non-null values.

Example - 
[`ServiceCounters`](https://github.com/Azure/azure-rest-api-specs/blob/b4276bd344f1df934a5b055f4faf2dc0aa627445/specification/search/data-plane/Azure.Search/preview/2020-06-30-Preview/searchservice.json#L9253) has 6 properties that were all required. The generated ctor for the type checks all args for non-nullability.
A new 7th property [`skillsetCount`](https://github.com/Azure/azure-rest-api-specs/blob/b4276bd344f1df934a5b055f4faf2dc0aa627445/specification/search/data-plane/Azure.Search/preview/2020-06-30-Preview/searchservice.json#L9285) has been added, and to maintain backwards compatibility it is not marked as required.
After this change, the generated code has a new ctor that takes 7 parameters and none of the arguments are checked in this method.

Below is the generated code (type has been renamed to `SearchServiceCounters`).

```
        internal SearchServiceCounters(SearchResourceCounter documentCounter, SearchResourceCounter indexCounter, SearchResourceCounter indexerCounter, SearchResourceCounter dataSourceCounter, SearchResourceCounter storageSizeCounter, SearchResourceCounter synonymMapCounter)
        {
            if (documentCounter == null)
            {
                throw new ArgumentNullException(nameof(documentCounter));
            }
            if (indexCounter == null)
            {
                throw new ArgumentNullException(nameof(indexCounter));
            }
            if (indexerCounter == null)
            {
                throw new ArgumentNullException(nameof(indexerCounter));
            }
            if (dataSourceCounter == null)
            {
                throw new ArgumentNullException(nameof(dataSourceCounter));
            }
            if (storageSizeCounter == null)
            {
                throw new ArgumentNullException(nameof(storageSizeCounter));
            }
            if (synonymMapCounter == null)
            {
                throw new ArgumentNullException(nameof(synonymMapCounter));
            }

            DocumentCounter = documentCounter;
            IndexCounter = indexCounter;
            IndexerCounter = indexerCounter;
            DataSourceCounter = dataSourceCounter;
            StorageSizeCounter = storageSizeCounter;
            SynonymMapCounter = synonymMapCounter;
        }

        internal SearchServiceCounters(SearchResourceCounter documentCounter, SearchResourceCounter indexCounter, SearchResourceCounter indexerCounter, SearchResourceCounter dataSourceCounter, SearchResourceCounter storageSizeCounter, SearchResourceCounter synonymMapCounter, SearchResourceCounter skillsetCounter)
        {
            DocumentCounter = documentCounter;
            IndexCounter = indexCounter;
            IndexerCounter = indexerCounter;
            DataSourceCounter = dataSourceCounter;
            StorageSizeCounter = storageSizeCounter;
            SynonymMapCounter = synonymMapCounter;
            SkillsetCounter = skillsetCounter;
        }
```

**Describe your ideas for solutions**
The new ctor should still have argument checks for the required parameters. Even better if it only sets the new property in its method body and forwards other args to the older ctor.
```
        internal SearchServiceCounters(SearchResourceCounter documentCounter, SearchResourceCounter indexCounter, SearchResourceCounter indexerCounter, SearchResourceCounter dataSourceCounter, SearchResourceCounter storageSizeCounter, SearchResourceCounter synonymMapCounter, SearchResourceCounter skillsetCounter) : this(documentCounter, indexCounter, indexerCounter, dataSourceCounter, storageSizeCounter, synonymMapCounter)
        {
            SkillsetCounter = skillsetCounter;
        }
```

**Comment by Mohit-Chakraborty** [comment]
Looking around, I see this issue is pretty prevalent actually.
See [SearchIndexerSkillset](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerSkillset.cs#L15) as another example. The type defines 2 required properties for its objects. So, we have a [ctor that takes 2 params](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerSkillset.cs#L21) and enforces that requirement. We also have [another ctor](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchIndexerSkillset.cs#L43) that takes in params for all the exposed properties and that does not have checks for the required properties. Again, allowing us to create objects that have null values for the properties that should never be `null`.

**Comment by Mohit-Chakraborty** [comment]
I think the correct fix would be to add the null checks in the property setters and use that in all ctor methods.
That way these required properties can never be set to `null` which is possible today after an object is constructed.

**Comment by AlexanderSher** [comment]
Second constructor is created for serialization purposes. In the example above with `ServiceCounters`, first constructor doesn't initialize `SkillsetCounter` property because object cause property isn't required but is read-only (`ServiceStatistics` that uses `SkillsetCounter`  is an output model).
