### ISSUE TITLE
Use CSharpType in WriteXmlDocumentation*** method will cause line feed in output

### ISSUE THREAD

**Issue by HarveyLink** [Azure/autorest.csharp#1198]
**Describe the issue or request**
We expect to **directly use Type** like `{resource.type}` in any comments writer method when we want to reference the type.
But when we do that in [WriteXmlDocumentation***](https://github.com/Azure/autorest.csharp/blob/39d8276362dc7bda4732be7e79b62d35d4d17724/src/AutoRest.CSharp/Mgmt/Generation/ResourceGroupExtensionsWriter.cs#L55) method, it will append `\r\n` after method name and do line feed in output. eg:
`"Returns a <see cref=\"global::Azure.ResourceManager.Sample.AvailabilitySetContainer\r\n\" /> object."`
```
/// <return>
/// Returns an <see cref="AvailabilitySetContainer
/// 
/// " /> object.
/// </return>
```
If we compare two types of writer method: `WriteXmlDocumentation***` & `Scope`, both could use FormattableString in parameter:
- `Scope` method receives FormattableString and do its own convert method for Type reference https://github.com/Azure/autorest.csharp/blob/39d8276362dc7bda4732be7e79b62d35d4d17724/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriter.cs#L39 
It append raw text **WITHOUT** \r\n followed.https://github.com/Azure/autorest.csharp/blob/f52c308d19dd54edbb3f440a6156a73923447429/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriter.cs#L198
![image](https://user-images.githubusercontent.com/30464227/115977248-c7328e00-a5a8-11eb-9689-c5c0ab5404c7.png)
- `WriteXmlDocumentation***` method receives string as parameter.
https://github.com/Azure/autorest.csharp/blob/39d8276362dc7bda4732be7e79b62d35d4d17724/src/AutoRest.CSharp/Common/Generation/Writers/DocumentationWriterExtensions.cs#L29
So the Type here will have to do its own convert, which will end with \r\n. https://github.com/Azure/autorest.csharp/blob/f52c308d19dd54edbb3f440a6156a73923447429/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriter.cs#L439
![image](https://user-images.githubusercontent.com/30464227/115977434-cdc20500-a5aa-11eb-8c1c-1800ffd73351.png)

**Describe your ideas for solutions**
The proper fix here would be to add support for FormattableString to the `WriteXmlDocumentation***`, maybe call the same convert method in `Scope`?

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by chamons** [comment]
Likely related to https://github.com/Azure/autorest.csharp/issues/1215
