### ISSUE TITLE
LLC generation should wrap all operation methods with a diagnostics scope

### ISSUE THREAD

**Issue by christothes** [Azure/autorest.csharp#1214]
In trying to record tests for an LLC, the following exception will occur:

**You may have forgotten to add clientDiagnostics.CreateScope(...), set your operationId to someClient.SomeOperation in SomeOperationAsync or applied the Azure.Core.ForwardsClientCallsAttribute to SomeOperationAsync.**

The LLC generator should  wrap all service method implementations with the diagnostics scope:

```C#
using DiagnosticScope scope = _diagnostics.CreateScope($"{nameof(ClientName)}.{nameof(OperationName)}");
scope.Start();
try
{
   <operation code>
}
catch (Exception ex)
{
    scope.Failed(ex);
    throw;
}
```

**Comment by chamons** [comment]
I believe this is now completed with 662bfbb. 

https://github.com/Azure/autorest.csharp/blob/feature/v3/samples/Azure.AI.DocumentTranslation/Generated/DocumentTranslationClient.cs#L276

Please reopen if there is more that I'm not seeing.
