### ISSUE TITLE
[LLC] Generated Doc Comments become ambiguous in "grow up" cases. 

### ISSUE THREAD

**Issue by ellismg** [Azure/autorest.csharp#1215]
From Krzysztof:

> I am trying to move WebPubSub to LLC + extensions. I ran into an interesting issues. The generator generates CreateXxxRequest methods with doc comments. The doc comments refer to method that will be calling the create method, e.g.:
>
>        /// <summary> Create Request for <see cref="SendToUser"/> and <see cref="SendToUserAsync"/> operations. </summary> 
>        /// <param name="userId"> The user Id. </param>
>        /// <param name="contentType"> Upload file type. </param>
>        /// <param name="requestBody"> The request body. </param>
>        private Request CreateSendToUserRequest(string userId, string contentType, RequestContent requestBody)
>
>When I manually add overloads to SendToUser, this doc comment does not compile anymore because of:
>
>Severity Code Description Project File Line Suppression State
Error CS0419 Ambiguous reference in cref attribute: 'SendToUserAsync'. Assuming 'WebPubSubServiceClient.SendToUserAsync(string, string, RequestContent, CancellationToken)', but could have also matched other overloads including 'WebPubSubServiceClient.SendToUserAsync(string, string, CancellationToken)'. Azure.Messaging.WebPubSub (netstandard2.0) D:\git\azure-sdk-for-net\sdk\webpubsub\Azure.Messaging.WebPubSub\src\Generated\WebPubSubServiceClient.cs 461 Active

In this specific case, we could just remove the doc comments from the private members (we had them because these used to be public, but are no longer and we just never stopped generating the docs) but we should also do the work such that if we are going to generate crefs to members, we generate them with the method signature we expect to target for cases where new overloads are added later.

**Comment by chamons** [comment]
Might need to output cref syntax w\ parms?

**Comment by chamons** [comment]
Likely related to https://github.com/Azure/autorest.csharp/issues/1198
