### ISSUE TITLE
Types represented in the REST spec with 'additional properties' should not be implemented as inheriting from `IReadOnlyDictionary`

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/autorest.csharp#1232]
**Describe the issue or request**
Types represented in the REST spec with 'additional properties' are implemented in .NET as types inheriting from `IReadOnlyDictionary`.
This presents some problems –
1.	As a user, I don't actively look for properties of a type that is-a dictionary. My assumption is that the only interesting thing about the type are the key-value pairs. Finding the names of the keys is the primary concern. So, I feel the main 'properties' of the type are not easily discoverable.
2.	Intellisense on the type is polluted by dictionary members. The few properties explicitly implemented by these 'dictionary' types are mixed with the inherited properties/methods.
3.	Indexer on the type only works for elements in `AdditionalProperties`. If the type is a dictionary, as a user I would expect all properties, including the ones defined separately to be accessible through indexing.

**Describe your ideas for solutions**
It seems composition is a more suitable pattern for these types, where they contain a dictionary of `AdditionalProperties` (same as current implementation) but aren’t themselves dictionaries. This avoids polluting the completion list of the members for these types.

**Comment by AlexGhiondea** [comment]
@chamons - please reach out to @KrzysztofCwalina and @tg-msft to make sure this is the right path forward.

**Comment by chamons** [comment]
I'm calling this 'done', until the spec work in https://github.com/Azure/azure-sdk-for-net/issues/21483 gets hashed out.
