### ISSUE TITLE
[Infrastructure] Fix autobump tool to stop blowing away work in mid-PR

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1258]
In multiple PRs, like https://github.com/Azure/azure-sdk-for-net/pull/21225, I'll be in the middle of fixing build issues and my work will get blown away by the bump tool.

We need to add a check list "if there are other commits from not me, don't force push"

**Comment by chamons** [comment]
0.5 if we have a handy "don't force push" option on the lib we're using from engsys.

**Comment by AlexanderSher** [comment]
Closing in favor of [#2300](https://github.com/Azure/autorest.csharp/issues/2300)
