### ISSUE TITLE
Unify codegen OperationInternals with OperationInternal from azure-sdk-for-net

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#1266]
https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/OperationInternals.cs

and 

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/OperationInternal.cs

I don't think we can completely get rid of the `OperationInternals` but we can at least build on top of the other and share some logic.

**Comment by pakrym** [comment]
cc @chamons @m-nash

**Comment by AlexanderSher** [comment]
Fixed
