### ISSUE TITLE
Serialization not supported for objects being passed into APIs

### ISSUE THREAD

**Issue by orenmichaely** [Azure/autorest.csharp#1304]
The generated model serialization classes which are passed into an API implement IUtf8JsonSerializable. 

IUtf8JsonSerializable only supports primitives and objects which implement IUtf8JsonSerializable. Our APIs accept anonymous objects and we are getting the following exception during serialization (Utf8JsonWriterExtensions.WriteObjectValue): "Not supported type <>f__AnonymousType0`3[System.String,System.Int32,System.String]" (classes which are not anonymous and do not implement IUtf8JsonSerializable are also not supported).

This issue is blocking the Personalizer track2 SDK release, so a quick resolution would be very helpful if possible.

**Comment by chamons** [comment]
I am meeting with the team to discuss this.

**Comment by chamons** [comment]
We are hitting this exception: https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/Utf8JsonWriterExtensions.cs#L120

**Comment by chamons** [comment]
Discussed on call and the plan is for the team to customize serialization on their end, and file a new issue here requesting general reflection based serialization (opt-in) as a potential feature request.
