### ISSUE TITLE
Generate code for Device Update swagger

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#1317]
Generate code for Device Update swagger with the new autorest management SDK design.

Swagger: https://github.com/Azure/azure-rest-api-specs-pr/blob/master/specification/deviceupdate/resource-manager/Microsoft.DeviceUpdate/preview/2020-03-01-preview/deviceupdate.json

**Comment by ShivangiReja** [comment]
Generated code - https://github.com/ShivangiReja/autorest.csharp/tree/Test_DeviceUpdate/samples/Azure.ResourceManager.DeviceUpdate/Generated

Sample -
https://github.com/ShivangiReja/autorest.csharp/blob/Test_DeviceUpdate/samples/Azure.ResourceManager.DeviceUpdate/Sample/Program.cs

There is an issue in the swagger, I've updated it. Here is the updated swagger -
https://github.com/ShivangiReja/autorest.csharp/blob/Test_DeviceUpdate/samples/Azure.ResourceManager.DeviceUpdate/sample.json

**Comment by chamons** [comment]
Unsure if this a bug or feature issue.

**Comment by ShivangiReja** [comment]
We can close this issue now. This is neither a bug nor feature request. I've created this is issue just to track the work item. This is the ask by @mayurid, service team added a new swagger for Device Update and we wanted to check if we can generate the code with the new design of management SDK.

I've added the generated code link above, now we can close this issue.
