### ISSUE TITLE
[LLC] Add enum values in comments

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1326]
Today we generate enums, but methods don't take enum they take the strings.

This creates a situation where people you pass Enum.ToString() and can pass it, and you can't. CamelCase vs pascalCase :(

The minute we generate the enum, it could be real enum or extensible enum.

- If it is real enum, ToString() issue.
- Extensible enums - Handles ToString() well but default params doesn't work cleanly because they don't support extensible enums (it isn't a constant value).

**Comment by chamons** [comment]
Decision is to add a switch to generate string or enums.

**Comment by annelo-msft** [comment]
With no models, no models for enum => we just use underlying type as enum, e.g. string, int
Have to worry about casing service used
Either generate as extensible enum, or keep underlying type
=> These are tooling customizations a person could do by hand today
=> Per @ellismg, we could add this later as an opt-in feature, and use it going forward

Question: what is the guidance for teams? Do this, or don't do this?  Trade-off, now we're generating types for enums
- [ ] => Need to come up with guidance; ideal: generate by default and opt-in to CLR-type; need to work this through with @KrzysztofCwalina 
=> we need the guidance to know whether it's an RC1.0 or RC1.1 feature

**Comment by annelo-msft** [comment]
We'll solve in docs for RC1.0, may bring in type generation later.

Having the enum types is hard to explain as part of LLC story.
