### ISSUE TITLE
[LLC]  Review generated documentation for methods and make sure it looks reasonable 

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1331]
Review generated LLC documentation for methods and make sure it looks reasonable.

We noticed some issues with rendering tables, for example.

**Comment by annelo-msft** [comment]
Shanghai team has done work for tables.
https://github.com/Azure/autorest.csharp/pull/1495

We believe this PR resolves this issue. This is more similar to what other languages are doing now.
