### ISSUE TITLE
Generated ClientOptions class names default to wrong name

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#1339]
With an autorest.md file like the one below, an authoring client was generating using the name `QuestionAnsweringProjectsClient`. This is good and was expected; however, the ClientOptions class was called `MicrosoftCognitiveLanguageServiceQuestionAnsweringAuthoringClientOptions`. Also, the model factory was called `MicrosoftCognitiveLanguageServiceQuestionAnsweringAuthoringModelFactory`, which is similarly incorrect.

Despite ease of workarounds and instances, I think this needs to be prioritized higher as we expect to generate a lot more LLCs.

**Comment by chamons** [comment]
@heaths  - Can you provide an example swagger/autorest config file?

**Comment by heaths** [comment]
See https://github.com/Azure/azure-sdk-for-net/pull/21810/files#diff-3f08795f311752ef6b770b5f39dda78c8d5add9eac2defa438508f1929dfd0b0. If you delete the non-generated `QuestionAnsweringClientOptions` class you'll repro the issue.

**Comment by chamons** [comment]
Hmm, I just threw this at the readme alone (so no customizations at all) (just the single edit needed to run it in autorest.csharp:

https://github.com/chamons/autorest.csharp/blob/dad1026d242fb98da3a90bfee5ac5eb918bbdd95/samples/Azure.AI.DocumentTranslation/readme.md

And I get:
```
    public partial class QuestionAnsweringClientOptions : ClientOptions
    public static partial class QuestionAnsweringModelFactory
```

I'm trying to see what the difference is here...

**Comment by heaths** [comment]
Ah, I forgot about the `title`. You need to remove that such that the actual swaggers' title is used.

Talking with @pakrym I understand why that change was made and maybe this is desirable behavior, but it certainly wasn't expected. I assumed that the generator would generate a *ClientOptions for each *Client, but Pavel had mentioned if there were no differences the arch board would probably recommend collapsing them into a single per-library ClientOptions anyway.

@KrzysztofCwalina @johanste would you agree that we want 1 ClientOptions class by default per SDK?

**Comment by johanste** [comment]
Python does not use `ClientOptions` classes. However, I can see scenarios where the same library contained multiple client classes, each with its own set of configuration parameters at some point in the future. But that should be solve:able with overloads in .NET (and presumably in Java/TS as well)

**Comment by chamons** [comment]
Confirmed @heaths - Removing the title makes this reproduce for me.

I'm going to leave this open for now until @KrzysztofCwalina and/or @ellismg confirm the desired behavior here.

**Comment by heaths** [comment]
I'd rather we figure out something better than `title`. Most of the titles I've seen are comprised of marketing terms we don't always use, meaning we then have to override the titles in autorest.md. If the goal is to use `require` and little else (e.g. no transforms), the less we have to override the better.

**Comment by ellismg** [comment]
> I'd rather we figure out something better than `title`.

I looked quickly at the swagger specification but nothing stood out as a specific property we could use instead that might make more sense.  Perhaps we could have something like `x-ms-client-name` which is an optional parameter that when set we use instead of "title" for the prefix?

I think that generating a client options type per client (which means per operation group) is the wrong default.  In cases like Storage (where we have multiple clients) we still try to minimize the number of `ClientOptions` types that we have, there isn't one per client.

One thing to note is that this `title` is also used today for cases where a swagger has operations which don't have an operation group prefix (i.e. an operationId without an `_` in the name) and whatever new scheme we come up with for naming things should also apply that name here.

**Comment by heaths** [comment]
I like the `x-ms-client-name` idea, falling back to `title`. It's consistent with other SDK usage patterns.

While anecdotal, many swaggers I've reviewed treat `title` as more of a marketing summary of the service. Generating class names from that, which might end up like (in this case) `MicrosoftAzureCognitiveLanguageServiceClientOptions` is probably not what service teams would expect or even think of. It certainly surprised me until someone mentioned it was because of the `title`.

I appreciate that, by default, we don't want 1 ClientOptions per Client. And in strongly typed languages we can always add overloads later if we do need to diverge ClientOptions types.

**Comment by ellismg** [comment]
FWIW - I just discovered that AutoRest already supports an option: `override-client-name` to control this: https://github.com/Azure/autorest/blob/d4bce7ef3a0ff37b28519d7cdd3fb1e683f7d45d/packages/extensions/modelerfour/src/modeler/modelerfour.ts#L264-L267

This is an autorest option however, not something that is determined from the swagger.

**Comment by heaths** [comment]
Could work, but should be properly documented. Only mentioned of it I see are in source implementation. Not ideal if someone isn't familiar with the code.

**Comment by ellismg** [comment]
FWWI, it is documented as part of the CLI (https://github.com/Azure/autorest/blob/main/docs/user/command-line-interface.md#commonly-used-settings) which also notes that you can set these in the config file or pass them on the command line.

**Comment by heaths** [comment]
That's good. :) Would be great to add that to the list of directives supported and, as you noted, in `--help`. Across autorest and autorest.* plugin repos it's hard to get a good overview of what's supported / what things do.

**Comment by AlexGhiondea** [comment]
@heaths can we close this?
