### ISSUE TITLE
Use generated csharp client in another assembly.

### ISSUE THREAD

**Issue by trojanmartin** [Azure/autorest.csharp#1351]
Is there any way I can use the generated client in another assembly without additional code? Just like it was in version 2.
When I generate a client with the `public-clients = true` flag, the class is public, but the constructor is internal.

**Comment by AlexGhiondea** [comment]
@pakrym could you take a quick look?

**Comment by pakrym** [comment]
`public-clients = true` doesn't generate a ctor because it doesn't know what authentication you might need. 

You can define a ctor in a partial class similar to https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/Azure.Template/src/MiniSecretClient.cs#L25-L38
