### ISSUE TITLE
[LLC] generated clients should mark _clientDiagnostics as internal

### ISSUE THREAD

**Issue by christothes** [Azure/autorest.csharp#1379]
When "growing up" an LLC client, it may be common to add additional methods in a partial instance. Such partial instances need access to the ClientDiagnostics passed to the constructor of the generated partial instance of the class.

**Comment by AlexanderSher** [comment]
Sorry, but I'm not sure I understand the issue. Partial definition of the type has access to private members that are defined in another partial definition.

**Comment by christothes** [comment]
My description was not totally accurate. The scenario I ran into was having to access the client diagnostics from an Operations class.

**Comment by AlexanderSher** [comment]
`ResourceOperations` should have its own instance of ClientDiagnostics.
Can you give a specific example of the problem you have?

**Comment by christothes** [comment]
In my `Operation` class, I internally new up an instance of `OperationsInternal`, which takes a clientDiagnostics instance in its constructor. This is initialized through the operation's public ctor, which is called by the developer taking the client instance and the operation Id as args. If the clientDiagnostics is not internal in the client, I can't access it from that ctor, unless the developer passes it to the Operation ctor. 

https://github.com/Azure/azure-sdk-for-net/blob/94532869feae8a6b124f50bae7174c7c1b17e98b/sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/PostLedgerEntryOperation.cs#L31

**Comment by AlexanderSher** [comment]
Usually operation instances are created by the client. Why do you need a public ctor for this operation?

**Comment by christothes** [comment]
Operations also usually have a public ctor to allow them to be re-hydrated given an operation Id.

**Comment by annelo-msft** [comment]
Per @christothes, not needed until CL GA
