### ISSUE TITLE
 error CS0122: 'ClientDiagnostics' is inaccessible due to its protection level 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Azure/autorest.csharp#1411]
can it be made public?

**Comment by AlexanderSher** [comment]
We don't want to have public dependencies on this type. What issue are your trying to solve?

**Comment by dzmitry-lahoda** [comment]
i used autorest to generate client from swagger. i got some cs files and tried to compile. compilation failed subject error

**Comment by AlexanderSher** [comment]
Have you referenced autorest nuget package in your csproj?

**Comment by dzmitry-lahoda** [comment]
Autorest generated project for me, I built the project which was generated. So I can try to reference some assembly.

**Comment by AlexanderSher** [comment]
These types are provided in the nuget package. They should be referenced with the package. Files themselves are in the folder `.nuget/packages/microsoft.azure.autorest.csharp/3.0.0-beta.XXXXMMDD.V/content/Azure.Core.Shared/

**Comment by dzmitry-lahoda** [comment]
any updates on this. what is guide to generate client to ANY up swagger json of  compatible version so that csproj compilable out of box given proper .net skd is installed? why should i fix project manually if that was generated?and still unclear how to compile project generated if it refs internal types from some microsoft assembly

**Comment by cataggar** [comment]
This took me a couple a few hours today to hunt down. These two properties control if sources files from `Shared/Core` or `Shared/Management` are included in your project.

``` xml
  <PropertyGroup>
    <IncludeAzureCoreSharedCode>true</IncludeAzureCoreSharedCode>
    <IncludeManagementSharedCode>true</IncludeManagementSharedCode>
  </PropertyGroup>
```

![image](https://user-images.githubusercontent.com/87583576/188036849-2e258aea-720b-4078-88a3-0be7ace215a5.png)

**Comment by cataggar** [comment]
For newer versions, I had to set `IncludeGeneratorSharedCode` to true. Note, I also switched to C# 11 because of UTF-8 string literals.

``` xml
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <IncludeGeneratorSharedCode>true</IncludeGeneratorSharedCode>
  </PropertyGroup>
```

If this changes again, just look at the `Microsoft.Azure.AutoRest.CSharp.targets` in the nuget package.
C:\Users\cataggar\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20230518.1\build\Microsoft.Azure.AutoRest.CSharp.targets

Relevant section this time:
``` xml
  <ItemGroup Condition="'$(_GenerateCode)' == 'true' OR '$(IncludeGeneratorSharedCode)' == 'true'">
    <Compile Include="$(AzureCoreSharedCodeDirectory)/**/*.cs" Condition="'$(IncludeAzureCoreSharedCode)' == 'true'" Link="Shared/Core/%(RecursiveDir)/%(Filename)%(Extension)" />
    <Compile Include="$(AutoRestSharedCodeDirectory)/**/*.cs" Link="Shared/AutoRest/%(RecursiveDir)/%(Filename)%(Extension)" />
  </ItemGroup>
```
