### ISSUE TITLE
How to actually use generated code, outside of azure sdk (.Net 4.8 Framework)

### ISSUE THREAD

**Issue by jmerkow** [Azure/autorest.csharp#1435]
I am trying to use autorest to generate code into a application that is using .net framework 4.8.
The api is defined in swagger 2.0.

My yaml looks like:
```yaml
title: LabelingPrivate
csharp: true
input-file:
  - labelingPrivate.json
namespace: Labeling.Private.Client
output-folder: ./Generated/
add-credentials: true
clear-output-directory: true
skip-csproj: true
```

Using the generated csproj doesn't work since that would be .net standard 2.x (and I am using framework 4.8). 
I tried adding the following xml:

```xml
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <IncludeGeneratorSharedCode>true</IncludeGeneratorSharedCode>
    <RestoreAdditionalProjectSources>https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20210728.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.16.0" />
  </ItemGroup>
```

but this doesn't seem to work for `<Project ToolsVersion="15.0">`, instead I added 
```xml
  <ItemGroup>
    <Compile Include="Generated/**/*.cs" />
  </ItemGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

then installed `Azure.Core` through the nuget manager, as well as `Microsoft.Azure.AutoRest.CSharp`.  This causes a whole bunch of ambiguity errors. But if I copy the files it added to the project, uninstall, and then re-add them, everything seems to work and compile. This process seems wrong to me, but its compiling....

Then to use it anywhere I need to make the `LabelingPrivateRestClient` public and modify the constructor to be internal. and now I can import it in other projects.

The package seems out of date with [the main package docs](https://github.com/Azure/autorest.csharp/blob/feature/v3/docs/client/initializing.md) as there are no constructors with the signature used, the only one available is `LabelingPrivateRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)`, which I had to make internal anyway....

So where do I go from here to be able to use this generated code?

**Comment by sopelt** [comment]
As the readme states the new V3 generated code is targeted towards netcore 3.1. For full framework you should try the `--legacy `flag as stated [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#default-autorest---csharp-generator-change).

**Comment by jmerkow** [comment]
Ok that works for one of them.  But I am having trouble with using these flags with the APIs I need from [azure-rest-specs](https://github.com/Azure/azure-rest-api-specs), specifically: [MachineLearning Services 2021-03-01-preview](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2021-03-01-preview)

I get this error: ```Process() cancelled due to exception : Cannot resolve pipeline stage 'openapi-document/multi-api/identity'.
  Error: Cannot resolve pipeline stage 'openapi-document/multi-api/identity'.```

**Comment by jmerkow** [comment]
> I get this error: `Process() cancelled due to exception : Cannot resolve pipeline stage 'openapi-document/multi-api/identity'. Error: Cannot resolve pipeline stage 'openapi-document/multi-api/identity'.`
> 
> Any idea what that means?

Figured this out, for anyone coming here, you cannot have refences to other files with `--v2 --legacy`

**Comment by jmerkow** [comment]
@sopelt So this implementation doesn't include many of the nice features as v3, i.e. AsyncPageable etc. Do you have any idea how I  can incorporate those?
