### ISSUE TITLE
[LLC] Use options.Apply() in service method calls

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1494]
A static `Apply()` method was [recently added to `RequestOptions`](https://github.com/Azure/azure-sdk-for-net/pull/22923/files#diff-d4b6f4359bb84b87e84578d0bbdd9e87e9c09e92dfc9a30443f655d2d3276ea1R107) to apply the options specified in LLC methods all in one place.

This will replace the [existing sections where RequestOptions](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjectsLowLevel/url/Generated/QueriesClient.cs#L101-L104) are applied in LLC generated code.

**Comment by AlexanderSher** [comment]
Any backward-compat issues we should be aware about?

**Comment by pakrym** [comment]
I think this one is safe.

1. LLC in general is in preview
2. We are moving pretty much the same code from being generated to being in the shared library
