### ISSUE TITLE
Preview versions are generated with lowercase "-preview"

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#1524]
Since in .NET names are supposed to be PascalCase, I created Roslyn analyzer ACZ0016 but it turns out there are 17 violations - all in generated code. I could suppress these, but it'll be risky because I'll have to declare hand-written models and any future generation may conflict. Instead, I think the generator should instead incur the breaking change because, for any existing values *not* in generated code, those have already shipped (presumably) and can be exempted.

**Comment by lirenhe** [comment]
@archerzz, could you help to check whether the problem still exists with the latest version of CodeGen?

**Comment by ArthurMa1978** [comment]
Track 2 should be `beta` instead of `preview`

**Comment by lirenhe** [comment]
> Track 2 should be `beta` instead of `preview`

I think this is mainly about the service version.  For client version, sure, we should use beta.

**Comment by heaths** [comment]
This is about the *service version*, which must match what's in swagger exactly. This was done correctly by the previous code gen. If the service defines api-version `2022-05-15-preview`, for example, C# codegen must define a `V2022_05_15_Preview` (notice the uppercase "P") that yields a string that matches the api-version `2022-05-15-preview` exactly.
