### ISSUE TITLE
[LLC] Generate SubClients

### ISSUE THREAD

**Issue by ellismg** [Azure/autorest.csharp#1527]
The .NET Design Guidelines have recently adopted a ["SubClient"](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-subclients) pattern.  We've been using this pattern by hand via [customizations for some of our LLC]() clients to get an [API surface](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/purview/Azure.Analytics.Purview.Account/api/Azure.Analytics.Purview.Account.netstandard2.0.cs) that follows this design.

We should teach the code generator how to do this for us.  I took a first stab at how this might be done here: https://github.com/ellismg/autorest.csharp/tree/ellismg/llc-sub-clients

**Comment by annelo-msft** [comment]
@ellismg will put up a draft PR for this

**Comment by AlexanderSher** [comment]
Resolved and merged into azure-sdk-for-net repo except for https://github.com/azure/autorest.csharp/issues/1665
