### ISSUE TITLE
[LLC] Set "default response classifier" on message

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1535]
In order for us to allow `Response.IsError` to reflect default behavior (i.e. which status codes are defined in the OpenAPI spec as success vs. error), we need to pass this information to the pipeline so it can be set on the response.

We achieve this via setting the `ResponseClassifier` on the message when the request is created.

In the LLC generator, we will need to:

1. [Generate properties on the client for each group of successful status codes in the OpenAPI spec](https://github.com/Azure/azure-sdk-for-net/pull/24083/files#diff-2eb5a04baba528d0f0008b55cd9d21a610926491c26d00012ae2ef9c6c6d1435R29)
2. [Generate classifier type definitions](https://github.com/Azure/azure-sdk-for-net/pull/24083/files#diff-2eb5a04baba528d0f0008b55cd9d21a610926491c26d00012ae2ef9c6c6d1435R162)
3. [Set the classifier on the message in CreateXxRequest](https://github.com/Azure/azure-sdk-for-net/pull/24083/files#diff-2eb5a04baba528d0f0008b55cd9d21a610926491c26d00012ae2ef9c6c6d1435R158)

In addition, we will:
4. [Remove the `RequestOptions` allocation from the default path](https://github.com/Azure/azure-sdk-for-net/pull/24083/files#diff-2eb5a04baba528d0f0008b55cd9d21a610926491c26d00012ae2ef9c6c6d1435L61)

**Comment by annelo-msft** [comment]
@AlexanderSher, can you confirm this is the design we want to go with before we assign it?

**Comment by AlexanderSher** [comment]
There is one limitation with this approach: users won't be able to customize how exceptions are created. I'd prefer classifier to be internal (rather than private) with method `ThrowOnErrorResponse`.

**Comment by annelo-msft** [comment]
Hi Alexander, the user will still be able to customize exception creation because we plan to move the customization to ResponseClassifier in https://github.com/azure/azure-sdk-for-net/issues/24031

> I'd prefer classifier to be internal (rather than private) with method `ThrowOnErrorResponse`.
We've actually discussed this a lot with @KrzysztofCwalina, @ellismg, and @pakrym, and decided that the following is a preferred API as it's more idiomatic to .NET

```csharp
      if (response.IsError())
      {
          throw new RequestFailedException(response);
      }
```

I am working on this as part of https://github.com/azure/azure-sdk-for-net/issues/23372

**Comment by AlexanderSher** [comment]
> because we plan to move the customization to ResponseClassifier

Ok, let's say a user needs custom error code handling and custom exception types. How this will be customized?

**Comment by AlexanderSher** [comment]
@annelo-msft @pakrym
Am I right that the following chunk of code would be the same for all methods:
```cs
                await Pipeline.SendAsync(message, options?.CancellationToken ?? default).ConfigureAwait(false);
                var statusOption = options?.StatusOption ?? ResponseStatusOption.Default;

                if (statusOption == ResponseStatusOption.NoThrow)
                {
                    return message.Response;
                }
                else
                {
                    if (!message.ResponseClassifier.IsErrorResponse(message))
                    {
                        return message.Response;
                    }
                    else
                    {
                        throw await _clientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
                    }
                }
```

**Comment by pakrym** [comment]
@AlexanderSher that's a great observation! Wonder if we can move this code into some shared file and not codegen it.

**Comment by AlexanderSher** [comment]
This is the code we generate right now for the `HEAD` as `bool` case:
```cs
switch (message.Response.Status)
{
    case int s when s >= 200 && s < 300:
        return Response.FromValue(true, message.Response);
    case int s when s >= 400 && s < 500:
        return Response.FromValue(false, message.Response);
    default:
        throw await _clientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
}
```

Which part of it should go into `ResponseClassifier`?

**Comment by annelo-msft** [comment]
Great question, @AlexanderSher!

In this case, we wouldn't use the standard code you noted in https://github.com/azure/autorest.csharp/issues/1535#issuecomment-928753655.  Instead, since we need to return `Response<bool>` we would have something like:

```csharp
            if (!message.ResponseClassifier.IsErrorResponse(message))
            {
                return Response.FromValue(message.Response.Status >= 200 && message.Response.Status < 300, message.Response);
            }
            else
            {
                if (options.StatusOption == ResponseStatusOption.NoThrow)
                {
                    return new ErrorResponse<bool>(message.Response, _clientDiagnostics.CreateRequestFailedException(message.Response));
                }
                else
                {
                    throw await _clientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
                }
            }
```
With the ResponseClassifier being:

```csharp
        private class ResponseClassifier200204404 : ResponseClassifier
        {
            public override bool IsErrorResponse(HttpMessage message)
            {
                switch (message.Response.Status)
                {
                    case 200:
                    case 204:
                    case 404:
                        return false;
                    default:
                        return true;
                }
            }
        }
```

What are your thoughts on this proposal?

**Comment by AlexanderSher** [comment]
`ResponseClassifier` in this case doesn't incapsulate all the logic related to the codes. Since `HEAD` as `bool` is a special case by itself, I think we should skip generating classifier for it for now.
