### ISSUE TITLE
C#: When multipart/form-data has more than 1 part, only the first one is generated

### ISSUE THREAD

**Issue by bkwdesign** [Azure/autorest.csharp#157]
using version: 2.0.4280 

Here's a portion of my Swagger 2.0.. there are 4 parameters, the first two are "normal" inputs, but the last two are part of the multpart/form-data ..

                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "text/json",
                    "application/xml",
                    "text/xml"
                ],
                "parameters": [
                    {
                        "name": "docid",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "userid",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "attachment",
                        "in": "formData",
                        "description": "PDF to upload.",
                        "required": true,
                        "type": "file"
                    },
                    {
                        "name": "doc_string",
                        "in": "formData",
                        "description": "Additional Document Data",
                        "required": true,
                        "type": "string"
                    }
                ],

With the above, I get the following multi-part logic generated:

            MultipartFormDataContent _multiPartContent = new MultipartFormDataContent();
            if (attachment != null)
            {
                StreamContent _attachment = new StreamContent(attachment);
                _attachment.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                FileStream _attachmentAsFileStream = attachment as FileStream;
                if (_attachmentAsFileStream != null)
                {
                    ContentDispositionHeaderValue _contentDispositionHeaderValue = new ContentDispositionHeaderValue("form-data");
                    _contentDispositionHeaderValue.Name = "attachment";
                    _contentDispositionHeaderValue.FileName = _attachmentAsFileStream.Name;
                    _attachment.Headers.ContentDisposition = _contentDispositionHeaderValue;
                }
                _multiPartContent.Add(_attachment, "attachment");
            }

It's all well and good, but, nothing is generated for my `doc_string` parameter.. and if I swap the order and put the `doc_string` parameter ahead of my `attachment`, I get the correct code generated for `doc_string`, but then my `attachment` parameter is ignored.

Seems to support 1 part... that doesn't seem very "multipart-ish"  ;-)

**Comment by MiYanni** [comment]
I'm told this has been fixed in the V3 generator via this PR: https://github.com/Azure/autorest.csharp/pull/886
For now, I'm closing this issue. Feel free to comment or reopen if there still a problem.
