### ISSUE TITLE
Better ways to get the get, put and delete methods

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1574]
In ResourceContainer, the way to get the Put method is to check the first method whose HttpMethod type is PUT.
In ResourceOperation, the way to get the Get and Delete method is similar.

This may not be true when there are multiple Get, Put and Delete methods in the same resource group. For instance, the following paths all have the three methods：

/{scope}/providers/Microsoft.Authorization/locks/{lockName}
/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/locks/{lockName}
/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}/providers/Microsoft.Authorization/locks/{lockName}

The methods under /{scope}/providers/Microsoft.Authorization/locks/{lockName} should be the main methods for operation or container regardless of whether it appears first.

**Comment by fengzhou-msft** [comment]
No longer applicable with operation group replaced by request path.
