### ISSUE TITLE
Add [Resource]ApiVersions object

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#1577]
Should follow the existing enum pattern and only have the latest version (VirtualMachinesApiVersion.cs)
Should have a default which points at the latest version

Each new should append to this file not rewrite it adding in the new version if one exists and updating the default

regenerating the exact same api version as before should not add a duplicate versoin

consider the case of 1 version was skipped between generation

Acceptance Criteria:

- Initial creation should have 1 version and 1 default pointing at it
- Subsequent generation should append the new version and update default
- Add tests to validate

**Comment by ArthurMa1978** [comment]
@m-nash  is this dup with https://github.com/azure/autorest.csharp/issues/1639

**Comment by ArthurMa1978** [comment]
Dup with #1639
