### ISSUE TITLE
[Feature]: Configuration to specify the parent class for a path

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1580]
# Description

Sometimes we need to re-locate the generated codes of a specific path to a different parent. For example, below are two APIs for checking name availability:
- https://github.com/Azure/azure-rest-api-specs/blob/3c16aae50c7110e1aad241ac93995621d4093d46/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/cosmos-db.json#L570
- https://github.com/Azure/azure-rest-api-specs/blob/3c16aae50c7110e1aad241ac93995621d4093d46/specification/communication/resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json#L65

It would be better if the generated codes could be under the collection of the corresponding resource collection.

**Comment by ArthurMa1978** [comment]
Please confirm this has been fixed or not @archerzz

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/autorest.csharp/issues/1650 should be the general solution for all these kind of issues

**Comment by archerzz** [comment]
Need to verify if we should do anything else for this issue.

**Comment by archerzz** [comment]
This should be covered by #1650 We can close this issue.

**Comment by archerzz** [comment]
Note that #1650 is for post GA. But I don't think this issue is required for GA, unless some RP we plan to release needs this feature.
