### ISSUE TITLE
Member variable should observe Customization overrid

### ISSUE THREAD

**Issue by Yao725** [Azure/autorest.csharp#1583]
Customization works with one small issue. ctor, methods are not emitted if exists in file under Customization folder. However properties still got emitted. 

Repo step:

  1. Copy XXCollection and XXOperation classes under Customization folder
  2. Rerun code gen.
  3. Generated files will have two fields remaining:

        private readonly ClientDiagnostics _clientDiagnostics;
        public static readonly ResourceType ResourceType = "Microsoft.MachineLearningServices/workspaces/environments";

**Comment by ArthurMa1978** [comment]
Already be fixed after we refactored the autorest.csharp
