### ISSUE TITLE
Omit orphaned models

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#1585]
Models can be orphaned by skipping an entire operation group like Operations or by replacing the type with a reference type therefore the original is no longer referenced anywhere

example there are two resource objects so we have to explicitly specify one

https://github.com/Azure/autorest.csharp/pull/1427/files#diff-73c11042786cf1e5a8d918e0ee37dcb8934f391ae7dd17dd3d6cb84bb766481bR15

**Comment by ArthurMa1978** [comment]
If we can omit all orphan models manually before GA then this feature can be postponed

**Comment by fengzhou-msft** [comment]
Explored the option to use Roslyn code analysis to remove orphaned models. 

Basic logic to find orphaned models: check if a model type is only referenced by its declaring files (using `SymbolFinder.FindReferencesAsync()`).

There are cases that an orphaned model refers to other models, only when that orphaned model is removed, we can detect other models as orphaned. **Therefore, we need multiple iterations to find and remove orphaned models until there are no more orphaned models.**

**We cannot remove all orphaned models because some models are not directly referenced but are still useful.** For instance, `AvailabilitySetSkuTypes` in compute is not referenced by code anywhere, but users need to check it so they know what values to pass as the String-typed `name` for the general `Sku` model for `AvailabilitySetData`. The description for `Sku` also directs users to check `AvailabilitySetSkuTypes` for possible values. Therefore, we may need to add configurations to not remove some orphaned models.

Considering the cost and gain, let's use codegen attributes to suppress orphaned models first, and revisit this item after GA.

**Comment by fengzhou-msft** [comment]
Orphaned models caused by generator behavior:
1. A model is replaced by common type model. Then the models only used by that replaced model could be orphaned. For instance, the CreatedByType model which is only used by SystemData becomes an orphan after SystemData is replaced by common type.
2. In the case of multiple `allOf`, the generator only inherits from one parent schema and the properties of other parents are flattened, therefore the models for other parents are not used in the generated code and become orphans. For instance, the `LocationResource` and `TaggedResource` inherited by [CommunicationServiceResource](https://github.com/Azure/azure-rest-api-specs/blob/54a98083200e56d88fe1182f2741a61aea91c788/specification/communication/resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json#L677-L690) are orphaned models.

**Comment by ArcturusZhang** [comment]
In my implementation #1998 , I only mark the ObjectSchema type to internal if it is not referenced by the public operations (directly or indirectly). The enum types will be left unchanged.
