### ISSUE TITLE
Support the case that some "keys" in the URL is also a variable

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#1587]
Usually we only deal with the case that the value part in the URL is a variable, for instance `resourceGroups/{resourceGroupName}`.
But in some special cases, the keys in URL can also be a variable, for instance `{recordType}/{recordName}`

An realistic case is here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L30

**Comment by ArcturusZhang** [comment]
Duplicate of https://github.com/Azure/autorest.csharp/issues/1702
