### ISSUE TITLE
[feature] support resource definition under different API paths

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1594]
# Description
A resource definition could appear under different API paths. Right now the .net generator fails to support this case. I think this is a high priority. We need to figure out a mechanism to support that type of cases. It seems a quiet common case.

### `NetworkInterface`
In https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/cloudServiceNetworkInterface.json, `NetworkInterfaces` are used in different API path. All corresponding `operationId` are named after `NetworkInterfaces_XXX`. So the generator will treat them as the same operation group. But since they are under different API paths, generator could not recognize the parent operatoin groups. That cannot be resolved by operation group mapping settings in markdown files either.

### `PublicIpAddress`
It's defined in https://github.com/Azure/azure-rest-api-specs/blob/04adf299cf13fc31321c3ebaee7f78895afd1e49/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/publicIpAddress.json#L490

But you can find the reference across different API path as below:
- https://github.com/Azure/azure-rest-api-specs/blob/04adf299cf13fc31321c3ebaee7f78895afd1e49/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/publicIpAddress.json#L37
- https://github.com/Azure/azure-rest-api-specs/blob/04adf299cf13fc31321c3ebaee7f78895afd1e49/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/cloudServicePublicIpAddress.json#L37
- https://github.com/Azure/azure-rest-api-specs/blob/04adf299cf13fc31321c3ebaee7f78895afd1e49/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/vmssPublicIpAddress.json#L37

That is a typical scenario of multiple operation groups for the same resource definition.

### `VirtualMachineRunCommand`
An example from compute RP. We have the resource called `VirtualMachineRunCommand` under two different paths and operation groups:
- https://github.com/Azure/azure-rest-api-specs/blob/c2e43f82e91ff7ad691381df56c535164b354cba/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/runCommands.json#L257
- https://github.com/Azure/azure-rest-api-specs/blob/c2e43f82e91ff7ad691381df56c535164b354cba/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/runCommands.json#L576

----

[Note]: This is migrated from [ADO 5889](https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_workitems/edit/5889/)

**Comment by ArthurMa1978** [comment]
Solve by the https://github.com/azure/autorest.csharp/issues/1608
