### ISSUE TITLE
[discussion] loosen response code check for long running

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1617]
# Description

Swagger definitions are not always accurate when describing the response codes for long running operations. For example, in the [cosmos-db notebook workspace creation API](https://github.com/Azure/azure-rest-api-specs/blob/f780b571abddf2fc99233212a00510d3bef6878d/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/notebook.json#L159), `HTTP 202` is not defined as a success response.

But in reality, `HTTP 202` will be returned, and the `RestOperation` class will throw error because 202 is not in the generated codes. See below:
```csharp
using var message = CreateCreateOrUpdateRequest(resourceGroupName, accountName, notebookWorkspaceName, notebookCreateUpdateParameters);
await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
switch (message.Response.Status)
{
    case 200:
        return message.Response;
    default:
        throw await _clientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
}
```

Of course we can:
1. Raise issue to service team to fix the swagger definition
2. Add autorest configuration as a work-around

But maybe we could be more tolerant in this case. We can leverage implementation in other language SDK to see how they achieve that.

**Comment by AlexanderSher** [comment]
We can't relax handing of status code without breaking some other service that assumes anything other than 200 is an error. I'd say we should do what spec tells us to do without being too smart.
