### ISSUE TITLE
Track 2 GA tooling work for Mgmt .Net SDK

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1620]

**Comment by m-nash** [comment]
https://github.com/Azure/autorest/pull/4356 m4 PR
https://gist.github.com/timotheeguerin/28fb5844bcffbd4d798bd9efedb8d8ec#file-codemodelv2-yaml-L117 example generation

**Comment by ArthurMa1978** [comment]
Related EPICs
- https://github.com/Azure/azure-sdk-for-net/issues/26387
- https://github.com/Azure/autorest.csharp/issues/1788
- https://github.com/azure/autorest.csharp/issues/1756

**Comment by ArthurMa1978** [comment]
We moved to Projects https://github.com/orgs/Azure/projects/148/views/1, so close all epic issues
