### ISSUE TITLE
Generate everything that was hand crafted in Azure.ResourceManager

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1623]
This might require us to split out some hand customization, but everything in the generated folder should be generated to ensure maintainability moving forward when the specs change.

**Comment by fengzhou-msft** [comment]
Initial plan is to leverage the `batch` feature in readme to generate resources in different namespaces (core/resources/management) and folders. We'll need to modify [CodeGeneration.targets](https://github.com/AlexanderSher/autorest.csharp/blob/59e414920db9dca31302d74536adecad656a7bf7/src/AutoRest.CSharp/build/CodeGeneration.targets#L34) as it currently specifies a single namespace and output folder in command line and it will override the settings in readme.

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/26419 merged
