### ISSUE TITLE
There is a concurrency issue in "new DefaultAzureCredential()" that needs to get investigated

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1628]
Create issue in azure-sdk-for-net with a repro based on master code

**Comment by Yao725** [comment]
Test Environment:
1. Azure.ResourceManager(1.0.0-beta.5)
2. Azure.Identity(1.5.0)

Test Code:
```
Parallel.For(1, 100001, (i, state) =>
{
    var client = new ArmClient(new DefaultAzureCredential());
});
```
Can't repro the issue, so closed.
