### ISSUE TITLE
Review designs to minimize breaking changes and implement the solution - overload for parameter change

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1630]
Parameter ordering such as moving CancellationToken from the end to the same spot it was.
does require us to know what position it was in for the last iteration

Implementation and design

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/autorest/pull/4356 m4 PR
https://gist.github.com/timotheeguerin/28fb5844bcffbd4d798bd9efedb8d8ec#file-codemodelv2-yaml-L117 example generation

**Comment by archerzz** [comment]
# Parameters Overload Design

## Axiom

1. Parameter list cannot shrink. (Guaranteed by M4)
    - Valid cases: A,B => A,B,C ; A,B=>A,B* (**\* means optional**)
    - Invalid cases: A,B => A ; A,B,C* => A,C*
    - The latest parameter list should be the longest
2. Required parameters cannot grow. (Guaranteed by M4)
3. Parameter list are sorted by required/optional. (CSharp generator will do this)
    - Valid cases: A,B => A,B* ; A,B,C => A,C,B*
    - Invalid cases: A,B,C => A,B*,C
4. If a parameter list P1 is a subset of another list P2, then P1 will have no conflict with P2 if all parameters in P1 are required.
    - Conflict: A,B,C* v.s. A,B,C*,D*
    - No conflict: A,B,C v.s. A,B,C,D*
5. If P1 and P2 have the same parameter sequence, then they have conflict.
    - e.g. A,B,C* v.s. A,B*,C*
6. If P1 and P2 is not subsequence of each other, then they do not have conflict.
    - e.g. A,B,C v.s. A,C,B*

## Algorithm

```csharp
// sort parameter lists including parameter overloads (change existing codes)
foreach (var overload in operation.SignatureParametersOverloads)
{
    //sort...
}
// implement in maybe ParameterOverloadsChooser.cs?
var parameterLists = GetOverloadParameterLists(...).Append(parameters).Sort(//by length, in order);

var parameterListDivisions = new HashSet<IList<IList<Parameter>>>(); // divide parameter lists by sequence, see rule #6 above
while (parameterLists.Count > 0)
{
    var division = new List<List<Parameer>>();
    division.Add(parameterLists.Pop()); // push the shortest to new division
    for (var i = 0; i < parameterLists.Count; i ++)
    {
        if (IsSubsequence(division.Last(), parameterLists[i])
        {
            // remove from Parameter List
            // add to division
        }
    }
    parameterListDivisions.Add(division);
}

foreach (var division in parameterListDivisions)
{
    // remove sequence having the same length in each division
    for (var i  = 0; i <division.Count - 1; i ++)
    {
        if (division[i].Count == division[i+1].Count)
        {
             //remove division[i]
        }
    }

    // make all parameters except those in last list required
    for (var i  = 0; i <division.Count - 1; i ++)
    {
        // make parameters required
    }
}
```

**Comment by archerzz** [comment]
LLC has the requirement: https://github.com/Azure/autorest.csharp/issues/1659

Both mgmt plan and LLC should share some common codes: https://github.com/Azure/autorest.csharp/issues/1658

**Comment by archerzz** [comment]
## About Property Bag

### Criteria

**TODO FIXME**
- optional parameter count == 3?

### How to

Before we divide all parameter lists into branches and do the filtering, remove any parameter list which triggers property bag wrapping, except the last one. Because if a previous version triggers wrapping, then the last one should trigger the wrapping as well. Then we don't need previous versions.

For example, 

Version | Parameters
---|---
v1 | A,B,C,D*,E*
v2 | A,B,C,D*,E*,F*
v3 | A,B,C,D*,E*,F*,G*
Expected Overloads | A,B,C,D*,E* (this is the last of a branch, so won't make all parameter required)
| | A,B,C,Bag

**Comment by blueww** [comment]
The above design from @archerzz  is generally good to me.
The parameter name "StorageAccountCollectionCreateOrUpdateOptions" might be too long, and createorUpdate is actually on account , so "StorageAccountCreateOrUpdateOptions" might be better

**Comment by annelo-msft** [comment]
Hi @archerzz, this is a great discussion -- thank you for organizing this!  I have a few comments from the data plane side:
- In data plane generated code, we do not use property bags.  These can be added to generated clients via manually-written convenience APIs.
- In cases 5 and 6, you show that we change the ordering of parameters that might be of the same type.  This could have the following problem:

In v1, the client is like this:
```csharp
class Client {
    Response DoThing(string a, string b, RequestContext context = default);
}
```
If `a` becomes optional in v2, the generator would create the client as:
```csharp
class Client {
    Response DoThing(string b, string a=default, RequestContext context = default);
}
```
Anyone caller whose application was doing ` DoThing(myAValue, myBValue);` would pass the wrong values for `a` and `b` in v2, with no compiler warnings - this is a behavioral breaking change.

I have suggested the following guidance for data plane generated code:  [Version-Aware Generated Methods: Optional Parameters](https://gist.github.com/annelo-msft/827658b363941fdde699ac3925dd6ccf).  I am interested to hear your thoughts on this slightly-modified design!

**Comment by archerzz** [comment]
@annelo-msft Agree with your comments. For the mgmt plane, the only extra work item is the property bag which can be implemented separately. Let's move parameter overload discussion to the gist you've pasted.

**Comment by Yao725** [comment]
## How to keep the code compatibility when implementing property bag
**(Updated based on offline discussion on April 29, 2022)**

Currently We are trying to implement the `property bag` feature in mgmt. plane. One of the issues here is how we can ensure the compatibility of our code. Considering that we are in the process of continually GA more RPs, I think this issue can be devided into two parts, that is, the `non-GAed RP` and `GAed RP`.

- ### 1 non-GAed RP
As the RP is still in preview, so the breaking changes are allowed, so we can just change the method signature, below is an example in `Azure.ResourceManager.Cdn`.
### Before
```csharp
public virtual async Task<Response<MetricsResponse>> GetLogAnalyticsMetricsAsync(IEnumerable<LogMetric> metrics, DateTimeOffset dateTimeBegin, DateTimeOffset dateTimeEnd, LogMetricsGranularity granularity, IEnumerable<string> customDomains, IEnumerable<string> protocols, IEnumerable<LogMetricsGroupBy> groupBy = null, IEnumerable<string> continents = null, IEnumerable<string> countryOrRegions = null, CancellationToken cancellationToken = default){}
```
### After
```csharp
public virtual async Task<Response<MetricsResponse>> GetLogAnalyticsMetricsAsync(IEnumerable<LogMetric> metrics, DateTimeOffset dateTimeBegin, DateTimeOffset dateTimeEnd, LogMetricsGranularity granularity, IEnumerable<string> customDomains, IEnumerable<string> protocols, LogAnalyticsGetLogAnalyticsMetricsOptions options, CancellationToken cancellationToken = default){}
```
- ### 2 GAed RP
As this RP is already GAed, we can't simply delete the old method and add the new method, and because we haven't implemented parameter overloading, so the customization is needed. For now, I think we might have two scenarios here and in the following I will use the following method in `Azure.ResourceManager` as an example.
-  #### Scenario 1
Scenario 1 is that We started with the method with one optional parameter, which then became two, three and up to multiple. In this scenario we need to consider the history of this method and provide the fully parameter overloads when we want to turn the optional parameters that are greater than two into property bag.
### Before
```csharp
// v1
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, CancellationToken cancellationToken = default){}
// v2
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, bool? recurse = null, CancellationToken cancellationToken = default){}
// v3
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, bool? recurse = null, string filter = null, CancellationToken cancellationToken = default){}
// v4
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, bool? recurse = null, string filter = null, string cacheControl = null, CancellationToken cancellationToken = default){}
```
### After
```csharp
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupGetOptions options, CancellationToken cancellationToken = default){}
// Customization
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, bool? recurse = null, string filter = null, string cacheControl = null, CancellationToken cancellationToken = default){}
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand, bool? recurse, string filter, CancellationToken cancellationToken){}
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand, bool? recurse, CancellationToken cancellationToken){}
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand, CancellationToken cancellationToken){}
```
-  #### Scenario 2
Scenario 2 is that we only start with one method in the history and it meets the criteria of the property bag. In this case, we keep the new generated method same as the scenario 1 and only need to add one customized method.
### Before
```csharp
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, bool? recurse = null, string filter = null, string cacheControl = null, CancellationToken cancellationToken = default){}
```
### After
```csharp
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupGetOptions options, CancellationToken cancellationToken = default){}
// Customization
public virtual async Task<Response<ManagementGroupResource>> GetAsync(string groupId, ManagementGroupExpandType? expand = null, bool? recurse = null, string filter = null, string cacheControl = null, CancellationToken cancellationToken = default){}
```

**Comment by archerzz** [comment]
@Yao725 Thanks for the update. So the conclusion is that:
- Option class is always required.
- When parameter overloading is involved:
  - we keep the latest overload version as-is
  - for all the prior versions, the optional parameters will be changed to required

And I think we cover the following use cases without ambiguity:
- Users only invoke with required parameters, e.g. `GetAsync(groupId)`
- Users skip some optional parameters using named parameters, e.g. `GetAsync(groupId, filter:abc)`
- Users skip some optional parameters using `null`, e.g. `GetAsync(gropuId, null, cancellationToken)`
- Users use option class, e.g. `GetAsync(groupId, new ManagementGroupGetOptions{})`

**Comment by ArthurMa1978** [comment]
Need align with DPG

**Comment by ArthurMa1978** [comment]
We have new solution for overload, #3596
