### ISSUE TITLE
[Doc] Tutorial - E2E sample of create VM and then mock test

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1631]
Build an e2e scenario that mocks our library including mocking some of the extension static methods

**Comment by ArthurMa1978** [comment]
https://medium.com/@martinrybak/how-to-mock-singletons-and-static-methods-in-unit-tests-cbe915933c7d this might the solution to mock static methods

**Comment by ArthurMa1978** [comment]
https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2022
Will use Microsoft Fakes to support mock test static methods, will provide doc for it

**Comment by dvbb** [comment]
Using [Microsoft Fakes shims ](https://docs.microsoft.com/en-us/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing?view=vs-2022) mock static methods of static class.

1. Add Fakes Assembly
In Solution Explorer, open your unit test project's references and select the reference to the assembly that contains the method you want to fake.
like that:
Azure.ResourceManager.XX.Tests -> Dependencies -> netcoreapp3.1 -> Projects -> Azure.ResourceManager.XX -> Right-click and select `Add Fakes Assembly`

2. Coding unit test
```
[Test]
public void ArmClientMockTest()
{
    using (ShimsContext.Create())
    {
        ShimArmClientExtensions.GetWebPubSubArmClientResourceIdentifier =
            (armClient, id) =>
                {
                    // This delegate will replace the original GetWebPubSub() method
                    WebPubSub webPubSub = armClient.UseClientContext((uri, credential, clientOptions, pipeline) => new WebPubSub(clientOptions, credential, uri, pipeline, id));
                    webPubSub.Data.Sku = new WebPubSubSku("Gen2");
                    webPubSub.Data.Location = AzureLocation.EastUS2;
                    return webPubSub;
                };
        ArmClient armClient = GetArmClient();
        ResourceIdentifier id = null;
        var webPubSub =  armClient.GetWebPubSub(id);
        Assert.IsNotNull(webPubSub);
        Assert.AreEqual("Gen2",webPubSub.Data.Sku.ToString());
        Assert.AreEqual("EastUS2", webPubSub.Data.Location.ToString());
    }
}
```
​Like the code above, we can write a new delegate to replace the original method.
