### ISSUE TITLE
See if we can consolidate ErrorResponse with the ResponseError in Azure.Core

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1636]
We are currently using https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L285 which doesn't match with the Azure.Core version here https://apiview.dev/Assemblies/Review/b67e68cfee4841bda045f895c90ad383#Azure.Core.ResponseError

We should investigate if / how we can conslidate these

**Comment by fengzhou-msft** [comment]
We're not doing this considering the complexity and effort needed.
