### ISSUE TITLE
Support setting headers in requests

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1638]
This is from Citrix customers. They want the ability to set some custom headers in requests for analytics purpose.
More specifically, we have two scenarios:
1. Allow Govind to identify
     all individual requests made as part of a broader “batch”.  It sounds
     like correlation ID might be the right solution for this scenario.

2. Allow Govind to identify
     all individual requests made as part of CVAD workload management. 
     This scenario is more like the x-ms-client-scenario-id header that we
     introduced for Azure Resource Graph queries.  Is the scenario ID
     header supported for CRM APIs?  If not, is there an equivalent?

**Comment by ArthurMa1978** [comment]
Proposal: Use policy, need a doc.

**Comment by archerzz** [comment]
There is already a doc in `Azure.Core` about how to use policy: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md

Anyway, I create a PR to improve it: https://github.com/Azure/azure-sdk-for-net/pull/26095
