### ISSUE TITLE
[feature]: group optional query parameters into a single option class

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1641]
# Description
Right now we flatten all query parameters into the corresponding operation methods, which has two issues:

- Adding new optional parameters could cause breaking change in method signature. Although we've raised linter rule to swagger review, but that's not guaranteed and cannot be applied to already published API specs.
- It can help to avoid name conflicts when the method names and parameter list are the same. If we group optional query parameters into a unique option class, then it's almost impossible to have the same parameter list.

# Design
For each API method:

- If there is at least one optional query parameter, create an option class which contains all the optional query parameters.
- The option class is named after `{ResourceType}{Operation}Options`.

**Comment by ArthurMa1978** [comment]
Dup with https://github.com/azure/autorest.csharp/issues/1630, close it
