### ISSUE TITLE
Add overloads generation for data-plane codegen (aka LLC)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#1659]
Needs https://github.com/Azure/autorest.csharp/issues/1658

Timeline Jan 2022

**Comment by lirenhe** [comment]
Do we still need this?

**Comment by lmazuel** [comment]
This issue was about versionning support in spirit (a new parameter added will auto-create an overload), so I think we still need it indeed.

cc @m-nash

**Comment by chunyu3** [comment]
Close this because we will support this in typespec versioning and resilience operation/models.
