### ISSUE TITLE
[LLC] Move RequestOptions into Core

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#1666]
To properly resolve Azure/azure-sdk-for-net#25125 we'd like to use `RequestContext` or `RequestOptions` to indicate that the caller doesn't want to throw, but instead get the raw response back with the 404 status code.

**Comment by annelo-msft** [comment]
Needed by Storage as well for: https://github.com/Azure/azure-sdk-for-net/issues/21511
