### ISSUE TITLE
Duplicated property name in generated model class

### ISSUE THREAD

**Issue by hquangthinh** [Azure/autorest.csharp#1667]
A valid swagger file version 2 contains following model definition

`"Erp.Tablesets.CustXPrtRow": {
  "type": "object",
  "properties": {
    "Company": {
      "description": "Company Identifier.",
      "type": "string"
    },
    "PartDescription": {
      "description": "Description Customer uses to describes the Part.",
      "type": "string"
    },
    "PartPartDescription": {
      "type": "string"
    }
  }
}`

This will generate a model class name ErpTablesetsCustXPrtRow with 2 properties PartDescription which will cause compile error

Can we keep property name as is because my use case is I don't author the swagger file

I attach herewith a full swagger file
[Erp.BO.CustomerPartXRefSvc.json.txt](https://github.com/Azure/autorest.csharp/files/7493588/Erp.BO.CustomerPartXRefSvc.json.txt)

**Comment by AlexanderSher** [comment]
Closing since https://github.com/Azure/autorest/issues/4363 is resolved.
