### ISSUE TITLE
[LLC] Update Generator to use the new LRO pattern

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1684]
Per the [.NET Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-lro-prefix), methods that initiate a long-running operation on the service should begin with the `Start` prefix.

**Comment by KrzysztofCwalina** [comment]
Are we generating short-LROs? If yes, they don't start with the "Start" prefix.

**Comment by annelo-msft** [comment]
@AlexanderSher, have you had a change to reach out to the .NET team to learn about the recent changes to LROs, including short LROs, and how they interact with the LRO generation story in LLC?

**Comment by annelo-msft** [comment]
@KrzysztofCwalina do you know if there are any updated guidelines on short LROs, or where the latest guidance can be found on this?

**Comment by annelo-msft** [comment]
Currently blocked on: https://github.com/Azure/azure-sdk/issues/3662

**Comment by annelo-msft** [comment]
The outcome has been decided:

https://github.com/Azure/azure-sdk/issues/3662#issuecomment-985112894

All LROs will use the pattern:

```csharp
public async virtual Task<DoThingOperation> DoThingAsync(
	bool waitForCompletion,
	int requiredParam,
 	bool optionalParam = false,
	CancellationToken cancellationToken = default)
```

The parameter name for `waitForCompletion` remains to be decided.

**Comment by annelo-msft** [comment]
Closed with https://github.com/Azure/autorest.csharp/pull/1764
