### ISSUE TITLE
duplicate method name

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#1698]
I'm working on https://github.com/Azure/azure-sdk-for-net/pull/25386/ and came across this today. It can be reproduced from that branch.

This is the description for [WorkloadNetwoks_ListDhcp](https://github.com/Azure/azure-rest-api-specs/blob/564d0137d08defea63d9de2413ef5336fbfe2e6d/specification/vmware/resource-manager/Microsoft.AVS/stable/2021-12-01/vmware.json#L2150-L2159). The method should be named `ListWorkloadNetworkDhcpAsync`, not `GetWorkloadNetworkDhcpAsync`.

https://github.com/Azure/azure-sdk-for-net/blob/deb889a6423f7035a1fd1ed74df08f97674c1e9e/sdk/avs/Azure.ResourceManager.Avs/src/Generated/PrivateCloud.cs#L844-L847

**Comment by ArcturusZhang** [comment]
Hi @cataggar , this issue has been fixed.
And due to the standard of DotNet and DotNet SDK, we cannot use the keyword `List`, instead of using `List[Resources]` we are using `Get[Resources]` now if it is not in a collection class.
