### ISSUE TITLE
[LLC] Rename --low-level-client flag to --data-plane

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1700]
This parallels managment plane flag called `--azure-arm`

**Comment by AlexanderSher** [comment]
Does it mean that `--data-plane==true` is `--low-level-client==false`?

**Comment by annelo-msft** [comment]
No ... `--low-level-client=true` means the same as `--data-plane=true` ... this is part of the LLC renaming effort.

**Comment by chunyu3** [comment]
So --data-plan=true will call LowLevelTarget, --azure-arm=true will call MgmtTarget, other will call DataPlaneTarget. 
the flag may not consistent with our target name, Is there any plan to rename the target accordingly?

**Comment by annelo-msft** [comment]
I think over time we'll merge LowLevelTarget and DataPlaneTarget -- this will require development of the model-generation story, which we will address after RC3.

I'll defer to @AlexanderSher on whether it makes sense to make changes internally to the generator as part of this change -- my vote would be not to, just to reduce churn in the change, but I understand there may be other considerations here.

**Comment by annelo-msft** [comment]
Closed with https://github.com/Azure/autorest.csharp/pull/1739
