### ISSUE TITLE
Hierarchical non-resource

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1703]
We have seen that cases that Non-Resources can have hierarchical structure (but should not happen in RPaaS RPs).
We could wrap the non-resource as a pesudo-resource with a fake ID made up from its request path. When doing this, we need to check if the corresponding ResourceData has ID property, if not, we need to something different in the constructor

Example here:
- https://github.com/Azure/azure-rest-api-specs/blob/c506d992d4540ef0a66711e794b2629c4f0960d0/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/sharedGallery.json#L226
- https://github.com/Azure/azure-rest-api-specs/blob/c506d992d4540ef0a66711e794b2629c4f0960d0/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/sharedGallery.json#L272
- https://github.com/Azure/azure-rest-api-specs/blob/c506d992d4540ef0a66711e794b2629c4f0960d0/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/sharedGallery.json#L325

**Comment by ArthurMa1978** [comment]
Should improve the request-path-to-resource-data config

**Comment by ArthurMa1978** [comment]
Manual fix before GA
