### ISSUE TITLE
Rename the body parameter model if it appears only in the request

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1726]
If a model that only appears in the body parameter but is not the return type, we need to rename it in this pattern: `[ResourceName][OperationName]Options`, for instance, `AccountUpdateOptions`, where `Account` is the resource name, `Update` is the operation name, `Options` is the fixed suffix.

**Comment by ArthurMa1978** [comment]
1. Modular has property which indicate the parameter is input only or not, can leverage this to implement this feature.
2. High risk if service team change the parameter definition

**Comment by ArthurMa1978** [comment]
@m-nash how can we do if service team make break change that change the parameter definition?

**Comment by ArthurMa1978** [comment]
As we can manually rename it by using directive, so postpone it
