### ISSUE TITLE
Replace effective same enumeration type with the one provided by System namespace

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1731]
For instance, we have an enum type in Sql RP `DayOfWeek` which provides `Sunday`, `Monday`, etc... we could replace this either with the one in System namespace which provides the same enum values.

Also the `DayOfWeek` in Sql needs to be defined inextensible enum

**Comment by ArthurMa1978** [comment]
Need to confirm this is a required feature or not, if yes then breaking change and should be fixed before GA

**Comment by archerzz** [comment]
This can be part of #1629 But let's get confirmation, before we add this as child item.

**Comment by ArthurMa1978** [comment]
dup with #1727 , close
