### ISSUE TITLE
Enable select HLC methods to use RequestOptions

### ISSUE THREAD

**Issue by tg-msft** [Azure/autorest.csharp#1734]
We want to enable select HLC methods to use `RequestOptions` (https://github.com/Azure/azure-sdk-for-net/issues/25626) and need to figure out the best way to support that via AutoRest.  I'd prefer not to generate the ENTIRE protocol layer for Storage just to call two of those methods.  Maybe we could do something like add an annotation that either takes a `RequestOptions` param to existing HLC generated methods, switches to the LLC generator for that method, or any other option that's cheap to implement?  This work item is currently just to track the scenario rather than ask for a specific design.

**Comment by annelo-msft** [comment]
Addressed with: https://github.com/Azure/autorest.csharp/pull/1991
