### ISSUE TITLE
[LLC] Generator creates duplicate when two MIME types are listed in consumes block

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1746]
#### Repro

Generate a client from this swagger file: https://github.com/Azure/autorest.testserver/blob/main/swagger/dpg-update1.json#L43

#### Actual result

Two identical methods are created for:
1. PostParametersAsync
2. PostParameters
3. CreatePostParametersRequest

#### Expected result

One method should be created that has the contentType parameter, allow the user to specify one or the other of the MIME types.

**Comment by fengzhou-msft** [comment]
Modelerfour changes for this issue: https://github.com/Azure/autorest/pull/4405, we will need to update the generator to leverage the new `requestMediaTypes` entry.

**Comment by lirenhe** [comment]
@annelo-msft, it looks this link is broken: https://github.com/Azure/autorest.testserver/blob/main/swagger/llc_update1.json#L43
Could you help to update it?

**Comment by pshao25** [comment]
> @annelo-msft, it looks this link is broken: https://github.com/Azure/autorest.testserver/blob/main/swagger/llc_update1.json#L43 Could you help to update it?

Updated. It changes to https://github.com/Azure/autorest.testserver/blob/main/swagger/dpg-update1.json

**Comment by annelo-msft** [comment]
Thank you, @pshao25! :)

**Comment by lirenhe** [comment]
The original PR was reverted due to the apply of the latest of m4 and autorest.core.  @pshao25,  could you take a look on how to add the fix back?
