### ISSUE TITLE
[LLC] Make --data-plane the default setting

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1769]
We have [recently renamed](https://github.com/azure/autorest.csharp/issues/1700) the `--low-level-client` configuration setting to `--data-plane`, in order to reflect the rename of LLC to Data Plane Code Generation.  This issue tracks taking this a step further and making --data-plane the default setting.  In order to do this, we will need to do the following:

- [ ] Introduce a new setting to represent the current default for HLCs (possibly something like `--legacy-convenience-client`?)
- [ ] Change the generator default to `--data-plane` when a setting is absent
- [ ] Update all existing HLC generator readme.md files to use the new setting

**Comment by annelo-msft** [comment]
@AlexanderSher FYI

**Comment by chunyu3** [comment]
we will use generation1-convenience-client for HLC target tag

**Comment by chunyu3** [comment]
PR: https://github.com/Azure/autorest.csharp/pull/2146
