### ISSUE TITLE
[Management Plane] Move required query parameters in parameter ordering

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1771]
Per offline discussion, update query parameter position in method signature to align with [data plane ordering](https://github.com/azure/autorest.csharp/issues/1765):

1. (waitForCompletion)
2. (required path and query parameters)
    a. Required path parameters, sorted to match the order of the URI
    b. Remaining required query params will come in the order they are defined in swagger after the path parameters
3. (RequestContent)/ Body parameters
4. (ContentType) – not used by management plane
5. (optional path and query parameters)
6. ([Match|Request]Conditions)
7. RequestContext

**Comment by ArthurMa1978** [comment]
@annelo-msft do you think that mgmt. plane also need to follow LLC pattern?  This is issue belong to the LLC Epics now.

**Comment by annelo-msft** [comment]
Hi @ArthurMa1978!  Yes, @m-nash and I discussed that management plane and data plane could align on parameter ordering with this small change to management plane -- we are making a change on the data plane side to converge with this as well as part of https://github.com/azure/autorest.csharp/issues/1765.  The reason we would like to do this is to make it possible for management plane and data plane to eventually converge to use the same generator code -- this wouldn't be possible if we didn't use the same parameter ordering.

You are right that it probably shouldn't be part of an LLC epic - could you recommend a management plane epic that we could add it to instead?

**Comment by archerzz** [comment]
I think this issue should have been resolved in #1843

**Comment by annelo-msft** [comment]
@AlexanderSher, we have item 5 listed as "optional path and query params" -- is there an example of valid optional path parameters?  Wouldn't this result in a malformed URI segment?

**Comment by annelo-msft** [comment]
@m-nash can you confirm that this issue has been closed?

**Comment by m-nash** [comment]
yeah this is completed from mgmt point of view

**Comment by annelo-msft** [comment]
Thank you, @m-nash !
