### ISSUE TITLE
[Data Plane Code Gen] Add support for generating v2 client when an optional parameter is added to an operation

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1786]
This issue tracks the work to enable the generator to generate a v2 client when an optional parameter is added to an operation, or a required parameter changes to optional.

The design we propose to enable the generator to handle these API evolutions automatically is:

When an optional parameter is added to an operation DoThing from vi to vi+1, the generator should do the following:

The design we propose to enable the generator to handle these API evolutions automatically is:

1. When an optional parameter is added to an operation `DoThing` from **v<sub>i</sub>** to **v<sub>i+1</sub>**, the generator should do the following:

    1. Make all parameters in the **v<sub>i</sub>** `DoThing` method signature required on the **v<sub>i+1</sub>** client.
    2. Add an overload to the `DoThing` method group on the **v<sub>i+1</sub>** client with the same set of parameters as in the **v<sub>i</sub>** method, maintaining the required/optional status for each.  Add the new optional parameter at the end of the [optional path and query parameters](https://github.com/azure/autorest.csharp/issues/1771#issue-1077102837) list in the new overload.

2. When a required parameter is changed to an optional parameter on an operation `DoThing` from **v<sub>i</sub>** to **v<sub>i+1</sub>**, the generator should do the following:

    1. If the parameter is in the last position on the required path and query parameter list, no new overload is added, but the parameter will be made optional by giving it a default parameter on the **v<sub>i+1</sub>** client.
    2. If the parameter is in a non-last position, a warning will be raised to the operator that the generator cannot handle this case automatically and they will need to manually add a convenience overload to handle this case.

The discussion in [this gist](https://gist.github.com/annelo-msft/827658b363941fdde699ac3925dd6ccf) explains how we arrived at this guidance.

**Comment by annelo-msft** [comment]
Additional guidance is available in this gist: https://gist.github.com/annelo-msft/827658b363941fdde699ac3925dd6ccf

**Comment by chunyu3** [comment]
We will support in Multiple api-version. close this.
