### ISSUE TITLE
[feature] support check name availability request in each resource collection

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1821]
## Description

This is a follow-up of #1651. We decided that:
1. We will not provide a generic check name availability operation in `ResourceManager`.
2. For each RP, its check name availability request will be only available for specific types. So we could generate the corresponding check name availability method in the collection class.

**Comment by ArthurMa1978** [comment]
Use directive to manually do this, need to go through all RPs

**Comment by ArthurMa1978** [comment]
Manually rename the checkNameAvaliablity to check<RP namespace>NameAvaliablity, no tool change

**Comment by archerzz** [comment]
SDKs require renaming check name availability:

- appservice: https://github.com/Azure/azure-sdk-for-net/pull/26407
- appconfiguration: https://github.com/Azure/azure-sdk-for-net/pull/26464
- cdn: https://github.com/Azure/azure-sdk-for-net/pull/26404
- communication: https://github.com/Azure/azure-sdk-for-net/pull/26463
- deviceupdate: https://github.com/Azure/azure-sdk-for-net/pull/26410
- keyvault:
- servicebus: https://github.com/Azure/azure-sdk-for-net/pull/26411
- storage: https://github.com/Azure/azure-sdk-for-net/pull/26412
- webpubsub: https://github.com/Azure/azure-sdk-for-net/pull/26413
