### ISSUE TITLE
[Data Plane] Duplication method issue when a request has two media type

### ISSUE THREAD

**Issue by Yao725** [Azure/autorest.csharp#1826]
After upgrading the autorest.testserver to the latest version 3.1.10, a duplication method issue will occurs when re-generating the TestServerProjects `media_types`.
In this [request path](https://github.com/Azure/autorest.testserver/blob/7cc7cafe7dfc110206222262c72ce6f8425ee124/swagger/media_types.json#L134), two [media types](https://github.com/Azure/autorest.testserver/blob/7cc7cafe7dfc110206222262c72ce6f8425ee124/swagger/media_types.json#L138) `text/plain` and `application/json` are included. Here the generator will generate two method with same parameters and the compile will fail.

**Comment by AlexanderSher** [comment]
@Yao725 is this bug still accurate?

**Comment by Yao725** [comment]
@AlexanderSher , I believe this should be fixed by #2232, so I will close this issue.
