### ISSUE TITLE
Sort parameters ordering

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1843]
[1771](https://github.com/Azure/autorest.csharp/issues/1771)

We need to sort the 2, 3 in above issue

**Comment by archerzz** [comment]
M4 has already sorted the original parameters to put required ones first. What we need to do:

- Split the parameters into two groups: required, and optional.
- In the required parameters, find the body parameter, and move it to the last position if found.
- Merge the required and optional parameters

**Comment by ArthurMa1978** [comment]
Already done

**Comment by archerzz** [comment]
There is still work to do on the mgmt plane.

- In LLC, the sorting is done in [buildContext.OrderedParameters](https://github.com/Azure/autorest.csharp/blob/4be41a9709ce49e840df8285b04f70a928496c01/src/AutoRest.CSharp/Common/Output/Models/RestClientBuilder.cs#L98)
- In mgmt/old data plane, the sorting is not fully implemented. The sorting is done in [BuildMethodParameters](https://github.com/Azure/autorest.csharp/blob/4be41a9709ce49e840df8285b04f70a928496c01/src/AutoRest.CSharp/Common/Output/Models/RestClientBuilder.cs#L115) which will invoke [OrderParameters](https://github.com/Azure/autorest.csharp/blob/4be41a9709ce49e840df8285b04f70a928496c01/src/AutoRest.CSharp/Common/Output/Models/RestClientBuilder.cs#L524). But `OrderParameters` only move optional parameters at the bottom.
