### ISSUE TITLE
Support different versions of common types

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#1856]
Today we are generating v2 of the common types only and placing them into Azure.ResourceManager.Models, which will have issues in the long term: there are two other versions of the common types and each RP snaps to a different version and some RPs snap to multiple versions.  We will eventually need to generate something that works for all of them since customers can include RPs that snap to different types in their program.

**Comment by ArthurMa1978** [comment]
In common-types\resource-management swagger there have 4 versions, and currently autorest.csharp take v2, ARM team prefer service team to use v3 but still lots of RPs are using v2, or even v1.
To mgmt. sdk, the major change between v2 and v3 is the common type 'Resource', v3 add a new property 'systemData', so what we want to do is keeping using v2 for GA, then after GA we can upgrade to support v3 which need us to upgrade the matching algorithm that can be compatible with both v2 and v3.
