### ISSUE TITLE
Remove the ClientDiagnostic param from RestOperations in mgmt generation

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#1897]
**Describe the issue or request**
This parameter is only used to create the exceptions which now have a public ctor

https://github.com/Azure/autorest.csharp/pull/1896#discussion_r789056041

**Comment by RodgeFu** [comment]
Already resolved in https://github.com/Azure/autorest.csharp/commit/f8e4aebaca03b812b6ce82d2e032667dd19c8a52#diff-b77ce14c73a18223de207ec2c655ef058685b81e731ab87b4df946624f1fa674
