### ISSUE TITLE
Refactor to split the internal `XXXExtensionClient` into multiple for clarity

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1900]
Now we generated a really big client for all the operations that should go into `RPExtensions`. We could split it into different classes to give us more clarity

**Comment by ArthurMa1978** [comment]
As we have already release 80+ stable RPs, so it's hard to make such a big change that will introduce breaking changes.
Put to backlog, need further discussion.

**Comment by ArcturusZhang** [comment]
This issue is related to the "mock extension method". Our approach is probably "making the extension clients public", so that our customer could mock the extension client, and corresponding the extension method will be the mock version.
In order to do that, we need to organize the extension clients so that they would not be messy
