### ISSUE TITLE
Omit the patch operation of resource that only contains `tags`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1922]
Since we introduced `tags` manipulation helper method, we do not have to introduce a Update method if it can only update the tags which introduce confusions to our customers.

The solution might be we could identify this in the generator and do not generate the Update method if it only updates tags.
In the future if they introduces something more in the update method, this condition will no longer meet, the function will show up again

**Comment by ArthurMa1978** [comment]
Omit here means make these kind of update methods internal
