### ISSUE TITLE
`apiVersion` parameter is missing from rest operation class of singleton resource

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#1938]
## Problem

See the definition of this [singleton resource](https://github.com/Azure/azure-rest-api-specs/blob/b2f2423182b461f9b556ff68e9db7e93085eda7f/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/firewallPolicy.json#L623). The constructor of the corresponding rest operation class is as follows.

```csharp
public FirewallPoliciesRestOperations(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string applicationId, Uri endpoint = null, string apiVersion = default)
```

It should have an `apiVersion` at the end. Otherwise, there will be compilation error in its resource class.

```csharp
internal SignaturesOverrides(ArmClient armClient, ResourceIdentifier id) : base(armClient, id)
        {
            _signaturesOverridesFirewallPolicyIdpsSignaturesOverridesClientDiagnostics = new ClientDiagnostics("Azure.ResourceManager.Network", ResourceType.Namespace, DiagnosticOptions);
            ArmClient.TryGetApiVersion(ResourceType, out string signaturesOverridesFirewallPolicyIdpsSignaturesOverridesApiVersion);
            // the following line cannot compile
            _signaturesOverridesFirewallPolicyIdpsSignaturesOverridesRestClient = new FirewallPolicyIdpsSignaturesOverridesRestOperations(_signaturesOverridesFirewallPolicyIdpsSignaturesOverridesClientDiagnostics, Pipeline, DiagnosticOptions.ApplicationId, BaseUri, signaturesOverridesFirewallPolicyIdpsSignaturesOverridesApiVersion);
            #if DEBUG
	    ValidateResourceId(Id);
            #endif
        }
```

**Comment by archerzz** [comment]
The problem still exists in the latest generated codes. 
Here is the current signature:
> public FirewallPolicyIdpsSignaturesOverridesRestOperations(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string applicationId, Uri endpoint = null)

Here is the expected signature:
> public FirewallPolicyIdpsSignaturesOverridesRestOperations(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string applicationId, Uri endpoint = null, string apiVersion = default)

**Comment by archerzz** [comment]
I think one root cause is that the `apiVersion` parameter is not defined in the corresponding API, which seems an issue in swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/b2f2423182b461f9b556ff68e9db7e93085eda7f/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/firewallPolicy.json#L623

**Comment by archerzz** [comment]
Filed an issue on `azure-rest-api-specs`: https://github.com/Azure/azure-rest-api-specs/issues/18128

**Comment by archerzz** [comment]
For track2 SDK GA, we will not adopt the latest REST API spec of `network`.

**Comment by fengzhou-msft** [comment]
Swagger fixed in latest version and there is a new [linter rule](https://github.com/Azure/azure-openapi-validator/issues/297) requested for mandatory api-version query parameter.
