### ISSUE TITLE
Experiment Metrics Advisor (developer driven evolution)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#1943]
As an experiment to confirm that DPG can grow to a meaningful SDK, we want to experiment on Metrics Advisor:
- Generate DPG of Metrics Advisor
- Grow the SDK to feature equivalence to the current SDK. To confirm feature equivalence, the testsuite needs to be runnable in live.

You _may_ decide to merge this work (as a refactoring), or to keep this work as an experiment that we don't merge.

Expected work is to take the _latest Swagger_ and rebuild the corresponding release.

**Comment by ShivangiReja** [comment]
I've selected some APIs from Metrics Advisor proposed in below table. My selection is based on the following reasons:

1.  APIs exposed from both MetricsAdvisorAdministrationClient and MetricsAdvisorClient
2.  Contains a mixture of all four http methods:  GET, POST, DELETE, PATCH
3. Contains create, delete, update and get operations.
4. Contains both paging and non-paging operation. (There is no LRO operation in MetricsAdvisor）

Please take a look and feel free to add/remove the APIs from below table. 

| Method Name                                     | OperationId                                   | Client                                 | Method | Return type| Parameters
|-----------------------------------------|-----------------------------------------|-----------------------------------------|-------------------------------------------------------------------------------|--------------|--------------|
| GetAllFeedback | listMetricFeedbacks | MetricsAdvisorClient               | POST   | `Pageable<MetricFeedback>`    | `string`, `GetAllFeedbackOptions`|
| GetFeedback | getMetricFeedback | MetricsAdvisorClient               | GET   | `Response<MetricFeedback>`    | `string` |
| GetMetricDimensionValues | getMetricDimension       | MetricsAdvisorClient               | POST    | `Pageable<string>`   | `string`, `string`, `GetMetricDimensionValuesOptions`|
| GetDataFeed   | getDataFeedById     | MetricsAdvisorAdministrationClient       | GET  | `Response<DataFeed>`         | `string` |
| GetDataFeeds | listDataFeeds     | MetricsAdvisorAdministrationClient              | GET  | `Pageable<DataFeed>`   | `GetDataFeedsOptions` |
| CreateDataFeed | createDataFeed     | MetricsAdvisorAdministrationClient          | POST | `Response<DataFeed>`   | `DataFeed` |
| UpdateDataFeed | updateDataFeed     | MetricsAdvisorAdministrationClient        | PATCH   | `Response<DataFeed>`  | `DataFeed` |
| DeleteDataFeed | deleteDataFeed     | MetricsAdvisorAdministrationClient         | DELETE    | `Response`  |    `string` |

**Comment by lirenhe** [comment]
@ShivangiReja, as discussed, please also help to prepare a doc for this experiment.  Thanks.

**Comment by ShivangiReja** [comment]
PR for this experiment - https://github.com/Azure/azure-sdk-for-net/pull/27363
Doc for this experiment - https://github.com/ShivangiReja/azure-sdk-for-net/blob/MetricsAdvisor-Experiment/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/developer.md
Benchmark results - https://github.com/ShivangiReja/azure-sdk-for-net/blob/MetricsAdvisor-Experiment/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/developer.md#9-test
