### ISSUE TITLE
Implement DPG core tests

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#1944]
Implement all testserver mentionned in https://github.com/Azure/autorest.testserver/wiki/Data-plane-codegen-testing in DPG testsuite.

Task is complete when there is a 100% for DPG testing in  http://azure.github.io/autorest/dashboard.html

**Comment by annelo-msft** [comment]
Test server repo: https://github.com/azure/autorest.testserver

**Comment by annelo-msft** [comment]
For developer-driven evolution, we'll need to resolve: https://github.com/Azure/autorest.csharp/issues/2014

**Comment by annelo-msft** [comment]
https://github.com/azure/autorest.csharp/issues/1787 was originally tracking service driven evolution case.

**Comment by pshao25** [comment]
We need to fix https://github.com/Azure/autorest.csharp/issues/2090.

**Comment by pshao25** [comment]
Need to finish https://github.com/Azure/autorest.csharp/issues/2132

**Comment by pshao25** [comment]
Reach to 100% coverage now.
