### ISSUE TITLE
Writing DPG customizations documentation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#1945]
As GA requirement for the project, we want to have explicitly written the documentation for service teams on how to grow-up their DPG into an improved SDK.

Documentation should be written with:
- Basics on customizations for this language
- One scenario, one section. Like a FAQ document

Required sections are (at the minimum):
- Change operation behavior (new signature, or any wrapping)
- Change client behavior (default pipeline configuration, etc.)
- Should include "option 4" HLC overload with full models (no serialization API)

More sections might be added, and I'll update this initial text with date when I add them (for clarity)

**Comment by annelo-msft** [comment]
@pshao25, @fengzhou-msft, @chunyu3, let's use the code generation customization documentation as an example to follow for the DPG customization documentation: https://github.com/Azure/autorest.csharp#c-code-generator-for-autorest-v3

Please put the documentation under: https://github.com/Azure/azure-sdk-for-net/tree/main/doc/Data%20Plane%20Code%20Generation

We'll add guidance and samples for:
- [ ] service-driven evolution @fengzhou-msft (this will later be automated [in Copper,](https://github.com/Azure/azure-sdk/issues/3910) as part of state-aware generator work)
- [ ] developer-driven evolution (Convenience grow-up methods) @pshao25 
- [ ] subclients @chunyu3

**Comment by annelo-msft** [comment]
@fengzhou-msft, @chunyu3, could you both please link your PRs for this to this issue?

**Comment by fengzhou-msft** [comment]
PR to add doc for service driven evolution: https://github.com/Azure/azure-sdk-for-net/pull/27713

**Comment by pshao25** [comment]
Dependency: https://github.com/Azure/autorest.csharp/issues/1945

**Comment by annelo-msft** [comment]
@pshao25 , @chunyu3 , could you please link the PRs implementing the parts of the documentation you're working on, like Feng did above?  Thank you!

**Comment by pshao25** [comment]
PR to add doc for developer driven evolution: https://github.com/Azure/azure-sdk-for-net/pull/27559

**Comment by lirenhe** [comment]
Doc for subclient by @chunyu3: https://github.com/Azure/azure-sdk-for-net/pull/27538

**Comment by lirenhe** [comment]
@annelo-msft , I close this item as all PRs for the related docs are merged. 
Feel free to reopen it if we need more customization docs
