### ISSUE TITLE
Flatten Single-Property objects

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1967]
In management plane its common to have objects with a single property. Sometimes we even have objects with a single property which happens to also be an object with a single property. Flattening these models introduces a lot of complexity around serializing back into exactly what the service expects. What we are planning to do in mgmt plane dotnet is to present these as wrapped properties and make the original internal which bypasses all the serialization complexity.

For a class defined as
```
public class MyObject
{
    public string Id {get; set;}
}
```
With a model that uses it like this
```
public MyObject MyObject {get; set;}
```
It will become
```
internal MyObject MyObject {get; set;}
public string MyObjectId
{
    get => MyObject.Id;
    set => MyObject.Id = value;
}
```
if someone adds a second property to MyObject we want to swap the internal back to public and then add browsable never to the wrapper property to maintain backwards compatibility. But we need to know that it was generated that way in the past

**Comment by ArcturusZhang** [comment]
Close since this is resolved by https://github.com/Azure/autorest.csharp/pull/1992
