### ISSUE TITLE
The generated client name is not PascalCasing in LLC

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2008]
The generated client name comes from laguage.default.name of root or operation group in code model. It should follow PascalCasing convention. (See section 3.1.2 in the [.NET Framework Design Guidelines](https://learning.oreilly.com/library/view/framework-design-guidelines/9780135896457/ch03.xhtml)).

Repro steps:
1. use node_modules\@microsoft.azure\autorest.testserver\swagger\dpg-customization.json to generate client.
2. Its name is DPGClient.

**Comment by lirenhe** [comment]
Pan discussed with Anne and we decided we won't fix this.
