### ISSUE TITLE
Include both protocol method and grow-up method will break user

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2014]
**Describe the issue or request**
We are considering adding both protocol method and grow-up method into DPG client. Eg.,
```
// protocol method
public virtual async Task<Response> GetModelAsync(string mode, RequestContext context = null); 
// grow-up method.
public virtual async Task<Response<Model>> GetModelAsync(string mode, CancellationToken cancellationToken = default); 

```
That will break if user calls GetModelAsync("mode") without RequestContext and CancellationToken.

This issue does not exist in post. Eg.,
```
// protocol method
public virtual async Task<Response> PostModelAsync(RequestContent requestContent, RequestContext context = null); 
// grow-up method.
public virtual async Task<Response<Model>> PostModelAsync(Input mode, CancellationToken cancellationToken = default); 
```

**Comment by annelo-msft** [comment]
In this case, if we are growing up the client from a DPG client, we will change the name of the grow-up method.  The recommended rename is `GetModelValueAsync` -- since there is a requirement that convenience methods will be reviewed by arch board instead of GA'ed, the arch board will review the new method name.

If we are adding protocol methods to an existing GA HLC, we wouldn't be able to change the name of the convenience method, we would need to change the name of the protocol method.  We could do this via C# generator transforms.

@KrzysztofCwalina, @ellismg  FYI

**Comment by KrzysztofCwalina** [comment]
I suggest that in cases where the only difference in overloads is RequestContext vs CancellationToken, we don't add the CancellationToken parameter and make the model castable from Response, i.e. I would do:

```csharp
// protocol method
public virtual async Task<Response> GetModelAsync(string mode, RequestContext context = null); 
// grow-up method.
public virtual async Task<Response<Model>> GetModelAsync(string mode); 
```
Users who want to pass a CancellationToken would do:

```csharp
Response r = clinet.GetModelAsync(mode, new RequestContxt(token));
var model = (Model)r;
```

**Comment by annelo-msft** [comment]
@KrzysztofCwalina, is the implication of this that we want to avoid using `CancellationToken` in the method signatures of all grow-up methods?  That would change what is documented here: https://github.com/ellismg/design-notes/blob/main/llc/llc-evolution.md#developer-driven-evolution

**Comment by KrzysztofCwalina** [comment]
> isn't making the model castable from Response in the https://github.com/Azure/autorest.csharp/pull/3 bucket that we will address after we have completed https://github.com/Azure/autorest.csharp/pull/4, e.g. the full grow-up story?

The way I think about it is that we postponed the official support, exploring all corner cases (e.g. casing untyped LROs to typed LROs), etc. But I think it would be totally reasonable to provide informal guidance to teams who run into simple cases like this one, unless we have a concrete concern about the informal guidance.

**Comment by KrzysztofCwalina** [comment]
> is the implication of this that we want to avoid using CancellationToken in the method signatures of all grow-up methods?

I would not go as far. The only thing I am saying is that not all helper overloads need to take cancellation tokens given the CTs are optional parameters anyway, and we know these parameters are not used in mainline scenarios. The intention of the guidelines that talk about adding cancellation tokens to all methods was that there should always be a way to cancel SDK service method calls by passing a CT, not that literally every overload takes a CTs. The latter is very not-.NET-like. In .NET rarely used optional parameters are not added to signatures of helper overloads.

**Comment by annelo-msft** [comment]
> The only thing I am saying is that not all helper overloads need to take cancellation tokens 

It feels a little arbitrary, though, that most grow-up methods would take an optional `CancellationToken`, but this specific case with no input model does not.  Would it possible to be crisp on the thinking behind when we take an optional CT parameter and when we don't?

**Comment by annelo-msft** [comment]
Re-opening per lack of clear guidance.

**Comment by KrzysztofCwalina** [comment]
What about this guidance:
1. If we run into overload conflict like described in this thread, it's ok to skip the CT from the only grow-up method.
2. If there is no overload conflict, and only one grow up method, the grow up method should take [optional] CT.
3. If there are more than one grow up methods that differ by the number of optional parameters, only the longest overload should take CT.

**Comment by annelo-msft** [comment]
I like it, thanks @KrzysztofCwalina!  

I'd still like to understand the **why** behind it, if possible.  I understand that we won't include CT in the 1. case because we want to reduce the number of CT in our APIs.  If that is the case, why would we include it in 2. and 3.?

Or is it that we don't include the CT in 1. to avoid an ambiguous overload, and in 2. and 3. we don't have that problem?

**Comment by KrzysztofCwalina** [comment]
My reasoning is the following: we want 4 things:
1. Users should be able to cancel server calls, if they want to, thus we need to have at least one overload taking CT.
2. We want to avoid having to mangle method names, i.e. avoid the "Value" suffix. 
3. Shorter parameters lists are simpler than longer ones, thus there rarely used parameter should not appear in helper overloads (this is generic .NET guideline/design-philosophy).
4. Cast operators are not visible in intellisense, and so relying on them has negative UX impact.

**Comment by annelo-msft** [comment]
Per offline discussion, we will do what was originally stated in https://github.com/Azure/autorest.csharp/issues/2014#issuecomment-1054460373 with the more general guidance listed here https://github.com/Azure/autorest.csharp/issues/2014#issuecomment-1055714190.

This is consistent with general .NET Guidelines: https://learning.oreilly.com/library/view/framework-design-guidelines/9780135896457/ch05.xhtml#sec5_1
**AVOID** having two overloads of the same method that both use default parameters.

**Comment by pshao25** [comment]
@annelo-msft @KrzysztofCwalina I have to say this design will cause a breaking change.
Say we have below currently:
```
// protocol method
public virtual async Task<Response> GetModelAsync(string mode, RequestContext context = null); 
```
Customer has a call to it as `Response result = await new DPGClient(Key, host).GetModelAsync("raw");` 

Later, we decide to add the grow-up story as current design:
```
// grow-up method.
public virtual async Task<Response<Model>> GetModelAsync(string mode); 
```

**Because C# method overload resolution will pick the one where the caller has specified all the arguments explicitly,** then the previous call `Response result = await new DPGClient(Key, host).GetModelAsync("raw");` will no longer go to protocol method any more. Instead, it will go to call the grow up method, which leads to compile error because the return value is `Response<Model>` not `Response`.

**Comment by KrzysztofCwalina** [comment]
Ah, good catch. 
Though I am not sure the proposal will work, i.e. it will be difficult to call the grow-up method. The only way to call it would be by explicitly passing a cancellation token.

**Comment by KrzysztofCwalina** [comment]
what if we did:

```csharp
// protocol method
public virtual async Task<Response> GetModelAsync(string mode, RequestContext context); 
// grow-up method.
public virtual async Task<Response<Model>> GetModelAsync(string mode, CancellationToken cancellationToken = default);
```
i.e. for bodyless requests, we don't make RequestContext optional.

BTW, I am pretty sure we had these discussions a couple of months ago. I just forgot about this issue with body-less requests.

**Comment by annelo-msft** [comment]
I prefer not using the `Value` suffix if we can avoid it ... we would need to make sure, though, that making RequestContext required  wouldn't introduce a breaking change to WebPubSub or other client.

**Comment by annelo-msft** [comment]
Per discussion in design meeting, making RequestContext required would introduce a breaking change to WebPubSub.  To make this work, we would need to know ahead of time whether we would be adding grow-up methods to a client in order to decide whether RequestContext should be required or not (since requiring it has a negative UX cost), and the premise of DPG is that we can add grow-up methods any time and may not know we need them a priori.

In our [grow-up guide](https://github.com/azure/autorest.csharp/issues/1945), we will suggest adding a suffix `Value` to the grow-up method for this case, with the official guidance being to “pick the best name for the method.”  Having a different method name will prevent the overload resolution issue.
