### ISSUE TITLE
Add a Response type that could wrap converted model and raw response

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2016]
**Describe the issue or request**
When we call directly to DPG, we will get a Response with raw information like status code, headers, etc. However, when we cast/convert Response to Model, we only extract the content from Response and change it to model. To grow up to full HLC story, we will have below method.
```
public virtual async Task<Response<Product>> GetModelValueAsync(string mode, CancellationToken cancellationToken = default)
{
    Response result = await GetModelAsync(mode);
    return Response.FromValue((Product)result, result);
}
```
In this method, we call DPG and change the Response to Model. But the return value is a Response. I think it should contain the raw Response information. Seems there is no appropriate implementation of Response. Here I choose Response.FromValue, but it returns an **internal** Type ValueResponse.

**Comment by annelo-msft** [comment]
The corresponding test case in the PR is here: https://github.com/Azure/autorest.csharp/pull/1989/files#diff-0c4e89480942d4b01d552e22e123cf84aa180917063177bd4485ef60a7cdb90cR36

**Comment by annelo-msft** [comment]
@pshao25, I'm not sure I understand the problem.  `ValueResponse<T>` is internal, but it derives from the public type `Response<T>`.  The method returns the public type.

Can you help me understand if there is something else needed?  I think using Response.FromValue is sufficient.

**Comment by pshao25** [comment]
@annelo-msft I'm just not sure and want confirm with you if this ValueResponse is good to go, because if I were the user, it would be very natural for me to check its status, get request ID, or whatever. But I couldn't get it from Response<Product> even it is called Response. Instead, I have to call the GetRawResponse(). It just makes me feel uncomfortable.

**Comment by annelo-msft** [comment]
We may consider adding a Status or HasValue property to `Response<T>`, but this is additive so won't do it now.
