### ISSUE TITLE
Add endpoint Uri property to clients generated by management plane

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2024]
Per https://github.com/Azure/azure-sdk-for-net/issues/24634, we need to add a Uri property to public client. Though the initial request is from HLC, we need to add this feature to DPG and management plane as well.

The HLC part and DPG part is tracked at https://github.com/Azure/autorest.csharp/issues/1616.

@m-nash for your information that we have separate this management part out from initial issue.

**Comment by m-nash** [comment]
This was fixed in azure-sdk-for-net since our only client is ArmClient.
