### ISSUE TITLE
Implement LRO tests for DPG test server test

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2027]
LRO part of #1944.

Blocked on https://github.com/Azure/autorest.csharp/issues/2050

- [ ] **lro** - protocol method: `public virtual Operation<BinaryData> Lro(WaitUntil waitUntil, string mode, RequestContext context = null)`
- [ ] **lro** - grow-up method: `public virtual GetProductOperation Lro(WaitUntil waitUntil, string mode)`

**Comment by annelo-msft** [comment]
@AlexanderSher will provide a helper method for Operations that is similar to PageableHelper.Select()
