### ISSUE TITLE
Document the ability to add a protocol method to a HLC SDK

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#2029]
See https://github.com/Azure/autorest.csharp/issues/1970 for the feature

Success is: a SDK devs needs to expose a protocol method in a given existing HLC, and we should provide one link to a document, and the developer should be autonomous (no ping to Alexander or Anne or Shivangi :))

**Comment by annelo-msft** [comment]
Please put the documentation under: https://github.com/Azure/azure-sdk-for-net/tree/main/doc/Data%20Plane%20Code%20Generation
