### ISSUE TITLE
Namer: Duplicate resolution

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.csharp#203]
- Recognize duplicate named types
  - Detect if name differences occur in different/hierarchical namespaces
- `member names cannot be the same as their enclosing type` resolution
- `'Range' is an ambiguous reference between 'Azure.Storage.Files.Models.V20190202.Range' and 'System.Range'` resolution

**Comment by pakrym** [comment]
Fixing specific issues on a case-by-case basis.
