### ISSUE TITLE
Update Generation for new LRO signatures

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2042]
New LRO method signatures are:

```csharp
public virtual Operation<BinaryData> DoThing(WaitUntil waitUntil, ..., RequestContext = default)
```

We will need to update the generator to make this change.

**Comment by AlexanderSher** [comment]
What should be the description of the `waitUntil` parameter?

**Comment by annelo-msft** [comment]
What about this?

<param name="waitUntil">Indicates whether this method should return once it has started the long-running operation or wait for the operation to fully complete before returning.</param>
