### ISSUE TITLE
Eliminate duplicate names that span across different packages including between data plane and mgmt. plane - For GA

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#2063]

**Comment by Yao725** [comment]
https://microsoftapc-my.sharepoint.com/:x:/g/personal/yaokou_microsoft_com/ERM4rgb_JP9Glhbl6eft0v0BNKAjPouynFDwA9MK6ETg0Q?e=51mEX1

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/27599

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/27731
