### ISSUE TITLE
Design distributed tracing scopes for pageable operations

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2075]
### Summary

In our HLC libraries, distributed tracing scopes are currently opened around every new "Get Page" network call.  For a call to get a collection of configuration settings in our AppConfig library (below), you can see that multiple sibling scopes are opened.  It is the library user's responsibility to create an outer scope to group these calls as a single logical "iterate over collection items" operation.  This is because we cannot detect when the caller is done iterating over the collection.

We will do the same thing in DPG clients as we are doing in HLC clients.

### Success criteria
- [ ] We have agreement that this is the pattern we want and don't plan to change it after GA.

### Application Insights view of distributed tracing spans
![image](https://user-images.githubusercontent.com/21269347/161307785-585b4a27-e348-4539-b944-29beff6355cb.png)

**Comment by ShivangiReja** [comment]
Outer method - https://github.com/ShivangiReja/azure-sdk-for-net/blob/MetricsAdvisor-Experiment/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorClient.cs#L72
Inner method - https://github.com/ShivangiReja/azure-sdk-for-net/blob/MetricsAdvisor-Experiment/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/MetricsAdvisorClient.cs#L1507

Here is an error I get if I add  different scopes in outer method and inner method based on the method names:

Message: 
**System.InvalidOperationException** : Expected diagnostic scope not created MetricsAdvisorClient.GetAllFeedback 
    created 2 scopes [MetricsAdvisorClient.GetMetricFeedbacks, Azure.Core.Http.Request] 
    You may have forgotten to add clientDiagnostics.CreateScope(...), set your operationId to MetricsAdvisorClient.GetAllFeedback in AsPages() implementation returned from GetAllFeedbackAsync or applied the Azure.Core.ForwardsClientCallsAttribute to AsPages() implementation returned from GetAllFeedbackAsync.

**Stack Trace**: 
DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) line 200
DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() line 262
DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() line 262
Boolean>.GetResult()
AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() line 103
AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() line 103
Boolean>.GetResult()
MetricFeedbackLiveTests.GetAllFeedbackWithMinimumSetup(Boolean useTokenCredential) line 209
MetricFeedbackLiveTests.GetAllFeedbackWithMinimumSetup(Boolean useTokenCredential) line 209
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

**Comment by annelo-msft** [comment]
Depends on https://github.com/azure/autorest.csharp/issues/2069 being solved first.

**Comment by annelo-msft** [comment]
Duplicate of https://github.com/azure/autorest.csharp/issues/2127

**Comment by annelo-msft** [comment]
@lmolkova, would you confirm that this is the design we want for DPG libraries post-GA?

**Comment by annelo-msft** [comment]
**Proposal:** We will use the same design as HLCs in DPG clients, i.e. one span for each page request.

**Comment by annelo-msft** [comment]
Approved by architects.
