### ISSUE TITLE
Test coverage lost because of call to report clear after each test

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2090]
Symptom: After testserver test #1763 merged, test coverage [report ](http://azure.github.io/autorest/dashboard.html) still says DPGAddNewOperation, DPGAddNewPath, etc. not covered.
Root cause: After each test run, we call [TestServerSession.DisposeAsync](https://github.com/Azure/autorest.csharp/blob/2886a5249cbbfcf8417948b7f4b8565a4191fee3/test/AutoRest.TestServer.Tests/Infrastructure/TestServerSession.cs#L94), in which we call [/report/clear](https://github.com/Azure/autorest.csharp/blob/2886a5249cbbfcf8417948b7f4b8565a4191fee3/test/AutoRest.TestServer.Tests/Infrastructure/TestServerV1.cs#L101) to server. This call will clear all the coverage data we collect for the previous tests.
I'm afraid we start a new test server session for each test so that previous coverage will be lost anyway.

**Comment by AlexGhiondea** [comment]
@pshao25 can you elaborate on why is this labeled blocking-release?

**Comment by pshao25** [comment]
> @pshao25 can you elaborate on why is this labeled blocking-release?

We cannot reach to 100% [coverage ](http://azure.github.io/autorest/dashboard.html)due this issue.

**Comment by lmazuel** [comment]
Hi @pshao25 
I have a feeling the way the C# testsuite is calling the testserver is not aligned with the testserver expectation. I don't think it's a testserver bug, but an integration issue on the C# side. I would suggest you talk to @timotheeguerin , and if he agrees there is a problem let's declare a bug there (on the testserver repo) and work with @timotheeguerin to fix it.
In the meantime, closing this issue.

**Comment by pshao25** [comment]
@lmazuel This is for C# test framework. I didn't see any bugs in test server so far.

We run tests in parallels. Each thread creates a new test server session.  Each test server session is responsible for several tests. So the last finished session wins to send the coverage report only containing the tests it runs. That is why DPG coverage is only 16% even we covered almost all the tests (except LRO).

We couldn't reach to 100% because of this defect.

**Comment by annelo-msft** [comment]
@pshao25, could you please add a time estimate to this issue?

**Comment by pshao25** [comment]
@annelo-msft I use this issue to track the work around we mentioned in the chat, and #2119 to track the test framework improvement in the future.
