### ISSUE TITLE
C# keywords used as variable names are not escaped

### ISSUE THREAD

**Issue by WibblyDibbler** [Azure/autorest.csharp#2096]
**Before filing a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**

The OpenAPI file is located at [https://sonicos-api.sonicwall.com/sonicos_files/default/sonicos_openapi.yml](https://sonicos-api.sonicwall.com/sonicos_files/default/sonicos_openapi.yml) (the version must be edited).  It defines the following path:
```
/sonicpoint/fairnet/policies/direction/{DIRECT}/range/{START}/{END}/interface/{IF}
```

The following was run to generate a client SDK:
```
autorest --powershell --input-file=sonicos_openapi_edited.yml --output-folder=~/Build/SonicOS --memory=16g --verbose
```

The generated code contains variables named as unescaped C# keywords, such as the following examples:
```
string if
var if
string interface
var interface
```

**Expected behavior**

When variable names use C# keywords, they should be escaped like the following:
```
string @if
```

**Additional context**

AutoRest generates over 29,000 files for this SDK.  There are file handle problems running AutoRest against this OpenAPI document on Windows 10 21H2 x64, which should be tracked separately.  This bug describes behavior when run on Ubuntu 20.04.3 x64.

The output from `autorest --version` is the following:
```
AutoRest code generation utility [cli version: 3.6.0; node: v16.14.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.8.1        /home/coinpump/.autorest/@autorest_core@3.8.1
 extension  @autorest/modelerfour                    4.15.414     /home/coinpump/.autorest/@autorest_modelerfour@4.15.414
 extension  @autorest/powershell                     3.0.480      /home/coinpump/.autorest/@autorest_powershell@3.0.480
```

**Comment by AlexanderSher** [comment]
Hi @WibblyDibbler 

I've tried a path in question from your swagger and generated code was correct:
![image](https://user-images.githubusercontent.com/8933858/174419609-b956b3a8-5dce-4c2f-ae64-429a940fe1df.png)

Can you please provide the version of autorest.csharp that you're using?
