### ISSUE TITLE
--version flag sets the core version to the autorest version that doesn't create JSON annotations

### ISSUE THREAD

**Issue by Invertisment** [Azure/autorest.csharp#2097]
I want to take an OpenAPI v3 definition file and generate C# objects with annotations for JSON processing.
But the way I made it work was odd, counterproductive and currently requires to hardcode/fetch the version.
I would have expected that sensible defaults would've existed in the first place.

Let's say this is my schema (without paths because I only needed the object definitions):
```
openapi: 3.0.0
info: {version: 0.0.1, title: Simple API, description: A simple API to illustrate OpenAPI concepts}
paths: {}
components:
  schemas:
    Artist:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string

```
If I run `autorest --csharp --input-file=schema.yaml` then the console prints this:

```
info    | AutoRest core version selected from configuration: ^3.7.0.
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/home/_/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist' (3.7.6)
```

And the object that it generates doesn't have the JSON annotations (boilerplate omitted):
```
        /// <summary> Gets the first name. </summary>
        public string FirstName { get; }
        /// <summary> Gets the last name. </summary>
        public string LastName { get; }
```

BUT if I use command `autorest --csharp --input-file=schema.yaml --version=3.0.6368` then it uses a different version of the package in the log:
```
info    | AutoRest core version selected from configuration: 3.0.6368.
   Loading AutoRest core      '/home/_/autorest/@autorestcore@3.0.6368/nodemodules/@autorest/core/dist' (3.0.6368)
```

And then it magically generates the same object but it has the annotations that I want:
```
        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

```

So where I'm going with this? 
There is a flag that will also generate these objects for Swagger 2.0 -- `--legacy`. And what it does is it sets the `--version` to the newest `@autorestcore` version that has this format: `2.0.xxxx`. 
I think that it's not enough to have that flag only for `2.0` and instead there should be a way to choose whether I want to use annotations or not.

And the the problem with my currently working command is that it won't use the newest `3.0.xxxx` package.

This could also be documented in some way. I'm not sure how you handle this kind of changes.

**Comment by timotheeguerin** [comment]
I am saying this issue is with the csharp generator. Autorest core doesn't care how the generator decide to implement serialization.
Transferred the issue to the csharp repo. If it turns our somehow that the generator is missing some information for autorest to have those attribute then it will be core problem but right now this looks like the csharp generator issue.

**Comment by AlexanderSher** [comment]
@Invertisment , can you please show the full log that you have for `autorest --csharp --input-file=schema.yaml --version=3.0.6368`?
