### ISSUE TITLE
[data-plane] when enable 'single top-level client', the name of service client is incorrect

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2099]
There are two scenarios which will generate the wrong service client name:
1. When we try to combine 'single top-level client' with 'client hierarchy' with an service which has no top-level method
swagger json:
```
{
  "swagger": "2.0",
  "info": {
    "version": "2021-10-19",
    "title": "SubClients"
  },
  "x-ms-parameterized-host": {
    "hostTemplate": "{endpoint}",
    "useSchemePrefix": true,
    "parameters": [
      {
        "$ref": "#/parameters/EndpointParameter"
      }
    ]
  },
  "schemes": [
    "https"
  ],
  "produces": [ "application/json" ],
  "consumes": [ "application/json" ],
  "paths": {
    "/client1/{cachedParameter}": {
      "get": {
        "operationId": "Client1_GetCachedParameter",
        "parameters": [
          {
            "name": "cachedParameter",
            "type": "string",
            "in": "path",
            "required": true,
            "x-ms-parameter-location": "client"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type":"string"
            }
          }
        }
      }
    },
    "/client2/{subParameter}": {
      "get": {
        "operationId": "Client2_GetSubParameter",
        "parameters": [
          {
            "name": "subParameter",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type":"string"
            }
          }
        }
      }
    }
  },
  "definitions": { },
  "parameters": { 
    "EndpointParameter": {
      "name": "endpoint",
      "in": "path",
      "required": true,
      "type": "string",
      "x-ms-skip-url-encoding": true,
      "description": "Account endpoint.",
      "x-ms-parameter-location": "client",
      "x-ms-parameter-grouping": {
        "name": "account-options"
      }
    }
  },
  "securityDefinitions": {},
  "security": [],
  "tags": []
}
```

set 'single top-level client' 

``` yaml
namespace: Azure.Service.SubClients
require: $(this-folder)/../../../readme.md
input-file: $(this-folder)/SubClients-LowLevel.json
data-plane: true
security: AzureKey
security-header-name: Fake-Subscription-Key
single-top-level-client: true
```

And add customization.cs to define 'client hierarchy'
``` c#
using Azure.Core;

namespace SubClient_LowLevel
{
    [CodeGenClient("Client2Client", ParentClient = typeof(Client1Client))]
    public partial class Client2 { }
}
```

The generated code will be
![image](https://user-images.githubusercontent.com/10458143/159635150-5232d903-63db-492c-b6d5-6b01f29c6667.png)

Because of no top-level method, there will no default top-level client for service, the parent client 'Client1Client' is promote to the single top-level client, its name should contain 'Client' as suffix. But actually it is not.

2. When there only have one operation group with name, then the generated service client name is not correct. Such testserver project body-array, it only have one operation group 'Array', when set 'single-top-level-client', it will generate the service client 'Array'. The name has no 'Client' suffix which is not correct.

**Comment by chunyu3** [comment]
The root cause is the order to create the LowLevelOutputLibrary, it call CreateClientInfo, in this function, it will check the SingleTopLevelClient flag, and mark Client1Client OperationGroup is subclient and change the client Name to 'Client1'.
Then it will call SetHierarchy method, in this method, it identified that 'Client1Client' is the only one top-level client, so it is promoted as service client, but it does not update the 'subclient' and 'clientName'. 
```
public static LowLevelOutputLibrary Create(CodeModel codeModel, BuildContext<LowLevelOutputLibrary> context)
        {
            UpdateListMethodNames(codeModel);

            var clientInfosByName = codeModel.OperationGroups
                .Select(og => CreateClientInfo(og, context))
                .ToDictionary(ci => ci.Name);

            var topLevelClientInfos = SetHierarchy(clientInfosByName, context);

           .......
     }
```

**Comment by annelo-msft** [comment]
@chunyu3 Can you add information to this issue stating:
- What is the problem (What can a service-team partner NOT do as a result of this issue)
- What is the expected behavior (given the inputs you've provided, what do you expect the output to be?)
- What is the repro?

I'd like to understand this so I can help determine whether this is a GA-blocking issue or not.

**Comment by chunyu3** [comment]
[https://github.com/Azure/autorest.csharp/pull/2256](url)
