### ISSUE TITLE
[DPG] [BUG] Azure PurviewCatalogClient constructor and other DPG Client Constructors are generated incorrectly

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2105]
### Problem

In the [Azure.Analytics.Purview.Catalog API](https://apiview.dev/Assemblies/Review/bdfd1e265f30435b8bd38e982710ad15), the constructor is generated as follows:

```csharp
public PurviewCatalogClient(Uri endpoint, TokenCredential credential, PurviewCatalogClientOptions options = null);
```

This is case for all the [DPG Clients](https://grep.app/search?q=data-plane%3A&filter[repo][0]=Azure/azure-sdk-for-net), except WebPubSubServiceClient.

### Success Criteria

All Data Plane Generated libraries have client constructors that follow [the guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-ctor), specifically:

```csharp
public PurviewCatalogClient(Uri endpoint, TokenCredential credential);
public PurviewCatalogClient(Uri endpoint, TokenCredential credential, PurviewCatalogClientOptions options);
```

**Comment by AlexanderSher** [comment]
For every type of credentials, we should generate two constructors: one that contains only client parameters without default values and one that contains all client parameters and client options:

```cs
public ServiceClient(TokenCredential credential, int param1) : this(credential, param1, true, new ServiceClientOptions()) {}
public ServiceClient(TokenCredential credential, int param1, bool param2, ServiceClientOptions options)
{
    // Constructor body
}
public ServiceClient(AzureKeyCredential credential, int param1) : this(credential, param1, true, new ServiceClientOptions()) {}
public ServiceClient(AzureKeyCredential credential, int param1, bool param2, ServiceClientOptions options)
{
    // Constructor body
}
```

If client doesn't use any credentials, there would be one pair of constructors:
```cs
public ServiceClient(int param1) : this(param1, true, new ServiceClientOptions()) {}
public ServiceClient(int param1, bool param2, ServiceClientOptions options) 
{
    // Constructor body
}
```

**Comment by annelo-msft** [comment]
I am fine with that for GA, since it should result in the success criteria in the description.  We don't currently have any DPG libraries with global parameters in the constructor, and we can revisit what the generator does in this case if we do.
