### ISSUE TITLE
Update developer-driven evolution doc with guidance on distributed tracing

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2115]
In grow-up scenarios, convenience layer will call protocol method. Both of them might need to have a diagnostic scope. We need to decide what the scope should be like. See whole conversation here:
https://github.com/Azure/azure-sdk-for-net/pull/27363#discussion_r822152875

**Comment by annelo-msft** [comment]
Guidance will be determined in resolution of https://github.com/Azure/autorest.csharp/issues/2127

**Comment by annelo-msft** [comment]
Guidance is here: https://github.com/azure/autorest.csharp/issues/2127#issuecomment-1086127240

**Comment by lirenhe** [comment]
@AlexanderSher/@annelo-msft  , as you are working on this feature, could you help to work on the document for it?

**Comment by annelo-msft** [comment]
Per @lmazuel and @KrzysztofCwalina, GA requirement is for partner docs is only "how to create the MVP".  That makes this issue something we can bring in after v1.0.

**Comment by pshao25** [comment]
We need to put the below information from @lmolkova:

We can't update DiagnosticSource version if we want to stay compatible with older Functions V2 (and maybe even v3) runtimes. 

However, everyone who uses tracing via OpenTelemetry or supported version of Application Insights SDK would have DiagnosticSource 5.0.0 or higher. AppInsights deprecated version that uses old DiagnosticSource  ~2 years ago.
I.e. in user apps, where DS version is resolved to 5.0.0+ as tracing SDK dependency, suppression would just work. 
Users who don't use tracing don't care about suppression at all.

So, my suggestion is to do neither and only document that suppression does not work on old DS versions.
