### ISSUE TITLE
Server compatible Model generation through Autorest csharp

### ISSUE THREAD

**Issue by shrja-ms** [Azure/autorest.csharp#2121]
**Need to generate server usable models through autorest csharp**
Our issue is that today Autorest generates only Client Side SDK, but we need to share a server SDK with our partners. And we want to use the models generated from autorest, but the problem is anything in response/Status parameters is inaccessible.
1. the generated SDK has Response(and status related fields), whose contructors are internal and not public, so the server wont be able to create any response.
2. Other issue is that serializer is dropping the enum fields and marking them as null.

I tried using these "x-csharp-usage": "model,output,converter",
"x-csharp-formats": "json" in the Response definition, but no luck.

Attaching the original Swagger here.
Above two issues are in below definitions:
1. Response
2. SyncResponse
3. ValidateForProtectionStatus
4. *Status //Any Status for that matter.
[ServerReview.txt](https://github.com/Azure/autorest.csharp/files/8371715/ServerReview.txt)

**Comment by ShivangiReja** [comment]
Hi @shrja-ms, I tried to generate code using attached swagger. [Here](https://github.com/ShivangiReja/autorest.csharp/tree/TestDataProtection/test/TestProjects/ServerReview) is the generated code.

I also tried to apply "x-csharp-usage" to Response model [here](https://github.com/ShivangiReja/autorest.csharp/tree/TestDataProtection/test/TestProjects/ServerReview#apply-x-csharp-usage-to-response) and it worked as expected without any issue. It generated Response model class as input and output model and you can see [here](https://github.com/ShivangiReja/autorest.csharp/blob/TestDataProtection/test/TestProjects/ServerReview/Generated/Models/Response.cs#L21) it generated public constructor. I also added `converter` for "x-csharp-usage" config, as a result generator added JsonConverter [here](https://github.com/ShivangiReja/autorest.csharp/blob/TestDataProtection/test/TestProjects/ServerReview/Generated/Models/Response.Serialization.cs#L15), so you can access deserialization.

You can refer [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServer.Tests/ModelWithConverterUsageTests.cs#L14-L35) to see how to use JsonConverter for serialization and deserialization.

**Comment by ShivangiReja** [comment]
Hi @shrja-ms, I tried to generate code using attached swagger. [Here](https://github.com/ShivangiReja/autorest.csharp/tree/TestDataProtection/test/TestProjects/ServerReview) is the generated code.

I also tried to apply "x-csharp-usage" to Response model [here](https://github.com/ShivangiReja/autorest.csharp/blob/TestDataProtection/test/TestProjects/ServerReview/readme.md#apply-x-csharp-usage-to-response) and it worked as expected without any issue. It generated Response model class as input and output model and you can see [here](https://github.com/ShivangiReja/autorest.csharp/blob/TestDataProtection/test/TestProjects/ServerReview/Generated/Models/Response.cs#L21) it generated public constructor. I also added `converter` for "x-csharp-usage" config, as a result generator added JsonConverter [here](https://github.com/ShivangiReja/autorest.csharp/blob/TestDataProtection/test/TestProjects/ServerReview/Generated/Models/Response.Serialization.cs#L15), so you can access deserialization.

You can refer [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServer.Tests/ModelWithConverterUsageTests.cs#L14-L35) to see how to use JsonConverter for serialization and deserialization.

**Comment by shrja-ms** [comment]
Hi @ShivangiReja Thanks for quick reply.
Few questions though
How can I add these converters in swagger.json itself and test the generated server on local machine? Can you please share stepwise guide? 
Right now what I observed was the changes were done in the autorest.md, and when I did that in my local machine, it did not generate any code. Maybe I am missing something.
[autorest.md](https://github.com/Azure/autorest.csharp/files/8385792/autorest.md)
![image](https://user-images.githubusercontent.com/77041475/160971816-68a7ce32-c672-448c-98df-e34415bb772f.png)

**Comment by ShivangiReja** [comment]
You can follow the below steps:
* Create [TestDataProtection](https://github.com/ShivangiReja/TestDataProtection) folder
* Add [ServerReview.json](https://github.com/ShivangiReja/TestDataProtection/blob/master/ServerReview.json) under `TestDataProtection/ServerReview.json`
* Add [autorest.md](https://github.com/ShivangiReja/TestDataProtection/blob/master/autorest.md) under `TestDataProtection/autorest.md`
* Run `autorest --csharp --require:C:\Users\shreja\source\repos\TestDataProtection\autorest.md` command and as a result it will generate [this](https://github.com/ShivangiReja/TestDataProtection/tree/master/generated) folder(attaching screenshot below  for your reference)
![image](https://user-images.githubusercontent.com/45216704/161008479-a02520d4-241f-4ac9-9e04-c2f15c4f4b79.png)

If you don't want to add "x-csharp-usage" config in your autorest.md, you can also add it in your swagger file like [this](https://github.com/ShivangiReja/TestDataProtection/blob/master/ServerReview.json#L2587-L2588). [Here](https://github.com/ShivangiReja/TestDataProtection/blob/master/generated/Models/Response.Serialization.cs#L15) is the generated result for the JsonConverter.

**Comment by shrja-ms** [comment]
Thanks Shivangi, for steps.
