### ISSUE TITLE
Add support for swagger extensions 

### ISSUE THREAD

**Issue by weshaggard** [Azure/autorest.csharp#215]
- [ ] Get list of extensions not handled by the code model
  - Determine which extensions are used by data plane
  - Determine which extensions are used my management plane
- [ ] Design generator output based on extension information
- [ ] Implement extension handling

**Comment by pakrym** [comment]
- [ ] x-ms-azure-resource
- [ ] x-ms-blob-sequence-number
- [ ] x-ms-client-flatten
- [ ] x-ms-client-name
- [ ] x-ms-client-request
- [ ] x-ms-client-request-id
- [ ] x-ms-client-request-id_Get
- [ ] x-ms-client-request-id_ParamGet
- [ ] x-ms-code-generation-settings
- [ ] x-ms-discriminator-value
- [ ] x-ms-enum
- [ ] x-ms-error-response
- [ ] x-ms-external
- [ ] x-ms-long-running-operation
- [ ] x-ms-long-running-operation-options
- [ ] x-ms-odata
- [ ] x-ms-pageable
- [ ] x-ms-parameter-grouping
- [ ] x-ms-parameterized-host
- [ ] x-ms-parameter-location
- [ ] x-ms-paths
- [ ] x-ms-request-id
- [ ] x-ms-skip-url-encoding

**Comment by MiYanni** [comment]
I started checking off ones from Pavel's list that I know we have at least most of the implementation working.

**Comment by pakrym** [comment]
I think we are generally done, if some new requirement comes up we can track it separately.
