### ISSUE TITLE
Tweak the body param type renaming when usages are only in public api parameters

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2150]
Right now the [algorithm ](https://github.com/Azure/autorest.csharp/blob/feature%2Fv3/src/AutoRest.CSharp/Mgmt/AutoRest/MgmtOutputLibrary.cs#L175)looks at usage count for whether or not it should change the type name or just the parameter name.

We want to tweak this to accept counts greater than 1 only if all of them are in public api parameters and not properties of another model.

When this is done we should remove the manual rename for `ResourceMoveContent` in Azure.ResourceManager and `ArmDeploymentContent` in Azure.ResourceManager.Resources

**Comment by ArcturusZhang** [comment]
Possibly resolved by https://github.com/Azure/autorest.csharp/pull/2270
