### ISSUE TITLE
Make "single-top-level-client: true" the default behavior 

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#2153]
It would be more consistent with everybody else. It's what autorest has usually be designed to do (one entry point, and operation groups under it), and also what Python and Java does (details for Java, they have one builder, that can build operation group clients, but the point is they have one builder as unique point of entry as well).

**Comment by annelo-msft** [comment]
@AlexanderSher, could you provide a cost for this issue?

**Comment by annelo-msft** [comment]
Adding to April sprint while it is being costed -- we will evaluate whether to keep it there once we have a better sense of it.

**Comment by annelo-msft** [comment]
I am removing the `blocking-release` tag for this issue, because I don't think we want to change DPG defaults right before GA.  We can revisit the need for this as we understand the issue better.
