### ISSUE TITLE
Add csharp autorest configuration model

### ISSUE THREAD

**Issue by weshaggard** [Azure/autorest.csharp#216]
- [ ] Discuss with Garrett design ideas
  - Some configuration concepts are language independent and some are language dependent
  - We have experience with this from AutoRest PowerShell, as we went through a few different iterations, but didn't find something that was great.
- [ ] Implement language independent configuration pipeline plugins (might be done by Garrett)
- [ ] Implement configuration C# models
- [ ] Implement C# specific configuration pipeline plugins

**Comment by pakrym** [comment]
Closing in favor of specific issues.
