### ISSUE TITLE
Add csharp code generation plugin

### ISSUE THREAD

**Issue by weshaggard** [Azure/autorest.csharp#218]
- [ ] Determine means of generating C# code
  - *Options*: Roslyn, library built on Roslyn, string smashing, etc. [NO TEMPLATES]
- [ ] Determine necessary information to add to the CSharpLanguage node of the code model
  - This is how we transfer/update information between plugins
- [ ] Implement model generation
- [ ] Implement communication generation (operations)
- [ ] Implement public surface generation (TBD)

**Comment by MiYanni** [comment]
Currently, we have a CSharpGen plugin that covers most of the list in the description. Closing.
