### ISSUE TITLE
A special case that single property flatten should not happen

### ISSUE THREAD

**Issue by Yao725** [Azure/autorest.csharp#2187]
In Cdn we have a property named [Parameters](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/AfdSecretData.cs#L46) in AfdSecretData. Its type [SecretParameters](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/Models/SecretParameters.cs) is a single property type so we flatten it. But the problems here is that the flattened property `SecretType` is internal, which means we lost the ability to set this value. The reason is SecretParameters is only a base type, in swagger the cdn team defines [many models](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L4617-L4733) that inherits from this type and they use  `SecretType` as the discriminator. Actually when we use this model, we need to pass the derived models like [CustomerCertificateParameters](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/Models/CustomerCertificateParameters.cs) to the Parameters property to make this request work as expected.

One option here might be that we provide a configuration that suppress the property flatten.

This problem also happens in below models:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/Models/AfdSecurityPolicyPatch.cs#L19-L21

**Comment by HarveyLink** [comment]
Same issue could be found at ML
https://github.com/Azure/azure-sdk-for-net/blob/ad327be66641d22533d47b8750edcd8f5a088d30/sdk/machinelearningservices/Azure.ResourceManager.MachineLearningServices/src/Generated/Models/BatchDeploymentDetails.cs#L89

https://github.com/forteddyt/azure-rest-api-specs/blob/048b2943c472175892f744444af57a11d4093293/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json#L5935

**Comment by Yao725** [comment]
Resolved by #2218.
