### ISSUE TITLE
LRO should support return 202 intermediate response

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#2191]
Currently the LRO methods can only return the final response data, but not directly return the 202 responses at first call when use `waitUntil.Started`.
The work around is manually parse the raw data, but definitely not the right behavior.

**Comment by archerzz** [comment]
Here is the case reported by storage team when trying our track2 SDK: [Storage restoreBlobRange](https://github.com/Azure/azure-rest-api-specs/blob/30c98b21ed04e3b6c80debf1e99918b15132e352/specification/storage/resource-manager/Microsoft.Storage/stable/2021-09-01/storage.json#L914).
The `202` response also contains some valuable information.

Moreover, in this case, the responses for `200` and `202` are the same. What if they are different?

**Comment by ArthurMa1978** [comment]
related to https://github.com/Azure/azure-sdk-for-net/issues/29060
