### ISSUE TITLE
Show library evolution in .NET DPG GA arch board meeting

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2199]
### Goals
The key message we want to illustrate in this meeting is that DPG APIs **_can be evolved_**.  We will show this evolution via a series of APIView diffs.

.NET Arch board issue: https://github.com/Azure/azure-sdk/issues/4237

### Concrete evolutions to illustrate
- [x] Initial DPG generation from original MA swagger [APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3)
- Add credential AADToken and AzureKey
- Name the client as MetricsAdvisorClient
- [x] Separation into two service clients [APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=6e6106710775407da6e0e50aad3e4549&doc=False&diffOnly=False&revisionId=42e4833cdbdf4d4db0b6fb3d1c5afd00#)
- Move the operations in MetricsAdvisorAdministrationClient out of MetricsAdvisorClient
- [x] Addition of models for v1 DPG GA [APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=42e4833cdbdf4d4db0b6fb3d1c5afd00&doc=False&diffOnly=False&revisionId=d6d6b97ca5a64227bba8ce7831d453e3#)
- Add all the generated models and customization models
- [x] Other swagger customizations [APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=d6d6b97ca5a64227bba8ce7831d453e3&doc=False&diffOnly=False&revisionId=8b3ee5e3460f4da5a2b0eed275238bfc)
- Change some Guid in signature to string (dataFeedId, feedbackId, and metricId)
- Change endpoint type from string to Uri
- [ ] Client-side evolutions for various operation types and method signatures (see below section)
- [x] Addition of custom MA credential type [APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=8b3ee5e3460f4da5a2b0eed275238bfc&doc=False&diffOnly=False&revisionId=fdd4def091fb4c5a84cf2ad8e12d966c) Line 74,75
- Add customized client (convenience layer)
- Add customized credential type.
- [x] Service-side evolutions 
- Optional input is added to a method with no other parameters ([APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=fdd4def091fb4c5a84cf2ad8e12d966c&doc=False&diffOnly=False&revisionId=6c146034ea50497f9eadde3594b1af58) Lines 21-23)
- Optional input is added to a method with only required parameters ([APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=fdd4def091fb4c5a84cf2ad8e12d966c&doc=False&diffOnly=False&revisionId=6c146034ea50497f9eadde3594b1af58) Lines 65-67)
- Optional input is added to a method with required and optional parameters ([APIView](https://apiview.dev/Assemblies/Review/0119b110f8404179b86a98e68e6c99e3?diffRevisionId=fdd4def091fb4c5a84cf2ad8e12d966c&doc=False&diffOnly=False&revisionId=6c146034ea50497f9eadde3594b1af58) Lines 57-59)
- Required input is changed to an optional input in a method with no other parameters ([APIView](https://apiview.dev/Assemblies/Review/c8b0b44916bb4517ac0c9fa49d9a7f37?diffRevisionId=f6c400a77e8d407e994b477c5bdb6efa&doc=False&diffOnly=False&revisionId=735fa276d20e458384447336226467b7) Lines 22-23)
- Required input is changed to an optional input when it is in the last position in the path parameter ([APIView](https://apiview.dev/Assemblies/Review/c8b0b44916bb4517ac0c9fa49d9a7f37?diffRevisionId=f6c400a77e8d407e994b477c5bdb6efa&doc=False&diffOnly=False&revisionId=735fa276d20e458384447336226467b7) Lines 19-20)
- Original content type has only one option ([APIView](https://apiview.dev/Assemblies/Review/49bcc1eeda464418b63ec20865888be8?diffRevisionId=bc4287a83b2248e29c6be176cdc6ab05&doc=False&diffOnly=False&revisionId=ea489e03bdbe42c4b453041677a5b990) Lines 12-13)

#### Client-side evolutions

We will show APIViews of DPG and DPG + Convenience for the following client-side evolutions:

- [x] Basic REST call, no required parameters: **ConfidentialLedger.GetConstitution**
  - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1), line 22-23.
  - Convenience methods: [APIView](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1), line 24-25.
- [x] Basic REST call, one required parameter: 
    - [x] From DPG to Convenience Client: **ConfidentialLedger.GetReceipt** 
      - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1), line 34-35
      - Convenience methods: [APIView](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1), line 36-37
    - [x] Adding protocol method to existing Convenience Client: **MetricsAdvisorAdministrationClient.DeleteDataFeed** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b), lines 217-220.
- [x] Basic REST call, takes only request body parameter: **MetricsAdvisorAdministrationClient.CreateDataFeed** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b), lines 205-208.
- [x] Basic REST call, addition of manually-written models: **MetricsAdvisorAdministrationClient.CreateDataFeed** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 205,207
- [x] Basic REST call, takes request body parameter + one required parameter: **MetricsAdvisorAdministrationClient.UpdateDataFeed** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 260,262
- [x] Basic REST call, ETag parameter: **DeviceUpdateClient.GetOperation** 
  - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/4d7d53c6581245759f465e12c8d9e5c5), line 87, 89
  - Coonvenience methods: [APIView](https://apiview.dev/Assemblies/Review/4d7d53c6581245759f465e12c8d9e5c5), line 86, 88
- [x] Basic REST call, name changes in Convenience API:
    - [x] **MetricsAdvisorClient.GetMetricFeedback** -> **GetFeedback**
      - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 44-47
      - Convenience methods: [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 26-27
    - [x] **MetricsAdvisorAdministrationClient.GetDataFeedById** -> **GetDataFeed**
      - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 233-234
      - Convenience methods: [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 231-232
    - [X] Takes request body: **MetricsAdvisorClient.CreateMetricFeedback** -> **AddFeedback**
      - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 14-15
      - Convenience methods: [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 12-13
- [x] Paging, no required parameters: **ConfidentialLedgerClient.GetCollections**
  - DPG methods: [APIView](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1), line 16-17
  - Convenience methods: [APIView](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1), line 18-19
- [x] Paging, many required parameters: **MetricsAdvisorAdministrationClient.GetDataFeeds** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 240
- [x] Paging, many optional parameters: **CropsClient.GetCrops**
  - DPG Methods: [APIView](https://apiview.dev/Assemblies/Review/975e922a55ee4280939bd5e64b711bb3/027e1228d9d04925b2300100f6cd3e08?diffRevisionId=02321a84773a4a2085a7a1ca3bd40bf1&doc=False&diffOnly=True), line 10-11
  - Convenience Methods: [APIView](https://apiview.dev/Assemblies/Review/975e922a55ee4280939bd5e64b711bb3/027e1228d9d04925b2300100f6cd3e08?diffRevisionId=02321a84773a4a2085a7a1ca3bd40bf1&doc=False&diffOnly=True), line 12-13
- [x] Paging, takes request body and only optional parameters: **MetricsAdvisorClient.GetMetricFeedbacks** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 46-47
- [x] Paging, takes request body and one required parameter: **MetricsAdvisorClient.GetMetricDimension** [APIView](https://apiview.dev/Assemblies/Review/a9812a1691e54ab4bf52540c4e54d433?diffRevisionId=9260bdbf10e346b9ba8dac7399ea885b&doc=False&diffOnly=False&revisionId=66cd7343ae6c47988e3f8b3caf52617b#Azure.AI.MetricsAdvisor.Models.DataFeed), line 36-37
- [ ] LRO, no request body: **DeviceUpdateClient.DeleteUpdate** [APIView](https://apiview.dev/Assemblies/Review/e697dac39d9b4911a21597bc035ae926/c857b6ea62284277b03575f37337ad82?diffRevisionId=4581fa709b2a429499629776de880aed&doc=False&diffOnly=True), line 14-15
  - TBV: I started this [here](https://apiview.dev/Assemblies/Review/e697dac39d9b4911a21597bc035ae926/c857b6ea62284277b03575f37337ad82?diffRevisionId=4581fa709b2a429499629776de880aed&doc=False&diffOnly=True), but found some issues I've filed.
- [ ] LRO, takes request body: **DeviceManagementClient.ImportDevices** [APIView](https://apiview.dev/Assemblies/Review/e697dac39d9b4911a21597bc035ae926/c857b6ea62284277b03575f37337ad82?diffRevisionId=4581fa709b2a429499629776de880aed&doc=False&diffOnly=True), line 4,6

#### Service-side evolutions
We will show APIViews of v1 and v2 for the following service-side evolutions:
  - **\<To Be Completed\>**

**Comment by annelo-msft** [comment]
@lirenhe, we will need APIViews for the non Metrics Advisor operations.  Is this something your team can take?  I can provide instructions for creating the APIViews if you don't yet have that knowledge on your team.  Thanks!

**Comment by lirenhe** [comment]
> @lirenhe, we will need APIViews for the non Metrics Advisor operations. Is this something your team can take? I can provide instructions for creating the APIViews if you don't yet have that knowledge on your team. Thanks!

Sure. I will do the assignment for those items. Thanks.

**Comment by archerzz** [comment]
All `ConfidentialLedgerClient` changes are in this PR: https://github.com/Azure/azure-sdk-for-net/pull/28679
And the corresponding API view is: https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1

**Comment by chunyu3** [comment]
- LRO, no request body: DeviceUpdateClient.DeleteUpdate 

- LRO, takes request body: DeviceManagementClient.ImportDevices 

These two items depend on issue https://github.com/Azure/autorest.csharp/issues/2212

**Comment by annelo-msft** [comment]
For 
> Basic REST call, no required parameters: **ConfidentialLedger.GetConstitution**

It would be ideal if [the diff did not show any deletions](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1?diffRevisionId=31c49496be044798ba4d6b869d9f9044&doc=False&diffOnly=False&revisionId=158566a510f44c8e9f02e0ac9c6cb8e6) (GetCurrentLedgerEntry is deleted on lines 27 & 28).  Would it be possible to create this diff?

![image](https://user-images.githubusercontent.com/21269347/168917044-aa36ca95-bd97-4572-83b1-74310e29127c.png)

**Comment by annelo-msft** [comment]
For
> Paging, many optional parameters: **CropsClient.GetCrops**

In the grow-up methods, we should add an Options type, such as:

```csharp
           public virtual Pageable<BinaryData> GetCrops(IEnumerable<string> phenotypes = null, IEnumerable<string> ids = null, IEnumerable<string> names = null, IEnumerable<string> propertyFilters = null, IEnumerable<string> statuses = null, DateTimeOffset? minCreatedDateTime = null, DateTimeOffset? maxCreatedDateTime = null, DateTimeOffset? minLastModifiedDateTime = null, DateTimeOffset? maxLastModifiedDateTime = null, int? maxPageSize = null, string skipToken = null, RequestContext context = null);
           public virtual AsyncPageable<BinaryData> GetCropsAsync(IEnumerable<string> phenotypes = null, IEnumerable<string> ids = null, IEnumerable<string> names = null, IEnumerable<string> propertyFilters = null, IEnumerable<string> statuses = null, DateTimeOffset? minCreatedDateTime = null, DateTimeOffset? maxCreatedDateTime = null, DateTimeOffset? minLastModifiedDateTime = null, DateTimeOffset? maxLastModifiedDateTime = null, int? maxPageSize = null, string skipToken = null, RequestContext context = null);
 +         public virtual Pageable<FoodCrop> GetCrops(GetCropsOptions options, CancellationToken cancellationToken = default);
 +         public virtual AsyncPageable<FoodCrop> GetCropsAsync(GetCropsOptions options, CancellationToken cancellationToken = default);
```

It looks like we should update https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/DeveloperDrivenEvolution.md with this guidance as well.

**Comment by annelo-msft** [comment]
For
>Basic REST call, ETag parameter: **DeviceUpdateClient.GetOperation** [APIView](https://apiview.dev/Assemblies/Review/c8b0b44916bb4517ac0c9fa49d9a7f37), line 84-85

I don't see the grow-up method added for GetOperation... where should I look?

**Comment by annelo-msft** [comment]
For
>Service-side evolutions

These look great - thank you!  Would it be possible to add one for the case where [a new body type is added](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/ServiceDrivenEvolution.md)?  @pshao25 should be able to tell us what method in which library has one of these (thank you in advance, @pshao25! :) )

**Comment by archerzz** [comment]
> For
> 
> > Basic REST call, no required parameters: **ConfidentialLedger.GetConstitution**
> 
> In the [APIView diff provided](https://apiview.dev/Assemblies/Review/6c11d7337755493bbe6942126b633be1?diffRevisionId=31c49496be044798ba4d6b869d9f9044&doc=False&diffOnly=False&revisionId=158566a510f44c8e9f02e0ac9c6cb8e6), `GetCurrentLedgerEntry` methods are deleted on lines 27 & 28.
> 
> ![image](https://user-images.githubusercontent.com/21269347/168917044-aa36ca95-bd97-4572-83b1-74310e29127c.png)
> 
> Would it be possible to create the APIView so only the additions are shown, no deletions? This is important because we want to illustrate how we can add convenience APIs without making breaking changes to the GA API. If there are deletions, architects might think we are making breaking changes.
> 
> Update: If we could update the APIView for the full client to show additions of convenience methods, but no deletions, that would help us with **ConfidentialLedgerClient.GetCollections** as well.

@annelo-msft It's actually still there. The problem is that the parameter name has been changed (see [the old API spec](https://github.com/Azure/azure-rest-api-specs/blob/e34c5f11d61ca17fdc9fd0f70446dd54b94d67f1/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/preview/0.1-preview/confidentialledger.json#L320) and [the new one](https://github.com/Azure/azure-rest-api-specs/blob/c24e31390f7bde23664f43190d9184f5fbbbd24f/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/preview/2022-20-04-preview/confidentialledger.json#L351)).
![image](https://user-images.githubusercontent.com/4516/168981299-14005695-300d-4ae8-9d6d-9fe052a913f4.png)

I have to update to use the new swagger spec (see [PR](https://github.com/Azure/azure-sdk-for-net/pull/28679)), because `ConfidentialLedger.GetConstitution` is only available in the new swagger spec.

**Comment by archerzz** [comment]
> For
> 
> > Paging, many optional parameters: **CropsClient.GetCrops**
> 
> In the grow-up methods, we should add an Options type, such as:
> 
> ```cs
> public virtual Pageable<BinaryData> GetCrops(IEnumerable<string> phenotypes = null, IEnumerable<string> ids = null, IEnumerable<string> names = null, IEnumerable<string> propertyFilters = null, IEnumerable<string> statuses = null, DateTimeOffset? minCreatedDateTime = null, DateTimeOffset? maxCreatedDateTime = null, DateTimeOffset? minLastModifiedDateTime = null, DateTimeOffset? maxLastModifiedDateTime = null, int? maxPageSize = null, string skipToken = null, RequestContext context = null);
> public virtual AsyncPageable<BinaryData> GetCropsAsync(IEnumerable<string> phenotypes = null, IEnumerable<string> ids = null, IEnumerable<string> names = null, IEnumerable<string> propertyFilters = null, IEnumerable<string> statuses = null, DateTimeOffset? minCreatedDateTime = null, DateTimeOffset? maxCreatedDateTime = null, DateTimeOffset? minLastModifiedDateTime = null, DateTimeOffset? maxLastModifiedDateTime = null, int? maxPageSize = null, string skipToken = null, RequestContext context = null);
> + public virtual Pageable<FoodCrop> GetCrops(GetCropsOptions options, CancellationToken cancellationToken = default);
> + public virtual AsyncPageable<FoodCrop> GetCropsAsync(GetCropsOptions options, CancellationToken cancellationToken = default);
> ```
> 
> This will make renaming the method unnecessary.
> 
> It looks like we should update https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/DeveloperDrivenEvolution.md with this guidance as well. The guidance for Convenience APIs is here: https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-parameters. We should call out that if the number of parameters or in general the complexity of the operation makes it qualified for the [guidelines for introducing an options type](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-parameters), we should do that.

@annelo-msft I've updated the convenience method to adopt `Options` class. The API view is updated. Here is the [corresponding PR](https://github.com/Azure/azure-sdk-for-net/pull/28728).
![image](https://user-images.githubusercontent.com/4516/169011600-db30eb11-8b0e-4f3e-811e-9d8fe7f0e5cf.png)

**Comment by annelo-msft** [comment]
> @annelo-msft I've updated the convenience method to adopt Options class. The API view is updated. Here is the https://github.com/Azure/azure-sdk-for-net/pull/28728.

Thank you, @archerzz!  The GetCropOptions type looks great. 

Would you mind also updating the method names?  Now that they take different parameter types, they won't cause an ambiguous call site and can be overloads.

![image](https://user-images.githubusercontent.com/21269347/169083954-a5de4626-108c-4a34-a09f-2c88b4efe789.png)

**Comment by annelo-msft** [comment]
@pshao25, thank you for adding those APIViews with ContentType!  A couple of comments on these:

> Original content type has only one option ([APIView](https://apiview.dev/Assemblies/Review/49bcc1eeda464418b63ec20865888be8?diffRevisionId=bc4287a83b2248e29c6be176cdc6ab05&doc=False&diffOnly=False&revisionId=f95de0d704d94b7caf12e2f7ea746a06) Lines 13-14)

This is great - thank you!

One comment here is that when we show this, let's make sure if people ask about why `CheckPrincipalAccessAsync` is deleted (2), we let them know we just haven't added that method back manually yet, but that we would in the case of a real library.

![image](https://user-images.githubusercontent.com/21269347/169086318-d0668d43-0173-4bad-800b-7de500faddbd.png)

> Original content type has more than one options: **WebPubSub** ([APIView](https://apiview.dev/Assemblies/Review/ac9256cefa2143c3af893b596542af6e?diffRevisionId=8910c260cf614f86883da049c4ea1f37&doc=False&diffOnly=False&revisionId=7eed1ee9549d416b9faba4ff070c3864) Line 62)

I don't see any methods added in the diff, can you help me understand?  Are we just showing what it would look like if the operation started by accepting two content types, and we wouldn't need to evolve the method?

**Comment by chunyu3** [comment]
There is the gist for 'Basic Rest Call Grow-up': https://gist.github.com/chunyu3/1a4afc22e94ebc3887fde6bdec04df3f. Please help to review it. Thanks

**Comment by lirenhe** [comment]
@chunyu3 , @pshao25 ,  please help to put all content together in https://gist.github.com/annelo-msft/8582310e0aab5c3dfa378de2c11849bb  Thanks.

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk/issues/4237
