### ISSUE TITLE
Design the exact set of csharp code to generate

### ISSUE THREAD

**Issue by weshaggard** [Azure/autorest.csharp#220]
Design the exact set of csharp code to generate
  - Target Azure.Core as the transport layer
  - partial classes
  - protocol layer
  - public apis - manual or generated?

**Comment by MiYanni** [comment]
We currently generate an internal layer with 'usable' functionality (passes many TestServer tests but not all). Pavel and I will discuss how to proceed with public surface. At minimum, models will be public. Since at majority of this is implemented already, closing this issue.
