### ISSUE TITLE
Clarify the usage of ClientOption.ServiceVersion

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2219]
I tried to generate the SDK by using the following swagger:  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/TranslatorText/stable/v1.1/TranslatorBatch.json

Here is the command I use:

Invoke-DataPlaneGenerateSDKPackage.ps1 -service cognitiveservices -namespace Azure.AI.DocumentTranslation -sdkPath c:/work/azure-sdk-for-net -inputfiles https://github.com/Azure/azure-rest-api-specs/blob/1f1d5b0b9ce6cc94605b2fd619dce374fb6e033a/specification/cognitiveservices/data-plane/TranslatorText/stable/v1.1/TranslatorBatch.json -securityScope https://cognitiveservices.azure.com/.default
   
 In   DocumentTranslationClientOptions.cs
 `public DocumentTranslationClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.Vv1_1 => "v1.1",
                _ => throw new NotSupportedException()
            };
        }
`

1. Though this could be a problem in Swagger, can we add a check for the supported version format to avoid generating the name like `ServiceVersion.Vv1_1`
2. The version is already part of the URL  `uri.AppendRaw("/translator/text/batch/v1.1", false);`,  I didn't see this ServiceVersion used in the dotnet SDK, other SDKs like python & JS don't have this 'Version' property,  is there any specific usage of it in dotnet?

**Comment by annelo-msft** [comment]
@tg-msft, are there Azure.SDK libraries that use the ServiceVersion enum currently?

**Comment by annelo-msft** [comment]
@lirenhe, is this sufficient clarification to close this issue?  We should create separate issues for specific concerns or feature asks that this explanation raises.

**Comment by lirenhe** [comment]
Thanks @annelo-msft and @tg-msft for the reply.

I have 2 questions:

1.  For the version name like 'v1.1' in Swagger, shall we generate the code like 'ServiceVersion.**Vv1_1**'  or just use 'ServiceVersion.**V1_1**'
2. For this case of documentTranslation, we did not pass that value to the service.  The version is hard coded in the uri path.
  uri.AppendRaw("/translator/text/batch/v1.1", false);    
So even we use a different value,  service would still get v1.1.  So my question would be 'shall we expose that value that is not referenced/used into the public constructor'?

As those are related to API design, I will leave it to you to decide whether we need take any action.
For this one, feel free to close it.

**Comment by mikekistler** [comment]
Any service version that is not date-based violates Azure API Guidelines and is flagged by linter rules.

**Comment by lirenhe** [comment]
@annelo-msft, thanks for your explanation. DocumentTranslation is just my experiment to check the generated code and do some test. I don't think there is a plan to port DocumentTranslation to DPG.

@mikekistler, we have this rule https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3012-apiversionpattern. But it does not seem to be applied to dataplane as I can see a lot of violation there.

**Comment by mikekistler** [comment]
The data plane linter rule for api-versioning is implemented in our Spectral ruleset, which we are in the process of integrating into the Azure linter.

https://github.com/Azure/azure-api-style-guide/blob/main/docs/azure-ruleset.md#az-version-policy

**Comment by lirenhe** [comment]
Close it as there is no furthur action in DPG side.
