### ISSUE TITLE
Modify the deserializer of `SubResource` and `WriteSubResource` to support `x-nullable` properties

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#2220]
Now the deserializer of `SubResource` and `WriteSubResource` regards the `Id` property as `x-nullable: false`. We need to modify that so that we no longer have to add `no-property-type-replacement` when this happens in our test cases.

**Comment by ArthurMa1978** [comment]
@archerzz is working the nullable fix, but not finalized

**Comment by archerzz** [comment]
Adding @ArcturusZhang who will follow up the nullable change.

**Comment by ArthurMa1978** [comment]
Related to https://github.com/Azure/azure-rest-api-specs/issues/23217
