### ISSUE TITLE
Provide documentation for swagger x-ms-format of id, resource type and location

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2221]
Provide documentation describing the three new values and when they should be used

https://github.com/Azure/autorest.csharp/pull/2051

`azure-location` and `etag` were added after that PR as well which should be documented.

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/autorest.csharp/blob/feature/v3/docs/mgmt/polishing.md#change-format-by-name-rules
