### ISSUE TITLE
Missing "expand" parameter of StorageAccounts_ListKeys in Track2 SDK 

### ISSUE THREAD

**Issue by yifanz0** [Azure/autorest.csharp#2246]
**Describe the issue or request**
In the swagger definition, there's an parameter called **expand** in the **StorageAccounts_ListKeys** operation. However in Track2 SDK, this parameter is missing in the public method signature of **Azure.ResourceManager.Storage.GetKeys**.

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/resource-manager/Microsoft.Storage/stable/2021-08-01/storage.json#L524
![image](https://user-images.githubusercontent.com/100746763/169755208-288a37ab-dead-48dc-bb8e-09d78f2dddd1.png)

Azure.ResourceManager.Storage.GetKeys in Track2 SDK:
![image](https://user-images.githubusercontent.com/100746763/169755406-41545884-afad-4328-bc39-01763a055454.png)

**Comment by ArcturusZhang** [comment]
Looks like autorest.java has already noticed this issue and has its own solution: https://github.com/Azure/autorest.java/blob/6192efc5167bd080c614bdc806b8f9d17cca25e4/preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java#L128-L169

**Comment by ArcturusZhang** [comment]
We also have similar solution in autorest.python: https://github.com/Azure/autorest.python/pull/1171/files

**Comment by ArcturusZhang** [comment]
> Looks like autorest.java has already noticed this issue and has its own solution: https://github.com/Azure/autorest.java/blob/6192efc5167bd080c614bdc806b8f9d17cca25e4/preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java#L128-L169 We could try to include similar things in autorest.csharp

We are going to take this as a short term solution. In long term, we will try to discuss this with the modeler team and see if they could do something on the modeler side

**Comment by pshao25** [comment]
I add this parameter snippet to DPG, and it could show up correctly as 
![image](https://user-images.githubusercontent.com/97225342/170621240-93fbef48-c628-4cd3-a3d5-89afa18a1b40.png)
So, DPG doesn't have this issue.
