### ISSUE TITLE
[LLC] refactor 'WritePageableLongRunningOperationMethod' method

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2247]
The 'WritePageableLongRunningOperationMethod' in src/AutoRest.CSharp/LowLevel/Generation/LowLevelClientWriter.cs is a long method and have some duplicate code comparing with normal LRO operation method 'WriteLongRunningOperationMethod'.

Need to refactor this method to divide it and resolve duplicatation.

**Comment by archerzz** [comment]
Close since:
- It's covered by #2552 
- It has been cleaned up recently, so the codes are not as bad as before.
