### ISSUE TITLE
Provide formula for REST API operation link in docs.microsoft.com

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2253]
As part of https://github.com/Azure/autorest.csharp/issues/2239, we will provide a link to the REST API docs for an operation with each protocol method reference docs page.  @mikekistler shared that there is a standard formula for this for most services.  Please provide that formula in the comments below.

**Comment by mikekistler** [comment]
Here’s the spec for the URL structure: [REST Reference Overview | Microsoft Docs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fnew-hope%2Fspecs%2Freference%2Frest-reference-overview%3Fbranch%3Dmain%23url-structure&data=05%7C01%7Cmikekistler%40microsoft.com%7C0624b2cd31e04457d81108da4329467a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637896141795983585%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dJolEQOdL2pAI3gNMbJS1C2I0Db%2BEP3zvkVBcQVFJOM%3D&reserved=0):
·         Format: docs.microsoft.com/en-us/rest/api/{product}/{service}/{resource}/{operation}

·         Example: docs.microsoft.com/en-us/rest/api/azure/iothub/deviceapi/bulkdeviceoperation

**Comment by mikekistler** [comment]
Update:

Looks the URL structure is changed to [https://docs.microsoft.com/rest/api/<service>/<operationGroup>/<operationName](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Frest%2Fapi%2F%253cservice%253e%2F%253coperationGroup%253e%2F%253coperationName&data=05%7C01%7Cmikekistler%40microsoft.com%7C5f3955e09d2d4b7adbd908da437a7973%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637896490578239647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8UYhyf6OOwx3hCmAJT%2BL0sQQjdzCAamVkjY5c%2B6KM2k%3D&reserved=0)>.

But as Ke Xu use uid to link the page is recommended. [https://review.docs.microsoft.com/en-us/engineering/projects/markdig-extensions/crossreference?branch=main](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fengineering%2Fprojects%2Fmarkdig-extensions%2Fcrossreference%3Fbranch%3Dmain&data=05%7C01%7Cmikekistler%40microsoft.com%7C5f3955e09d2d4b7adbd908da437a7973%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637896490578239647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LA39%2FiFQgto%2FUjNDrrj1nn5znI7cpGEkJLwWpYj5vaM%3D&reserved=0)
 
Uid is defined in the yaml file [https://github.com/Azure/azure-docs-rest-apis/blob/live/docs-ref-autogen/advisor/Configurations/Create-In-Resource-Group.yml#L2](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-docs-rest-apis%2Fblob%2Flive%2Fdocs-ref-autogen%2Fadvisor%2FConfigurations%2FCreate-In-Resource-Group.yml%23L2&data=05%7C01%7Cmikekistler%40microsoft.com%7C5f3955e09d2d4b7adbd908da437a7973%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637896490578239647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hNsRM08apIe%2BFTPiW494LDJg5dDCZtm6hbgwBTUd39M%3D&reserved=0).

**Comment by annelo-msft** [comment]
@archerzz, can you confirm this will work for docs generation and if so, close the issue?

**Comment by lirenhe** [comment]
Need some verification for this effort and the eng work will be integrated into https://github.com/Azure/autorest.csharp/issues/2239 for estimation. So close this item to avoid duplicate.

**Comment by chunyu3** [comment]
Reopen this issue. There are some issues when we generate the URL.  We need to discuss the solution and the possible format.

**Comment by mikekistler** [comment]
@kexugit @yishengjin1413  There is some confusion about whether there is a reliable "formula" for the docs link for an operation that we could produce in our generator.  What is your recommendation?

**Comment by annelo-msft** [comment]
Removing the blocking release and DPG v1.0 GA tags, since we have decided that we will require REST API links to be specified in the swagger.  We will automate those links if/when we are able to find a correct formula, but this is not blocking.

**Comment by lirenhe** [comment]
Based on the previous discussion, there is no consistent formula between different service.  I don't think we need this item.
Feel free to open it if you have any other suggestions.

cc @mikekistler   @xboxeer
