### ISSUE TITLE
Implement generating documentation for polymorphic definitions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2254]
Implement the requirements described in https://github.com/Azure/azure-sdk-for-net/issues/28962

**Comment by archerzz** [comment]
@chunyu3 This should be part of #2288

**Comment by chunyu3** [comment]
We already support polymorphic in resquest/response payload. But the inner-polymorphic which means that one child/descendant field is polymorphic is not spreaded. we will support inner-polymorphic in GA1.1

**Comment by chunyu3** [comment]
the inner-polymorphic is tracked in https://github.com/Azure/autorest.csharp/issues/2746. close this one.
