### ISSUE TITLE
[DPG] Optional parameter with x-ms-enum produces wrong request

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2260]
**Case 1: Enum has only one value and x-ms-enum has modelAsString as default value false.**
Add below swagger snippet to any operation:
```
{
    "name": "$expand",
    "in": "query",
    "required": false,
    "type": "string",
    "enum": [
      "kerb"
    ],
    "x-ms-enum": {
      "name": "ListKeyExpand"
    },
    "description": "Specifies type of the key to be listed. Possible value is kerb."
}
```
**Actual behavior:**
```C#
public virtual async Task<Response> GetModelAsync(string mode, RequestContext context = null)
{
    ...
    using HttpMessage message = CreateGetModelRequest(mode, context);
    ...
}
internal HttpMessage CreateGetModelRequest(string mode, RequestContext context)
{
    ...
    uri.AppendQuery("$expand", "kerb", true);
    ...
}
```
**Expected behavior:** `$expand` is optional parameter it should be passed in `null`.

**Case 2: Enum has only multiple values and x-ms-enum has modelAsString as default value false.**
Add below swagger snippet to any operation:
```
{
    "name": "$expand",
    "in": "query",
    "required": false,
    "type": "string",
    "enum": [
      "kerb",
      "aaa"
    ],
    "x-ms-enum": {
      "name": "ListKeyExpand"
    },
    "description": "Specifies type of the key to be listed. Possible value is kerb."
  }
```
**Actual behavior:**
```C#
public virtual async Task<Response> GetModelAsync(string mode, string expand = null, RequestContext context = null)
{
    ...
    using HttpMessage message = CreateGetModelRequest(mode, expand, context);
    ...
}
internal HttpMessage CreateGetModelRequest(string mode, string expand, RequestContext context)
{
    ...
    if (expand != null)
    {
        uri.AppendQuery("$expand", expand, true);
    }
    ...
}
```
**Expected behavior:** modelAsString is false, we should not generate expand as string.

**Case 3: Enum has only one value and x-ms-enum has modelAsString as true.**
Add below swagger snippet to any operation:
```
{
    "name": "$expand",
    "in": "query",
    "required": false,
    "type": "string",
    "enum": [
      "kerb"
    ],
    "x-ms-enum": {
      "name": "ListKeyExpand",
      "modelAsString": true
    },
    "description": "Specifies type of the key to be listed. Possible value is kerb."
  }
```
**Actual behavior:** same as Case 2. It is expected in this case.

**Case 4: Enum has only multiple values and x-ms-enum has modelAsString as true.**
Add below swagger snippet to any operation:
```
{
    "name": "$expand",
    "in": "query",
    "required": false,
    "type": "string",
    "enum": [
      "kerb",
      "aaa"
    ],
    "x-ms-enum": {
      "name": "ListKeyExpand",
      "modelAsString": true
    },
    "description": "Specifies type of the key to be listed. Possible value is kerb."
  }
```
**Actual behavior:** same as Case 2. It is expected in this case.

**Comment by lirenhe** [comment]
The similar issue was reported in mgmt. SDK https://github.com/Azure/autorest.csharp/issues/2246, but Pan tried and found in DPG, we have the similar issue.   So create this seperate issue as DPG has a separate code path.

@pshao25, seems the result of case1&2 are not expected, is that correct?

@annelo-msft, could you help to check do we need to fix them before GA and what is the expected behaviour from the API signature prospective?

**Comment by pshao25** [comment]
> The similar issue was reported in mgmt. SDK #2246, but Pan tried and found in DPG, we have the similar issue. So create this seperate issue as DPG has a separate code path.
> 
> @pshao25, seems the result of case1&2 are not expected, is that correct?
> 
> @annelo-msft, could you help to check do we need to fix them before GA and what is the expected behaviour from the API signature prospective?

Case 1&2 is not expected. Case 3&4 is expected I think, I just put them to provide more details.

**Comment by archerzz** [comment]
FYI. There is an issue filed on M4: https://github.com/Azure/autorest/issues/4548 We could wait for the M4 to fix this issue in upstream.

**Comment by ArcturusZhang** [comment]
Considering that we do not have models in DPG, it is OK that we just use string for the enumeration types?
I believe we need to document the expected values into the document of the corresponding parameter

**Comment by chunyu3** [comment]
Not affected DPG from typespec, low priority. Move to Backlog.
