### ISSUE TITLE
Improve the CI for CodeGen PR to build the PR for SDK change in azure-sdk-for-net

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2262]
We should try to avoid the update of CodeGen to cause unexpected behaviour for mgmt. SDK and data plane SDK.

Mgmt SDK team has built the following tool that regenerates every package in azure-sdk-for-net whose namespace starts with Azure.ResourceManager.
https://github.com/arcturuszhang/regen

Here are the asks and please work with mgmt SDK team to investigate:
1. Can we extend the functional of this tool to also support DPG？
2. Can we put this as part of the CI for CodeGen PR so that we could review the potential API change in sdk repo.
3. It would be good to move that tool into azure-sdk-tools repo.

**Comment by AlexanderSher** [comment]
The following command executed in `azure-sdk-for-net` root should regenerate all dependent projects:
`dotnet build eng/service.proj /t:GenerateCode`

If this call doesn't work as expected, we need to fix the following msbuild target (or one of its dependencies).

**Comment by chunyu3** [comment]
> The following command executed in `azure-sdk-for-net` root should regenerate code in all dependent projects: `dotnet build eng/service.proj /t:GenerateCode`
> 
> If this call doesn't work as expected, we need to fix the following msbuild target (or one of its dependencies).

yes, we will use `dotnet build eng/service.proj /t:GenarateCode`. We need to update this a little bit to support:
1. can re-run the script from an specific resource, such as the broken resource of previous run.
2. check if it works for management and DPG
3. parallel running scope setting and memory issue.

**Comment by lirenhe** [comment]
Discussed with @AlexanderSher,  seems we don't need to use https://github.com/arcturuszhang/regen and we could improve the current pipeline directly. 
@AlexanderSher, for this https://github.com/Azure/autorest.csharp/issues/2300, is it about the same goal we want to achieve and will you take care of this effort?
