### ISSUE TITLE
Add tests to validate that generated authentication functions correctly

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2272]
We have tests that validate that [this functionality](https://github.com/Azure/autorest.csharp/issues/2222) is generated correctly:

> We have test coverage for [this](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/SecurityDefinition-LowLevel) sample [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServerLowLevel.Tests/SecurityDefinitionTests.cs) which has both "oauth2" and "apiKey" security schemes.

We need to add tests to validate that the generated code works as expected.

**Comment by annelo-msft** [comment]
@lirenhe  FYI

**Comment by lirenhe** [comment]
@pshao25,  for CADL, we shall also leverage the security definition inside CADL file for authentication. 
Could you help to verify our current behaviour is correct?  
Add the DPG 1.1 label as this could be the common codebase to support of CADL security definition.
