### ISSUE TITLE
doc(dpg): Updates Basic Method Signature in Reference Docs

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2285]
## Updates to Reference Docs

- [ ] Change the `<param name="content">`  tag:

    From: `<param name="content"> The content to send as the body of the request. </param>`
    To: `<param name="content"> The content to send as the body of the request. Details of the request body schema are in the Remarks section below.</param>`

- [ ] Change the `<param name="context">` tag:
    From: `<param name="context"> The request context, which can override default behaviors on the request on a per-call basis. </param>`
    To: `<param name="context"> The request context, which can override default behaviors of the client pipeline on a per-call basis. </param>`

- [ ] Add a `<returns>` tag describing the method's return value.  If the return value is `Response` or `Task<Response>`, the text should be as follows:

    - `The response returned from the service. Details of the request body schema are in the Remarks section below.`

    - Please add `Details of the response body schema are in the Remarks section below` to the response description only when the Response contains a response body with a defined schema.

- [ ] Add an `<exception>` tag:

    `<exception cref="RequestFailedException">Service returned a non-success status code.</exception>`

**Comment by annelo-msft** [comment]
@pshao25, would it be possible to create sample reference docs from the updated files in this PR so we can see what the final result looks like after processing in the docs generation pipeline?  I'd like to make it as easy as possible for all of us to identify when the `<returns>` block has an incorrect return value, and this is easier to see in the processed docs.

**Comment by pshao25** [comment]
> @pshao25, would it be possible to create sample reference docs from the updated files in this PR so we can see what the final result looks like after processing in the docs generation pipeline? I'd like to make it as easy as possible for all of us to identify when the `<returns>` block has an incorrect return value, and this is easier to see in the processed docs.

Are you saying this?
https://raw.githack.com/Azure/azure-sdk-for-net/ef22ee5702b3cb631b8431d3b82796283dfe9a7c/doc/ApiDocGeneration/Azure.Security.ConfidentialLedger/docfx-output/docfx_project/site/api/index.html
https://raw.githack.com/Azure/azure-sdk-for-net/11fa954fe7/doc/ApiDocGeneration/Azure.IoT.DeviceUpdate/docfx-output/docfx_project/site/api/index.html
https://raw.githack.com/Azure/azure-sdk-for-net/11fa954fe7/doc/ApiDocGeneration/Azure.Messaging.WebPubSub/docfx-output/docfx_project/site/api/index.html
