### ISSUE TITLE
doc(dpg): Add <example> in Reference Docs

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2286]
### Examples

- [ ] Add an example section before remarks section using `<example>` tag with a copy-and-paste sample showing two samples that illustrate:

    - Create client
    - Create `RequestContent` using C# anonymous types and `RequestContent.Create` method.  Use `<outer>-<inner>-<propertyName>` to populate string parameter values.
    - Calling the method
    - Parse the `Response` returned from the method using `JsonDocument.Parse` 
    - Print the values from the response body using `Console.WriteLine`

####

  1. The first sample will show the method call passing only required properties for the input request body
  2. The second sample will show the method call passing all properties for the input request body
  3. Consider adding example code in a separate file and pull it into the docs from there to ensure it builds

Refer [sample Example section](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles#examples) for more details.

**Comment by archerzz** [comment]
One key point is the composition of sample values sent to client. Due to the limited time and the complexity of the swagger definitions, I think we need to control the expectation of the sample values: **we should compose syntactically correct sample values but could not guarantee the semantic correctness**.

That's because of the following factors (but not limited to):

- Incorrect Definition: for example, a property `A` is marked as required, but all its sub-properties are optional. Thus, it's hard to assign a value to `A`. We would fall back to `A = new {};` in such cases.
- Semantically Exclusive Properties: for example, if property A is defined, then property B cannot be set.
- Lack of Format: this is a very common pattern 
  - an `id` property could be of the following types:
    - Resource Identifier
    - GUID
    - Custom ID format
  - a `appUri` property is defined as string without `uri` format
- Advanced Schema: like `anyOf`
- Validation: like `minimum`, `maximum`

**Comment by annelo-msft** [comment]
@archerzz, please provide sample swagger files for each of the cases you're concerned with.  This is for several reasons:

- We should make sure we have linter rules preventing these kinds of swagger errors in the future.
- We should make sure the scenarios are realistic and show up in existing swagger files in order to determine whether or not we should block GA on investigations for them.

Thanks!

**Comment by annelo-msft** [comment]
@archerzz, would it be possible to create sample reference docs from the updated files in this PR so we can see what the final result looks like after processing in the docs generation pipeline?

**Comment by archerzz** [comment]
> @archerzz, would it be possible to create sample reference docs from the updated files in this PR so we can see what the final result looks like after processing in the docs generation pipeline?

@annelo-msft Yes. See the links here: https://github.com/Azure/azure-sdk-for-net/pull/29236#issuecomment-1158957822
