### ISSUE TITLE
doc(dpg): Update <remarks> in Reference Docs

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2288]
### Remarks

We will update the `<remarks></remarks>` tag as follows:

- [ ] Remove `<remarks><code></code></remarks>` block for Error Response.

- [ ] Add link to REST API documents for the given operation.  This will be obtained as follows:
    1. If https://swagger.io/specification/v2/#externalDocumentationObject contains a URI, use this for the link
    2. Use the [Formula to create the REST API link](https://github.com/Azure/autorest.csharp/issues/2253) provided by @mikekistler.

- [ ] Update `<remarks><code></code></remarks>` for the Request Body schema to indicate whether the parameter is required or optional.
- [ ] Update `<remarks><code></code></remarks>` for the Request Body schema with the parameter descriptions.
- [ ] Update `<remarks><code></code></remarks>` for the Response Body schema with the parameter descriptions.
- [ ] Add Polymorphic types
   - [ ]  If a method takes one for the derived type, add description - `This method takes one of the  JSON object below as a payload. Please select a JSON object to view the schema`
   - [ ] The list of polymorphic definitions is potentially long. So we decided providing several levels of expanding menu.
        - One for the list of all derived definitions (Show a few with a "See More..." link that expands to the full list
        - When one of the definition names is clicked, the page expands to show the schema for that particular JSON object in place.

Refer [sample `Remarks` section](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles#remarks) to see the polymorphic types.

 v1.1 requirement development tracked by per https://github.com/Azure/azure-sdk-for-net/issues/28962#issue-1247187851

**Comment by annelo-msft** [comment]
@ShivangiReja, I remember from the discussion with Krzysztof and Ted that they had said some features for documenting polymorphic schema should be added in v1.1 and not v1.0.  Do you recall offhand which features were deferred to v1.1?  If not, I can go back to the recording to obtain this information.

**Comment by ShivangiReja** [comment]
@annelo-msft I think we decided that we will look into the nested polymorphic types in V1.1 and we can refer Search https://github.com/Azure/azure-rest-api-specs/blob/d850f41f89530917000d8e6bb463f42bb745b930/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchindex.json as an example. It has nested level of polymorphism.

[Here](https://github.com/Azure/azure-sdk-for-net/issues/28962) you added the information about polymorphic schema to track the work for V1.1.

[Here](https://microsoft-my.sharepoint.com/personal/annelo_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fannelo%5Fmicrosoft%5Fcom%2FDocuments%2FRecordings%2FDPG%20C%5F%20Design%20Discussion%2D20220520%5F140606%2DMeeting%20Recording%2Emp4&parent=%2Fpersonal%2Fannelo%5Fmicrosoft%5Fcom%2FDocuments%2FRecordings&ga=1) is the recording, you can find polymorphic schema discussion around ~24 minutes.

**Comment by annelo-msft** [comment]
Thank you @ShivangiReja!

**Comment by annelo-msft** [comment]
With regard to the above requirement:
 
> - Add link to REST API documents for the given operation. This will be obtained as follows:
>     - If https://swagger.io/specification/v2/#externalDocumentationObject contains a URI, use this for the link
>     - Use the https://github.com/Azure/autorest.csharp/issues/2253 provided by @mikekistler.

Since many of the generated REST API links in https://github.com/Azure/azure-sdk-for-net/pull/29264 are invalid links and result in a 404 response, we will change this requirement to the following:

**- Add a link to the REST API documents for the given operation.  This should be provided if https://swagger.io/specification/v2/#externalDocumentationObject contains a URI.**

We will validate in DPG tests that if this value is provided, the REST API link is correctly added, and this will be sufficient for DPG v1.0 GA.  Services will be expected to provide these links prior to GA of their service libraries.

FYI @chunyu3, @KrzysztofCwalina, @mikekistler, @ShivangiReja, @lirenhe
