### ISSUE TITLE
How to add cookies to AutoRest requests? (.NET/C#)

### ISSUE THREAD

**Issue by heinrich-ulbricht** [Azure/autorest.csharp#2301]
I need to add a session cookie to authenticate AutoRest requests. How would I do this?

Background: Authentication is done before AutoRest is being used to issue API requests. The existing session must be used which requires sending the session ID via cookie.

(This is on .NET/C#)

**Comment by AlexanderSher** [comment]
@heinrich-ulbricht can you please provide a reference to your configuration file and inputs?

**Comment by AlexanderSher** [comment]
@heinrich-ulbricht the only supported version of authentication is done through token credential: https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet
While I'm not sure if [InteractiveBrowserCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential?view=azure-dotnet) will work for you, but you can create your own type of credential.

Alternatively, you can use [DelegatedTokenCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.core.delegatedtokencredential?view=azure-dotnet)
