### ISSUE TITLE
Suppressing nested scope not work if framework version less than 5.0

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2304]
In this [test](https://github.com/Azure/azure-sdk-for-net/blob/ea748355105ead2208946cc4159e3ce78eaafce2/sdk/core/Azure.Core/tests/OperationInternalOfTTests.cs#L222), we create a scope named `WaitForCompletionResponse`, inside which we will create a nested scope named `UpdateStatus`.

**Expected:** nested `UpdateStatus` will be suppressed because we pass in `true` to the `suppressNestedClientActivities` of ClientDiagnostics [constructor](https://github.com/Azure/azure-sdk-for-net/blob/ea748355105ead2208946cc4159e3ce78eaafce2/sdk/core/Azure.Core/tests/OperationInternalOfTTests.cs#L20).

**Actual:** for target `net461`, `netcoreapp3.1` the nested is not suppressed. (target `net6.0` works well) 

**Root cause:** when we create DisagnosticScope, we decide whether to enable by this [line](https://github.com/Azure/azure-sdk-for-net/blob/ea748355105ead2208946cc4159e3ce78eaafce2/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L42), in which we will [try to get the method `GetCustomProperty` from `Activity` type](https://github.com/Azure/azure-sdk-for-net/blob/ea748355105ead2208946cc4159e3ce78eaafce2/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L392). This method only exists in .net version larger than 5.0. See Activity doc [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-6.0).

**Additional inforamtion:** I saw we have tested the suppressing nested scope scenario in the [ClientDiagnosticsTests.Net50.cs](https://github.com/Azure/azure-sdk-for-net/blob/ea748355105ead2208946cc4159e3ce78eaafce2/sdk/core/Azure.Core/tests/ClientDiagnosticsTests.Net50.cs#L199), but not such tests in ClientDiagnosticsTests.cs.

**Comment by lirenhe** [comment]
@annelo-msft, could you help to check whether this is a DPG 1.0 GA blocker?

**Comment by ShivangiReja** [comment]
Diagnostics scope suppression tests work in code gen repo because I added `<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="5.0.0"/>` in [`AutoRest.TestServerLowLevel.Tests.csproj`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServerLowLevel.Tests/AutoRest.TestServerLowLevel.Tests.csproj#L29)


As per @lmolkova :

>We can't suppress scopes if an old System.Diagnostics.DiagnsoticSource package is used. All supported consumers we have, come with later version of it. But we can't update the version we depend on in Core because of some important reasons. I have some details [here](https://github.com/Azure/azure-sdk-for-net/pull/28066#discussion_r849039613)
>
>So there are two ways to test the change
> * Add `<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="5.0.0"/>` to TestServerLowLevel.Tests project
>* Or make it multi-target for netcoreapp3.1 and net5+ and only test scope suppression on .net 5

**Comment by annelo-msft** [comment]
@pshao25, could you follow @lmolkova's guidance that @ShivangiReja shared for this test?

**Comment by pshao25** [comment]
By design.

Additional information is:
Everyone who uses tracing via OpenTelemetry or supported version of Application Insights SDK would have DiagnosticSource 5.0.0 or higher. AppInsights deprecated version that uses old DiagnosticSource  ~2 years ago.
I.e. in user apps, where DS version is resolved to 5.0.0+ as tracing SDK dependency, suppression would just work. 
Users who don't use tracing don't care about suppression at all.
