### ISSUE TITLE
Generate Models for body-string.json cases

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2307]
## Problem

The DPG generator does not generate models.  Our longer-term vision is to generate version-tolerant Track 2 compliant models as described by the Azure SDK .NET guidelines.  As a first step, we'd like to achieve parity with the HLC generator, and we will achieve this by:
1. Providing coverage for the autorest.testserver model generation test cases
2. Supporting the C# generator transforms [described here](https://github.com/Azure/autorest.csharp#customizing-the-generated-code).

## Specific work tracked by this issue

This issue tracks the work to generate models for the cases described in the [body-string.json](https://github.com/Azure/autorest.testserver/blob/main/swagger/body-string.json) test swagger.

## Success Criteria

- Models generated from [body-string.json](https://github.com/Azure/autorest.testserver/blob/main/swagger/body-string.json) match the output of the HLC generator for [body-string.json](https://github.com/Azure/autorest.testserver/blob/main/swagger/body-string.json)
- Test coverage matches the HLC generator test coverage for this swagger: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServer.Tests/body-string.cs

## Implementation note

@AlexanderSher has filed this issue with a recommended DPG implementation: https://github.com/Azure/autorest.csharp/issues/2207

The Shanghai team owns the final decision regarding how this feature will be implemented.

**Comment by annelo-msft** [comment]
@lirenhe, FYI, this is the first issue for model generation for DPG v1.1.

**Comment by lirenhe** [comment]
Close this one as we will investigate how to leverage CADL for model generation.
