### ISSUE TITLE
Determine whether DPG generator correctly decides when to return Operation vs Operation<BinaryData>

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2312]
For issue https://github.com/Azure/autorest.csharp/issues/2212, we changed the behavior of the DPG generator to return `Operation` from LRO protocol methods instead of `Operation<BinaryData>`.  The criterion for deciding whether to return `Operation` vs. `Operation<BinaryData>` was to do the same thing the HLC generator does when it decides whether a generated subtype of Operation should inherit from Operation or Operation\<T\>.

We confirmed for CLU and Device Update that this was the correct behavior for the generator in this PR:
- https://github.com/Azure/azure-sdk-for-net/pull/28915/files#r888261943
- https://github.com/Azure/azure-sdk-for-net/pull/28915/files#r890331921 (@dpokluda confirmed in a separate thread)

@heaths has shared that this is *not* the correct behavior for the CLU SubmitJob operation.  Before making another change to the DPG generator, we will clarify the requirements for when `Operation` should be returned vs `Operation<BinaryData>`

**Comment by annelo-msft** [comment]
@lirenhe, @KrzysztofCwalina, @lmazuel FYI

**Comment by heaths** [comment]
Here's the 2022-05-15-preview swagger from which we're generating our CLU 1.1.0 beta DPG: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/e7f37e4e43b1d12fd1988fda3ed39624c4b23303/specification/cognitiveservices/data-plane/Language/preview/2022-05-15-preview/analyzeconversations.json (it's in main, FWIW).

**Comment by lirenhe** [comment]
cc @chunyu3

**Comment by annelo-msft** [comment]
Generator functionality is correct.  Per @mikekistler, the final value of the LRO should be described in a 200 response in the response block of the start-operation endpoint.

@heaths, we will need you to update the CLU swagger in the main branch to unblock the [autorest.csharp upgrade](https://github.com/Azure/azure-sdk-for-net/pull/29338).

**Comment by heaths** [comment]
@mikekistler @tg-msft is using the resource URI for a final `GET` when the initial request is a `PUT` still correct even if the initial `PUT` returns a `Operation-Location` header? At this point, though, I don't suppose we could change it even if it is wrong since I imagine other services rely on this for some operations.

At some point, I really think we need to document all the different LRO patterns and make sure we are aligned across generators on how they should all work.

**Comment by mikekistler** [comment]
Yes, you want the resource URL for the final `GET` because the `Operation-Location` header points to the status monitor, and I don't think that is what .NET wants to return as the "final result" of a PUT.
