### ISSUE TITLE
Do we support multiple responses and exceptions in comments

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2314]
This is an example of response in swagger: https://github.com/Azure/azure-rest-api-specs/blob/3196a62202976da192d6da86f44b02246ca2aa97/specification/cognitiveservices/data-plane/TranslatorText/preview/v1.0-preview.1/TranslatorBatch.json#L656-L735

In a response there might be several successful responses and exceptions. However, in our current implementation https://github.com/Azure/autorest.csharp/blob/feature%2Fv3/src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs#L102-L103, when we generate [schema document for <remarks>](https://github.com/Azure/autorest.csharp/issues/2288), we only take the first response and the first exception. So the response we generate now is like 
https://github.com/Azure/autorest.csharp/blob/621093e2bb936b146f73dd49da1047c43e334df9/samples/Azure.AI.DocumentTranslation/Generated/DocumentTranslationClient.cs#L893-L925
And the error response we generate is like
https://github.com/Azure/autorest.csharp/blob/621093e2bb936b146f73dd49da1047c43e334df9/samples/Azure.AI.DocumentTranslation/Generated/DocumentTranslationClient.cs#L903-L917

There is only one response and one error, I don't know how many successful responses we might have in swagger, but at least in swagger there will be multiple exceptions. Do we support multiple successful respones and exceptions if there exists?

**Comment by lirenhe** [comment]
@annelo-msft, is it OK to investigate the solution after 1.0 GA?

**Comment by annelo-msft** [comment]
@pshao25, the examples you're showing come from the DocumentTranslation library which is an [HLC in azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/translation/Azure.AI.Translation.Document/src/autorest.md?plain=1#L12).  Do we have any examples of multiple responses defined for any of the GA-blocking DPG libraries?

**Comment by pshao25** [comment]
@annelo-msft correct one thing, this swagger generates DP in our [autorest repo](https://github.com/pshao25/autorest.csharp/blob/208ad168744162428af3dd01d5a557fe3ea46ef8/samples/Azure.AI.DocumentTranslation/readme.md#L12).

I checked confidentialledger, deviceupdate, webpubsub, and purview. They are not facing this. This should be post-GA issue.

**Comment by annelo-msft** [comment]
> @annelo-msft correct one thing, this swagger generates DPG in our [autorest repo](https://github.com/pshao25/autorest.csharp/blob/208ad168744162428af3dd01d5a557fe3ea46ef8/samples/Azure.AI.DocumentTranslation/readme.md#L12).

Yes, I agree that this is correct.  However, since we don't ship a release of the DPG for DocumentTranslation, any issues with the output do not block GA for v1.0.

> I checked confidentialledger, deviceupdate, webpubsub, and purview. They are not facing this. This should be post-GA issue.

Agreed.

**Comment by lirenhe** [comment]
We won't support this. Close the item.
