### ISSUE TITLE
Add link to REST API documentation to protocol method <remarks> tag in generated reference docs

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2315]
Modelerfour passes `externalDocs` through, and as a result DPG codegen cannot get the 'externalDocs' to generate rest api doc link which will affect .NET reference doc.

This issue will track Modelerfour to support `externalDocs`.

**Comment by annelo-msft** [comment]
@chunyu3, would you please add a link to the m4 issue tracking this work?

**Comment by annelo-msft** [comment]
@chunyu3, @tg-msft has shared that m4 passes through all the swagger info as raw input to the generator, so implementing REST API links from externalDocumentationObject should not be blocked on m4 missing this feature.

Please follow up with @lmazuel on details here, as this level of implementation detail is outside my scope.

**Comment by lirenhe** [comment]
> @chunyu3, would you please add a link to the m4 issue tracking this work?

https://github.com/Azure/autorest/issues/4563

**Comment by chunyu3** [comment]
autorest.csharp has upgrade to new modelerfour version which support ExternalDocs. Close this issue.
