### ISSUE TITLE
[Bug] Api-Version not being attached during pagination

### ISSUE THREAD

**Issue by sarkar-rajarshi** [Azure/autorest.csharp#2323]
Api-Version is not being added as a query parameter when building next page request

The request for first page works as expected (api-version is being added)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/73562869/174414527-631b749d-0c11-46cc-8971-be7b4b6f27d3.png)
.

The request for the next page is not adding api-version, instead it relies solely on the nextLink that is being sent back from the server.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/73562869/174414569-3ff58ac3-d163-452e-a599-50b80565cfe1.png)

Resources:-
- Link to arch board decision: https://github.com/Azure/azure-sdk/issues/3817#issuecomment-1033226508
- Autorest configuration used: https://github.com/Azure/azure-sdk-for-net/blob/feature/jobrouter-repo-setup/sdk/communication/Azure.Communication.JobRouter/src/autorest.md
- Swagger file used to generate client: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/JobRouter/preview/2021-10-20-preview2/communicationservicejobrouter.json
- Operation pasted in the screenshot: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/JobRouter/preview/2021-10-20-preview2/communicationservicejobrouter.json#L1529-L1615

**Comment by annelo-msft** [comment]
Since this is a [`generation1-convenience-client`](https://github.com/Azure/azure-sdk-for-net/blob/feature/jobrouter-repo-setup/sdk/communication/Azure.Communication.JobRouter/src/autorest.md?plain=1#L20), assigning to @AlexanderSher.

**Comment by jsquire** [comment]
@sarkar-rajarshi:   Would you be so kind as to please help us understand whether this blocks a release and, if so, what the timing for that release is?

**Comment by sarkar-rajarshi** [comment]
@jsquire we are currently going through the SDK review process. Once review is complete, this would be blocking us. Tentative timeline for release would be end of year.
