### ISSUE TITLE
Generate basic pageable service methods from a Cadl API description 

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2332]
This tracks the work to obtain parity with what the DPG generator can generate from swagger files today, for pageable operations.

The DPG 2.0 generator should generate the same API and implementation from Cadl as it did for DPG 1.0 from swagger.

Support for paging in Cadl was provided in: https://github.com/Azure/cadl-azure/tree/main/packages/cadl-azure-core#api
And example Cadl input:

  @doc("Lists the existing widgets.")
  list is ResourceList<Widget>;

**Comment by annelo-msft** [comment]
We should address https://github.com/Azure/azure-sdk-for-net/issues/29342 as part of this as well.

**Comment by lirenhe** [comment]
Update the title and use this issue to track the work for protocal methods generation for paging

**Comment by lirenhe** [comment]
@chunyu3, could you take a look?
