### ISSUE TITLE
Generate convenience methods corresponding to protocol methods defined on a client, from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2335]
### Convenience methods for all operations

This issue tracks the work to generate convenience methods for all operations described in Cadl file.  Generating just a subset of methods is still in design https://github.com/Azure/autorest.csharp/issues/2443, and out of scope for this issue.

#### Input Cadl file
[petstore.cadl](https://github.com/microsoft/cadl/blob/main/packages/samples/petstore/petstore.cadl)

#### Expected output

Operations added to generated client:
- [ ] [ReadValue](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-0ec10628434582dfdc035202ee4a69f55d2b3d4ab4b6f90fdbbe725f63139367R17-R55)
- [ ] [Create](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-0ec10628434582dfdc035202ee4a69f55d2b3d4ab4b6f90fdbbe725f63139367R57-R79)
- [ ] [DeleteValue](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-0ec10628434582dfdc035202ee4a69f55d2b3d4ab4b6f90fdbbe725f63139367R81-R119)

Generated model files:
- [ ] [Pet.cs](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-d77e56a151ec6556711070374e5523122011c4282cca9ba50daf4f527dc3a2e3)
- [ ] [Pet.Serialization.cs](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-b316976d184a1d51b769e4a8bb40d2f64ec890c6d394bf7b75382629370c8c26), including
    - [ToRequestContent](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-b316976d184a1d51b769e4a8bb40d2f64ec890c6d394bf7b75382629370c8c26R56-R61)
    - [FromResponse](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-b316976d184a1d51b769e4a8bb40d2f64ec890c6d394bf7b75382629370c8c26R63-R67)

#### Requirements
- [ ] Documentation comments are provided from `@doc` and `@summary` decorators in the Cadl definition.  Json schema definitions in remarks and examples are not included.
- [ ] Method signature is generated according to rules described in [create convenience method signature](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/DeveloperDrivenEvolution.md#create-the-convenience-method-with-new-signature)
- [ ] No parameter validation is included, because models are service parameters and _should not be validated_ according to the [.NET guidelines on parameter validation](https://azure.github.io/azure-sdk/dotnet_introduction.html#parameter-validation)
- [ ] Diagnostic scope is created according to the following rules [discussed in greater detail here](https://github.com/Azure/autorest.csharp/issues/2127#issuecomment-1086127240):
    - Do not create a diagnostic scope if the convenience method has the same name as the protocol method
    - Do create a diagnostic scope if the convenience method has a different name from the protocol method. 
- [ ] Input model is converted to RequestContent, if present.  
    - `RequestContent content = model.ToRequestContent();`
- [ ] RequestContext is created from CancellationToken.  Call a local `FromCancellationToken()` method as shown in the example, until https://github.com/Azure/azure-sdk-for-net/issues/30066 is implemented.
    - `RequestContext context = RequestContext.FromCancellationToken(CancellationToken cancellationToken);`
- [ ] Protocol methods are called for both sync and async variants with the created inputs:
    - `Response response = ProtocolOperation(content, <other-params>, context);`
- [ ] If there is no output model, the response returned from the protocol operation is returned from the method.  If there is an output model, the response is converted to an output model using the model's FromResponse method, and `Response<OutputModel>` is returned:
    - `return Response.FromValue(Model.FromResponse(response), response);`
- [x] If a model is an input model, it has a method `ToRequestContent` that returns a `RequestContent` containing the model Json, as follows:
```csharp
  internal RequestContent ToRequestContent()
  {
      var content = new Utf8JsonRequestContent();
      content.JsonWriter.WriteObjectValue(this);
      return content;
  }
```
- [x] If a model is an output model, it has a static method `FromResponse` that takes a `Response` containing the model Json and returns a model instance:
```csharp
  internal static OutputModel FromResponse(Response response)
  {
      using var document = JsonDocument.Parse(response.Content);
      return DeserializeOutputModel(document.RootElement);
  }
```

### Design discussion
Further details where the design has been worked out can be found here: https://github.com/Azure/autorest.csharp/issues/2371

**Comment by annelo-msft** [comment]
Generation of [options parameter types](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-parameters) for convenience methods is tracked by https://github.com/Azure/autorest.csharp/issues/2475

**Comment by pshao25** [comment]
No parameter validation is included, because models are service parameters and should not be validated.
Does that mean even it is a required parameter, we will not check the null? Like [this](https://github.com/Azure/autorest.csharp/blob/be8afb50563ed8f5947a4c3250ffc4f30c1ab970/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L82).
And what if it is a query parameter or a path parameter? I think at least the path parameter should be validated? Like [this](https://github.com/Azure/autorest.csharp/blob/be8afb50563ed8f5947a4c3250ffc4f30c1ab970/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L141)

**Comment by annelo-msft** [comment]
> In last design meeting, you have filed https://github.com/Azure/autorest.csharp/issues/2460 to rediscuss this. Should we follow the new discussion result? If so, I think this should be in the August scope.

Let's address #2460 after we complete this issue, and after we have made further progress on the model generation work.  Our priority right now is to deliver the August MVP, and #2460 can be completed after that if needed.

> Does that mean even it is a required parameter, we will not check the null? Like [this](https://github.com/Azure/autorest.csharp/blob/be8afb50563ed8f5947a4c3250ffc4f30c1ab970/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L82).
And what if it is a query parameter or a path parameter? I think at least the path parameter should be validated? Like [this](https://github.com/Azure/autorest.csharp/blob/be8afb50563ed8f5947a4c3250ffc4f30c1ab970/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L141)

The protocol method will do all necessary validation, so nothing is required in the convenience method.

Let's do validate the input model for now, to prevent a NullReferenceException when we call ToRequestContent on it.

> There is a possibility that method already have a parameter called content. How about we make it inline as [this](https://github.com/Azure/autorest.csharp/blob/be8afb50563ed8f5947a4c3250ffc4f30c1ab970/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L87)? But this is endless, because the method may also have the parameters called context, response.

Sure, we can inline the content conversion.
I think it is unlikely that the method will take parameters called `context` and `response`.  If they do, please have the generator return a warning, and rename the variable `context1` or `response1`.

**Comment by pshao25** [comment]
> Let's address https://github.com/Azure/autorest.csharp/issues/2460 after we complete this issue, and after we have made further progress on the model generation work.

So, we still follow the current naming guidance, i.e., add a `Value` to method when it is ambiguous, right?

**Comment by annelo-msft** [comment]
> So, we still follow the current naming guidance, i.e., add a Value to method when it is ambiguous, right?

That is correct.

> One more question: we will put the convenience methods in the same file/class with the protocol methods, correct?

Yes, that is correct.  Let's put the sync/async convenience methods right before their corresponding protocol methods.

**Comment by pshao25** [comment]
@KrzysztofCwalina Seems the requirement here is not correct for [DeleteValue](https://github.com/Azure/azure-sdk-for-net/pull/30004/files#diff-0ec10628434582dfdc035202ee4a69f55d2b3d4ab4b6f90fdbbe725f63139367R81-R119). 

We agreed before that if there is no body and no return type, then we would not add the convenience API. The delete method meet this condition so that we should not generate the convenience API. My question now is: if user sets the decorator @OpenAPI.extension("x-ms-convenient-api", true) to such method, should we ignore it or fail it?

cc @annelo-msft @lirenhe
