### ISSUE TITLE
Provide design for generating models with enum properties from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2338]
There are two kinds of enumeration:
    - "Fixed enum". Meaning the set of values is fixed and guarantee to not change, even in future API versions. In Swagger, this is defined as "modelAsString=false". [In Cadl, using the "enum" keyword](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#enums).
    - "Extensible enum". Meaning the set of values is considered incomplete, and customers may:
        - want to send a custom string not defined in the extensible enum
        - receive an unknown string from the service.
    In Swagger this is defined as "modelAsString=true". In Cadl, using "knownValues" decorator.
 
August MVP: 
- [x] Generate fixed enum of strings: https://github.com/Azure/autorest.csharp/issues/2477
- [x] Generate extensible enum of strings: https://github.com/Azure/autorest.csharp/issues/2528

**Comment by annelo-msft** [comment]
Address https://github.com/Azure/azure-sdk-for-net/pull/30176/files#r932531328

**Comment by lirenhe** [comment]
@annelo-msft, I saw your requirement is 'Generate fixed enum of strings',  so does this mean 'fixed enum of ints' is out of scope for August MVP?

**Comment by annelo-msft** [comment]
@lirenhe, this issue is for the design discussion, so this design is still being worked out.  The implementation is tracked in https://github.com/Azure/autorest.csharp/issues/2477, which still has the `needs-design` label.

We can move forward on the implementation of extensible enums, though.  I'll separate those into a different issue.  There are no fixed enums in the August MVP, so those are lower priority for us at the moment.

**Comment by lirenhe** [comment]
Move the work of fixed enum into #2591  and close this item
