### ISSUE TITLE
Make serialization of DPG-generated models available in the public API

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2351]
Currently, Azure SDK models are written to/read from wire formats internally in service methods on a client.

This tracks the work to design and implement serialization as part of the public API.  Before starting this work, we will need to formalize requirements for this.

[Description TBD]

**Comment by ArthurMa1978** [comment]
Customer report similar ask here https://github.com/Azure/azure-sdk-for-net/issues/31095
