### ISSUE TITLE
Make generated models that don't need to be visible in the public API internal

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2363]
Per @m-nash:

Another thing to consider here is with MPG we found quite a few models that are defined in the swagger that don't need to be public in the SDK.  Typically this was handled by the input/output/model usages however this didn't always get things correct.  We added an extra step in post processing to auto mark anything not needed to be public as internal.

[Description TBD]

**Comment by lirenhe** [comment]
@ArcturusZhang , with your work of internalizer and remover, I believe this problem should be resolved.
Could you help to summerize the design and put it in https://github.com/Azure/autorest.csharp/tree/feature/v3/docs
Thanks
