### ISSUE TITLE
Provide compatibility checks to catch and prevent API breaking changes

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2365]
The DPG generator needs an automated check to determine whether it has generated an API breaking change.  This does not need to be part of the generator; a CI check will suffice.

This tracks the work to determine whether ApiCompat is sufficient for our needs.  What are its capabilities and limitations?

If it is not sufficient, we will need to provide a solution to do this.

**Comment by lirenhe** [comment]
Discussed this with the team, ApiCompat could handle this correctly.  No further work needed.
