### ISSUE TITLE
Provide design for generating convience methods from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2371]
## Simple convenience method generation

This issue tracks the work to define the output of the DPG generator for convenience methods generated on a DPG client from Cadl.

### Scope of issue

Provide design for basic synchronous REST operations with simple models, e.g. flat models with primitive property types.

This will cover the following cases:

HTTP Method:
- [x] Read (GET)
- [x] Create (POST)
- [x] Delete (DELETE)

Parameters:
- [x] Output model (Read, ambiguous method call)
- [x] Input/Output model (Create)
- [x] No input or output model (Delete, ambiguous method call)

### Convenience method definition
1. Documentation comment
2. Method signature
1. Parameter checking
3. Diagnostic scope 
4. Input model conversion to RequestContent
5. Creation of RequestContext from CancellationToken
6. Call to protocol method
7. Response conversion to output model

### Example

The example uses [petstore.cadl](https://github.com/microsoft/cadl/blob/main/packages/samples/petstore/petstore.cadl) as input.

### Implementation

Implementation work tracked in https://github.com/Azure/autorest.csharp/issues/2335

### Full scope of convenience method design (out of scope for this issue)

- Specify subset of operations to generate convenience methods for: https://github.com/Azure/autorest.csharp/issues/2443
- Provide design for convenience methods for Paging and LRO
- Generate all models
- Generate convenience APIs for PATCH operations (models may be different) - e.g. Update

**Comment by lirenhe** [comment]
Is it a valid case that a convience method takes json (requestContent) as input and returns a model?
It is a kind of partial support of model in API.

**Comment by annelo-msft** [comment]
### Design

1. **Method signature** - Create method signature according to rules described in [Create convenience method signature](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/DeveloperDrivenEvolution.md#create-the-convenience-method-with-new-signature)
1. Parameter checking - Models are service parameters and should not be validated according to the [.NET guidelines on parameter validation](https://azure.github.io/azure-sdk/dotnet_introduction.html#parameter-validation)
2. Diagnostic scope - Do/do not create a diagnostic scope according to the following rules [discussed in greater detail here](https://github.com/Azure/autorest.csharp/issues/2127#issuecomment-1086127240):
    - Do not create a diagnostic scope if the convenience method has the same name as the protocol method
    - Do create a diagnostic scope if the convenience method has a different name from the protocol method. 
4. Input model conversion to RequestContent
5. Creation of RequestContext from CancellationToken
6. Call to protocol method
7. Response conversion to output model

**Comment by lirenhe** [comment]
> > Is it a valid case that a convience method takes json (requestContent) as input and returns a model?
> 
> @lirenhe, it is not a valid case that I am aware of. What motivates this question (what real world scenario are you thinking of)?

When I investigated Go DPG with a 3rd party library for documentDB, https://github.com/a8m/documentdb, I found they are using the similar approach:

Some of the APIs are protocal methods directly:  https://github.com/a8m/documentdb/blob/5b41ba0aaeb1e362da52ea4c20fafe97dd1e314b/client.go#L40

Other methods contain the model but they only provide the model for the response:  https://github.com/a8m/document db#readdatabase

Do we have users who prefer the input is json format but they want models as the output. 
I don't have a real scenario now and probably this is not a valid case, but do we have any user study for this pattern?

**Comment by KrzysztofCwalina** [comment]
The methods are internal, so it might not matter initially, but I think long term the To and From methods should take ServiceVersion parameter. I can imagine serialization having to work slightly differently depending on which service version is called.

**Comment by KrzysztofCwalina** [comment]
Separately, we should think (long term) what we want the methods do. I am not thrilled about using the JSON serializer. We should generate writing code using Utf8JsonWriter only, and reading code should using JsonElement only. Also, I would love to optimize Utf8JsonContent. e.g. can it pool the buffer? Can it write directly to the output stream?

**Comment by annelo-msft** [comment]
Approved in the 07/21 design discussion, with follow-up issues filed.
