### ISSUE TITLE
Typer: Create Response composite type of schema and header schemas

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.csharp#238]
For responses, we can't use the raw schema type because we won't store header information. To store it, we have to synthesize a schema and add it to the code model. Also, these schemas should be a new schema type and have a collection within the `schemas` node.

There are a bunch of options:
- Create schema where headers are the properties and a Body property is the response body schema.
- Do not make a new schema. Instead, add the headers as properties to the original body schema.
- Create a schema only for headers. And, add it as a property to the existing schema.
- Create a schema for every differenting body/header combination.
- Create a schema for headers. Create another schema where the headers use a Headers schema as a property, and the body is the normal schema type.

**Comment by pakrym** [comment]
Done.
