### ISSUE TITLE
DPG:  Generate CADL emitter for .net DPG

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2399]
The emitter would take CADL files as input and output the codemodel (based on current design)

This work should be part of the E2E flow for CADL support:  https://github.com/Azure/autorest.csharp/issues/2251

Please reference how other SDKs implement the emitter https://github.com/Azure/autorest.java/issues/1545

**Comment by chunyu3** [comment]
The first version of csharp emitter is implemented. it will support basic features:
- overall code model
- operation
- basic type
- attributes of parameter

PR: https://github.com/Azure/autorest.csharp/pull/2446
