### ISSUE TITLE
Generate .NET client from confidentialledger Cadl API description

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2402]
For our August MVP, we will generate a .NET client for a service that will be specified mid-July.  In the meantime, we want to show that DPG v1.1 has parity with DPG v1.0 with regard to generating clients with protocol methods from swagger.

This issue tracks validating that a DPG generator can generate the ConfidentialLedger client and protocol methods from [cadl-samples/data-plane/confidentialledger](https://github.com/Azure/cadl-azure/pull/1637), to achieve parity with what DPG v1.0 can generate from the confidential ledger OpenAPI description.

#### Inputs:
Cadl files: [cadl-samples/data-plane/confidentialledger](https://github.com/Azure/cadl-azure/pull/1637)

#### Outputs:
ConfidentialLedger files generated by DPG v1.0: [sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/Generated](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/Generated)

##### Exceptions:
There are a few things we won't generate from this Cadl file:
- Additions to the API described in the ConfidentialLedger customization layer
- We can't currently name the ConfidentialLedgerIdentityServiceClient private Uri property `identityServiceUri` because of https://github.com/microsoft/cadl/issues/678
- We won't generate the GetLedgerEntries operation because pageable operations are out of scope for the August MVP.

**Comment by annelo-msft** [comment]
@jsquire FYI.

**Comment by archerzz** [comment]
Found two issues during CADL compilation into `cadl.json`:
- Looks like the content in the second import (`./identityservice.cadl`) is not processed: https://github.com/Azure/cadl-azure/blob/031a45243f8974d48bfc7165b14180795ad373b6/packages/cadl-samples/data-plane/confidentialledger/main.cadl#L1-L2
- There is an unknown kind for `statusCode`, worked around by manually editing the `cadl.json` to change it to `int32`.
![image](https://user-images.githubusercontent.com/4516/187642559-1b6522eb-7360-4536-9f0a-831753d0c3c4.png)

**Comment by lirenhe** [comment]
@archerzz, could you fix issues you found directly or do you need some more input from others?

**Comment by lirenhe** [comment]
@archerzz,  when this work completes, could you submit a 'review only' PR for the SDK generated, it would be helpful for others to review the generated SDK.

**Comment by lirenhe** [comment]
@archerzz, please verify the code generated  with the latest codegen.
Can we make this as part of the CI?

**Comment by archerzz** [comment]
- generated codes: https://github.com/archerzz/autorest.csharp/tree/dpg/samples/confidential-ledger/samples/ConfidentialLedger
- API view: https://apiview.dev/Assemblies/Review/259f891e90934da4a7855efc7c137d5f

**Comment by chunyu3** [comment]
Verified. confirm with @annelo-msft

**Comment by lirenhe** [comment]
No further action needed.  Close this item.
