### ISSUE TITLE
Need x-ms-error-response parity in CADL model

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2439]
We use `x-ms-error-response` to tell if a response is an error, and generate document by this flag as https://github.com/Azure/autorest.csharp/blob/feature%2Fv3/src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs#L102-L103

Currently, swagger emitter for CADL not generate this flag. Issue created [here](https://github.com/Azure/cadl-azure/issues/1712). 

Not sure if CADL compiler contains this information but we need this.

**Comment by AlexanderSher** [comment]
x-ms-error-response is used to mark response as error, but **autorest.csharp** doesn't use error responses. All error status codes are handled by instances of https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/StatusCodeClassifier.cs , so even in convenience methods there will be no way to utilize error responses cause protocol method will throw an exception for error code.

**Comment by pshao25** [comment]
We discussed here https://github.com/Azure/autorest.csharp/pull/2424#discussion_r924300364. We currently not need this, so close.

**Comment by weidongxu-microsoft** [comment]
This might still helpful for other SDKs.

For now, we can only use default rule, like "*" and >= 400 as error.

**Comment by pshao25** [comment]
> This might still helpful for other SDKs.
> 
> For now, we can only use default rule, like "*" and >= 400 as error.

Yes, I saw this issue has been triaged to fix. https://github.com/Azure/cadl-azure/issues/1712
