### ISSUE TITLE
Need change the sequence of rename features

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#2445]
The `rename-rules` is happened before `prepend-rp-prefix` and `rename-mapping` so the 'Serialized Name' in the document might not right.
For example:
```
Serialized Name: NetworkRuleSetIpRule
```
But here the `Ip` is renamed to `IP`, so if we use `NetworkRuleSetIpRule` as the key to do `prepend-rp-prefix` and `rename-mapping` then nothing happen

**Comment by RodgeFu** [comment]
PR:
https://github.com/Azure/autorest.csharp/pull/3677
https://github.com/Azure/azure-sdk-for-net/pull/38379
