### ISSUE TITLE
Generate input models with reference and value type properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2451]
### Input model with reference and value type properties
This issue tracks the work to implement generation of input models with reference and value type properties in the DPG generator.

#### Input Cadl file
[Cadl testserver models/input-basic](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/input-basic)

#### Expected output
Files: 
- [ ] [InputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-input-basic/sdk/template/Azure.Template/src/Generated/Models/InputModel.cs)
- [ ] [InputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-input-basic/sdk/template/Azure.Template/src/Generated/Models/InputModel.Serialization.cs)

Requirements:
- [ ] If `doc` is not specified for model and properties, generate a warning. (Pending on [this issue](https://github.com/Azure/cadl-azure/issues/1748) in cadl compiler)
- [x] Input models have only one public constructor, and it takes required values
- [x] Required properties are not settable on input models
- [x] Required reference type properties are checked for null in constructor
- [x] Write operation is defined in serialization partial class
- [x] Required properties are written without checking to see if they're defined

#### Test Coverage
To the extent we can, we should reuse tests from [ModelShapes](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/ModelShapes)

**Comment by archerzz** [comment]
We have the basic model and serialization ready. See the following PRs. However, until we have the input/output/roundtrip info from the emitter, we cannot proceed.

- https://github.com/Azure/autorest.csharp/pull/2508
- https://github.com/Azure/autorest.csharp/pull/2519

**Comment by annelo-msft** [comment]
@archerzz, if we assume all models are roundtrip models for now, can we move forward with generating only roundtrip models?

**Comment by annelo-msft** [comment]
Cadl work is tracked in this issue: https://github.com/Azure/cadl-azure/issues/1733

**Comment by archerzz** [comment]
close since it's implemented, see test case: https://github.com/Azure/autorest.csharp/blob/30e69df58b7cfcd8e700f3400601722c74186ab3/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/ModelWriterTests.cs#L29-L45
