### ISSUE TITLE
Generate input models with dictionary type properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2453]
Design will be specified in https://github.com/Azure/autorest.csharp/issues/2472

### Input model with Collection and Dictionary properties
This issue tracks the work to implement generation of input models with dictionary type properties in the DPG generator.

#### Input Cadl file
TBD

#### Expected output
Files: 
TBD

Requirements:
TBD

#### Test Coverage
To the extent we can, we should reuse tests from [ModelShapes](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/ModelShapes)

**Comment by archerzz** [comment]
CADL `Map<K,V>` is replaced by `Record<V>`. The design is in #2474

**Comment by archerzz** [comment]
@annelo-msft I've added the initial support of dictionary support in #2657 

You can refer to the following test cases for the expected output. I checked the contents which look fine to me.

- general test cases: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/DictionaryWritingTests.cs
- optional dictionary property: https://github.com/Azure/autorest.csharp/blob/6761a1b7074b9c74f06790f7989b4c724f0a8234/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/OptionalPropertyWritingTests.cs#L55
- read-only dictionary property: https://github.com/Azure/autorest.csharp/blob/6761a1b7074b9c74f06790f7989b4c724f0a8234/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/ReadonlyPropertyWritingTests.cs#L53-L56

**Comment by lirenhe** [comment]
@archerzz, can we close this item?

**Comment by annelo-msft** [comment]
@archerzz, I don't see where the output models are - the files containing types that have dictionary properties.  Can you provide links to the Cadl input and generated output?

**Comment by archerzz** [comment]
@annelo-msft I didn't write the Cadl file for model generation. I always start from the InputModel, assuming the emitter will generate the correct JSON output.
- Here are the InputModel definition for output models: https://github.com/Azure/autorest.csharp/blob/8cfc0d7838c9736de204d4d9ab726acd8bdb3f56/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/DictionaryWritingTests.cs?rgh-link-date=2022-08-30T03%3A14%3A08Z#L36-L47
- Here are the corresponding generated codes: https://github.com/Azure/autorest.csharp/blob/8cfc0d7838c9736de204d4d9ab726acd8bdb3f56/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/DictionaryWritingTests.cs?rgh-link-date=2022-08-30T03%3A14%3A08Z#L416-L560
