### ISSUE TITLE
Rename configuration `rename-rules` to `acronym-mapping`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#2456]
The name `rename-rules` looks similar to `rename-mapping` and is not quite fully described what this configuration could do.
We would like to rename it to reflect its real purpose.

**Comment by RodgeFu** [comment]
PR: 
https://github.com/Azure/autorest.csharp/pull/3676
https://github.com/Azure/azure-sdk-for-net/pull/38294
