### ISSUE TITLE
Sample generation V2

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2459]
Current sample generation often produces code that won't compile, e.g.:
- https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjectsLowLevel/body-complex/Generated/PrimitiveClient.cs#L1257
- https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjectsLowLevel/body-complex/Generated/PolymorphicrecursiveClient.cs#L398
- https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjectsLowLevel/lro/Generated/LROsClient.cs#L90

Also, generation happens before post-generation Roslyn-based transformation are applied. 

Instead of using ad-hoc writer for the samples, we should use Roslyn input to produce samples that are guaranteed to compile.

**Comment by lirenhe** [comment]
Not high priority for GA, move into backlog.

**Comment by chunyu3** [comment]
We will add all the example correctness and enhancement in issue https://github.com/Azure/autorest.csharp/issues/3274. close this one.
