### ISSUE TITLE
[DPG Design] Consider whether we want to make RequestContext required in protocol methods when generating convenience methods

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2460]
For DPG v1.0 GA, where we would add convenience methods manually, the guidance was what is documented here: https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/DeveloperDrivenEvolution.md#create-the-convenience-method-with-new-signature

This has us adding the `Value` suffix to a convenience method if it introduces an ambiguous call site with the protocol method.  If we are adding protocol methods to a GA'ed convenience client and the convenience APIs cannot be changed, we would make RequestContext required instead of suffixing the protocol method.

We should consider now that we can [generate convenience APIs alongside protocol methods](https://github.com/Azure/autorest.csharp/issues/2335), that we can make RequestContext required in all cases to disambiguate methods rather than adding a suffix to the convenience API.

This raises questions about how we could detect whether a protocol method with an optional RequestContext has GA'ed or not and can be changed.  Given the implications for versioning, this issue is out of scope for the DPG v1.1 August MVP.

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/2887

**Comment by lirenhe** [comment]
close this one as duplicate 0f #2887
