### ISSUE TITLE
Generate round-trip models with reference and value type properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2463]
### Rount-trip model with reference and value type properties
This issue tracks the work to implement generation of round-trip models with reference and value type properties in the DPG generator.

#### Input Cadl file
[Cadl testserver models/roundtrip-basic](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/roundtrip-basic)

#### Expected output
Files: 
- [ ] [RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-roundtrip-basic/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)
- [ ] [RoundTripModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-roundtrip-basic/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.Serialization.cs)

Requirements:
- [ ] If `doc` is not specified for model and properties, generate a warning.
- [x] Round-trip models have only one public constructor, and it takes required values
- [x] Required properties are both gettable and settable on round-trip models
- [x] Required reference type properties are checked for null in constructor
- [x] `Write` method is defined in serialization partial class
- [x] `DeserializeRoundTripModel` method is defined in serialization partial class

#### Test Coverage
To the extent we can, we should reuse tests from [ModelShapes](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/ModelShapes)

**Comment by lirenhe** [comment]
doc related work will be put into a separate task.  Other work completed

**Comment by annelo-msft** [comment]
@lirenhe / @archerzz, could you provide the output of the generator on https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/roundtrip-basic, so I can confirm that this issue is complete?

**Comment by annelo-msft** [comment]
> doc related work will be put into a separate task.

@lirenhe, could you provide a link that issue here?

**Comment by lirenhe** [comment]
> > doc related work will be put into a separate task.
> 
> @lirenhe, could you provide a link to that issue here?

I created https://github.com/Azure/autorest.csharp/issues/2603.   Please update that issue if there are more asks on @doc part.
