### ISSUE TITLE
Add support for tests from CADL test server

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2467]
Similar to [autorest testserver](https://github.com/Azure/autorest.testserver), we need support for CADL test server. Tests should work offline.

**Comment by lirenhe** [comment]
@AlexanderSher,  what do you mean by ' Tests should work offline.' Can we reuse the CADL files from https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models?

**Comment by annelo-msft** [comment]
@lmazuel has asked that we postpone work on this until mid next-week, while they solve some issues with the new Cadl test server.
