### ISSUE TITLE
Generate input models with collection type properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2469]
### Input model with collection type properties
This issue tracks the work to implement generation of input models with collection type properties in the DPG generator.

#### Input Cadl file
[Cadl testserver models/collections-basic](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/collections-basic/main.cadl#L16-L24) (InputModel)

#### Expected output
Files: 
- [ ] [InputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-collections-basic/sdk/template/Azure.Template/src/Generated/Models/InputModel.cs)
- [ ] [InputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-collections-basic/sdk/template/Azure.Template/src/Generated/Models/InputModel.Serialization.cs)

Requirements:
- [ ] If `doc` is not specified for model and properties, generate a warning. (Pending on [this issue](https://github.com/Azure/cadl-azure/issues/1748) in cadl compiler)
- [x] Input models have only one public constructor, and it takes required values
- [x] Constructor takes `IEnumerable<string>` and `IEnumerable<int>` for list parameters
- [x] Required reference type properties are checked for null in constructor using `Argument.AssertNotNull`
- [x] List properties are initialized from IEnumerable using System.Linq `.ToList()`
- [x] Required properties are not settable on input models
- [x] Input collection properties can be mutated after construction
- [x] Properties are of type `IList<T>`
- [x] Write operation is defined in serialization partial class
- [x] All items in each collection are written to Json array

#### Test Coverage
To the extent we can, we should reuse tests from [ModelShapes](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/ModelShapes)

**Comment by archerzz** [comment]
close since this is implemented, see test case: https://github.com/Azure/autorest.csharp/blob/30e69df58b7cfcd8e700f3400601722c74186ab3/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/CollectionWritingTests.cs#L34-L50
