### ISSUE TITLE
Generate round-trip models with collection type properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2471]
### Round-trip model with collection type properties
This issue tracks the work to implement generation of round-trip models with collection type properties in the DPG generator.

#### Input Cadl file
[Cadl testserver models/collections-basic](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/collections-basic/main.cadl#L36-L44) (RoundTripModel)

#### Expected output
Files: 
- [x] [RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-collections-basic/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)
- [x] [RoundTripModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-collections-basic/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.Serialization.cs)

Requirements:
- [ ] If `doc` is not specified for model and properties, generate a warning. (Pending on [this issue](https://github.com/Azure/cadl-azure/issues/1748) in cadl compiler)
- [x] Round-trip models have constructors taking required values
    - Public constructor taking `IEnumerable<string>` and `IEnumerable<int>` for list parameters
        - List properties are initialized from IEnumerable using System.Linq `.ToList()`
        - Required reference type properties are checked for null in constructor using `Argument.AssertNotNull`
    - Internal constructor taking `IList<string>` and `IList<int>` for list parameters
        - List properties are initialized from IList by assignment
- [x] Collection properties are not settable
- [x] Properties are of type `IList<T>`
- [x] Write operation is defined in serialization partial class
- [x] DeserializeRoundTripModel method is defined in serialization partial class
- [x] Internal constructor taking `IList<T>` is called

#### Test Coverage
To the extent we can, we should reuse tests from [ModelShapes](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/ModelShapes)

**Comment by annelo-msft** [comment]
We have a number of outstanding issues to address but will move forward with this implementation as these can be changed after the August MVP if needed:
- https://github.com/Azure/autorest.csharp/issues/2515
- https://github.com/Azure/autorest.csharp/issues/2513

**Comment by ArcturusZhang** [comment]
Hi @annelo-msft I have a question: will we have `IReadOnlyList<>`? This is not mentioned in the description

**Comment by annelo-msft** [comment]
IReadOnlyList\<T\> is used only for output models and readonly properties, which aren't covered in this issue.  It's described in the corresponding issue for output models: https://github.com/Azure/autorest.csharp/issues/2470, and the [generated client design doc](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/design/GeneratedClientDesign.md).

**Comment by archerzz** [comment]
We can close this issue. See the codes generated under a test project:
- https://github.com/archerzz/autorest.csharp/blob/dpg/model-e2e/collection/test/TestProjects/CadlCollection/Generated/Pet.cs
- https://github.com/archerzz/autorest.csharp/blob/dpg/model-e2e/collection/test/TestProjects/CadlCollection/Generated/Pet.Serialization.cs

**Comment by annelo-msft** [comment]
@lirenhe / @archerzz, could you provide the output of the generator on https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/roundtrip-basic, so I can confirm that this issue is complete?
