### ISSUE TITLE
Provide design for models with Record<T> Cadl properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2474]
`Record<T>` replaces the deprecated `Map<K, V>`, and will be generated in C# as a Dictionary with string keys.

Design TBD.

#### Notes
This issue replaces https://github.com/Azure/autorest.csharp/issues/2472.

**Comment by lirenhe** [comment]
@archerzz, is this work already completed?

**Comment by archerzz** [comment]
> @archerzz, is this work already completed?

Yes. See the test case: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServerLowLevel.Tests/LowLevel/Generation/DictionaryWritingTests.cs
