### ISSUE TITLE
Provide design for generating options parameter types in convenience APIs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2475]
Continues the work of https://github.com/Azure/autorest.csharp/issues/2335

TBD

**Comment by annelo-msft** [comment]
@m-nash, I believe this is something the management plane SDKs are already doing -- would you be able to point me to the relevant design specs and/or implementation so we can see whether it's possible align data plane and management plane here?  Thanks!

@srnagar FYI

**Comment by ArcturusZhang** [comment]
Close this issue in favor of https://github.com/Azure/autorest.csharp/issues/2476
