### ISSUE TITLE
Generate options parameters types in convenience methods with long parameter lists

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2476]
As described in [the guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-parameters) and designed in https://github.com/Azure/autorest.csharp/issues/2475.

**Comment by ArcturusZhang** [comment]
Corresponding mgmt plane implementation: https://github.com/Azure/autorest.csharp/pull/2862

**Comment by chunyu3** [comment]
Mgmt. SDK already has the design and implementation about property bag. https://github.com/Azure/autorest.csharp/issues/2951
Please investigate how we could leverage that to handle the long list of paramters for DPG.

**Comment by chunyu3** [comment]
DPG will not automatically generate option bag for long parameter lists.
When customer want to generate option bag, they need to define/customize in client.tsp.
