### ISSUE TITLE
Generate models with "fixed enum" of string properties from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2477]
### Input/Output/Round-trip models with fixed enum type properties
This issue tracks the work to implement generation of models with Cadl fixed enum properties in the DPG generator.  These correspond to .NET CLR enum types.  https://github.com/Azure/autorest.csharp/issues/2528 tracks the generation of Cadl "string enums" or "extensible enums" separately.

If we need to triage this work, generation of Round-trip models is P0, and generation of Input and Output models is P1.

#### Input Cadl file
[Cadl testserver models/enum-properties](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/enum-properties)

#### Expected output

Standard Enum Files:
- [x] [DayOfTheWeek.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/DayOfTheWeek.cs)
- [x] [DayOfTheWeek.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/DayOfTheWeek.Serialization.cs)
- [x] Generated as CLR enum
- [x] Is in `.Models` namespace
- [ ] Generator warning if `@doc` is not provided on enum (Pending on [this issue](https://github.com/Azure/cadl-azure/issues/1748) in cadl compiler)
- [x] `@doc`-decorated values use the Cadl-provided value in the docstrings (`Wednesday` has a `@doc` value)
- [x] Values without `@doc`-decorated value have the name of the value in the docstrings.
- [x] Serialization file contains `DayOfTheWeekExtensions` extension class
- [x] `ToSerialString` converts enum value to string
- [x] `ToDayOfTheWeek` converts string to enum value

Input Model Files: 
- [x] [InputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/InputModel.cs)
- [x] [InputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/InputModel.Serialization.cs)
- [x] Input models have only one public constructor, and it takes required values
- [x] Required properties are not settable on input models
- [x] Write operation is defined in serialization partial class

Output Model Files: 
- [x] [OutputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/OutputModel.cs)
- [x] [OutputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/OutputModel.Serialization.cs)
- [x] Output models have internal constructor taking required values
- [x] Required properties are not settable on output models
- [x] DeserializeOutputModel method is defined in serialization partial class

Round-Trip Model Files: 
- [x] [RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)
- [x] [RoundTripModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.Serialization.cs)
- [x] Round-trip models have public constructor, and it takes required values
- [x] Required properties are both gettable and settable on round-trip models
- [x] `Write` method is defined in serialization partial class
- [x] `DeserializeRoundTripModel` method is defined in serialization partial class

#### Design notes
Design discussed in https://github.com/Azure/autorest.csharp/issues/2338

**Comment by KrzysztofCwalina** [comment]
> ToSerialString converts enum value to string
> ToDayOfTheWeek converts string to enum value

I think these should work with UTF8, not String.

**Comment by annelo-msft** [comment]
> I think these should work with UTF8, not String.

@KrzysztofCwalina, we will address this as part of the serialization optimization work item, rather than slowing progress toward the MVP by making changes to serialization.
