### ISSUE TITLE
DPG: Emit model from CADL input

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2480]
Emit models from cadl file.
1.Emit following models:

- [x] Primitive type (String, Int*, Float*, Bytes, and so on)
- [x] Extensible Enum type
- [x] Sealed Enum type
- [x] array type
- [x] dictionary type
- [x] object/complex type, the fields of object are primitive type 
- [x] nested model (composite model with other)
- [x] polymorphism

2. Add constrains, format, default value to Model

**Comment by lirenhe** [comment]
cc @AlexanderSher.  Please help to make sure E2E works.
