### ISSUE TITLE
Support the Cadl @header decorator

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2494]
Design tracked by https://github.com/Azure/autorest.csharp/issues/2493

**Comment by lirenhe** [comment]
Reopen this as there are still work needed.   @ArcturusZhang, could you add more detail on this?  Thanks

**Comment by ArcturusZhang** [comment]
Close this issue in favor of the other https://github.com/Azure/autorest.csharp/issues/2493
