### ISSUE TITLE
Provide design for representing Cadl arrays of value types

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2513]
In our C# design review, a concern was raised about representing all collections with IEnumerable and IList.  See https://github.com/Azure/azure-sdk-for-net/pull/30176/files#r932519434 for details.

Provide a design for how we will handle this in the code generator.

See https://github.com/Azure/cadl-azure/issues/1789 regarding the ask on the Cadl side and related discussion.

**Comment by annelo-msft** [comment]
Address https://github.com/Azure/azure-sdk-for-net/pull/30176/files#r932458521 as part of larger collection conversation.

**Comment by annelo-msft** [comment]
One proposal, per @KrzysztofCwalina is:

We could also use some heuristics, e.g.
1.	If collection of bytes => BinaryData
2.	If collection of primitives => T[] or Memory\<T\>
3.	if collection of structs =>  T[] or Memory\<T\> (?)
4.	otherwise => IList\<T\>

This could look like:
[RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-value-type-collections/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)
[RoundTripModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-value-type-collections/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.Serialization.cs)

See property type: https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-value-type-collections/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs#L43

Questions:
- Do we have any Track 2 libraries that have array properties in models?
- How would we decide between T[] and Memory\<T\>
- How would we specify in Cadl if we wanted to override the heuristic?  
- How would we decide whether to use IList\<T\> vs. T[] in general?  If it is a manual step, how would we instruct library authors?

Right now, our method of differentiation is by use case:
For example, IList\<int\> might be a better representation of mutable ZipCodes property. And int[] is probably better for return property DailyTemperaturesSince1765.

Is it size that decides it?  Mutability?

**Comment by annelo-msft** [comment]
We'll do 1 & 4 for August MVP.

GeoJson would be a good example for T[] use cases.

Form Recognizer as well.

**Comment by annelo-msft** [comment]
Moving out of v2.0b1, as the following items track 1 & 4:
1: https://github.com/Azure/autorest.csharp/issues/2471
4: https://github.com/Azure/autorest.csharp/issues/2516

**Comment by chunyu3** [comment]
@archerzz  please do performance tuning on iteration array with `T[] ` or `IList<T>` as following:

IList<int> a = new int[]{ 1, 2, 3, 4};
IList<int> b = new List(){ 1, 2, 3, 4};
int[] c = new int[]{1, 2, 3, 4};

1. compare iteration over `a` and `b`
2. compare iteration over `a` vs over `c`

If the performance is the same, we will use the same signature for #2, #3, #4, that is IList<T>

Thanks

**Comment by archerzz** [comment]
## Iteration Perf BenchMark

Here are the codes of benchmark.
```csharp
        private static readonly IList<int> IntList = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
        private static readonly IList<int> IntListInitializedByArray = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
        private static readonly int[] IntArray = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };

        [Benchmark]
        public int IterateList()
        {
            var sum = 0;
            foreach (var i in IntList)
            {
                sum += i;
            }
            return sum;
        }

        [Benchmark]
        public int IterateListInitializedByArray()
        {
            var sum = 0;
            foreach (var i in IntListInitializedByArray)
            {
                sum += i;
            }
            return sum;
        }

        [Benchmark]
        public int IterateArray()
        {
            var sum = 0;
            foreach (var i in IntArray)
            {
                sum += i;
            }
            return sum;
        }
```

And the benchmark is as below:
|                        Method |                  Job |              Runtime |      Mean |     Error |    StdDev |
|------------------------------ |--------------------- |--------------------- |----------:|----------:|----------:|
|                   IterateList |             .NET 6.0 |             .NET 6.0 | 93.790 ns | 1.6098 ns | 1.3442 ns |
| IterateListInitializedByArray |             .NET 6.0 |             .NET 6.0 | 52.713 ns | 0.7947 ns | 0.7434 ns |
|                  IterateArray |             .NET 6.0 |             .NET 6.0 |  4.533 ns | 0.0614 ns | 0.0544 ns |
|                   IterateList |        .NET Core 3.1 |        .NET Core 3.1 | 96.423 ns | 1.9598 ns | 2.0970 ns |
| IterateListInitializedByArray |        .NET Core 3.1 |        .NET Core 3.1 | 55.323 ns | 0.6259 ns | 0.5855 ns |
|                  IterateArray |        .NET Core 3.1 |        .NET Core 3.1 |  4.810 ns | 0.0984 ns | 0.0920 ns |
|                   IterateList | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 99.659 ns | 0.7572 ns | 0.6712 ns |
| IterateListInitializedByArray | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 80.682 ns | 1.5763 ns | 1.6187 ns |
|                  IterateArray | .NET Framework 4.6.1 | .NET Framework 4.6.1 |  5.840 ns | 0.0872 ns | 0.0773 ns |

As you can see, raw array is **20X faster** than generic List, and List initialized by array is **2X faster** than List.

**Comment by m-nash** [comment]
@chunyu3 
Sounds like our path forward here is to default to IList<T> and IReadOnlyList<T> except for byte[] that will be BinaryData.

We might in the future add a decorator in cadl that can be set to indicate we should use T[] but only in the cases where we explicitly turn this on.  Until we have that use case this can be lower priority.

**Comment by chunyu3** [comment]
already implemented. close it.
