### ISSUE TITLE
Implement default namespace for models, and enable Cadl override

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2514]
We will either put models in a `.Models` namespace by default and allow configuration to override this, or put them in the main namespace by default and allow configuration to specify putting them in a `.Models` namespace.  @KrzysztofCwalina, @tg-msft, FYI.

See discussion https://github.com/Azure/azure-sdk-for-net/pull/30176/files#r932491403

This issue tracks the work to implement the default namespace for models and handle the override as specified from Cadl configuratoin.

**Comment by lirenhe** [comment]
@archerzz, could you help to check whether there are any engineer effort in this issue?  thanks

**Comment by archerzz** [comment]
> @archerzz, could you help to check whether there are any engineer effort in this issue? thanks

Right now we don't use `.Models` namespace for models. So, model classes are generated under the same namespace of client classes.

If we decided to use `.Models` namespace by default and provide options to override, then there will be engineering efforts that:
- change default namespace of model classes to `XXX.Models`
- support configuration to override namespace

**Comment by archerzz** [comment]
Probably pending on the discuss in https://github.com/Azure/cadl-azure/issues/1787

**Comment by lirenhe** [comment]
Updated based on the discussion. 


- [ ]  Have the configuration of 'namespace' in cadl-project.yaml
- [ ]  model-namespace in cadl-project.yaml, default 'true' to put models in a `.Models` namespace by default. Else, put models in the root namespace.

As this would impact all SDKs, please prioritize this work.
