### ISSUE TITLE
Generate models with properties of type Cadl `bytes`

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2516]
We will generate properties specified in Cadl as `bytes` as BinaryData, see https://github.com/Azure/azure-sdk-for-net/pull/30176#discussion_r932501033

There are outstanding serialization questions to address as part of providing this design.

**Comment by AlexanderSher** [comment]
So is it `BinaryData` or `byte[]`? Right now, `ByteArraySchema` is converted into `byte[]`.

**Comment by annelo-msft** [comment]
For August MVP, Cadl `bytes` keyword maps to BinaryData, see https://github.com/Azure/azure-sdk-for-net/blob/main/doc/design/GeneratedClientDesign.md#type-mappings-from-cadl-to-net

**Comment by annelo-msft** [comment]
Included in Beta1 for end of September.

**Comment by annelo-msft** [comment]
We prefer `BinaryData` over `bytes[]` for the following reasons, per @KrzysztofCwalina:

- Users need to often interpret bytes they receive and create bytes they send. BinaryData makes common tasks related to byte playload conversions easy, e.g. convert string to UTF8 bytes or deserlialize JSON bytes to POCO.
- T[] is read/write, BinaryData is read-only. We try to keep our output models immutable
- BinaryData can be a more efficient representation of bytes received or to be send over the wire (because T[] needs to be exact size, and BinaryData does not)

We will address backward compatibility for GA APIs through existing features, either using C# customization or specifying types through Cadl decorators.

**Comment by archerzz** [comment]
Just a head-up. One lesson we learned from Mgmt Track 2 is that we should take care if `BinaryData` would be used to represent multiple data types, e.g. polymorphism.

**Comment by annelo-msft** [comment]
> Just a head-up. https://github.com/Azure/autorest.csharp/issues/2447 we learned from Mgmt Track 2 is that we should take care if BinaryData would be used to represent multiple data types, e.g. polymorphism.

Thank you, @archerzz!  Can you help us understand what the issues surrounding BinaryData and polymorphism?  It looks like the issue you linked is about strings, so I don't see the connection but would like to understand better.  Also, do you know if there is a resolution for this issue and/or what the timeline for resolution is?  Thanks!

**Comment by archerzz** [comment]
> > Just a head-up. #2447 we learned from Mgmt Track 2 is that we should take care if BinaryData would be used to represent multiple data types, e.g. polymorphism.
> 
> Thank you, @archerzz! Can you help us understand what the issues surrounding BinaryData and polymorphism? It looks like the issue you linked is about strings, so I don't see the connection but would like to understand better. Also, do you know if there is a resolution for this issue and/or what the timeline for resolution is? Thanks!

@annelo-msft The issue is that in mgmt SDK, `BinaryData` in the generated codes used to represent a JSON object. Then later on, some change has been made so that `BinaryData` can represent strings. But the corresponding serialization/deserialization logic has not been updated. So error could happen when handling `BinaryData` because we're treating it as JSON object, but actually it could be string.

This is not an issue for DPG, since we have a clear 1:1 mapping between `byte[]` and `BinaryData`. I raised this issue just for a head-up, because `BinaryData` could be extended to represent other types.

**Comment by archerzz** [comment]
@annelo-msft I guess for cadl `bytes`, we want to generate the following class and serialization. Can you confirm?

## model class
```csharp
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Cadl.TestServer.PrimitiveProperties
{
    /// <summary> Round-trip model with primitive properties to show serialization and deserialization of each. </summary>
    public partial class PrimitivePropertyModel
    {
        /// <param name="requiredBytes"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="requiredBytes"/> is null. </exception>
        public PrimitivePropertyModel(BinaryData requiredBytes)
        {
            Argument.AssertNotNull(requiredBytes, nameof(requiredBytes));

            RequiredBytes = requiredBytes;
        }

        public global::System.BinaryData RequiredBytes{ get; set; }
    }
}
```

---

## Serialization Class
```csharp
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure;
using Azure.Core;

namespace Cadl.TestServer.PrimitiveProperties
{
    public partial class PrimitivePropertyModel: IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
       {
            writer.WriteStartObject();
            writer.WritePropertyName("requiredBytes");
#if NET6_0_OR_GREATER
			writer.WriteRawValue(RequiredBytes);
#else
            JsonSerializer.Serialize(writer, JsonDocument.Parse(RequiredBytes.ToString()).RootElement);
#endif
            writer.WriteEndObject();
        }

        internal static PrimitivePropertyModel DeserializePrimitivePropertyModel(JsonElement element)
        {
            BinaryData requiredBytes = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("requiredBytes"))
                {
                    requiredBytes = BinaryData.FromString(property.Value.GetRawText());
                    continue;
                }
            }
            return new PrimitivePropertyModel(requiredBytes);}
        }
    }
}
```
