### ISSUE TITLE
[BUG] The 'rename-mapping' can't support some format correctly 

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#2524]
- [ ] `date-time`
- [ ] `duration` :  The generated code is wrong which missing the parameter of `GetTimeSpan()` method.
- [x] `ip-address`

**Comment by ArcturusZhang** [comment]
[Address review comments for DataFactory by ArthurMa1978 · Pull Request #30241 · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/pull/30241/files#diff-2462659e0ebbe5dfe8b701e329326d139f5b4d2b5fb5471a2fa6765a32afd591) end of file there are 2 duration , if use rename-mapping, the generated code is not right
