### ISSUE TITLE
Generate models with extensible enum properties from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2528]
### Input/Output/Round-trip models with enum and "string enum" type properties
This issue tracks the work to implement generation of models with Cadl "string enum" type properties in the DPG generator.  These correspond to "extensible enums" or "strongly typed strings" in .NET.

If we need to triage this work, generation of Round-trip models is P0, and generation of Input and Output models is P1.

#### Input Cadl file
[Cadl testserver models/enum-properties](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/enum-properties)

#### Expected output

String Enum Files:
- [x] [TranslationLanguage.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/TranslationLanguage.cs)
- [x] No corresponding .Serialization.cs file.
- [x] Is in `.Models` namespace
- [x] "String enum" is generated as a strongly-typed string (see [FDG3, Section 4.11](https://learning.oreilly.com/library/view/framework-design-guidelines/9780135896457/ch04.xhtml#sec4_11)
- [x] "String enum" is defined as a readonly partial struct
- [x] Public constructor takes string value
- [x] Constructor calls Argument.AssertNotNull on value
- [x] Values are provided as public static properties of the strong-typed string type
- [x] Values are get-only
- [x] Overrides `ToString()`
- [x] `==`, `!=` and cast operators are provided
- [x] Provides Equals(StringEnum other)
- [x] Defines Equals(object) and GetHashCode(), but applies [EditorBrowsableState.Never] to them
- [ ] Generator warning if `@doc` is not provided on enum.  (Pending on [this issue](https://github.com/Azure/cadl-azure/issues/1748) in cadl compiler)
- [x]  `@doc`-decorated values use the Cadl-provided value in the docstrings
- [x] Values without `@doc`-decorated value have the name of the value in the docstrings (`Undocumented` does not have a `@doc` value)

Input Model Files: 
- [x] [InputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/InputModel.cs)
- [x] [InputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/InputModel.Serialization.cs)
- [x] Input models have only one public constructor, and it takes required values
- [x] Required properties are not settable on input models
- [x] Write operation is defined in serialization partial class

Output Model Files: 
- [x] [OutputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/OutputModel.cs)
- [x] [OutputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/OutputModel.Serialization.cs)
- [x] Output models have internal constructor taking required values
- [x] Required properties are not settable on output models
- [x] DeserializeOutputModel method is defined in serialization partial class

Round-Trip Model Files: 
- [x] [RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)
- [x] [RoundTripModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-enum-properties/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.Serialization.cs)
- [x] Round-trip models have public constructor, and it takes required values
- [x] Required properties are both gettable and settable on round-trip models
- [x] `Write` method is defined in serialization partial class
- [x] `DeserializeRoundTripModel` method is defined in serialization partial class

#### Design notes
Design discussed in https://github.com/Azure/autorest.csharp/issues/2338
Corresponding issue tracking "fixed enum" properties is https://github.com/Azure/autorest.csharp/issues/2477

**Comment by archerzz** [comment]
Related work item: https://github.com/Azure/autorest.csharp/issues/2535
Also the depending PR: https://github.com/Azure/autorest.csharp/pull/2536

**Comment by lirenhe** [comment]
Pending on input model and output model.

**Comment by lirenhe** [comment]
We only support string as the enum value
