### ISSUE TITLE
Support the Cadl `interface` keyword

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2529]
### Client generation from Cadl interfaces
This issue tracks the work to implement generation of multiple clients defined by operations grouped by the Cadl interfaces keyword.  See https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#interfaces

#### Input Cadl file
[Cadl testserver clients/interfaces](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/clients/interfaces/main.cadl)

#### Expected output

Two clients are generated as shown [here](https://github.com/annelo-msft/azure-sdk-for-net/tree/cadl-test-client-interfaces/sdk/template/Azure.Template/src/Generated)
- DogsClient with operations GetDog and SetDog
- CatsClient with operations GetCat and SetCat

**Comment by lirenhe** [comment]
@chunyu3, please make sure current CADL compiler and our CADL model could support this. Thanks

**Comment by chunyu3** [comment]
confirmed that we will regard 'interface' and 'namespace' as same when using them to group methods. And each interface will emitted as a client which is by design.
