### ISSUE TITLE
Correctly use enums in protocol method generation

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2535]
Right now, RestClientBuilder generates methods with string and int parameters instead of enums because `TypeFactory.CreateType` incorrectly resolves type for enums:
https://github.com/Azure/autorest.csharp/blob/7da8185a8500150c26766b65f03fe2a2a030e932/src/AutoRest.CSharp/Common/Generation/Types/TypeFactory.cs#L32-L37

When fixed, either `RestClientBuilder` or `LowLevelClientWriter` must be updated to generate correct signatures for protocol methods and CreateXxxMethods.

**Comment by lirenhe** [comment]
@AlexanderSher,  seems this item is related to code refactoring.  So do you think this is required for August MVP? And could you provide the cost estimate for this item?  Thanks
