### ISSUE TITLE
remove 'Configuration.json' dependency for cadl in autorest.csharp

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2539]
When we generate SDK from cadl, the configuration.json is not used anymore.
We need to remove the dependency of the configuration when input is cadl in autorest.csharp.

**Comment by AlexanderSher** [comment]
How are we fulfilling `Configuration`?

**Comment by chunyu3** [comment]
emitter will auto emit Configuration.json from cadl-project.yaml or cadl options.
