### ISSUE TITLE
Confirm DPG v1.0 and DPG v2.0 parity with regard to resiliency

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2550]
### DPG v1.0 and DPG v2.0 parity

This issue tracks the work to show that the DPG v2.0 generator can generate the same client output from a Cadl file as the DPG v1.0 generator can from a swagger file.

#### Cadl Inputs

- [dev-driven](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/resiliency/dev-driven)
- [srv-driven-1](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/resiliency/srv-driven-1)
- [srv-driven-2](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/resiliency/srv-driven-2)

#### Expected Outputs

The generated clients should match those generated from the corresponding autorest.testserver swagger files:

- [dpg-customization.json](https://github.com/Azure/autorest.testserver/blob/main/swagger/dpg-customization.json)
- [dpg-initial.json](https://github.com/Azure/autorest.testserver/blob/main/swagger/dpg-initial.json)
- [dpg-update1.json](https://github.com/Azure/autorest.testserver/blob/main/swagger/dpg-update1.json)

#### Test Coverage

The tests written for the DPG v1.0 clients should work against the DPG v2.0 clients as well.

**Comment by lirenhe** [comment]
I think this could be part  of the effort of Test server support. 
@annelo-msft, what is the priority of this item?

**Comment by pshao25** [comment]
@annelo-msft looks like we only need to do the comparison, there is no coding effort, correct?

I would still put these three test scenarios into #2467

**Comment by pshao25** [comment]
Current gap:
1. Fixed enum is not in the August scope: https://github.com/Azure/cadl-ranch/blob/fa1f20e21bf8dfa6316f7b2025cb7670ffbff068/packages/cadl-ranch-specs/http/resiliency/dev-driven/main.cadl#L26
2. paging and lro cannot be filtered now. Tracked by https://github.com/Azure/autorest.csharp/issues/2565
3.

**Comment by lirenhe** [comment]
Will move to 2.0 beta as srv-driven2 is not a correct CADL file.

**Comment by lirenhe** [comment]
@pshao25, seems only 9&10 left and they are not the scope for beta2,   I plan to move this item to 2.0GA.
Is there anything else left for this item?

**Comment by pshao25** [comment]
None of the cald files in cadl-ranch is ready. Not sure if @iscai-msft would update them?
