### ISSUE TITLE
[DPG]  CADL Emitter should skip the features that CodeGen does not support currently.

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2565]
Today, CodeGen does not support all features in CADL, e.g. LRO, Paging, Patch model, etc.
Keep modifying the CADL source files to exclude them would be difficult especially the CADL files are complex.
CADL emitter should report a warning and avoid generate internal models for the feature that current CodeGen does not support.

Otherwise, CodeGen would fail to generate the SDK code. and we don't want to keep modifying the CADL source file
Based on the discussion, it would be more straightforward to implement this feature in Emitter side.

cc @AlexanderSher 

List of features that need to be excluded:

- [ ] Patch operation
- [ ] Paging
- [ ] LRO
- [ ] Models with discriminator
- [ ] Non extensible enum with type int

**Comment by AlexanderSher** [comment]
We can exclude `Models with discriminator` cause we generate what is needed on CADL side and it doesn't create any problems on the autorest.csharp side
