### ISSUE TITLE
Suppress generation of convenience methods for PATCH operations

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2574]
For the August MVP, we will not generate convenience methods for PATCH operations.  Since we are currently generating convenience methods for all operations from a Cadl API description, we will need to suppress generation of convenience methods for PATCH operations.  This issue tracks the work to do that suppression.

**Comment by lirenhe** [comment]
Related to https://github.com/Azure/autorest.csharp/issues/2565.

**Comment by annelo-msft** [comment]
@lirenhe, I'd like to be careful about saying this is an unsupported feature.  Right now, it is by-design that we don't generate convenience methods for PATCH operations.  The recommendation to users of DPG2.0 libraries is to call a PATCH protocol method and format the json-merge-patch payload themselves.  We may at some point add convenience methods to handle this scenario differently in .NET based on customer feedback about specific scenarios.

I'd prefer if we didn't close this issue until we have specifically disabled generation of convenience methods for PATCH operations.  Thanks!

**Comment by lirenhe** [comment]
Thanks for the clarification, @annelo-msft. Reopen this item.
