### ISSUE TITLE
Generate clients with authentication specified by Cadl @useAuth decorator

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2577]
Cadl support for the `@useAuth` decorator is available with https://github.com/microsoft/cadl/pull/795.

We will support generation of the same set of client constructors for authentication types we supported in DPG v1.0:
- AADToken (a.k.a OAuth2Flow): While Cadl has [several different models]( https://github.com/microsoft/cadl/blob/main/packages/rest/lib/auth.cadl#L86), DPG 1.0 creates one constructor that accepts `TokenCredential` and leaves instantiation of the specific `TokenCredential`-derived type to the user.
- AzureKey (a.k.a ApiKeyAuth): Cadl supports adding api key to [header, query or cookie](https://github.com/microsoft/cadl/blob/main/packages/rest/lib/auth.cadl#L36). DPG 1.0 uses `AzureKeyCredentialPolicy` that always adds key [to the header](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/AzureKeyCredentialPolicy.cs#L30).

Right now, at most one AADToken and one AzureKey are supported, both in HLC and DPG. HLC [merges identical security schemas](https://github.com/Azure/autorest.csharp/blob/f7ea672aeaa84049dfccc5c5e5ab6b93d3e7c86c/src/AutoRest.CSharp/DataPlane/Generation/DataPlaneClientWriter.cs#L426), DPG 1.0 doesn't have well-defined behavior (see https://github.com/Azure/autorest.csharp/issues/2590). 

Details of DPG v1.0 support can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/AzureSDKCodeGeneration_DataPlane_Quickstart.md#authentication-configuration-in-autorestmd).

This is needed for parity with DPG v1.0.

**Comment by lirenhe** [comment]
@chunyu3   please help to make @useAuth  info could be extracted from emitter.

**Comment by annelo-msft** [comment]
@schaabs, @tg-msft, @KrzysztofCwalina, please let us know if you have any concerns with following the DPG1.0 spec in generating client constructor authentication. I know historically much of this has been done in the convenience layer.  We have tracking the design work to support additional Cadl features.

**Comment by AlexanderSher** [comment]
autorest.csharp part is done, emitter part remains

**Comment by chunyu3** [comment]
I am working on emitter part for auth.

**Comment by chunyu3** [comment]
emit user authentication in PR https://github.com/Azure/autorest.csharp/pull/2628
