### ISSUE TITLE
apiVersion should not be a global parameter

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2582]
We now have a gap between the generated client from cadl and the generated client from M4:
![image](https://user-images.githubusercontent.com/97225342/184590699-dec0fb35-3016-47e9-9ab7-37a7308af0e7.png)
apiVersion is a global parameter now. The root cause is: now the output of emitter will add an apiVersion parameter to each operation
![image](https://user-images.githubusercontent.com/97225342/184590786-c36c6a48-4615-490d-ba02-aaaa73821b6b.png)
but previously in M4 it is not an operation level parameter. I believe we need to keep consistence with previous behavior.
Here is how to define the api version in cadl: https://github.com/microsoft/cadl/blob/e84b800c12298aabc92780a6db448ddec5c1006d/packages/samples/petstore/petstore.cadl#L8

**Comment by lirenhe** [comment]
@chunyu3, @AlexanderSher,   I think we should have a separete logic to handle apiversion (or serviceVersion in CADL).
This could be handled either in Emitter or CodeGen side, could you help to make a decision on how to solve this? Thanks

cc @annelo-msft for awareness.

**Comment by chunyu3** [comment]
As discussed with @AlexanderSher , We will add ApiVersion as a property of InputNamespace( SDK library level), and will not emit to each client as an client Parameter.
