### ISSUE TITLE
Provide command line tool for generating a .NET SDK from a Cadl file

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2584]
To validate DPG 2.0 features, we will need a way to use the new Cadl emitter and autorest.csharp functionality to create an output SDK.

@lirenhe has provided [this README](https://github.com/Azure/autorest.csharp/blob/632df1f6dfd24ed30ac4f5f7167921a5e36f31b5/src/CADL.Extension/readme.md#generate-sdk-from-cadl), however, I am currently getting the following error:

![image](https://user-images.githubusercontent.com/21269347/184678068-7db756ff-0f69-4da1-a445-19ef4d49344c.png)

We will also need to resolve how to manage version dependencies.  As I was following the README steps, it became clear that different library versions were needed for different things, here is my command history, for trying to generate an SDK for [the simplest Cadl test case](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/roundtrip-basic/main.cadl):

```
  27        7.638 npm install @cadl-lang/compiler@0.33.0
  28        2.278 npm install @cadl-lang/rest@0.15.1
  29        2.321 npm install c:\src\autorest.csharp/src/CADL.Extension/Emitter.Csharp/azure-tools-cadl-csharp-0.1.0.t…
  31        0.909 cadl compile --emit @azure-tools/cadl-csharp .\main.cadl
  34        2.441 npm install @cadl-lang/compiler@0.34.0
  35        2.187 npm install @azure-tools/cadl-azure-core
  36        2.143 npm install @cadl-lang/rest@latest
  37        0.949 cadl compile --emit @azure-tools/cadl-csharp .\main.cadl
  38        1.942 npm install @azure-tools/cadl-azure-core
  39        1.034 cadl compile --emit @azure-tools/cadl-csharp .\main.cadl
  40        2.134 npm install @cadl-lang/versioning
  41        1.876 npm install @azure-tools/cadl-azure-core
  42        0.980 cadl compile --emit @azure-tools/cadl-csharp .\main.cadl
  43        2.955 npm install @azure-tools/cadl-ranch-expect
  44        1.175 cadl compile --emit @azure-tools/cadl-csharp .\main.cadl
```

**Comment by annelo-msft** [comment]
@iscai-msft, @lmazuel - I know you have been thinking about version dependency issues for Python, any guidance you have for addressing version dependencies will be very helpful!

**Comment by iscai-msft** [comment]
yeah right now it's kind of difficult, I know @timotheeguerin has been looking into this on the cadl side right now to improve. Python has been using pnpm and has been generating from cadl-ranch as a sub-workspace (see [here](https://gist.github.com/iscai-msft/e220e73236de81ff2e7b992e37b79f6f) for more details). 

The first error you showed looks like you might not have built it (iirc), so you might have to run `pnpm run build` / `npm run build` etc (depending on what you're using to manage your packages)

**Comment by lirenhe** [comment]
@pshao25 , assign this item to you and please help to check the comments above.
