### ISSUE TITLE
DPG 2.0GA: Show generated convenience methods

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2586]
One of the requirements for the [August MVP Arch Board](https://github.com/Azure/azure-sdk/issues/4549) is to show that convenience methods can be generated for protocol methods with basic models.  This includes the following features:

DPG **v2.0b1**:
- Basic input/output model convenience methods: https://github.com/Azure/autorest.csharp/issues/2335
- Extensible enum parameters: https://github.com/Azure/autorest.csharp/issues/2556
- Don't generate convenience methods for PATCH: https://github.com/Azure/autorest.csharp/issues/2574

DPG **v2.0b2**:
- Generate convenience methods only for specified operations: https://github.com/Azure/autorest.csharp/issues/2336
- Don't use `Value` suffix on convenience methods: https://github.com/Azure/autorest.csharp/issues/2460
- Options parameters: https://github.com/Azure/autorest.csharp/issues/2476
- Convenience methods for paging operations: https://github.com/Azure/autorest.csharp/issues/2715
- Convenience methods for LROs: https://github.com/Azure/autorest.csharp/issues/2958
- Convenience methods for Paging LROs
- Multiple content types: https://github.com/Azure/autorest.csharp/issues/2550, [srv-driven-2](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/resiliency/srv-driven-2/main.cadl#L100)

**Comment by annelo-msft** [comment]
@srnagar will propose a unified outline across languages that aligns with this.

**Comment by lirenhe** [comment]
Update the title and move to DPG 2.0 beta2
