### ISSUE TITLE
Provide design for multiple security schemas

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2590]
In most cases, swagger input provides at most one `KeySecurityScheme` and one `OAuth2SecurityScheme`. However, it is possible to provide more than one security scheme of each type when there is more than one input. We need to provide correct design for these cases or prohibit such input. 

Specifically, if multiple schemas of the same type are allowed, what should be done if:
- schemas are absolutely identical (throw an exception, report a warning and treat them as one)
- schemas have non-essential differences (e.g. one `AADToken` definition has all scopes from the other and some additional)
- schemas have essential differences

**Comment by annelo-msft** [comment]
Can we detect this case and have the generator throw an exception for the time being?

**Comment by archerzz** [comment]
> Can we detect this case and have the generator throw an exception for the time being?

I have an PR which will delete identical security scheme: https://github.com/Azure/autorest.csharp/pull/2581 I think it's easy to change to throw an exception if security schemes are identical.

As for case 2&3 on top, that depends on the strategy we choose. How do we tolerate security schemes of the same type?

**Comment by AlexanderSher** [comment]
I think we should just throw for everything and postpone the decision. CADL `@useAuth` decorator provides quite complicated inputs that we would have to resolve anyway: https://github.com/microsoft/cadl/blob/b44b8d414e8e940c2eb7a9d92fa40857b3eba3f5/packages/rest/docs/authentication.md

**Comment by chunyu3** [comment]
Cadl already support to provide multiple security schemas, and it will generate clients to support multiple authentication now.

**Comment by lirenhe** [comment]
Close it as duplicate
