### ISSUE TITLE
Cannot generate endpoint with server decorator

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2592]
Add below decorator to the cadl file:
`@server("http://localhost:3000", "Testserver endpoint")`

Run the emitter, there is no parameter with `"IsEndpoint": true`

Therefore, no endpoint generated.

**Comment by annelo-msft** [comment]
We will need to generate endpoint in order to generate any basic client.  Adding this to the August MVP requirements - it is covered as part of the parity requirement.

**Comment by annelo-msft** [comment]
Related to https://github.com/Azure/cadl-azure/issues/1785, which is needed to indicate that the endpoint is a Uri.
