### ISSUE TITLE
Lack of ResponseBodyType leads to example difference between cadl version and swagger version

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2594]
This issue actually depends on the solution to https://github.com/Azure/cadl-ranch/pull/49. I will upate this issue after we find a solution.

### Symptom
Take this [operation](https://github.com/Azure/autorest.testserver/blob/da9260e442bf3736cac5017bf34af6b34f9ceeb5/swagger/dpg-initial.json#L13-L26) as example.
Corresponding cadl: 
https://github.com/Azure/cadl-ranch/blob/c4f41f483eac812527f7b6dc837bd22d255a18ed/packages/cadl-ranch-specs/http/resiliency/srv-driven-1/main.cadl#L29-L39

**swagger version:**
https://github.com/Azure/autorest.csharp/blob/45138313e7c5daa4fdeeb37217bafc1acfb2c481/test/TestServerProjectsLowLevel/dpg-initial/Generated/ParamsClient.cs#L101-L112

**cadl version:**
https://github.com/Azure/autorest.csharp/blob/45138313e7c5daa4fdeeb37217bafc1acfb2c481/test/CadlRanchProjects/srv-driven-1/Generated/ParamsClient.cs#L138-L146

Pay attention to the difference:
1. The text `This sample shows how to call HeadNoParamsAsync and parse the result.`
2. The result `Console.WriteLine(result.ToString());`

### Root cause:
1. The text `This sample shows how to call HeadNoParamsAsync and parse the result.`

The cadl version does not have `parse the result`. We generate this line [here](https://github.com/Azure/autorest.csharp/blob/cf3f4bef2e1fdb860ffb282a45b2aa491d88a43e/src/AutoRest.CSharp/LowLevel/Generation/LowLevelExampleComposer.cs#L177). The generated cadl `LowLevelClientMethod.ResponseBodyType` is `null` while the generated swagger `LowLevelClientMethod.ResponseBodyType` is `CodeModelInput`.

2. The result `Console.WriteLine(result.ToString());`

Same reason. We generate this line [here](https://github.com/Azure/autorest.csharp/blob/cf3f4bef2e1fdb860ffb282a45b2aa491d88a43e/src/AutoRest.CSharp/LowLevel/Generation/LowLevelExampleComposer.cs#L356-L363). The generated cadl `LowLevelClientMethod.ResponseBodyType` is `null` while the generated swagger `LowLevelClientMethod.ResponseBodyType` is `CodeModelInput`.

Looking into the generated cadl.json, there is no `BodyType` generated in `Responses`.

We don't think a model without a property as a response
https://github.com/Azure/autorest.csharp/blob/cf3f4bef2e1fdb860ffb282a45b2aa491d88a43e/src/AutoRest.CSharp/LowLevel/Generation/LowLevelExampleComposer.cs#L436-L439

**Comment by AlexanderSher** [comment]
The difference in output is caused by the difference in input.
- In swagger version, response has schema of type object: https://github.com/Azure/autorest.testserver/blob/main/swagger/dpg-initial.json#L19-L24 
- In CADL version, response has no body:
https://github.com/Azure/cadl-ranch/blob/c4f41f483eac812527f7b6dc837bd22d255a18ed/packages/cadl-ranch-specs/http/resiliency/srv-driven-1/main.cadl#L29-L39

As a result, emitter doesn't generate any body type (which is correct in this case):
```
"Responses": [
 {
  "$id": "24",
  "StatusCodes": [
   200
  ],
  "BodyMediaType": "Json"
 }
],
```
