### ISSUE TITLE
Support Multiple content types defined in CADL files: protocol methods

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2597]
CADL already supports multple content types, 

 @Cadl.Rest.produces("application/json", "image/png")

We need to make sure the generated SDK should have the same behavoir with DPG 1.0

This is the requirement for August MVP, see https://github.com/Azure/autorest.csharp/issues/2578

**Comment by pshao25** [comment]
@annelo-msft I saw this [issue](https://github.com/microsoft/cadl/issues/665) is closed and this [one](https://github.com/microsoft/cadl/issues/756) is open (but this one is in the September milestone). Seems this one is the correct ayntax how to set content type at operation level?

**Comment by annelo-msft** [comment]
The test case for this is the [resiliency/srv-driven-2](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/resiliency/srv-driven-2/main.cadl#L100-L115) test case @lmazuel provided.  We should generate what we did in DPG 1.0: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjectsLowLevel/dpg-update1/Generated/ParamsClient.cs#L376

If for some reason the Cadl doesn't give us the information we need to generate this, we should communicate this and update the cadl-ranch test case.

**Comment by annelo-msft** [comment]
@AlexanderSher, are these duplicates? https://github.com/Azure/autorest.csharp/issues/2553

**Comment by AlexanderSher** [comment]
No, this issue is for protocol methods. #2553 is for convenience methods.

**Comment by annelo-msft** [comment]
Ah, if it's for protocol methods, then it is in the August MVP milestone.

**Comment by pshao25** [comment]
@annelo-msft still, there is no place we could know whwther an operation is multi content type, because cadl haven't suppport it yet.
