### ISSUE TITLE
Enable generation of client libraries from Cadl in the azure-sdk-for-net repo

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2600]
### Problem statement
Today, we do not have an automated way to run DPG2.0 to generate client library source from Cadl in the azure-sdk-for-net repo.  This means we cannot release a library from Cadl using our release pipelines.

For DPG2.0b2, we will need to do this, as the requirement for that milestone is that we can generate a preview library from a Cadl definition.

We should follow the same principle we currently follow, where only one version of the generator can generate all libraries in the azure-sdk-for-net repo without special casing.  If there are any dependency issues that need to be resolved, or commitments we need to get from the Cadl team around breaking changes, those should be tracked and resolved as part of this issue.

### Success Criteria
- Running `dotnet msbuild /t:GenerateCode` generates a library in the azure-sdk-for-net repo from a Cadl API description
- All libraries in the azure-sdk-for-net repo (data plane swagger/data plane Cadl/management plane) can be generated from the latest version of the generator

**Comment by annelo-msft** [comment]
@lirenhe, FYI

**Comment by chunyu3** [comment]
duplicate https://github.com/Azure/autorest.csharp/issues/2585
