### ISSUE TITLE
Support additional auth types from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2601]
For DPG2.0b1, we will support the same authentication feature set as we did in DPG1.0, as tracked by https://github.com/Azure/autorest.csharp/issues/2577

Work remains to generate clients that use [additional types of auth](https://github.com/microsoft/cadl/blob/main/packages/rest/lib/auth.cadl#L86) that can be expressed in Cadl.

Per @AlexanderSher:
how much of these we need to support?https://github.com/microsoft/cadl/blob/b44b8d414e8e940c2eb7a9d92fa40857b3eba3f5/packages/rest/docs/authentication.md

Specifically:
- Do we need to support tuples?
- Which of the models are we going to support? https://github.com/microsoft/cadl/blob/main/packages/rest/lib/auth.cadl
- How are we going to map authentication models into existing Azure.Identity objects?

https://github.com/Azure/autorest.csharp/issues/2590 is a related issue.

**Comment by lirenhe** [comment]
Close it as duplicate
