### ISSUE TITLE
Generate comments for models API from @doc in CADL

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2603]
- [ ] Generate comments for models and convinience API from `@doc` in CADL
- [x] If `@doc` is not specified for model and properties, generate a warning. (done by cadl in https://github.com/Azure/cadl-azure/issues/1748)

Sample input & output

- [Cadl testserver models/roundtrip-basic](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/roundtrip-basic)

- [RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-models-roundtrip-basic/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)

**Comment by lirenhe** [comment]
Need to confirm whether the warning could be the output of CADL compiler/linter directly.

**Comment by archerzz** [comment]
> Need to confirm whether the warning could be the output of CADL compiler/linter directly.

CADL will enforce the check on the compiler. See: https://github.com/Azure/cadl-azure/issues/1748
