### ISSUE TITLE
Obtain namespaces from Cadl file instead of generator configuration

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2606]
Once Cadl provides an approach to specifying client namespaces, we will need to consume this in the generator.

The Cadl dependency is being tracked by: https://github.com/Azure/cadl-azure/issues/1903

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/2755

**Comment by lirenhe** [comment]
Close it as duplicate
