### ISSUE TITLE
Generate long-running operations service methods from Cadl API description

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2608]
The DPG 2.0 generator should generate the same API and implementation from Cadl as it did for DPG 1.0 from swagger.

Cadl LRO support was provided in https://github.com/Azure/cadl-azure/issues/664

**Comment by chunyu3** [comment]
duplicate https://github.com/Azure/autorest.csharp/issues/2698

**Comment by lirenhe** [comment]
close it as duplicate
