### ISSUE TITLE
Design multi-version client generation from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2609]
We will need to generate clients that are version aware to support version-tolerant models.

This includes:
- Support for generating ServiceVersion enum from versions specified in Cadl
- Support for using the ServiceVersion value set in ClientOptions to create requests
- Support for throwing NotSupportedException from service methods added after the client's target version
- Documentation comments include "Added in \<service-version\>" for operations and parameters
- Generator fails if operations don't support `api-version` parameter

Related to: https://github.com/Azure/autorest.csharp/issues/2362

**Comment by lirenhe** [comment]
Close it as duplicate.  Let's use https://github.com/Azure/autorest.csharp/issues/2362 to track the progress of this effort.
