### ISSUE TITLE
Provide design for convenience methods for operations that support multiple content types

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2619]
In HLC, for every content type, there is a pair of methods (sync and async) in the client, corresponding pair in the rest client, and a create request method. Example from test server - [AnalyzeBody operation](https://github.com/Azure/autorest.testserver/blob/main/swagger/media_types.json#L14):
- `application/json`:
  - [`Task<Response<string>> AnalyzeBodyAsync(SourcePath input = null, CancellationToken cancellationToken = default)`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/media_types/Generated/MediaTypesRestClient.cs#L125)
  - [`Response<string> AnalyzeBody(SourcePath input = null, CancellationToken cancellationToken = default)`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/media_types/Generated/MediaTypesRestClient.cs#L146)
  - [`HttpMessage CreateAnalyzeBodyRequest(SourcePath input)`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/media_types/Generated/MediaTypesRestClient.cs#L102) 
- other types:
  - [`Task<Response<string>> AnalyzeBodyAsync(Models.ContentType contentType, Stream input = null, CancellationToken cancellationToken = default)`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/media_types/Generated/MediaTypesRestClient.cs#L62)
  - [`Response<string> AnalyzeBody(Models.ContentType contentType, Stream input = null, CancellationToken cancellationToken = default)`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/media_types/Generated/MediaTypesRestClient.cs#L84)
  - [`CreateAnalyzeBodyRequest(Models.ContentType contentType, Stream input)`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/media_types/Generated/MediaTypesRestClient.cs#L40) 

Generation of `RequestContent` is part of `CreateXxxRequest` method, e.g.::
- In `HttpMessage CreateAnalyzeBodyRequest(SourcePath input)`:

  ```cs
  if (input != null)
  {
      request.Headers.Add("Content-Type", "application/json");
      var content = new Utf8JsonRequestContent();
      content.JsonWriter.WriteObjectValue(input);
      request.Content = content;
  }
  ```
- In `HttpMessage CreateAnalyzeBodyRequest(Models.ContentType contentType, Stream input)`:

  ```cs
  if (input != null)
  {
      request.Headers.Add("Content-Type", contentType.ToSerialString());
      request.Content = RequestContent.Create(input);
  }
  ```

In DPG, there is only one protocol method that handles all the cases. We need to specify how convenience methods will handle different content types, what and how many convenience methods will be generated for every operation.
- for all types:
[public virtual async Task<Response> AnalyzeBodyAsync(RequestContent content, ContentType contentType, RequestContext context = null)](https://github.com/Azure/autorest.csharp/blob/bd9e5e7ab713f028076c12e54751364957eea45f/test/TestServerProjectsLowLevel/media_types/Generated/MediaTypesClient.cs#L80)
- CreateXxxRequest
[internal HttpMessage CreateAnalyzeBodyRequest(RequestContent content, ContentType contentType, RequestContext context)](https://github.com/Azure/autorest.csharp/blob/bd9e5e7ab713f028076c12e54751364957eea45f/test/TestServerProjectsLowLevel/media_types/Generated/MediaTypesClient.cs#L504)
See also: https://github.com/Azure/autorest.csharp/issues/2553

**Comment by chunyu3** [comment]
Convenience method:
- `application/json`
```
public async Task<Response<string>> AnalyzeBodyAsync(SourcePath input = null, CancellationToken cancellationToken = public async Task<Response<string>> AnalyzeBodyAsync(SourcePath input = null, CancellationToken cancellationToken = default)
{
    RequestContext context = FromCancellationToken(cancellationToken);
    Response response = AnalyzeBodyAsync(input.ToRequestContent(), context);
    return response;
}

```

- other types
```
public async Task<Response<string>> AnalyzeBodyAsync(Stream input = null, CancellationToken cancellationToken = default)
{
    RequestContext context = FromCancellationToken(cancellationToken);
    Response response = AnalyzeBodyAsync(RequestContent.Create(input), context);
    return response;
}
```

CreateXxxRequest:
[internal HttpMessage CreateAnalyzeBodyRequest(RequestContent content, ContentType contentType, RequestContext context)](https://github.com/Azure/autorest.csharp/blob/bd9e5e7ab713f028076c12e54751364957eea45f/test/TestServerProjectsLowLevel/media_types/Generated/MediaTypesClient.cs#L504)

**Comment by chunyu3** [comment]
@AlexanderSher has discussed this in arch-board meeting, and decide that for application/json type, convenience method will use the `model` as input parameter, other content-types, it will use  `Stream` as input parameter. But the `Stream` should be seekable, codegen will generate validate for it , if user pass a non-seekable stream, throw exception.

**Comment by lirenhe** [comment]
Close it as duplicate.
