### ISSUE TITLE
Handle the same property name with model name

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2626]
We could define cadl as 
```
model Message {
  message: string;
}
```
We will generate as 
```C#
public partial class Message
{
    public string Message { get; set; }
}
```
This leads to error

> error CS0542: 'Message': member names cannot be the same as their enclosing type

See details here: https://github.com/Azure/cadl-ranch/pull/49#issuecomment-1216050629

**Comment by pshao25** [comment]
@KrzysztofCwalina @tg-msft Python will append a "Property" to the property name. How about we generate this case as 
```C#
public partial class Message
{
    public string MessageProperty { get; set; }
}
```
and if there already have a `MessageProperty` like
```
model Message {
  message: string;
  messageProperty: string;
}
```
we could generate as 
```C#
public partial class Message
{
    public string MessagePropertyAutoGenerated { get; set; }
    public string MessageProperty { get; set; }
}
```

Another solution is: we don't do anything, let users do the customization.

What do you think?

**Comment by pshao25** [comment]
@m-nash Would you take a look at the desgin above?

**Comment by chunyu3** [comment]
.Net does not support this. Will add lint-rule to prevent to define a property with the same name as model.

**Comment by chunyu3** [comment]
Filed an issue https://github.com/microsoft/cadl/issues/1234 to cadl-lint

**Comment by pshao25** [comment]
Since there would be a linter to avoid such case, close this one.
