### ISSUE TITLE
unable to generate top level generation1-convenience-client

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#2638]
In this [internal pull request](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/6644729), I'm attempting to upgrade to "Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20220822.2". The configuration used to be `azure-arm: true`, but now I'm producing almost the same thing with:
```
generation1-convenience-client: true
public-clients: true
```

The top level `AvsManagementClient.cs` is gone and I don't know why. How do I get it to generate the top level convenience client? Or why was it removed?

**Comment by cataggar** [comment]
I tried switching to the version from https://github.com/Azure/azure-sdk-for-net/blob/main/eng/Directory.Build.Common.props#L8 , but it did not help.

``` xml
<PackageReference Include="Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20210504.1" PrivateAssets="All" />
```

**Comment by cataggar** [comment]
For my info, https://github.com/Azure/azure-sdk-for-net/pull/30583 now has a track2 client for AVS from 5 days ago.

**Comment by AlexanderSher** [comment]
Hi @cataggar , why have you removed `azure-arm: true`?

**Comment by cataggar** [comment]
@AlexanderSher, 

If I add it back, I get:

>   Exception: Enabling both 'generation1-convenience-client' and 'azure-arm' at the same time is not supported.
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ValidateConfiguration() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSha 
  rpGen.cs:line 72
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\P 
  lugins\CSharpGen.cs:line 24
     at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRe 
  st\Plugins\CSharpGen.cs:line 97
  fatal   | Process() cancelled due to failure

If I remove `generation1-convenience-client`, I get:

>   fatal   | Internal error in AutoRest.CSharp
     Please file an issue at https://github.com/Azure/autorest.csharp/issues/new. 
     Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.

> Exception: The blobDuration property of LogSpecification ends with "Duration" but does not use the duration format to be generated as TimeSpan type. Add "format": "duration" with directive in autorest.md for the property if it's ISO 8601 format like P1DT2H59M59S. Add "x-ms-format": "duration-constant" if it's the constant format like 1.2:59:59.5000000. If the property does not conform to a TimeSpan format, please use "x-ms-client-name" to rename the property for the client.

**Comment by AlexanderSher** [comment]
> Exception: The blobDuration property of LogSpecification ends with "Duration" but does not use the duration format to be generated as TimeSpan type. Add "format": "duration" with directive in autorest.md for the property if it's ISO 8601 format like P1DT2H59M59S. Add "x-ms-format": "duration-constant" if it's the constant format like 1.2:59:59.5000000. If the property does not conform to a TimeSpan format, please use "x-ms-client-name" to rename the property for the client.

This is the issue you need to address in your input. Here is the property in question: https://github.com/Azure/azure-rest-api-specs-pr/blob/AVS/2022-05/specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json#L5365

**Comment by cataggar** [comment]
Even with that removed, `azure-arm` is creating completely different code than before. I'd like to stay focused on `generation1-convience-client` for this issue. Any idea why a top level client is no longer generated?

**Comment by AlexanderSher** [comment]
You have swagger input for resource manager, so correct setting is `azure-arm: true`
@m-nash , @Yao725 , @ArcturusZhang  - can you please take a look?

**Comment by Yao725** [comment]
Hi @cataggar, you should not use the flag `generation1-convenience-client`, this is for data plane generation. If you want to have the top-level client, you should use this [script](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/avs/Microsoft.Azure.Management.Avs/src/generate.ps1) to generate the track 1 code management plane library. Azure.ResourceManager.Avs belongs to the track 2 management plane library and it will only have one client named ArmClient, which is defined in our core library Azure.ResourceManager.
