### ISSUE TITLE
No headers in request method

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2643]
**Symptom:**
In request method, there is no header set:
https://github.com/pshao25/autorest.csharp/blob/4dc1fd395672d24b5f3f5219d8ef1b5456a65a75/test/CadlRanchProjects/dev-driven/Generated/TestserverClient.cs#L494-L507
Post content cannot be successfully sent. (at least cadl ranch cannot get this value.)

**Expected:**
https://github.com/pshao25/autorest.csharp/blob/4dc1fd395672d24b5f3f5219d8ef1b5456a65a75/test/TestServerProjectsLowLevel/dpg-customization/Generated/DPGClient.cs#L518-L531

We should have header as
https://github.com/pshao25/autorest.csharp/blob/4dc1fd395672d24b5f3f5219d8ef1b5456a65a75/test/TestServerProjectsLowLevel/dpg-customization/Generated/DPGClient.cs#L528-L529

**Root cause:**
We should have clientMethod.Request.Headers to write headers.
https://github.com/pshao25/autorest.csharp/blob/4dc1fd395672d24b5f3f5219d8ef1b5456a65a75/src/AutoRest.CSharp/Common/Generation/Writers/RequestWriterHelpers.cs#L221

We build header parameters by `InputParameter.Location`. However, there are two parts don't have it.

- Output of emitter don't have it
- We initialize InputParameter hard coded as `RequestLocation.None`
https://github.com/pshao25/autorest.csharp/blob/4dc1fd395672d24b5f3f5219d8ef1b5456a65a75/src/AutoRest.CSharp/Common/Input/Inputs.cs#L93

**Comment by chunyu3** [comment]
Normal head parameter defined in operation will be emit and mark the location 'head'. but the top-level head such as 'content-type' is set to each operation.

**Comment by AlexanderSher** [comment]
M4 has generated two parameters:
- contentType: https://github.com/Azure/autorest.csharp/blob/b20e5ee38dce9d743b5c3390118433e2499ff4c1/test/TestServerProjectsLowLevel/dpg-customization/Generated/CodeModel.yaml#L343-L355
- accept: https://github.com/Azure/autorest.csharp/blob/b20e5ee38dce9d743b5c3390118433e2499ff4c1/test/TestServerProjectsLowLevel/dpg-customization/Generated/CodeModel.yaml#L368-L380

Both have types declared as constants.

**Comment by AlexanderSher** [comment]
autorest.python just generates these parameters manually: 
https://github.com/Azure/autorest.python/blob/autorestv3/packages/cadl-python/src/emitter.ts#L262-L303
https://github.com/Azure/autorest.python/pull/1387/files
