### ISSUE TITLE
Support Customization with CADL input in DPG

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2650]
Need to verify whether CADL+DPG could still support the customization on models:
Detailed description could be found in https://github.com/Azure/autorest.csharp#customizing-the-generated-code

**Pre-generation customizations:**
- [ ] Make a model internal (only model itself becomes internal - all usages of the models must be updated manually)
- [ ] Rename a model class
- [ ] Change a model or client namespace
- [ ] Make model property internal
- [ ] Rename a model property
- [ ] Change a model property type
- [ ] Preserve raw Json value of a property
- [ ] Convert property to field
- [ ] Renaming an enum
- [ ] Renaming an enum member
- [ ] Changing an enum to an extensible enum
- [ ] Make a client internal
- [ ] Rename a client

**Post-generation customizations:**
- [ ] Replace any generated member
- [ ] Customize serialization/deserialization methods (replaces any )
- [ ] Changing member doc comment (doc comment is changed with generated member)
- [ ] Remove any generated member
- [ ] Remove any type
- [ ] Extending a model with additional constructors (simply means that models are generated as partial classes)

**Configuration settings (not really a customization):**
- [ ] Exclude models from namespace

**Swagger-specific customizations (out-of-scope)**
- Change model namespace or accessibility in bulk
- Change operation accessibility in bulk

With model generation , we should decide what kinds of customization we should support in CADL+DPG and verify/implement it.

cc @AlexanderSher  @annelo-msft

**Comment by annelo-msft** [comment]
@lirenhe, let's first find out why we need to support these with the new process in place, and whether we should support them as C# partial class transforms or in a convenience layer description in Cadl.

@KrzysztofCwalina, @tg-msft FYI

**Comment by AlexanderSher** [comment]
Bulk changes are done via swagger-specific transformations, so they are out of scope of this task.

**Comment by AlexanderSher** [comment]
> @lirenhe, let's first find out why we need to support these with the new process in place

We need this to resolve issue described in https://github.com/Azure/cadl-ranch/pull/49 (at least property renaming item).

**Comment by AlexanderSher** [comment]
`Changing member doc comment` is not a separate customization - it comes in a batch with replacing of generated property

**Comment by annelo-msft** [comment]
> We need this to resolve issue described in https://github.com/Azure/cadl-ranch/pull/49 (at least property renaming item).

That test case is intended to cover the DPG 1.0 parity requirement, we should not require a full customization layer to address that requirement.
