### ISSUE TITLE
Can't add bearer authentication token

### ISSUE THREAD

**Issue by BrunoASP2001** [Azure/autorest.csharp#2661]
**Describe the issue or request**
Hi everyone!
I have already posted part of this issue on AutoRest's main github (you can see the post for more information here https://github.com/Azure/autorest/issues/4624), after some discussing there, they suggested that I asked the new issue here.
So, I want to use the class library that AutoRest generated from LiveTiles's Reach API, problem is that I need to be authenticated in order to use the endpoints, for this, LiveTiles gave me a JWT Token which I use to authenticate myself, but I can't find anywhere on the generated code on how to insert this token.
I have searched other examples that use flags like --add-credentials or --azure-arm (like this one for example https://github.com/affinda/affinda-dotnet), in which cases it creates properties to add credentials, but when I use them in my API, it doesn't create anything for that, it does the same as if those flags weren't used.
____________________________________________________________________________________________________________________________________
_(Meanwhile, while exploring the generated ReachAPIClient, I found a way to authenticate myself, by doing the following:
![image](https://user-images.githubusercontent.com/104068064/187479414-cd19a80b-f679-42fc-b367-5408acad354b.png)
This works exactly as I wanted, problem is that I need to add this manually to all endpoints (which are a lot), is there a way to do this automatically?)_ **(Ignore this part, I found out that it doesn't do anything, I was testing in an endpoint that doesn't need authentication, my bad)**
____________________________________________________________________________________________________________________________________

As given in the other post, this might be usefull:
LiveTiles's Reach API: https://api.condense.ch/swagger/index.html?__hstc=96799296.1fd31d1f6864b24263374fad6ff35cf3.1608636891257.1608636891257.1608640595673.2&__hssc=96799296.1.1608640595673&__hsfp=528994668
LiveTile's Reach API (downloadable):
[reachapi.zip](https://github.com/Azure/autorest.csharp/files/9454280/reachapi.zip)
Yamls used to fix some errors:
[readme-reach.md](https://github.com/Azure/autorest.csharp/files/9454282/readme-reach.md)
AutoRest Output:
[AutoRest Output.txt](https://github.com/Azure/autorest.csharp/files/9454295/AutoRest.Output.txt)

**Comment by AlexanderSher** [comment]
Hi @BrunoASP2001 , please remove `azure-arm` from readme-reach.md and add `security` section to your input:
![image](https://user-images.githubusercontent.com/8933858/187838087-a27b7566-d755-422b-89c1-a0a55da0271c.png)
