### ISSUE TITLE
Provide the design spec of high level architecture for CADL+DPG

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2665]
Most of the design issues of CADL+DPG are solved now and I believe the overall architecture design for dotnet is quite stable now.
Please help to provide the design spec of high level architecture for CADL+DPG.
It would be useful to continue the future refactoring of our codebase including mgmt. SDK.

**Comment by AlexanderSher** [comment]
Resolved in https://github.com/Azure/autorest.csharp/pull/2695
