### ISSUE TITLE
Support JSON payload that are not object or array in convenience method

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2671]
This is what we generated for https://github.com/Azure/cadl-ranch/blob/7435655e82b732b3573379f76e0e613423d244e9/packages/cadl-ranch-specs/http/hello/main.cadl#L19
```
public virtual async Task<Response<string>> WorldValueAsync(CancellationToken cancellationToken = default)
{
    using var scope = ClientDiagnostics.CreateScope("HelloClient.WorldValue");
    scope.Start();
    try
    {
        RequestContext context = FromCancellationToken(cancellationToken);
        Response response = await WorldAsync(context).ConfigureAwait(false);
        return Response.FromValue(string.FromResponse(response), response);
    }
    catch (Exception e)
    {
        scope.Failed(e);
        throw;
    }
}
```
Pay attention to `string.FromResponse(response)`, which cannot pass compilation.

We should design how we could parse from a `Response` to a framework type (int, string, array, etc).

Here is an example how HLC does: https://github.com/Azure/autorest.csharp/blob/38b656da2df4cdd7f603a8943a59706ab337cc64/test/TestServerProjects/body-number/Generated/NumberRestClient.cs#L57-L75

**Comment by lirenhe** [comment]
Based on the discussion, this may not be a real scenario. Put this into the backlog.

**Comment by chunyu3** [comment]
Current DPG will generate as following, the issue should be resolved.

```
public virtual async Task<Response<string>> WorldValueAsync(CancellationToken cancellationToken = default)
{
    using var scope = ClientDiagnostics.CreateScope("HelloClient.WorldValue");
    scope.Start();
    try
    {
        RequestContext context = FromCancellationToken(cancellationToken);
        Response response = await WorldAsync(context).ConfigureAwait(false);
        return Response.FromValue(response.Content.ToObjectFromJson<string>(), response);
    }
    catch (Exception e)
    {
        scope.Failed(e);
        throw;
    }
}
```

**Comment by chunyu3** [comment]
close this because it has been resolved.
