### ISSUE TITLE
Support for operation-location/resourceLocation polling

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#2672]
One of the LRO pattern used by service teams, is:
- Returns a 202 with a Operation-Location header
- This payload contains a "status" key with current progress
- Once "status" reached a final state, if the state is success, do a finalGet on `resourceLocation` if present

This is an example of final payload:
```json
{
	"operationId": "3e971df5-e55c-4d5f-acd4-a64a7093d29a",
	"status": "Succeeded",
	"update": {
		"updateId": {
			"provider": "fabrikam",
			"name": "vacuum",
			"version": "2022.901.442.40"
		},
		"description": "My update description"
	},
	"resourceLocation": "/deviceUpdate/sdkinstance/updates/providers/fabrikam/names/vacuum/versions/2022.901.442.40?api-version=2022-10-01",
	"traceId": "3897b477d98d2b41947873f6366b4938",
	"lastActionDateTime": "2022-09-02T00:34:00.049925Z",
	"createdDateTime": "2022-09-02T00:33:01.8230331Z",
	"etag": "e85ccce2 - 1 a46 - 4198 - b798 - 35 b6f1598fe2"
}
```

This is already supported in Java, Python and TS. I'm happy to provide additional guidance if there are questions.

**Comment by lirenhe** [comment]
@lmazuel, I am looking at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#202-accepted-and-location-headers, the doc is not clear about:

5.If the operation is complete, return the exact same response that would have been returned had the operation been executed synchronously.

Will the payload be returned together with the call of 'status = succeed' or when we see 202 with 'status = succeed', we should do another call to get the payload?

**Comment by lmazuel** [comment]
@lirenhe this has been confirmed unsopported by DeviceUpdate.

A status monitor always returns a 200, the status check is finished when the `status` key move to a success string. When it does, if `resourceLocation` exists, a final GET must be done on it.

**Comment by lirenhe** [comment]
@AlexanderSher, could you take a look?

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/2726
@AlexanderSher  will create an PR to resolve this.
