### ISSUE TITLE
Support array payload in convenience method

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2673]
Returning an array (of string is the most always case) exists on real life, but we haven't support is now.

Cadl:
```
op world(): string[];
```

What we generate now is:
```
public virtual async Task<Response<IList<string>>> WorldValueAsync(CancellationToken cancellationToken = default)
{
    using var scope = ClientDiagnostics.CreateScope("HelloClient.WorldValue");
    scope.Start();
    try
    {
        RequestContext context = FromCancellationToken(cancellationToken);
        Response response = await WorldAsync(context).ConfigureAwait(false);
        return Response.FromValue(IList<string>.FromResponse(response), response);
    }
    catch (Exception e)
    {
        scope.Failed(e);
        throw;
    }
}

```
Pay attention to `IList<string>.FromResponse(response)` which is invalid.

Epic: https://github.com/Azure/cadl-azure/issues/1943

**Comment by pshao25** [comment]
We could change it to
```C#
public virtual async Task<Response<IReadOnlyList<string>>> WorldValueAsync(CancellationToken cancellationToken = default)
{
    using var scope = ClientDiagnostics.CreateScope("HelloClient.WorldValue");
    scope.Start();
    try
    {
        RequestContext context = FromCancellationToken(cancellationToken);
        Response response = await WorldAsync(context).ConfigureAwait(false);

        var document = JsonDocument.Parse(response.Content, default);
        List<string> array = new List<string>();
        foreach (var item in document.RootElement.EnumerateArray())
        {
            array.Add(item.GetString());
        }

        IReadOnlyList<string> value = array;
        return Response.FromValue(value, response);
    }
    catch (Exception e)
    {
        scope.Failed(e);
        throw;
    }
}
```

**Comment by lirenhe** [comment]
@pshao25, could you take a look?  thanks

**Comment by pshao25** [comment]
@KrzysztofCwalina @tg-msft Could you review the design above is OK for you? It is almost the same as HLC.

**Comment by pshao25** [comment]
@m-nash Would you take a look at this design?

**Comment by lirenhe** [comment]
@pshao25, Python is also working on this so you may check with them as well.
We also need support the return type is the array of models.

**Comment by pshao25** [comment]
We do have many real services who takes array as response/input, both in HLC and management plane, here is an example in HLC which has array input and output:
https://github.com/Azure/azure-sdk-for-net/blob/84ec01fbfe07cefd19b0a1501a98d80dbe53b8bb/sdk/digitaltwins/Azure.DigitalTwins.Core/src/Generated/DigitalTwinModelsRestClient.cs#L81

**Comment by chunyu3** [comment]
@m-nash will discuss with Arch board if we will wrap the method to pageable method if the response is an array.

**Comment by chunyu3** [comment]
@m-nash has confirmed with Laurent and Krzysztof that we need to support array payload directly:

- There is a cadl lint rule to prevent a raw array be an input body: https://github.com/Azure/cadl-azure/issues/2194
- When response is an array payload, we will wrap it to pageable

**Comment by pshao25** [comment]
Decision: we will have a flag for raw array (e.g. int32[]) which is by default off
**1. When off, we generate:**
Convenience
Public Response<IReadOnlyList<int>> X(…)
Protocol
Public Response X(…)

**2. When on, we generate:**
Convenience
public Pageable<int> X(...)
Protocol
public Pageable<BinaryData> X(...)

**Comment by pshao25** [comment]
Question: how to do the deserialization for `IReadOnlyList<int>`

Solution 1: deserialize in the convenience body. https://github.com/Azure/autorest.csharp/issues/2673#issuecomment-1236238345

Solution 2: we create a helper file in Generator.Shared
```C#
public virtual async IReadOnlyList<int> DeserializeIntCollection(Response response)
{
      using var document = await JsonDocument.ParseAsync(response.ContentStream, default, cancellationToken).ConfigureAwait(false);
      List<string> array = new List<string>();
      foreach (var item in document.RootElement.EnumerateArray())
      {
          array.Add(item.GetString());
      }
      return array;
}
```
Similar to string/boolean/.../

**Comment by pshao25** [comment]
Perf on Solution1 & Solution2:
10 items of int:
|            Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|------------------ |---------:|---------:|---------:|-------:|----------:|
| CallGenericMethod | 974.5 ns | 12.60 ns | 11.78 ns | 0.0038 |     624 B |
|        CallInline | 882.7 ns |  8.13 ns |  7.20 ns | 0.0038 |     584 B |

10 items of string:
|            Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------ |---------:|----------:|----------:|-------:|----------:|
| CallGenericMethod | 1.319 us | 0.0245 us | 0.0241 us | 0.0057 |   1,000 B |
|        CallInline | 1.170 us | 0.0182 us | 0.0161 us | 0.0057 |     960 B |

Reference code:
```C#
[Benchmark]
public void CallGenericMethod()
{
    var mockResponse = new MockResponse(200);
    mockResponse.SetContent(_arrayData);

    var result = DeserializationHelpers.DeserializeCollection<int>(mockResponse, item => item.GetInt32());

    foreach (var item in result)
    {
        _ = item;
    }
}

[Benchmark]
public void CallInline()
{
    var mockResponse = new MockResponse(200);
    mockResponse.SetContent(_arrayData);

    if (mockResponse.ContentStream == null)
    {
        throw new ArgumentNullException(nameof(mockResponse.ContentStream));
    }

    using var document = JsonDocument.Parse(mockResponse.ContentStream);

    List<int> array = new List<int>();
    foreach (var item in document.RootElement.EnumerateArray())
    {
        array.Add(item.GetInt32());
    }

    foreach (var item in array)
    {
        _ = item;
    }
}

private readonly string _arrayData = "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]";
```

**Comment by m-nash** [comment]
Given inline is faster and less alloc and its autogenerated code so we aren't hand writing the duplicate I think we should go with inline.
