### ISSUE TITLE
apiVersion parameter: apiVersion should be an client parameter and set into HTTP request as query parameter

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2679]
1. apiVersion should be defined as client parameter, and there will be an _apiView field of client:
```
private readonly string _apiVersion;
```

and will be initialized in client constructor: e.g.
![constructor](https://user-images.githubusercontent.com/10458143/188526948-e0e807e6-96a7-422d-b09e-2b6297cbf6d9.png)

2. in each Create***Request method, the HTTP request message will set 'api-version' as query parameter. e.g.
![httprequest](https://user-images.githubusercontent.com/10458143/188526969-ed7e06a1-8301-4dca-8874-5b177f2a8771.png)

**Comment by lirenhe** [comment]
@chunyu3,  could you sumerize what is the current behaviour for the CADL input and what is the expected SDK?

**Comment by chunyu3** [comment]
Scenarios:

1. the client library only has one apiVersion, all the operation has the same api-version
Set _apiVersion Field of client
add api-version head into Http request in Create***Request and will use _apiVersion, as following
```c#
uri.AppendQuery("api-version", _apiVersion, true);
```
2.  the client library has multiple apiVersion, the operations may have different api version
only add api-version head into HTTP request in Create***Request, and use the api version value. as following:
```c#
uri.AppendQuery("api-version", "2019-11-01-preview", true);
```
