### ISSUE TITLE
[emitter]Support 'is' keyword

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2682]
Sometimes you want to copy all aspects of a type without creating a nominal inheritance relationship. The `is` keyword can be used for this purpose. It is like spread, but also copies [decorators](https://github.com/microsoft/cadl/blob/0a528079a54ab74de2614cbdd59eb4a907d58e05/docs/tutorial.md#Decorators) in addition to properties. One common use case is to give a better name to a [template](https://github.com/microsoft/cadl/blob/0a528079a54ab74de2614cbdd59eb4a907d58e05/docs/tutorial.md#Templates) instantiation:

- [x]  the target type is primitive type, e.g string

model TransactionId is string;

- [ ] the target type is complex type

**Comment by lirenhe** [comment]
I would like to see the design signoff for 'the target type is complex type'    @chunyu3

**Comment by chunyu3** [comment]
It is not expected behavior to define two models with the same schema. If it is for naming, use re-naming mechanism. @chunyu3  will confirm the behavior of cadl compiler if two different models schemas will return, if so, need to talk with cadl team about if it is correct or not.

**Comment by chunyu3** [comment]
cadl compile will emit two models with the same schema.
