### ISSUE TITLE
Multiple cadl templates with different real types leads to model conflict

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2683]
We need to use cadl templates in `@azure-tools/cadl-azure-core` when we write CADL. Say we have this two operations:
```
interface Jobs {
  @doc("Gets the status of an existing deployment job.")
  getDeploymentStatus is ResourceRead<DeploymentJob>;
}
interface Projects {
  @doc("Gets the details of a project.")
  get is ResourceRead<Project>;
}
```
We could see that both of them use `ResourceRead`. The definition of `ResourceRead` is:
```
@autoRoute
@doc("Get a {name}", TResource)
@readsResource(TResource)
op ResourceRead<TResource, TCustom extends Foundations.CustomizationFields = {}>(
  ...Foundations.ItemKeysOf<TResource>,
  ...Foundations.CustomParameters<TCustom>,
  ...Foundations.ApiVersionParameter
): Foundations.ResourceOkResponse<TResource &
  Foundations.CustomResponseFields<TCustom>> | Foundations.ErrorResponse;

model ResourceOkResponse<T> is Cadl.Http.Response<200> {
  ...T;
}
```
So current we will generate a model called `ResourceOkResponse` by expanding the properties of real types. But we have two types now: `DeploymentJob` and `Project`. Both of them we need to keep.

Same situation when we use other templates.

Solutions:
1. We don't generate `ResourceOkResponse`, instead, we generate real types.
2. We put the different `ResourceOkResponse`s into different namespaces according to the interface names.

**Comment by lirenhe** [comment]
@pshao25, so the ask is about the mutliple names for the model template.  Instead of using different models, can we also generate it as a template class?

cc @annelo-msft

**Comment by pshao25** [comment]
> @pshao25, so the ask is about the mutliple names for the model template. Instead of using different models, can we also generate it as a template class?
> 
> cc @annelo-msft

If we generate it as a template class, the return type of a convenience method would be as long as Task<Response<ResourceOkResponse<DeploymentJob >>>. It would be even longer if it is an LRO.

**Comment by lirenhe** [comment]
In TS, the model name and the template model name are combined to decide the name.
https://github.com/Azure/autorest.typescript/blob/cadl-integration/packages/cadl-rlc-emitter/src/modelUtils.ts#L344-L365

Just FYI, it doesn't mean dotnet should do the same.

**Comment by jsquire** [comment]
This seems like an area where we should start an architect discussion.   However, I'm unable to follow we're actually discussing.   It would be helpful to see a side-by-side comparison of the CADL to each option for generated output that is under consideration.   Once there's clarity on those options, please loop in Krzysztof for discussion/decisions.

**Comment by pshao25** [comment]
@jsquire 
A more intuitive example is: when we declare our operation as `Azure.Core.ResourceList<Resource>` [here](https://github.com/Azure/autorest.csharp/blob/c5eca29aaa781cf58a06048bafbf20c7a48dbf45/test/TestProjects/Pagination-Cadl/Pagination-Cadl.cadl#L160), the compiler will return the response type named `CustomPage`, so [this](https://github.com/Azure/autorest.csharp/blob/c5eca29aaa781cf58a06048bafbf20c7a48dbf45/test/TestProjects/Pagination-Cadl/Generated/Models/CustomPage.cs) is what we generate for the return model. Pay attention to the [inner type](https://github.com/Azure/autorest.csharp/blob/c5eca29aaa781cf58a06048bafbf20c7a48dbf45/test/TestProjects/Pagination-Cadl/Generated/Models/CustomPage.cs#L38) is `LedgerEntry`. Then if we define another operation as `Azure.Core.ResourceList<Resource2>`, what should be the inner type of `CustomPage`? `Resource` or `Resource2`?

In the solution of this [PR](https://github.com/Azure/autorest.csharp/pull/2966), I concatenate the template name and its arguments name, so that the corresponding model name could be `CustomPageLedgerEntry`. If there is a resource2, we could call it `CustomPageResource2`.

This this an example for `CustomResource`, but there are others like `AcceptedResponse`, `ResourceOkResponse`, etc. They would all be concatenated by the resource name as generated in that PR.

+@m-nash @KrzysztofCwalina

**Comment by m-nash** [comment]
@pshao25 lets discuss in our sync but at minimum the concatenation should be reversed.  The more concrete descriptor should be first so `LedgerEntryCustomPage` vs `CustomPageLedgerEntry`.  Also I could see us dropping the `Custom` all together to become `LedgerEntryPage`.

@KrzysztofCwalina given recent conversations around cadl not giving us concrete names to use and the generator needing to "come up with something meaningful" let me know your thoughts here.

**Comment by pshao25** [comment]
@m-nash Yes, we could carefully design how we generate the name. The logic in this [PR](https://github.com/Azure/autorest.csharp/pull/2966) is the same as what Java is doing.

> cadl not giving us concrete names to use and the generator needing to "come up with something meaningful"

Another idea is to force cadl have friendly name. Like [this](https://github.com/Azure/cadl-azure/pull/2383).

**Comment by m-nash** [comment]
Yes, although even there they have `PagedLedgerEntry` which just reads odd to me but maybe thats just dotnet and if so we would still end up needing a way to change it.

**Comment by pshao25** [comment]
We will track all the templates at https://github.com/Azure/autorest.csharp/issues/2993
