### ISSUE TITLE
[DPG]: Determine client option class name for multiple top-level clients

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2687]
**Describe the issue or request**

Right now, we have the following logic to determine the name of a DPG client option class: https://github.com/Azure/autorest.csharp/blob/3aeed711ebbd9e254e29449d755ebb8afde52572/src/AutoRest.CSharp/LowLevel/Output/DpgOutputLibraryBuilder.cs#L102-L106

If there are multiple top-level clients, the class name is from:
1. Configuration `LibraryName`
2. namespace name if above is not available.

However, right now there is no source input for  `LibraryName` in `Configuration.json`, so the class name will always come from namespace, which sometimes is too long.
https://github.com/Azure/autorest.csharp/blob/3aeed711ebbd9e254e29449d755ebb8afde52572/test/TestProjects/PetStore-Cadl/Generated/Configuration.json#L4

**Describe your ideas for solutions**

We should define the source for `LibraryName`.

**Comment by archerzz** [comment]
For Augst MVP, we can work around by manually editing the `Configuration.json` to update the `LibraryName` property to a proper value, so that the generated client option class has a good name.

**Comment by chunyu3** [comment]
we will auto gen Configuration.json from cadl and cadl-project.yaml. Then this issue will be resolved. duplicate https://github.com/Azure/autorest.csharp/issues/2755

**Comment by lirenhe** [comment]
@archerzz, could you help to verify this problem is resolved?

**Comment by archerzz** [comment]
> @archerzz, could you help to verify this problem is resolved?

Verified. For CADL project, `LibraryName` will be first used to compose the `ClientOptions` class name. So if I try the following command:
> node node_modules/@cadl-lang/compiler/dist/core/cli.js compile --emit @azure-tools/cadl-csharp .\samples\confidentialledger\main.cadl --output-path .\samples\confidentialledger\ --option @azure-tools/cadl-csharp.library-name=Ledger

I'll get `LedgerClientOptions` class for both `ConfidentialLedgerClient` and `IdentityClient`.
