### ISSUE TITLE
LRO advanced from CADL

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#2699]
See https://github.com/Azure/autorest.csharp/issues/2698 for the basics.

As CADL gives more way to detail the precise LRO flow expected, we anticipate more complex work to flow the additional information to codegen, with possibly azure-core update in the meantime.

This issue is not about parity, since we're talking about information that Swagger didn't have a way to declare.

**Comment by archerzz** [comment]
We need more details about how LRO is defined in CADL. By now, we've found the information is scattered around in the CADL definitions, v.s. centralized in `x-ms-longrunning-options` in swagger.

- `@pollingOperation(monitorOp)`: we can specify the polling operation separately
- `@pollingLocation`: specify the entity (normally the header) to get the polling URL, this seems overlapped with `@pollingOperation` above
- `@finalLocation`: specify the URL of the final request of LRO?

**Comment by chunyu3** [comment]
Need to confirm with @lmazuel

**Comment by chunyu3** [comment]
We will use https://github.com/Azure/autorest.csharp/issues/2988 to track LRO. close this one.
