### ISSUE TITLE
Provide design for convenience methods for operations with more than one success status code

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2719]
Some operations may declare more than one successful status code: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/data-plane/Microsoft.Tables/preview/2019-02-02/table.json#L146

Right now, `Azure.Core.ResponseClassifier` handles only error codes.

**Comment by chunyu3** [comment]
@AlexanderSher has discussed this in the archboard meeting. Current m4 does not support this multiple return-type for different success status codes. Need to discuss with stewardship board if we need support this for cadl and explicit it in guideline

**Comment by chunyu3** [comment]
#1 multiple codes, same response type:  check if it is implemented or not and add test case

#2 multiple codes, multiple return types:

**Comment by lirenhe** [comment]
@mikekistler, currently CADL also supports returning multiple success status code for one operation. (Not LRO)

  @post create(...Widget): {
    @statusCode statusCode: 204;
  }|
  {
    @statusCode statusCode: 200;
    @body widget: Widget
  }| Error;

I would like to check with you whether this is a valid scenario from API design prospective.  Shall we allow service team to design API like this?

**Comment by mikekistler** [comment]
We should disallow this -- specifically we should disallow multiple success status codes if they do not all define the same schema.

I thought that we stated this in our Azure API Style Guide but checking just now I could not find it, so I will add that.

**Comment by lirenhe** [comment]
Thanks @mikekistler for update. Close this one as this is not a valid case.
