### ISSUE TITLE
Provide design for mapping between response headers and models.

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2720]
Some services define custom response headers. For example, [`ContainerRegistry_CreateManifest`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerregistry/data-plane/Azure.ContainerRegistry/stable/2021-07-01/containerregistry.json#L149)

In HLC, `ContainerRegistryRestClient.CreateManifest` method returns internal [`ResponseWithHeaders<ContainerRegistryCreateManifestHeaders>`](https://github.com/Azure/azure-sdk-for-net/blob/7cd48c766d4e71300345dee8ac8a2a2958b02a5c/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/ContainerRegistryRestClient.cs#L233), which is later used to create [public model](https://github.com/Azure/azure-sdk-for-net/blob/7cd48c766d4e71300345dee8ac8a2a2958b02a5c/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/UploadManifestResult.cs) in hand-written [public client](https://github.com/Azure/azure-sdk-for-net/blob/7cd48c766d4e71300345dee8ac8a2a2958b02a5c/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs#L150). Considering the amount of required hand-written code, we can conclude that response headers aren't really supported in HLC

To support response headers in `Model.FromResponse` generation in DPG, we need some mechanism to map headers to model properties.

**Comment by chunyu3** [comment]
rest client of sdk/tables/Azure.Data.tables is an example which is auto-generated by HLC

**Comment by chunyu3** [comment]
Need to contact cadl team about it.

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/2493
