### ISSUE TITLE
C# model generation

### ISSUE THREAD

**Issue by markm77** [Azure/autorest.csharp#2724]
Hi there,

I have been using AutoRest for C# model generation for a while now - it's part of how I create models for my open source .NET project here: https://github.com/finlabsuk/open-banking-connector .

It seems model generation has been removed: https://github.com/Azure/autorest.csharp/issues/2416

Is this a permanent decision or do you plan to re-enable model generation in the future?

It's quite a major effort to switch tools in this area so any guidance on your plans would be really helpful.

I really hope you can consider re-enabling model generation as it's a very useful part of the .NET eco-system and the alternative solutions all have their issues.

BR,
Mark

**Comment by lirenhe** [comment]
@markm77, please follow https://github.com/Azure/autorest.csharp/issues/198#issuecomment-1249312968 to workaround this problem.
We shall have a formal document to describe different behaviours and our recommendations.

**Comment by markm77** [comment]
Thanks very much @lirenhe  for the reply. I will try your workaround soon when next creating models. I look forward to your document and (hopefully) continued support for model generation which is really very useful for the community. BR, Mark
