### ISSUE TITLE
DPG LROs for `PATCH` method do not return final response from original  URI

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#2726]
Cognitive Services - Question Answering has a couple of LROs that use a `PATCH` method (management-style, apparently): https://github.com/Azure/azure-rest-api-specs/blob/8ff0e3b8dc12cd793f4f2208d76f9f3a7f51176c/specification/cognitiveservices/data-plane/Language/stable/2021-10-01/questionanswering-authoring.json#L731

The intent seems to be that a final `GET` on the same endpoint should be done when the job state from the `Operation-Location` from the original `PATCH` method completes successfully: https://github.com/Azure/azure-rest-api-specs/blob/8ff0e3b8dc12cd793f4f2208d76f9f3a7f51176c/specification/cognitiveservices/data-plane/Language/stable/2021-10-01/questionanswering-authoring.json#L681

However, this is not happening because of what @AlexanderSher and I found in _NextLinkOperationImplementation.cs_:
```C#
// Set final uri as original request's uri if one of these requirements are met:
// 1.Original request is a put method;
// 2.Original request is a management plane patch method. For data plane patch method, the final uri will be determinned by the original response header and "_finalStateVia";
// 3.Original response header contains "Location" and FinalStateVia is configured to OriginalUri.
if (_requestMethod == RequestMethod.Put || _requestMethod == RequestMethod.Patch && _startRequestUri.Scheme == "https" && _startRequestUri.Host == "management.azure.com" || _originalResponseHasLocation && _finalStateVia == OperationFinalStateVia.OriginalUri)
{
    return _startRequestUri.AbsoluteUri;
}
```

The second conditional clause would otherwise work if not for the `Host` check against "management.azure.com". This is why I call this a "management-style LRO", which we know some other services implement.

FWIW, this seems to work for Python currently and, because of the first conditional clause, does work for another `PUT` LRO in this same library.

Python logic for the final URI: https://github.com/Azure/azure-sdk-for-python/blob/1015d60ed677e5b5245d817d22beaf1721195f7b/sdk/core/azure-core/azure/core/polling/base_polling.py#L224

**Comment by heaths** [comment]
Relevant code in Python: https://github.com/Azure/azure-sdk-for-python/blob/1015d60ed677e5b5245d817d22beaf1721195f7b/sdk/core/azure-core/azure/core/polling/base_polling.py#L252-L253

**Comment by AlexanderSher** [comment]
Translating python logic into `NextLinkOperationImplementation` terms:
```cs
if (_finalStateVia == OperationFinalStateVia.Location && _lastKnownLocation != null) 
{
    return _lastKnownLocation;
}

if (_finalStateVia == OperationFinalStateVia.AzureAsyncOperation && _requestMethod == RequestMethod.Post) 
{
    return null;
}

if (response.ContentStream?.Length > 0)
{
    try
    {
        using JsonDocument document = JsonDocument.Parse(response.ContentStream);
        var root = document.RootElement;
        if (root.TryGetProperty("resourceLocation", out resourceLocation))
        {
            return resourceLocation;
        }
    }
    finally
    {
        // It is required to reset the position of the content after reading as this response may be used for deserialization.
        response.ContentStream.Position = 0;
    }
}

if (_requestMethod == RequestMethod.Put || _requestMethod == RequestMethod.Patch) 
{
    return _startRequestUri.AbsoluteUri;
}

if (_requestMethod == RequestMethod.Post && _lastKnownLocation != null) 
{
    return _lastKnownLocation;
}

return null;
```

**Comment by heaths** [comment]
FWIW, I updated my swagger transforms to change the `final-state-via` to `original-uri`:
```yaml
directive:
- where-operation: QuestionAnsweringProjects_UpdateSources
  transform: |
    $["x-ms-long-running-operation-options"] = {
        "final-state-via": "original-uri"
    };
    $["x-ms-pageable"] = {
      "nextLinkName": "nextLink",
      "itemName": "value"
    };
    $.responses["200"] = {
      description: "All the sources of a project.",
      schema: {
        "$ref": "#/definitions/QnaSources"
      }
    };
```
But even that doesn't work because the existing implementation has this check:
```c#
            if (_requestMethod == RequestMethod.Put || _requestMethod == RequestMethod.Patch && _startRequestUri.Scheme == "https" && _startRequestUri.Host == "management.azure.com" || _originalResponseHasLocation && _finalStateVia == OperationFinalStateVia.OriginalUri)
            {
                return _startRequestUri.AbsoluteUri;
            }
```
That last conditional clause has a `_originalResponseHasLocation` check which isn't true. Seems to me that removing the cloud-unfriendly check for PATCH operations against "management.azure.com" might be best. Maybe with little time to test for regressions we could opt out of that specific part of the condition.

/cc @kristapratico
