### ISSUE TITLE
bug(dpg): anonymous cadl type definition will result in parameters without name

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2733]
**Describe the issue or request**
See the [sample CADL file](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwrJIGF6dXJlLXRvb2xzL8UsxhFjb3JlIjsKCkBzZXJ2aWNlVGl0bGUoIlRleHQgYXV0aG9yxEgpCi8vQFbJWC7HY2VkKFPGN8cccykKbmFtZXNwYWNlIMREQchDOwoKZW51bSDPMCB7CiAgdjE6ICIyMDIxLTDEAyIsxBQyxhQyLTA5LTEyIiwKfQoKQENhZGwuUmVzdC5yZXNvdXJjZSgicHJvamVjdHMiKQptb2RlbCBQxhHFW0BrZXnEB3Zpc2liaWxpdHkoInJlYWQiKQogIGlkOiBzdOYAniAgZGVzY3JpcHRpb24%2FyhgKICDkANLLEn0KCmludGVyZuQA5OkA4MVuY3JlYXRl5wCAU3RhdHVzTW9uaXRvciBpcyBDdXN0b21Db3JlLlBvbGxpbmdPcGVyYcRxPMc0PsVxQEHkAZsuxSpwzyooyXIu2m7kAN3NHsR%2Fy1VMb25nUnVu5AHLUucBSEPFL1dpdGjnAaJQcm92aWRlZE5hbWXuAJ9kZWxl2FrIT0TFJMs4ICBsaXN0xxBz1zZMaXN0zTRkZXBsb3nea0Fj5QFCCiAgIOgB%2B%2BQCQSDlAZLEAXNsb3TkAMbsAe0gIH3GJccyCiAgxXFnZegApNduUmVhZOsAo30K6wLx6gHhxXzrAq5wYXJlbnTIRChU5AGh9QLNb%2BgB6OQCzyAg5gLR6QH95gHlyEc8VD7vAKVGb3VuZMY%2FLs815wEO5wMQICDJaUntAwV95QKA5QCaSHR0cC5yb3V08gCXb3Ag8QLCVOYA%2FvAAk%2B0BOPkAycc85QFR).

```
  deployProject is Azure.Core.ResourceAction<
    Project,
    {
      slotName: string;
    },
    Project
  >;
```

Anonymous type is defined as the paramter of `Azure.Core.ResourceAction` which is [defined here](https://github.com/Azure/cadl-azure/blob/f3e797d1be0ff6e12819138f6b00bb22f8cb0231/packages/cadl-azure-core/lib/operations.cadl#L160-L164) as:
```
op ResourceAction<TResource, TParams, TResponse> is Foundations.ResourceOperation<
  TResource,
  TParams,
  TResponse
>;
```

That will result in parameters without name, like below.
```json
    {
       "$id": "91",
       "Name": "",
       "NameInRequest": "",
       "Type": {
        "$ref": "40"
       },
       "Location": "Body",
       "IsRequired": true,
       "IsApiVersion": false,
       "IsResourceParameter": false,
       "IsContentType": false,
       "IsEndpoint": false,
       "SkipUrlEncoding": false,
       "Explode": false,
       "Kind": "Method"
      },
```

It refers to type of id `40` which is also defined without name.
```json

   "$id": "40",
   "Name": "",
   "Namespace": "",
   "IsNullable": false,
   "Properties": [
    {
     "$id": "41",
     "Name": "slotName",
     "SerializedName": "slotName",
     "Description": "",
     "Type": {
      "$id": "42",
      "Name": "string",
      "Kind": "String",
      "IsNullable": false
     },
     "IsRequired": true,
     "IsReadOnly": false,
     "IsDiscriminator": false
    }
   ]
  }
```

**Comment by chunyu3** [comment]
For those anonymous body parameter/model, we will provide an name `${operation.Name}Properties`.

**Comment by AlexanderSher** [comment]
This must be discussed with @KrzysztofCwalina 
Specifically, we must decide:
- Would it be a breaking change to add a name to the model
- How to resolve name conflicts if there is a parameter with said name already

**Comment by chunyu3** [comment]
@AlexanderSher  will discuss this in archboard meeting: either forbidden the anonymous type in cadl file or provide an convention to name this type.

**Comment by lirenhe** [comment]
The PR has been there for 2 weeks, do we have a conclusion on how  to handle this?  @chunyu3   @AlexanderSher

**Comment by chunyu3** [comment]
@AlexanderSher has discussed in the archboard meeting, and decide we will not allow the anonymous cadl type in Azure Cadl. A lint rule will be added in the Azure cadl to enforce every model should have a name.
