### ISSUE TITLE
Design of error response in convenience method

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2744]
Cadl:
```
@get
@route("/invalid")
op invalid(): NoContentResponse | InvalidAuth;

@error
model InvalidAuth {
  @statusCode _: 403;
  error: string;
}
```
This is an operation with no-body successful response and with-model error response. See swagger [here](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KDQp1c2luZyBDYWRsLkh0dHA7DQpAc2VydmljZVZlcnNpb24NCkBkb2MoIklsbHVzdHJhdGVzIGNsaWVudHMgZ2VuZcQSZCB3aXRoIEFwaUtleSBhdXRoZW50aWNhdGlvbi4iKQ0KQHVzZUF1dGgoxiPECzzGC0xvxydoZWFkZXIsICJ4LW1zLWFwaS1rZXkiPikNCm5hbWVzcGFjZSDEOMtaxkLlAMfmAKRDaGVjayB3aGV0aGVy5wCmIGlz7ACSZWTmAJFnZXQNCkByb3V0ZSgiL2ludmFsaWTEGm9wIMcOKCk6IE5vQ29udGVudFJlc3BvbnNlIHwgScYf5ACNxnxlcnJvcg0KbW9kZWzMHiB7DQogIEBzdGF0dXNDb2RlIF86IDQwMzvEF8U1OiBzdHJpbmc7DQp9DQo%3D). Current behavior [here](https://github.com/Azure/autorest.csharp/blob/bdc076cfe6dcfb1003416c9926c08039a5a05005/test/CadlRanchProjects/api-key/Generated/ApiKeyClient.cs).

There are three issues:
1. Generated convenience method should not return model
```C#
public virtual Response<InvalidAuth> InvalidValue(CancellationToken cancellationToken = default)
{
    using var scope = ClientDiagnostics.CreateScope("ApiKeyClient.InvalidValue");
    scope.Start();
    try
    {
        RequestContext context = FromCancellationToken(cancellationToken);
        Response response = Invalid(context);
        return Response.FromValue(InvalidAuth.FromResponse(response), response);
    }
    catch (Exception e)
    {
        scope.Failed(e);
        throw;
    }
}
```
2. ResponseClassifier should not contain 403
```C#
private static ResponseClassifier _responseClassifier204403;
private static ResponseClassifier ResponseClassifier204403 => _responseClassifier204403 ??= new StatusCodeClassifier(stackalloc ushort[] { 204, 403 });
```
3. When there is error happening, we should throw a model type error `InvalidAuth` instead of an internal error.

For 1&2, what I think it add an isError flag to OperationResponse which is the output of emitter.

**Comment by chunyu3** [comment]
.Net will ignore error model as before.

**Comment by lirenhe** [comment]
@pshao25, do we have a service that is impacted by this behaviour?

**Comment by pshao25** [comment]
> @pshao25, do we have a service that is impacted by this behaviour?

Yes. This is very common.

E.g., [anomalydetector](https://github.com/Azure/azure-rest-api-specs/blob/f47eeea0df3a5a81ea42945ed96290b3fb8e588a/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/MultivariateAnomalyDetector.json#L187-L203) has 204 response without body and a user-defined error response. 

In the last sync meeting, we decide just fix 1&2 and still throw internal error for 3.
