### ISSUE TITLE
DPG does not generate ASP.NET extension methods

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#2762]
The DPG code generator does not generate ASP.NET extension methods as we did for HLCs e.g., https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClientBuilderExtensions.cs. Seems as part of shift-left, these should be generated automatically to avoid needing to hand-code them for each and every DPG SDK.

**Comment by lirenhe** [comment]
@heaths,  could you help to provide more context on why we need to 'generate ASP.NET extension methods' as part of the DPG?  For the current services onboard to DPG, we didn't got that ask, is it specific for KeyVault?

cc @m-nash

**Comment by heaths** [comment]
All SDKs are supposed to have ASP.NET extension methods: https://azure.github.io/azure-sdk/dotnet_implementation.html#integration-with-aspnet-core. These allow customers to register clients as services for ASP.NET apps - really, any app that uses the .NET configuration builder facilities, which are more commonly used for ASP.NET but may also be used for MAUI apps, etc.

If we'll be generating DPG libraries more frequently without necessary human coding, the generators need to do this. All our other libraries have this, but @tg-msft asked that I not do so manually with a DPG SDK I just GA'd yesterday since the generator should probably do this and we don't want any conflicting implementations.

/cc @annelo-msft @AlexanderSher

**Comment by chunyu3** [comment]
DPG should auto gen this part.

**Comment by scottaddie** [comment]
@m-nash Can we also please generate the methods to fix this issue? https://github.com/Azure/azure-sdk-for-net/issues/31718
