### ISSUE TITLE
[Test server] url.json

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#277]
- [x] Code generated
- [x] Tests for all scenarios
- [ ] API shape questions
- [ ] Fix identified issues
- [x] https://github.com/Azure/autorest.csharp/issues/291
- [x] https://github.com/Azure/autorest.csharp/issues/293
- [ ] https://github.com/Azure/autorest.csharp/issues/325

**Comment by MiYanni** [comment]
Implemented. Additional work for the tests have their own issues. Closing.
