### ISSUE TITLE
[CADL DPG] Generate Codes in sdk-folder defined in cadl-project.yaml

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.csharp#2778]
Example `cadl-project.yaml`:
```
emitters:
  "@azure-tools/cadl-csharp":
    "sdk-folder": sdk/confidentialledger/Azure.Security.ConfidentialLedger
```
When generating codes, the emitter should generate codes in `sdk-folder` when the option is defined.

**Comment by chunyu3** [comment]
https://gist.github.com/dw511214992/de785084657716b59e19a99970800544#3-generateoutputjson
