### ISSUE TITLE
[Test server] body-string.json

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#278]
- [x] Code generated
- [x] Tests for all scenarios
- [ ] API shape questions
- [ ] Fix identified issues

https://github.com/Azure/autorest.csharp/issues/288
https://github.com/Azure/autorest.csharp/issues/289
https://github.com/Azure/autorest.csharp/issues/290

**Comment by MiYanni** [comment]
Implemented. Additional work for the tests have their own issues. Closing.
