### ISSUE TITLE
[Test server] body-complex.json

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#279]
- [x] Code generated
- [x] Tests for all scenarios
  - https://github.com/Azure/autorest.csharp/pull/315
- [ ] API shape questions
- [ ] Fix identified issues

**Comment by pakrym** [comment]
@yanancai can you please take a look at writing tests and filing issues for this?

**Comment by yanancai** [comment]
@pakrym I think you @ a wrong person here. I have no context for this issue.

**Comment by pakrym** [comment]
My bad.

**Comment by MiYanni** [comment]
Implemented. Additional work for the tests have their own issues. Closing.
