### ISSUE TITLE
[Feature REQ] Handle optional properties nullable

### ISSUE THREAD

**Issue by HarveyLink** [Azure/autorest.csharp#2792]
**Describe the issue or request**
Currently we have the nullable filter to handle the null value in test. 
But customer may still hit the null exception in their debug.
Since we can't make our test cover all the properties and add `x-nullable`, it's more reasonable for us to have a design change in code gen to make the properties not marked as `requried` not throw null exception.

**Comment by ArcturusZhang** [comment]
Our current behavior in deserializer:

If the property is not marked as `x-nullable: true` in its corresponding swagger, our generated deserializer will check if the property in JSON is null, if it is null, throw exception (only in debug mode)

We would like to see:
Only do the above checks for required properties. If an optional property has a null value in the JSON response, we just deserialize it as the `default` of its type (null for reference types, default for value types)

**Comment by brutusbuckeye** [comment]
@ArcturusZhang has any progress been made on this? It is a blocker for AKS API calls via the Azure SDK for Dot Ne.

**Comment by ArcturusZhang** [comment]
Oh sorry we might forget to notice you and close this issue - the debug check in deserialization for null values have been removed for quite a long time.
Now the deserialization process should not throw any exceptions unless the type in the payload cannot match the type in the code. It no longer throw exception if it gets a `null` in the JSON, if the type in C# code could accept a null value.

Please have a try and let us know if there is any issue on this.
I am not sure which version we removed those checks, but if you start with the latest, I believe it should be fine

**Comment by ArcturusZhang** [comment]
Close this since this change has been made.
