### ISSUE TITLE
Does not generate domain model classes

### ISSUE THREAD

**Issue by PGPoulsen** [Azure/autorest.csharp#2798]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

Hi

I'm trying to follow the example to generate a client. (https://github.com/Azure/autorest/blob/main/docs/generate/readme.md)

And when I run

`autorest --input-file=pets.json --csharp`

I get a `PetClient` class and a `PetClientOptions` class. But it does not generate the Dog or Kitten classes for me, eventhough I can see the they are defined the pets.json file.

What am I missing here?

/peter

**Comment by lirenhe** [comment]
Please use this flag  'generation1-convenience-client' and have a try.

**Comment by PGPoulsen** [comment]
Adding --generation1-convenience-client seemed to do the trick. Thanks :)
