### ISSUE TITLE
[Feature Req] Change the way we handle empty string value in deserialization

### ISSUE THREAD

**Issue by xboxeer** [Azure/autorest.csharp#2802]
**Describe the issue or request**
In this github issue, https://github.com/Azure/azure-sdk-for-net/issues/31701, the keyvault id is an empty string, and SDK is throwing exception that the value cannot be null for property resourceId

**Describe your ideas for solutions**
We should either not throwing exception when keyvault id is empty string, or we should throw the exception before we are trying to constructing the resource identifior  throw an empty string, throwing the exception in the resource identifior ctor will miss a lot of context information. 
The keyvault id here can applied to any kind of id property in raw response that SDK is trying to desterilize to a resource identifior 

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by xboxeer** [comment]
CC @ArcturusZhang

**Comment by xboxeer** [comment]
@ArcturusZhang do we have any update on this?

**Comment by Yao725** [comment]
I believe these issues are also related to this feature request:

- https://github.com/Azure/azure-sdk-for-net/issues/33245
- https://github.com/Azure/azure-sdk-for-net/issues/33388

**Comment by fengzhou-msft** [comment]
We decided to use a config both for mgmt palne and data plane to specify the models that should treat empty string as null. The intial types to check for empty strings could be: `Uri`, `Guid`, `ResourceIdentifier` or plus others that we may add format in `autorest.md` for the original string in swagger.

**Comment by fengzhou-msft** [comment]
Previously we fixed the issue with custom code for several SDKs. After the generator fix, we should remove those custom code and fix with the configs for easier maintenance in the future.
