### ISSUE TITLE
CADL: Models generated from templates should not be put into Azure.Core

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2803]
From the APIView generated by ADP https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files
A couple of classes are created under the namespace of Azure.Core.

https://apiview.dev/Assemblies/Review/5b7d805ce109492094e0f8dc193b11f4#Azure.Core

We need to design a better way to handle models generated from templates

**Comment by ArcturusZhang** [comment]
Specific to this issue, these classes might be completely unnecessary. These Paged<T> classes will never be needed in our convenient pageable method if we implement them in this way: https://github.com/Azure/autorest.csharp/pull/2819
Because the `Paged<T>` class has already be parsed in the protocol method by hardcoding the property names `value` and `nextLink`.

**Comment by ArcturusZhang** [comment]
> Specific to this issue, these classes might be completely unnecessary. These Paged classes will never be needed in our convenient pageable method if we implement them in this way: #2819 Because the `Paged<T>` class has already be parsed in the protocol method by hardcoding the property names `value` and `nextLink`. Given that these are unnecessary, we could either:
> 
> 1. letting the emitter never emit them. This might be unpractical because the generator might need it when writing the protocol method to determine the property name of `values` and `nextlink`.
> 2. just write them as is in the generator, and introduce the internalizer and remover in the mgmt plane to DPG as well. Since those classes are not used anywhere, the remover will remove them, and we never need to worry about them anymore

Taking (2) as initial approach of resolving this. Tracking in https://github.com/Azure/autorest.csharp/issues/2841

**Comment by chunyu3** [comment]
Paged<T> will be internal now.

**Comment by chunyu3** [comment]
close this. Reopen this after we meet with some critical problem.
