### ISSUE TITLE
Make code structure to mono repo

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2804]
Because of this requirement https://github.com/Azure/autorest.csharp/issues/2584, we make @autorest.csharp as a denpendency of emitter. This makes the e2e development and release process a disaster. We need to:
1. Change the code repo structure to mono repo
2. Change this [line](https://github.com/Azure/autorest.csharp/blob/1f55931671671946fe42c350c8608e6a4ab643a5/eng/Generation.psm1#L79) to make it call the dev version of codegen

**Comment by lirenhe** [comment]
Move to backlog as this is not the priority for now.
