### ISSUE TITLE
[Feature Req]Support sample generation for DPG generated data plane SDK

### ISSUE THREAD

**Issue by xboxeer** [Azure/autorest.csharp#2813]
**Describe the issue or request**
Support sample generation for DPG generated data plane SDK

**Describe your ideas for solutions**
Support sample generation for DPG generated data plane SDK

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by xboxeer** [comment]
CC @lirenhe @ArthurMa1978

**Comment by lirenhe** [comment]
We may not do it before GA.  Assign to @ArcturusZhang as he also works with sample generation in mgmt. SDK

**Comment by lirenhe** [comment]
Not a priority now, move to the backlog
