### ISSUE TITLE
Add convenience API of paging methods

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2817]
Example of protocol method:
```C#
public virtual AsyncPageable<BinaryData> GetLedgerEntriesAsync(RequestContext context = null) {}
public virtual Pageable<BinaryData> GetLedgerEntries(RequestContext context = null) {}
```

Corresponding convenience method:
```C#
public virtual AsyncPageable<LedgerEntry> GetLegerEntryValuesAsync(CancellationToken cancellationToken = default)
{
    var context = new RequestContext { CancellationToken = cancellationToken };

    AsyncPageable<BinaryData> pageableBindaryData = GetLedgerEntriesImplementationAsync("PaginationClient.GetLegerEntryValues", context);
    return PageableHelpers.Select(pageableBindaryData, response => CustomPage.FromResponse(response).Value);
}

public virtual Pageable<LedgerEntry> GetLegerEntryValues(CancellationToken cancellationToken = default)
{
    var context = new RequestContext { CancellationToken = cancellationToken };

    Pageable<BinaryData> pageableBindaryData = GetLedgerEntriesImplementation("PaginationClient.GetLegerEntryValues", context);
    return PageableHelpers.Select(pageableBindaryData, response => CustomPage.FromResponse(response).Value);
}
```

**Comment by lirenhe** [comment]
@pshao25,  please confirm about the right approach of implementing this.

**Comment by chunyu3** [comment]
@pshao25 will help to do bench mark performance test to verify which implementation has the better performance, calling protocol method and serialize results or call rest api and serialize result page by page as mgmt-plan does.

**Comment by pshao25** [comment]
Performance result:
![image](https://user-images.githubusercontent.com/97225342/199448107-06087f62-49cb-4e74-958f-b7f62da30c9d.png)
- Data: one page with 1000 items `{ received: "model" }`
- networkLatency: call the local test server on the same machine, test server returns this page with 1000 items
- protocolMethod: call protocol method first and then desiarialize the 1000 items one by one.
- hlc: call generated hlc code, which will desiarialize the 1000 items together.

Conclusion:
Maybe the data is not large enough, however, compared with the network latency, I don't think we would get the performance improvement by changing the desiarialization method. 2.792 ms is just local call. When it comes to real internet, it would be longer.

**Comment by m-nash** [comment]
@pshao25  lets remove the network latency as we cannot control that, Use a mock transport so that we are only testing the latency that our code introduces.  At minimum the HLC is allocating 3x less memory which is important as well.

**Comment by pshao25** [comment]
**Test category:**
1. restWrapper: when we call HLC, we parse the whole data by calling the deserialization method.
2. protocol: when we call the protocol method, we will split the whole array into items one by one. 
3. protocolWrapperWithAccessToArray: we call protocol method first to split the whole array into items one by one, and then we call the item deserialization method one by one. We call ToArray() to make sure all the items are deserialized.
4. protocolWrapperWithAccessFirst: we call protocol method first to split the whole array into items one by one, and then we call the item deserialization method. But we call First() to only call the deserialization method for the first item.
5. protocolWrapperWithAccess: we call protocol method first to split the whole array into items one by one, and then we call the item deserialization method one by one. We call foreach to loop call the deserialization method for an item. It is supposed to be the same as Pt.3.

**Test result (only one property in an item):** 
- 5 items in a page:

|                           Method |       Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Allocated |
|--------------------------------- |-----------:|---------:|---------:|-------:|-------:|----------:|
|                      restWrapper | 1,425.8 ns | 22.81 ns | 17.81 ns | 0.1316 |      - |   1,112 B |
|                         protocol |   523.5 ns |  8.33 ns |  7.79 ns | 0.0401 |      - |     336 B |
| protocolWrapperWithAccessToArray | 2,055.7 ns | 29.14 ns | 29.93 ns | 0.1945 |      - |   1,632 B |
|   protocolWrapperWithAccessFirst |   873.7 ns | 15.76 ns | 23.60 ns | 0.0763 | 0.0010 |     640 B |
|        protocolWrapperWithAccess | 2,428.7 ns | 46.63 ns | 41.34 ns | 0.1869 |      - |   1,568 B |

- 100 items in a page:

|                           Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Allocated |
|--------------------------------- |----------:|----------:|----------:|-------:|-------:|----------:|
|                      restWrapper | 19.908 us | 0.3769 us | 0.5283 us | 1.9226 | 0.0610 |     16 KB |
|                         protocol |  7.759 us | 0.1271 us | 0.1127 us | 0.6409 |      - |      5 KB |
| protocolWrapperWithAccessToArray | 38.726 us | 0.7697 us | 0.8555 us | 3.4790 | 0.0610 |     29 KB |
|   protocolWrapperWithAccessFirst |  8.078 us | 0.1582 us | 0.1480 us | 0.6714 |      - |      6 KB |
|        protocolWrapperWithAccess | 38.475 us | 0.7467 us | 0.5830 us | 3.4180 | 0.0610 |     28 KB |

- 500 items in a page:

|                           Method |      Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Allocated |
|--------------------------------- |----------:|---------:|---------:|--------:|-------:|----------:|
|                      restWrapper |  97.53 us | 1.933 us | 4.078 us |  8.1787 | 0.8545 |     68 KB |
|                         protocol |  37.75 us | 0.733 us | 0.978 us |  2.8687 | 0.1831 |     24 KB |
| protocolWrapperWithAccessToArray | 188.84 us | 3.770 us | 4.487 us | 17.0898 | 2.1973 |    141 KB |
|   protocolWrapperWithAccessFirst |  38.61 us | 0.756 us | 1.131 us |  2.9297 | 0.1831 |     24 KB |
|        protocolWrapperWithAccess | 192.93 us | 3.293 us | 2.919 us | 16.6016 | 0.9766 |    137 KB |

- 1000 items in a page:

|                           Method |      Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Allocated |
|--------------------------------- |----------:|---------:|---------:|--------:|-------:|----------:|
|                      restWrapper | 186.62 us | 2.190 us | 2.049 us | 16.3574 | 3.1738 |    135 KB |
|                         protocol |  75.77 us | 0.904 us | 1.041 us |  5.7373 | 0.7324 |     47 KB |
| protocolWrapperWithAccessToArray | 376.42 us | 4.702 us | 4.398 us | 34.1797 | 6.8359 |    282 KB |
|   protocolWrapperWithAccessFirst |  76.72 us | 1.141 us | 0.953 us |  5.7373 | 0.7324 |     48 KB |
|        protocolWrapperWithAccess | 395.38 us | 3.973 us | 3.318 us | 33.2031 | 3.9063 |    274 KB |

**Comment by pshao25** [comment]
Code for reference:
```C#
[Benchmark]
public void restWrapper()
{
    JsonDocument jsonDocument = JsonDocument.Parse(fakeData);
    dpg_customization_hlc.Models.ProductResult.DeserializeProductResult(jsonDocument.RootElement);
}

[Benchmark]
public void protocol()
{
    var value = getProtocol();
}

[Benchmark]
public void protocolWrapperWithAccessToArray()
{
    var items = getProtocol();
    items.Select(item => dpg_customization_LowLevel.Models.Product.DeserializeProduct(JsonDocument.Parse(item.ToMemory()).RootElement)).ToArray();
}

[Benchmark]
public void protocolWrapperWithAccessFirst()
{
    var items = getProtocol();
    items.Select(item => dpg_customization_LowLevel.Models.Product.DeserializeProduct(JsonDocument.Parse(item.ToMemory()).RootElement)).First();
}

[Benchmark]
// To check if ToArray allocates extra memory
public void protocolWrapperWithAccess()
{
    var items = getProtocol();
    foreach (var item in items.Select(item => dpg_customization_LowLevel.Models.Product.DeserializeProduct(JsonDocument.Parse(item.ToMemory()).RootElement)))
    {
       
    }
}
```

**Comment by m-nash** [comment]
@pshao25 thanks a ton for the detailed analysis this was very helpful.  I talked with @KrzysztofCwalina and we decided for simplicity in our first iteration of dpg we will utilize the existing method writers to write convenience methods the same way we do any other hlc client dataplane/mgmtplane.  In the future once we catch up on our project timelines we can tackle this issue here which talks about possible improvements to the code such that wrapping protocol methods would be possible with near zero difference in performance.

In general we do want to wrap protocol methods from our convenience methods as this effectively acts like dogfooding in a way where it allows us to identify and resolve any friction that might exist in the process of creating a custom convenience method from a customers perspective.

I would ask that Benchmark code to an Autorest.Csharp.Perf project so that we can keep and replicate this testing in the future if needed.  We can follow a similar pattern to [Azure.Core.Perf](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core/perf) project and the [ResourceIdentifierBenchmark](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/perf/ResourceIdentifierBenchmark.cs) tests.

**Comment by pshao25** [comment]
Here is what we could add for a paging operation:
```C#
public virtual AsyncPageable<LedgerEntry> GetLedgerEntriesAsync(CancellationToken cancellationToken = default)
{
    async Task<Page<LedgerEntry>> FirstPageFunc(int? pageSizeHint)
    {
        using var scope = ClientDiagnostics.CreateScope("PaginationClient.GetLedgerEntries");
        scope.Start();
        try
        {
            var response = await GetLedgerEntryPageAsync(cancellationToken).ConfigureAwait(false);
            return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
        }
        catch (Exception e)
        {
            scope.Failed(e);
            throw;
        }
    }
    async Task<Page<LedgerEntry>> NextPageFunc(string nextLink, int? pageSizeHint)
    {
        using var scope = ClientDiagnostics.CreateScope("PaginationClient.GetLedgerEntries");
        scope.Start();
        try
        {
            var response = await GetLedgerEntryNextPageAsync(nextLink, cancellationToken).ConfigureAwait(false);
            return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
        }
        catch (Exception e)
        {
            scope.Failed(e);
            throw;
        }
    }
    return PageableHelpers.CreateAsyncEnumerable(FirstPageFunc, NextPageFunc);
}

public async Task<Response<CustomPage>> GetLedgerEntryPageAsync(CancellationToken cancellationToken = default)
{
    RequestContext context = FromCancellationToken(cancellationToken);
    using var message = CreateGetLedgerEntriesRequest(context);
    await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
    switch (message.Response.Status)
    {
        case 200:
            {
                CustomPage value = default;
                using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                value = CustomPage.DeserializeCustomPage(document.RootElement);
                return Response.FromValue(value, message.Response);
            }
        default:
            throw await ClientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
    }
}

public async Task<Response<CustomPage>> GetLedgerEntryNextPageAsync(string nextLink, CancellationToken cancellationToken = default)
{
    if (nextLink == null)
    {
        throw new ArgumentNullException(nameof(nextLink));
    }

    RequestContext context = FromCancellationToken(cancellationToken);
    using var message = CreateGetLedgerEntriesNextPageRequest(nextLink, context);
    await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
    switch (message.Response.Status)
    {
        case 200:
            {
                CustomPage value = default;
                using var document = await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false);
                value = CustomPage.DeserializeCustomPage(document.RootElement);
                return Response.FromValue(value, message.Response);
            }
        default:
            throw await ClientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
    }
}
```
What we need to pay attention:
1. Except the paging method itself, we need to add two helper methods `GetLedgerEntryPageAsync` and `GetLedgerEntryNextPageAsync`. If we decide to make it public, we should review the name.
2. The return type of these two helper methods is `CustomPage`, which holds the actual data `LedgerEntry`. Its structure is 
```C#
public partial class CustomPage
{
    public IReadOnlyList<LedgerEntry> Value { get; }
    public string NextLink { get; }
}
```
The reason it is called `CustomPage` is: it is defined in the cadl template. If there are more than one paging operations with different item type, the latter one would replace the previous one, so that only one `CustomPage` exists. We need to give different `CustomPage` different names. We don't have this feature, need to implement it first.
3. There is a little bit different when we call `using var message = CreateGetLedgerEntriesRequest(context);`. The parameter is `RequestContext`, so we need to first change the cancellationToken to requestContext by ` RequestContext context = FromCancellationToken(cancellationToken);`
