### ISSUE TITLE
The method name is not updated for GetXXX/ListXXX operatoin

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2820]
Generate  [ConfidentialLedge](https://github.com/Azure/cadl-azure/tree/main/packages/cadl-samples/data-plane/confidentialledger) project, the method `listXXX` (e.g. listLedgerEntries) does not change to `GetXXX`

**Comment by chunyu3** [comment]
https://azure.github.io/azure-sdk/dotnet_introduction.html#naming

**Comment by lirenhe** [comment]
The same problem also exist in ADP   https://apiview.dev/Assemblies/Review/5b7d805ce109492094e0f8dc193b11f4#ADP.DiscoveryResultUploadsClient
