### ISSUE TITLE
Proper use of AdditionalProperties

### ISSUE THREAD

**Issue by tracyboehrer** [Azure/autorest.csharp#2833]
What is the proper way to handle AdditionalProperties.  Nothing I've tried in OpenAPI actually works as expected.

When I use:

```
additionalProperties: true
```

or

```
additionalProperties:
   type: object
```

autorest will add

```
        /// <summary> Additional Properties. </summary>
        public IDictionary<string, object> AdditionalProperties { get; }
```

To the class.  But this doesn't work with System.Text.Json.JsonSerializer apparently.

We've stopped using the OpenAPI notation in the definition, and just manually include

```
        [JsonExtensionData]
        public IDictionary<string, JsonElement> AdditionalProperties { get; set; } = new Dictionary<string, JsonElement>();
```

**Comment by ArcturusZhang** [comment]
Hi @tracyboehrer we are developing a new feature that enables public serialization/deserialization of the generated models.
For more details and samples of how to use that please refer to: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/System.ClientModel/README.md
