### ISSUE TITLE
Breaking change when adding a new optional query parameter

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2839]
WebPubSub is releasing its new version by adding a new optional parameter.
V1 API:
```C#
public virtual Azure.Response SendToAll(Azure.Core.RequestContent content, Azure.Core.ContentType contentType, System.Collections.Generic.IEnumerable<string> excluded = null, Azure.RequestContext context = null)
```
V2 API:
```C#
public virtual Azure.Response SendToAll(Azure.Core.RequestContent content, Azure.Core.ContentType contentType, System.Collections.Generic.IEnumerable<string> excluded = null, string filter = null, Azure.RequestContext context = null)
```
A new optional `filter` is added. According to the [guidance](https://github.com/Azure/azure-sdk-for-net/blob/b6f2858a40b796eb077a9579c604dd84926abcbd/doc/DataPlaneCodeGeneration/ServiceDrivenEvolution.md), we need to add back the V1 version API to avoid breaking change.

However, if there is a call 
```C#
await serviceClient.SendToAllAsync(RequestContent.Create(jsonContent), ContentType.ApplicationJson)
```
The code breaks with ambiguous call error.

And this call will face the same issue:
```C#
await serviceClient.SendToAllAsync(RequestContent.Create(jsonContent), ContentType.ApplicationJson, null)
```

**Comment by pshao25** [comment]
My proposal is we add back the API like:
```C#
public virtual async Task<Response> SendToAllAsync(RequestContent content, ContentType contentType);
public virtual async Task<Response> SendToAllAsync(RequestContent content, ContentType contentType, IEnumerable<string> excluded);
public virtual async Task<Response> SendToAllAsync(RequestContent content, ContentType contentType, IEnumerable<string> excluded, RequestContext context);
```
Make the optional parameters in the V1 API to required and add one API per one optional parameter.

**Comment by lirenhe** [comment]
@pshao25, I think we should follow https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/ServiceDrivenEvolution.md for the solution and is there any difficulty for service team to follow this guidence?

**Comment by lirenhe** [comment]
@m-nash , @AlexanderSher,  please let us know if you have any concern with the above approach.

**Comment by pshao25** [comment]
Sorry, my bad. There are no issues in the documentation above, so close this issue.

**Comment by pshao25** [comment]
> @pshao25, I think we should follow https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/ServiceDrivenEvolution.md for the solution and is there any difficulty for service team to follow this guidence?

The doc is correct. I think it should no difficulties for service team to follow.
