### ISSUE TITLE
Generate .NET client from Anomaly Detector (aka MVAD) Cadl API description

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2840]
This issue tracks validating that a DPG generator can generate the MVAD client, models, convinience APIs and protocol methods from https://github.com/Azure/azure-rest-api-specs/tree/feature/anomaly-detector-cadl/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl, to achieve parity with what DPG v1.0 can generate from MVAD OpenAPI description.

Inputs:
https://github.com/Azure/azure-rest-api-specs/tree/feature/anomaly-detector-cadl/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl

**Comment by pshao25** [comment]
We need to fix:
1. https://github.com/Azure/autorest.csharp/issues/2845
2. https://github.com/Azure/autorest.csharp/issues/2832
3.

**Comment by lirenhe** [comment]
Close this item as all work completed.
