### ISSUE TITLE
[Feature Req] Enable abstract base class for dataplane by default

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2857]
Right now dataplane does not default to abstract for base classes of polymorphic sets.  We should use logic similar to [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Models/Types/ModelTypeProvider.cs#L46).  As soon as we do this all types that are already GAd will become abstract which is a breaking change so we will have to add the [suppress-abstract-base-class](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/AutoRest/Plugins/Configuration.cs#L36) to each of those cases to ensure no breaking changes.

After that all new polymorphic sets will adopt the abstract keyword which is what we want.

**Comment by lirenhe** [comment]
@archerzz, could you check how much effort needed to support this? Thanks
