### ISSUE TITLE
The property marked as @key in CADL should be readonly in the generated models

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2858]
https://microsoft.github.io/cadl/docs/standard-library/built-in-decorators/#key
@key - mark a model property as the key to identify instances of that type

So this means the property could not be set at the client level and it should be readonly.

Please help to verify this behavior.

**Comment by m-nash** [comment]
We will be requiring that you set visibility when you set key so that we don't need to infer visibility from key. https://github.com/Azure/cadl-azure/pull/2351

**Comment by archerzz** [comment]
Closing per comment above. Thanks @m-nash !
