### ISSUE TITLE
Support union operator in cadl

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2872]
An example: https://github.com/Azure/cadl-ranch/blob/7435655e82b732b3573379f76e0e613423d244e9/packages/cadl-ranch-specs/http/resiliency/srv-driven-2/main.cadl#L109-L115

A fix for reference: https://github.com/Azure/autorest.csharp/pull/2660/

**Comment by chunyu3** [comment]
break Union to different senarios:
1. Union of string value:  may convert to enum
2. Union of different types

Find the valid scenarios of Union and break down to different tasks.

**Comment by pshao25** [comment]
1. Union of string value: we currently decide not to allow this https://github.com/Azure/autorest.csharp/issues/2972#issuecomment-1372576395
2. Union of different types: when it is in model, we track here https://github.com/Azure/autorest.csharp/issues/2936; when it is a paramter type, we will come back to discuss if there is real case.

So close this one.
