### ISSUE TITLE
[HLC] Should we include the discriminator in the model factory method?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#2874]
In the generated model factory of HLC packages, we have the discriminator property in the method signature.
For instance
https://github.com/Azure/autorest.csharp/blob/0eaeaf1237588923a1a6bd35693e4e94e27d23d9/test/TestServerProjects/body-complex/Generated/AutoRestComplexTestServiceModelFactory.cs#L70
where the `kind` of type `MyKind` is the discriminator.
Should it be in the signature? The discriminator should be intrinsic to that model, therefore I believe we should not include it in the method. Same question to the base model - it even does not have a linked discriminator value, should we include it in the model factory?

I found this issue when working on the post processor, which marks types that are not publicly used internal. The discriminator type (enum or extensible enum) is a type that is not publicly used, therefore it will be changed to internal, and the model factory will have compilation errors because we are using internal types inside the signature of a public method.

**Comment by m-nash** [comment]
For the concrete types the discriminator should not be in the model factory signature.  There should be a way to create and mimic "unknown" values so we should probably also have one factory method that returns the base type and that one should take the discriminator as a parameter.

**Comment by m-nash** [comment]
@ArcturusZhang I believe it does now after some recent changes to Unknown deserialization
