### ISSUE TITLE
defect(cadl): usage of model is incorrect if it inherits a model

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2882]
## Problem

See this [input model](https://github.com/Azure/autorest.csharp/blob/05205d82be7a708200197aacccb439a58e0f030b/test/TestProjects/Models-Cadl/Models-Cadl.cadl#L156). If it extends `BaseModel`, then in the generated `cadl.json` its usage is `RoundTrip`.

**Comment by chunyu3** [comment]
The root cause: resolveUsages() API apply the same usage for base and derived model.

I filed an issue for cadl for this https://github.com/microsoft/cadl/issues/1421

**Comment by chunyu3** [comment]
Resolved. Close it.
