### ISSUE TITLE
Autorest should not inject copyright header to generated files

### ISSUE THREAD

**Issue by dolly22** [Azure/autorest.csharp#2884]
**Describe the issue or request**
Autorest csharp `v3` injects fixed copyright header to all generated c# files. This licensing and copyright message is unexpected.

```
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>
```

**Describe your ideas for solutions**

It would be nice to be able to customize generated files header or at least change it to something more appropriate as `v2` generator injected.

```
// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
```

**Comment by xboxeer** [comment]
@dolly22 May I know why do you want to remove these copy right information? Are you using autorest to generate SDK for your own API?

**Comment by dolly22** [comment]
@xboxeer Yes, we are currently using autorest `v2` to generate clients (C# and typescript) for our own api. I'm trying to upgrade and use autorest `v3`.

**Comment by iivmok** [comment]
Can somebody make it clear: is autorest supposed to be used by projects outside of microsoft or not?

**Comment by xboxeer** [comment]
@iivmok autorest is an open source project and it can be used outside Microsoft. We are considering to add a new feature to enable/disable Microsoft copy right information

**Comment by gregoks** [comment]
@xboxeer Did you add an option to remove this header from the generates files? I've tried using --license-header=none but it doesnt do anything..

**Comment by ArcturusZhang** [comment]
> @xboxeer Did you add an option to remove this header from the generates files? I've tried using --license-header=none but it doesnt do anything..

So this issue is discussing whether the generated files should include license headers, but we currently do not support cusotmizing the license headers.
Could you open a new issue as a feature request to supersede this issue?

**Comment by gregoks** [comment]
Thanks @ArcturusZhang , I have created a new issue - https://github.com/Azure/autorest.csharp/issues/5078

**Comment by ArcturusZhang** [comment]
I had a fix that allows the user to customize the file header - if you pass in empty string, and it will not have file headers any more.
That does not fixes this issue, but I think it nullifies the issue we are discussing here.
