### ISSUE TITLE
CADL+DPG: The generated csproj work could not compile

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2885]
repo steps:
1. use the following PR and https://github.com/Azure/azure-rest-api-specs/pull/21525
2. call the command:   npx cadl compile --emit @azure-tools/cadl-csharp --output-path "path" client.cadl --option @azure-tools/cadl-csharp.new-project=true
3. invoke dotnet build on the generated code.

Expect:  the generated code could compile successfully.
Actual: Got the following error:
error
: The package reference 'Microsoft.Azure.AutoRest.CSharp' should not specify a version.  Please specify the version in
'D:\codegen\azure-sdk-for-net\eng\Packages.Data.props' or set VersionOverride to override the centrally defined versio
n. [D:\codegen\azure-sdk-for-net\sdk\anomalydetector\Azure.AI.AnomalyDetector2\src\Azure.AI.AnomalyDetector.csproj]

The generated  csproj file:

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <IncludeGeneratorSharedCode>true</IncludeGeneratorSharedCode>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20221122.1" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.25.0" />
  </ItemGroup>
</Project>

**Comment by lirenhe** [comment]
As this also blocks AOAI, please work on it with high priority.   
You may confirm the fix with @m-nash on this as he had the original PR to enable csproj generation in CodeGen.

**Comment by lirenhe** [comment]
close it as we use dotnet build in our onboarding document

**Comment by m-nash** [comment]
@lirenhe I would leave this open and lower the priority.  The reason being a customer outside of azure-sdk-for-net would end up with a bunch of .cs files and no .csproj file to build.  They would have to manually create this.  It would be far better if they had an option to create this for their first generation.

**Comment by chunyu3** [comment]
We already support to create compliable project file in scaffolding folder creation. close it.
