### ISSUE TITLE
Use overloads when both protocol and convenience are new at the same time

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2887]
If we are creating the protocol and convenience methods at the same time they should both use the same name and the overload that takes RequestContent should not have optional parameters.

As an example with this comment https://apiview.dev/Assemblies/Review/0eacd79245e14c6fa88d5991aac2e02f#5fdf7c9f2e154394a459e56ea4a166ce the two method would be
```c#
public virtual Pageable<Model> GetMultivariateModels(int? skip = null, int? maxCount = null, CancellationToken cancellationToken = default);
public virtual Pageable<BinaryData> GetMultivariateModels(int? skip, int? maxCount, RequestContext context);
```

**Comment by chunyu3** [comment]
Will load the previous version Generate code to SourceInputModel to identify the existence of protocol or convenience method.

**Comment by chunyu3** [comment]
Solution: load the previous version Generate code to SourceInputModel to identify the existence of protocol or convenience method, and then apply override strategy accordingly.

- Short-term: take the existing code in azure-sdk-for-net as base SourceInputMode

- Long-term: release version compatible, use released version as bas SourceInputMode. Refer to https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.ApiCompat/src/Microsoft.DotNet.ApiCompat.Core/Rules/Compat/CannotMakeNonVirtual.cs

@pshao25 will investigate the cost of short-term and long-term solutions, choose one suitable solution to implement according to the results.

**Comment by pshao25** [comment]
```C#
Case 1: v1 has no methods and v2 add protocol method
// v1: no protocol
// v2: only add protocol (context is optional)
public virtual Response RoundTrip(RequestContext context = null);

Case 2: v1 has no methods and v2 add protocol + convenience
// v1: no protocol
// v2: add protocol + convenience (context is required)
public virtual Response<RootModel> RoundTrip(CancellationToken cancellationToken = default);
public virtual Response RoundTrip(RequestContext context);

Case 3: v1 has only protocol and v2 add convenience
// v1: only protocol
public virtual Response RoundTrip(RequestContext context = null);
// v2: add convenience (context is optional and name is suffixed with value)
public virtual Response<RootModel> RoundTrip(CancellationToken cancellationToken = default);
public virtual Response RoundTripValue(RequestContext context = null);
```

**Comment by pshao25** [comment]
What should this operation be generated if there is no protocol method generated before?
```
@convenienceAPI
op test(optional?: int32): void;
```

Option 1: Not going to pass the compilation
```
public virtual Response Test(int? optional = null, RequestContext context);
```

Option 2: Not good I think
```
public virtual Response Test(RequestContext context, int? optional = null);
```

Option 3: Not apply the overload when there are optionl parameters
```
public virtual Response Test(int? optional = null, RequestContext context = null);
```

**Comment by pshao25** [comment]
We have analyzer [AZC0002](https://github.com/Azure/azure-sdk-tools/blob/86cbeea066f99955cbc424b90ead36c99da72e67/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs#L58-L71) avoid generating required `RequestContext` without any [overloads](https://github.com/Azure/azure-sdk-tools/blob/86cbeea066f99955cbc424b90ead36c99da72e67/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs#L60-L63).

Case 1: generate protocol and convenience together
```
public virtual Task<Response> Method(string resultId, RequestContext context = null);
public virtual Task<Response<Model>> Method(string resultId, CancellationToken cancellationToken);
public virtual Task<Response<Model>> Method(string resultId);
```
Conform to analyzer and won't break calling `Method("aaa")` as **convenience method**

Case 2: protocol in v1 and add convenience in v2
```
public virtual Task<Response> Method(string resultId, RequestContext context);
public virtual Task<Response<Model>> Method(string resultId, CancellationToken cancellationToken = default);
public virtual Task<Response> Method(string resultId);
```
Conform to analyzer and won't break calling `Method("aaa")` **as protocol method**

**Comment by pshao25** [comment]
Current design of flow:
1. Flag "load-existing" in cadl-location.yaml to indicate whether we download the latest code (not GA code) in sdk repo. True after the service is GAed. False when the service is under preview.
2. Parameter in codegen called "existing-project-folder", after we download the latest code, we pass the path to this parameter, then the codegen will take the existing code into consideration.

Remaining issue:
When the "existing-project-folder" is empty, should codegen take it as "this is the first time to generate, so we generate required requestcontext for protocol", or "we don't apply this feature, so still optional requestcontext for protocol".

**Comment by pshao25** [comment]
Decision on 2.28: 
1. Download the latest GA version: get GA number from csproj file, and get the commit number from release tag. Put this script into azure/azure-sdk-tools.
2. We don't need this parameter, codegen just read it from download path. 

Remaining issue: the answer is "this is the first time to generate, so we generate required requestcontext for protocol"

**Comment by pshao25** [comment]
Workflow:
![image](https://user-images.githubusercontent.com/97225342/226530335-f218027a-2256-4121-ae53-d783e00f9312.png)

**Comment by weshaggard** [comment]
If we end up needing to pull down the latest GA source code for every library, I have some concerns that doing the validation step across the entire repo will become more expensive as well as have more networking reliability issues. I'm less concern if we only need to do it for one library when we are generating but when we try to do it for hundreds of libraries that is likely going to cause some issues.  

Do we not have better options such as getting the source from before we do the generation to feed that as an input instead?

**Comment by m-nash** [comment]
@weshaggard I am not sure I understand the difference.  If we "get the source from before we do the generation to feed that as an input instead" wouldn't that still require us to download the source?

**Comment by weshaggard** [comment]
In the case I was thinking we would already have cloned the source down and that could be an input to the generation and then it could update the source in place.

**Comment by pshao25** [comment]
> In the case I was thinking we would already have cloned the source down and that could be an input to the generation and then it could update the source in place.

Say they project is `sdk\anomalydetector\Azure.AI.AnomalyDetector` and we are in commit A now. Commit B is the latest GA version. Are you saying we check out to commit B first and read contract from folder `sdk\anomalydetector\Azure.AI.AnomalyDetector` itself? Then:
1. I don't think checkout is a faster thing. In my daily practice, checkout takes far more longer than the sparse download.
2. Consider the user scenario. They are writing typespec and want to see what the SDK would look like after some change. They write an operation and then generate once. They find the SDK is not what they want so they change the typespec and generate again. Repeat this kind of process several times. Then what should we do? Revert every change and go back to a clean commit B? This is another cost. (Think about the sparse download is just a one-time effort)
3. If we checkout to commit B, how about the other projects? They would go to commit B together.
4. Consider the merge process. We are in commit A first and then we checkout to commit B. We generate new SDK and have a commit C based on commit B. Now we want to merge the commit C back to commit A. I'm afraid there are conflicts.

**Comment by weshaggard** [comment]
No I wasn't suggesting we do a checkout at all I'm hopping we don't need to have the latest GA and we can get away with just having the current source code before the code generation and we can use that as input to get what we need. So in your scenario if they generated and didn't like what they had they would simply revert the updated source code to get back to the original state.

**Comment by pshao25** [comment]
@weshaggard 
1. Then users should have the knowledge of the download step, which we definately not want they have. They should take generator as a black box instead of knowing how the box works.
2. The download step is kind of a "workaround". We want to apply new features but we shouldn't break existing version, so we download the GA version to make sure the GA version not break. We want to apply new features as more as possible (as long as GA not breaks). If we take the current source code as input, it would hold back us doing this.

**Comment by weshaggard** [comment]
I'm not sure I understand what you mean by users would have to have knowledge? What knowledge to they need to have? All they do is run the code gen and our tools will take the current files as input. 

@m-nash it seems like this might require a higher-level design meeting to get on the same page before we go down the path of needing to pull older versions of source code everytime we code gen.

**Comment by pshao25** [comment]
> What knowledge to they need to have?

They should know "the results depend on the current status in the project, i.e., if they don't revert the change the output would be not correct", which they don't now.
