### ISSUE TITLE
Update cadl-project.yaml to not use model namespace

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2889]
https://apiview.dev/Assemblies/Review/0eacd79245e14c6fa88d5991aac2e02f#f7b11600102e4ee9893d074c4c3cfd00

**Comment by lirenhe** [comment]
@pshao25, as this is just a configuration change, could you help to handle is ASAP? You may also update the existing samples/tests to remove the additional 'models' in the namespace.
