### ISSUE TITLE
CSharp emitter configuration option `generateConvenienceAPI` is not working as expected 

### ISSUE THREAD

**Issue by imakhlin** [Azure/autorest.csharp#2900]
Version: "@azure-tools/cadl-csharp": "0.1.9"

Example configuration: [`cadl-project.json`](https://github.com/Azure/azure-rest-api-specs-pr/blob/d1d0190ee459c556815771c7d1516a6cfc0c07aa/specification/adp/DataManagement/cadl-project.yaml)
>   "@azure-tools/cadl-csharp":
    library-name: "test.lib"
    namespace: "test.namespace"
    sdk-folder: "../../clients/some-path"
    clear-output-folder: true
    new-project: true    
    generateConvenienceAPI: true

I would expect that with `generateConvenienceAPI` turned ON, any operation exposed by service will have convenient API and models.
Unfortunately, emitter produces convenient APIs and Models only when I explicitly add `@Azure.DPG.convenienceAPI` decorator to each operation.

**Comment by lirenhe** [comment]
@imakhlin,  the config of `generateConvenienceAPI` is used internally to test the model generation. We don't expect people to use it for SDK generation and as I know, it is designed to generate models only.
Please follow https://github.com/Azure/azure-rest-api-specs/blob/8bf87228b145af455f7cdf39e0f2d17d7782e91d/specification/cognitiveservices/AnomalyDetector/client.cadl to define your ConvenienceAPI

**Comment by imakhlin** [comment]
@lirenhe I added the `[client.cadl](https://github.com/Azure/azure-rest-api-specs-pr/pull/9634/files#diff-7c8b4fbe14ff407726a799ee8f3ffcabcd86ad964a29622d0335dc393ff56884R11)` for ADP project and found another issue in generated C# code. [The issue](https://github.com/Azure/autorest.csharp/issues/2912) is that generated code uses the augmented operation name in the route (path) instead of the original operation name in swagger (openAPI)

**Comment by imakhlin** [comment]
@lirenhe I think this issue could be closed if this decorator should not be used that way.
