### ISSUE TITLE
Differentiate the API call from protocol method and convenience API in the telemetry

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2906]
We use the telemetry to analyze the behavour of the end users.
Today, through user-agent, we could know the source of an API call about whether it is from java, dotnet etc.

With DPG, we introduced both protocol method and convenience API, so we should have a way to tell whether an API call is from  protocol method and convenience API, that will help us to understand the customer behaviour.

**Comment by pshao25** [comment]
This is not feasible. Creating a new scope costs, so our principle is to create scopes as less as possible:
- If convenience API has the same name as protocol API, then only protocol API has scope.
- If convenience API has different name from protocol API, then convenience API will have a new scope and the protocol one suppressed.

In one word, there is only one scope for a pair of convenience and protocol.

More detailed version: https://github.com/azure/autorest.csharp/issues/2127#issuecomment-1086127240

**Comment by chunyu3** [comment]
For diagnostic, we will monitor the calls to an API, not need to category from protocol or convenience, not need to separate different scope. close it.
