### ISSUE TITLE
Generate a convenience layer for mgmt. plane SDK that a parent resource can create its child resource directly

### ISSUE THREAD

**Issue by xboxeer** [Azure/autorest.csharp#2910]
**Describe the issue or request**
The currently way of creating child resource is unintuitive, developers need to get the child resource collection and call the CreatOrUpdate method in the child resource collection, many developers are unable to find out this way to create a child resource from its parent resource .

**Describe your ideas for solutions**
We should provide a convenience layer to support direct create child resource on its parent resource. 
This should not include the ResourceGroups resource itself, as lot it is the parent of most other Azure Resource, adding the convenience layer on ResourceGroups resource will result too many create method on ResourceGroupResource

**Comment by ArthurMa1978** [comment]
This is the convenience way to crate any arm resource https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager#managing-existing-resources-by-resource-identifier.
