### ISSUE TITLE
CSharp emitter should respect the operation names defined in the CADL when using @convenienceAPI decorator

### ISSUE THREAD

**Issue by imakhlin** [Azure/autorest.csharp#2912]
I found that OpenAPI spec and .Net client emitted from the CADL have different routes (paths).
DPG uses the operation name overrides defined in the `client.cadl` while openapi emitter uses the original operation names from CADL interface.
Note, the main reason for overriding the operation names in DPG's `client.cadl` was to solve method signature uniqueness problem in the generated C# client. I didn't want to change the routes!
 
**For example:**
We have two LRO POST actions with same name for different resource type - routes are different so no problem with the API here. Action name for example is :generate 
In OpenApi sec the routes will look like this:
1. /discoveries/{discoveryId}/specialFilesUploadInfo:generate
2. /uploads/{uploadId}/specialFilesUploadInfo:generate

In `client.cadl` I had to override the operation names to prevent compilation errors, so I have
1. generateDiscoverySpecialFileUploadLocations
2. generateUploadSpecialFiles

As result the generated C# client will compose the Http message using action names defined in DPG client rather than those defined in CADL for API spec.
If both SDK and API will be published like this customer will be in trouble. I think the API surface should look the same for generated SDK and OpenApi.
 
PS: I know I can use the same operation names for the API as I defined for the SDK, but it sounds wrong to me. I want the API to be predictable and if I have same action on different resource types I want to use the same action names for consistency.

Reference project: [ADP](https://github.com/Azure/azure-rest-api-specs-pr/pull/9634)
- [client.cadl](https://github.com/Azure/azure-rest-api-specs-pr/pull/9634/files#diff-7c8b4fbe14ff407726a799ee8f3ffcabcd86ad964a29622d0335dc393ff56884R74)

**Comment by m-nash** [comment]
I think the bug here is more around respecting the operation route vs the operation name.  The "operation name" in a client cadl context is just a method name which we are respecting, however the `route` we use should never change from what the service cadl defines.

**Comment by chunyu3** [comment]
The cadl compiler will compose the route for the operation if the operation has @autoRoute decorator.

**Comment by chunyu3** [comment]
File issue https://github.com/microsoft/cadl/issues/1420 for cadl

**Comment by chunyu3** [comment]
As describe in https://github.com/microsoft/cadl/issues/1420, Use @actionSegment decorator to set down the action segment . emitter and codegen don't need to handle this.

close this issue.
