### ISSUE TITLE
cadl-csharp emitter should create actual Types from CADL models

### ISSUE THREAD

**Issue by glharper** [Azure/autorest.csharp#2930]
**Describe the issue or request**
For the CADL:
model Deployment { [fields definitions] };

A corresponding Deployment type should be created in the emitted C#. (Currently only the CADL routes are transformed into C# code).

Example Deployment CADL definition: https://github.com/Azure/azure-rest-api-specs/blob/feature/cognitiveservices/openai-cadl/specification/cognitiveservices/OpenAI.Authoring/models/deployment.models.cadl

**Comment by lirenhe** [comment]
@glharper, you need to define client.cadl file to list all convenience APIs, then models used in those APIs will be transformed into C# code. 
Here is one example: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/AnomalyDetector/client.cadl

Note, if you create client.cadl file, you need to specify that in npx cadl compile command.
