### ISSUE TITLE
Move logic of clear-output-folder from emitter to codegen

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2935]
**Background:**
We will decide the method signature according to the provious generated ones. Example: https://github.com/Azure/autorest.csharp/issues/2887.
Therefore, we cannot let users pass in `true` to this parameter and clear existing code arbitrarily,

**Expectation:**
We need to move this clear logic to codegen. What's more, we need to check if the signature changes, we can only do the clear if there is no signature change.

**Comment by lirenhe** [comment]
@chunyu3, what do you think of this proposal?

**Comment by chunyu3** [comment]
I think the previous code is the one already existed in the azure-sdk-for-net, Not the one iteratively generated by customer.

So eventually the `Generated` folder need be clear before we start to generate the code, you can move the codegen after you load the existing code if needed, then clear it and then re-generate. But we need to  pay attention to whether we need to load the code or not.
