### ISSUE TITLE
Redesign of RenameListToGet

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2941]
**Symptom:**

Example Cadl spec comming from authoring (but maybe out of date):
```
interface Deployments {
  @doc("Lists the existing deployments.")
  list is ResourceList<Deployment>;
}
interface Projects {
  @doc("Lists the existing projects.")
  list is ResourceList<
    Project,
    {
      parameters: ListQueryParams;
    }
  >;
}
```

There are two `list` operations in different interfaces. Currently, they are in the same client. So the generated SDK would be like:
```C#
public virtual AsyncPageable<BinaryData> GetAuthoringClientsAsync(int? maxCount = null, int? skip = null, int? maxpagesize = null, RequestContext context = null)
{
    return GetAuthoringClientsImplementationAsync("AuthoringClient.GetAuthoringClients", maxCount, skip, maxpagesize, context);
}

public virtual AsyncPageable<BinaryData> GetAuthoringClientsAsync(string projectName, RequestContext context = null)
{
    Argument.AssertNotNullOrEmpty(projectName, nameof(projectName));

    return GetAuthoringClientsImplementationAsync("AuthoringClient.GetAuthoringClients", projectName, context);
}
```
They are two overloads for the two `list` operations repectively. However, the name is not appropriate as `GetAuthoringClientsAsync`.

**Root cause:**

We rename list to get [here](https://github.com/Azure/autorest.csharp/blob/19ce1f0e470f201ec4d81ac993119d1e1ea65806/src/AutoRest.CSharp/LowLevel/Output/DpgOutputLibraryBuilder.cs#L184) by passing in the client name. If there is no appropriate resource name, we will use the client name. It makes sense to MGMT, but not for data plane.

**Solutions:**
Maybe the return type would be better to be a resource name. In this case, it would be:
```C#
public virtual AsyncPageable<BinaryData> GetProjectsAsync(int? maxCount = null, int? skip = null, int? maxpagesize = null, RequestContext context = null);
public virtual AsyncPageable<BinaryData> GetDeploymentsAsync(string projectName, RequestContext context = null);
```

**Comment by chunyu3** [comment]
If `Deployment` and `Project` are two different resources, we should defined those into sperate OperationGroup, not the same client. 
Emitter now is relayed on the @client and listClient to group the client, the information of resource name `project` and `deployment` will be erased. 
client.cadl is owned by DPG team, we need to define the right client.cadl as Laurent said.

**Comment by pshao25** [comment]
@chunyu3 so you are saying this cadl spec is not valid? If so, we need to add a linter.

**Comment by chunyu3** [comment]
> @chunyu3 so you are saying this cadl spec is not valid? If so, we need to add a linter. This spec is in our [test](https://github.com/Azure/autorest.csharp/blob/19ce1f0e470f201ec4d81ac993119d1e1ea65806/test/TestProjects/Authoring-Cadl/Authoring-Cadl.cadl) which comes from Authoring.
> 
> And it don't have to be two operations. One operation without any resouce names will have `getXXXClient` method name.

hello @pshao25 I don't mean cadl spec is not valid.  I mean in this case we need to define `Deployment` and `Project` into two OperationGroup(resource client) in client.cadl to customize.
