### ISSUE TITLE
Decide the response type of operation when resource type is different from response type

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2943]
Disscussion in Cadl Discussion: https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1670837861389?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1670837861389&teamName=Azure%20SDK&channelName=Cadl%20Discussion%20%F0%9F%90%AE&createdTime=1670837861389&allowXTenantAccess=false

In a short, what should be the operation return type of below operation? `ResourceType` or `ResponseType`?
```
@createsOrReplacesResource(ResourceType)
op WhatEverName is Foundations.ResourceCollectionOperation<ResourceType, {}, ResponseType>
```
Emitted swagger will return `ResponseType`, see [here](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmfMIGF6dXJlLXRvb2xzL8UsxhFjb3JlIjsKCnVzaW5nIENhZGwuSHR0cDvMEVJlc3TNEVbJYsgXQcRNLkNvcmU7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJDb250b3NvIFdpZGdldCBNYW5hZ2VyIiwKfSkKQOcAs2VkKMcnLsYnxybIcXPMK0RlcGVuZGVuY3koCiAgW1veOi52MjAyMl8wOF8zMSzrAK%2FLITFfMF9QcmV2aWV3XzFdXQopCm5hbWVzcGFjZSDVXTsKCmVudW0gyEMg5ADwy2g6ICLEDS0wOC0zMeQA6goKCkBkb2MoIkEgd8VJLiIpCkByZXNvdXJjZSgixhVzIikKbW9kZWzoASzEV0BrZXnIIU5hbWUiKcQVxU1UaGXHTyDkALHEVCAgQHZpc2liaWxpdHkoInJlYWTFFsQgOiBzdHLlAbt9Cs1oQ3JlYXRlUmVzcG9uc2XGdtVG6gCGzUwvLyBPcGVyYXTlAQwv0wEKCmludGVyZuQBUsZ05gE0QGPFe3NPclJlcGxhY2VzUugBFMYnxHZvcCBjdXN0b23mAKjGGSBpcyBGb3VuZMZ25AKrxThDb2xsZWPEFOkAkzzGMiwge30s9QDyPuQAxQ%3D%3D).

Our current behavior is return `ResourceType` because the `ResourceType` might be very complicated template, e.g., `CustomPage` will be generated from [this](https://github.com/chunyu3/autorest.csharp/blob/6673ff82a60907a058f5aae28fefac94bcde3976/test/TestProjects/Confidentialledger-Cadl/confidentialledger.cadl#L175).

**Comment by pshao25** [comment]
Our decision is: we use `ResponseType1

Reference: https://github.com/Azure/autorest.csharp/issues/2924#issuecomment-1371762243

**Comment by lirenhe** [comment]
> Our decision is: we use `ResponseType`
> 
> Reference: [#2924 (comment)](https://github.com/Azure/autorest.csharp/issues/2924#issuecomment-1371762243)

@pshao25, what is the feature gap with our current CodeGen?
