### ISSUE TITLE
CodeGen should flattern parameters defined with alias in CADL 

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2944]
Based on the email discussion, we should support the following in .NET DPG.

alias Foo = {
  id: string;
  name: string;
};
op M1(...Foo) : void;

// Same as

op M1(id: string, name: string): void;

**Comment by lirenhe** [comment]
As this would impact the SDK for openAI, we should treat this as high priority.

**Comment by chunyu3** [comment]
# with spread model which only contain one target

```cadl
model Foo {
  id: string;
  name: string;
}
alias FooAlias = {
  id: string;
  name: string;
};

op spreadWithModel(...Foo): void

op spreadWithAlias(...FooAlias): void
```

it will generate c# methods:
```
spreadWithModel(RequestContent content, RequestContext context = null);  //protocol method
spreadWithModel(Foo foo, CancellationToken cancellationToken = default); //convenience method
```

```
spreadWithAlias(RequestContent content, RequestContext context = null); //protocol method

spreadWithAlias(Foo foo, CancellationToken cancellationToken = default); //convenience method , option 1
or 
spreadWithAlias(string id, string name, CancellationToken cancellationToken = default); //convenience method, option2
```
For the convenience method, shall we flatten all the body parameters or not (option1 or option2)?

**Comment by chunyu3** [comment]
# with spread model/alias  which contains multiple targets

## model/alias only contain primitive type property

```
model Foo {
  @path id: string;
  id: string;
  name: string;
}

alias FooAlias = {
  @path id: string;
  id: string;
  name: string;
};
```

**Comment by chunyu3** [comment]
If we flatten body model as method paramters, we need to update the convenience method body to combine those flattened parameters to body json object.

There are two approach: 

1. Generate the body model ( as internal), and in convenience method, create the model and call toRequestConent to seraialize. - it may meet `anonymous model` issue.
```
internal partial class FooAlias 
    {
        /// <summary> Initializes a new instance of Friend. </summary>
        /// <param name="name"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/> is null. </exception>
        public FooAlias(string name, int32 age)
        {

            Name = name;
             Age = age;
        }

        /// <summary> Gets or sets the name. </summary>
        public string Name { get; set; }
        public int32 Age { get; set; }
    }
}
public virtual Response spreadWithAlias(string name, Int32 age, CancellationToken cancellationToken = default)
{
   ......
   FooAlias foo = new FooAlias(name, age);
   RequestContent content = foo.ToRequestContent()
  ......
}
```
3. Do not Generate the body model. in the convenience method, serialize the parameters to the json directory.
```
public virtual Response spreadWithAlias(string name, Int32 age, CancellationToken cancellationToken = default)
{
   ......
   RequestContent content = new Utf8JsonRequestContent();
       content.JsonWriter.WriteStartObject();
        content.JsonWriter.WritePropertyName("name");
        content.JsonWriter.WriteStringValue(Name);
       content.JsonWriter.WritePropertyName("age");
        content.JsonWriter.WriteNumberValue(Age)
        content.JsonWriter.WriteEndObject();
  ......
}
```

**Comment by chunyu3** [comment]
https://cadlwebsite.z1.web.core.windows.net/prs/1396/standard-library/rest/examples.html This is the document showing different Cadl operation styles, what it means in http context and what we'd want the client to be

**Comment by chunyu3** [comment]
option2

> If we flatten body model as method paramters, we need to update the convenience method body to combine those flattened parameters to body json object.
> 
> There are two approach:
> 
> 1. Generate the body model ( as internal), and in convenience method, create the model and call toRequestConent to seraialize. - it may meet `anonymous model` issue.
> 
> ```
> internal partial class FooAlias 
>     {
>         /// <summary> Initializes a new instance of Friend. </summary>
>         /// <param name="name"></param>
>         /// <exception cref="ArgumentNullException"> <paramref name="name"/> is null. </exception>
>         public FooAlias(string name, int32 age)
>         {
> 
>             Name = name;
>              Age = age;
>         }
> 
>         /// <summary> Gets or sets the name. </summary>
>         public string Name { get; set; }
>         public int32 Age { get; set; }
>     }
> }
> public virtual Response spreadWithAlias(string name, Int32 age, CancellationToken cancellationToken = default)
> {
>    ......
>    FooAlias foo = new FooAlias(name, age);
>    RequestContent content = foo.ToRequestContent()
>   ......
> }
> ```
> 
> 2. Do not Generate the body model. in the convenience method, serialize the parameters to the json directory.
> 
> ```
> public virtual Response spreadWithAlias(string name, Int32 age, CancellationToken cancellationToken = default)
> {
>    ......
>    RequestContent content = new Utf8JsonRequestContent();
>        content.JsonWriter.WriteStartObject();
>         content.JsonWriter.WritePropertyName("name");
>         content.JsonWriter.WriteStringValue(Name);
>        content.JsonWriter.WritePropertyName("age");
>         content.JsonWriter.WriteNumberValue(Age)
>         content.JsonWriter.WriteEndObject();
>   ......
> }
> ```

We will use #1 approach
