### ISSUE TITLE
CodeGen should have the ability to combine 2 services into one package for CADL+DPG

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2945]
We could define 2 services in CADL within 2 separate folders, but we should have the ability to combine them into one package.

For Swagger input, we already have that support for Purview service, we should consider how we could support it for CADL as well.

**Comment by lmazuel** [comment]
Additional clarity: we do not want to support two services in one client, or an hybrid client with cross-service methods. A service is a boundary. Though one service can be split in multiple clients like we do today, so from two services you may want three clients for instance.

**Comment by lirenhe** [comment]
@lmazuel, discussed with @m-nash and the approach that using a for loop to generate different clients and combine them together does not work for dotnet due to its complexity for the CI pipeline.
I would like to confirm for mutliple service, will there be a single sidecar file (client.cadl) to define the whole client, convenience API for multiple services?

**Comment by lmazuel** [comment]
Single client.cadl for one generation always.

**Comment by chunyu3** [comment]
Write client.cadl to combine two services(Authoring, Inference) into one package, and two clients will be generated under same Namespace and share the same clientOptions.

Following is the cadl project with generated code:
https://github.com/chunyu3/autorest.csharp/tree/openAIOnboarding/samples/OpenAI

**Comment by lirenhe** [comment]
Thanks @chunyu3,  could the .csproj file be generated or created from template correctly?

**Comment by chunyu3** [comment]
We already provide a way to combine two service into one package by a shared client.tsp. which will share the same namespace and clientOptions.  
There is another issue to track multiple service in one package with different namespace and clientOpttions. 
Close this one.
