### ISSUE TITLE
Design of property bag

### ISSUE THREAD

**Issue by Yao725** [Azure/autorest.csharp#2951]
### Purpose

The purpose of propert bag is to pack the parameters in a new model when the method has too many parameters.

### Background

When service APIs are updated in a new version, it is allowed to add a new optional input parameter. One possible consequence of this is that the API will have more and more input parameters as the version is updated. As we know, too many parameters can make the API difficult to use and increase the possibility of inadvertent switching of parameters in the call, which can lead to the service side returning unexpected results and making it difficult to discover the root cause. Based on above reasons, we decided to use a feature known as `property bag` to control the total number of method's parameters in the SDK.

#### When to use property bag

We take the number of parameters as the condition to trigger property bag. The detail is that we will use property bag to control the number of parameters once the public API contains more than **5**:exclamation: parameters.

#### What will be changed

Totally, property bag will only change the public API signature and has nothing to do with the internal rest operation. Here two steps will be taken:

##### Step 1: Changing the public method signature

Suppose we have a method in `SampleResource` as shown below:

```csharp
class SampleResource
{
  Response DoSomething(string a, string b = null, string c = null, string d = null, int? e = null, int? f = null);
}
```
It can be seen that `DoSomething` has six parameters. It satisfies the condition that we trigger property bag, and at this point, all parameters, whether non-required or required, will be packed into a new required parameter whose name is always `options`. So the original method signature will be updated to:
```csharp
class SampleResource
{
  Response DoSomething(SampleResourceDoSomethingOptions options);
}
```

##### Step 2: Adding a new class

Since we replace original multiple parameters with one new parameter `options`, a new class that consists of all the original parameters should also be added to the generated code. The four main rules for generating this new class are:
1. The name of this new class will be determined by the expression `{Resource or Collection or Extensions name}{Method name}Options`.
2. All the properties of this class should be `public`, the properties corresponding to the original required parameters will only have `get` accessor and the properties corresponding to the original non-required parameters will have both a `get` and a `set` accessor.
3. All the properties corresponding to the original non-required parameters will be explicitly initialized with honoring `x-ms-client-default`.
4. Only one public ctor with required parameters corresponding to read-only properties will be provided.

Based on above rules, the new class generated from step 1 will be:
```csharp
class SampleResourceDoSomethingOptions
{
  public SampleResourceDoSomethingOptions(string a)
  {
    A = a;
  }
  
  public string A { get; }
  
  public string B { get; set; } = null;
  
  public string C { get; set; } = null;
  
  public string D { get; set; } = null;

  public int? E { get; set; } = null;
  
  public int? F { get; set; } = null;
}
```

**[Note]**:

There are three exceptions that the parameter should not be included in property bag class, and will always be exposed in the public API：
- First parameter of extension method.
- LRO parameter: For LRO, a qualifier whose type is defined as [WaitUntil](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/WaitUntil.cs) will be added as the first parameter of the method to indicate if the user wants to wait for the LRO to simply start or wait for completion.
- Request context parameter: Normally, a optional request context parameter will be defined as the last parameter. In management plane, its type will be [CancellationToken](https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken), and in DPG, [RequestContext](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/RequestContext.cs) will be used as more context is needed.

#### Non-LRO method
In `Azure.ResourceManager.AlertsManagement`, `AlertsManagementExtensions` has an original method which looks like:
```csharp
class AlertsManagementExtensions
{
  public static async Task<Response<ServiceAlertSummary>> GetServiceAlertSummaryAsync(this SubscriptionResource subscriptionResource, AlertsSummaryGroupByField groupBy, bool? includeSmartGroupsCount = null, string targetResource = null, string targetResourceType = null, string targetResourceGroup = null, MonitorServiceSourceForAlert? monitorService = null, MonitorCondition? monitorCondition = null, ServiceAlertSeverity? severity = null, ServiceAlertState? alertState = null, string alertRule = null, TimeRangeFilter? timeRange = null, string customTimeRange = null, CancellationToken cancellationToken = default);
}
```
This method signature will be changed into:
```csharp
class AlertsManagementExtensions
{
  public static async Task<Response<ServiceAlertSummary>> GetServiceAlertSummaryAsync(this SubscriptionResource subscriptionResource, AlertsManagementExtensionsGetServiceAlertSummaryOptions options, CancellationToken cancellationToken = default);
}
```
And the `AlertsManagementExtensionsGetServiceAlertSummaryOptions` should be:
```csharp
public partial class AlertsManagementExtensionsGetServiceAlertSummaryOptions
{
  public AlertsManagementExtensionsGetServiceAlertSummaryOptions(AlertsSummaryGroupByField groupby)
  {
    Groupby = groupby;
  }

  public AlertsSummaryGroupByField Groupby { get; }

  public bool? IncludeSmartGroupsCount { get; set; } = null;

  public string TargetResource { get; set; } = null;

  public string TargetResourceType { get; set; } = null;

  public string TargetResourceGroup { get; set; } = null;

  public MonitorServiceSourceForAlert? MonitorService { get; set; } = null;

  public MonitorCondition? MonitorCondition { get; set; } = null;

  public ServiceAlertSeverity? Severity { get; set; } = null;

  public ServiceAlertState? AlertState { get; set; } = null;

  public string AlertRule { get; set; } = null;

  public TimeRangeFilter? TimeRange { get; set; } = null;

  public string CustomTimeRange { get; set; } = null;
}
```

#### LRO method
In `Azure.ResourceManager.DeviceProvisioningServices`, `DeviceProvisioningServicesCertificateResource` has an original method which looks like:
```csharp
class DeviceProvisioningServicesCertificateResource
{
  public virtual async Task<ArmOperation> DeleteAsync(WaitUntil waitUntil, string ifMatch, string certificateCommonName = null, byte[] certificateRawBytes = null, bool? certificateIsVerified = null, DeviceProvisioningServicesCertificatePurpose? certificatePurpose = null, DateTimeOffset? certificateCreatedOn = null, DateTimeOffset? certificateLastUpdatedOn = null, bool? certificateHasPrivateKey = null, string certificateNonce = null, CancellationToken cancellationToken = default);
}
```
This method signature will be changed into:
```csharp
class DeviceProvisioningServicesCertificateResource
{
  public virtual async Task<ArmOperation> DeleteAsync(WaitUntil waitUntil, DeviceProvisioningServicesCertificateResourceDeleteOptions options, CancellationToken cancellationToken = default);
}
```
And the `DeviceProvisioningServicesCertificateResourceDeleteOptions` should be:
```csharp
public partial class DeviceProvisioningServicesCertificateResourceDeleteOptions
{
  public DeviceProvisioningServicesCertificateResourceDeleteOptions(string ifMatch)
  {
    Argument.AssertNotNull(ifMatch, nameof(ifMatch));

    IfMatch = ifMatch;
  }

  public string IfMatch { get; }

  public string CertificateCommonName { get; set; } = null;

  public byte[] CertificateRawBytes { get; set; } = null;

  public bool? CertificateIsVerified { get; set; } = null;

  public DeviceProvisioningServicesCertificatePurpose? CertificatePurpose { get; set; } = null;

  public DateTimeOffset? CertificateCreatedOn { get; set; } = null;

  public DateTimeOffset? CertificateLastUpdatedOn { get; set; } = null;

  public bool? CertificateHasPrivateKey { get; set; } = null;

  public string CertificateNonce { get; set; } = null;
}
```

**Comment by ArcturusZhang** [comment]
Close this issue since this has been implemented in https://github.com/Azure/autorest.csharp/pull/2862
