### ISSUE TITLE
[TypeSpec] Add an option to generate all models, whether or not there are used in operations

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#2960]
There are scenarios like EventGrid or some IoT, were we need the models for various reasons while they are not necessary linked to an operation.

Not necessary urgent compared to current work like OpenAI

cc @JoshLove-msft

**Comment by chunyu3** [comment]
Now we only can retrieve out the models used in an operation. If we want to generate models which are not used in any operation, we need cadl compiler to provide an API to return all the models in the whole namespace.

**Comment by lmazuel** [comment]
As OpenAPIv3 and Swagger emitters are already able of this behavior, it means the API exists

**Comment by chunyu3** [comment]
Wait cadl to define the decorator

**Comment by cataggar** [comment]
What is the purpose of `unreferenced-types-handling: keepAll`? I thought it was to keep all the model types that are not referenced in routes. #2974

**Comment by chunyu3** [comment]
After discussed with @lmazuel and @JoshLove-msft , since we can make it work with the client.tsp via @usage and @access decorators, we don't need to implement this option to generate all models. close this issue.
