### ISSUE TITLE
Support LiteralType (StringLiteral, BooleanLiteral, NumericLiteral)

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2972]
Design how to support literalType.

LiteralType can be used in a model property or the operation parameter, or union. as following:

```
model A {
  name: string;
  type: "TypeA"
}

op get(@query top: 4)

model B {
   repeatabilityResult?: "accepted" | "rejected";
}

```

**Comment by archerzz** [comment]
Just couple of my cents. We should divide this issue into child issues.
- Model property: add as default value of the property, in constructor or in property initializer
- Operation parameter: as default value of the parameter which is also optional
- Union: change the union into fixed enum

**Comment by chunyu3** [comment]
> Just couple of my cents. We should divide this issue into child issues.
> 
> * Model property: add as default value of the property, in constructor or in property initializer
> * Operation parameter: as default value of the parameter which is also optional
> * Union: change the union into fixed enum

- Model property:  define as a get property, and initialize it in the constructor, remove it from constructor parameter
- Operation parameter: it is usually an path / query/ header parameter.  We shall remove from the method parameter list, and just set the value in the Create***Request when we create the HTTP request.
- Union: we will not support Union of LiteralType now. We may convert it to enum in codegen.

**Comment by chunyu3** [comment]
Model Property:

``` cadl
model Foo {
  name: string;
  type: "accepted"
}
```

Generated C# model:

```
    public partial class Foo
    {
        internal Foo(string name)
        {
            Argument.AssertNotNull(name, nameof(name));

            Name = name;
            Age = "accepted";
        }

        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Gets the age. </summary>
        public string Type { get; }
    }
```

```
    public partial class Thing
    {
       void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("name");
            writer.WriteStringValue(Name);
             writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }
        internal static Foo DeserializeThing(JsonElement element)
        {
            string name = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    age = property.Value.GetString();
                    continue;
                }
            }
            return new Thing(name, age);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static Thing FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeThing(document.RootElement);
        }
    }
```

**Comment by chunyu3** [comment]
- LiteralType as model property: we will support this. Above is the proposal of generated code. Need to decide whether we need serialize the Literal property to json object or not. [@Michael Nash](mailto:micnash@microsoft.com) will discuss this with archboard.
- LiteralType as operation parameter: Need to confirm with cadl team about the syntax of literal parameter, is it to tend to set the parameter default value?
- LiteralType in union. We will not support LiteralType union. And suggest to use fixed enum for this. We will add linter rule to avoid this.

**Comment by m-nash** [comment]
Had a conversation with @lmazuel and his suggestion was to conceptually treat anything that is literal as "private".  This would allow us to evolve if anything goes from a literal to an enum in the future since the property was never public in the first place.  He also suggests that serialization should happen to cover us from any service making a bad spec and requiring it, however deserialization isn't needed since the property is private anyways.

For the 3 scenarios above we would do the following
model A
``` public partial class A
    {
        internal A(string name)
        {
            Argument.AssertNotNull(name, nameof(name));

            Name = name;
            Type = "accepted";
        }

        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Gets the age. </summary>
        internal string Type { get; }
    }

    void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("name");
            writer.WriteStringValue(Name);
             writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }
        internal static Foo DeserializeA(JsonElement element)
        {
            string name = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
            }
            return new A(name);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static Thing FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeThing(document.RootElement);
        }
```

The only difference from what you had is the property is internal.

For the operation scenario we would omit the value on the signature (making it "private") and then pass the value in the appropriate location if it is path/query/header/body.

For the third scenario I still think we should have a linter rule for this one as it creates an ambiguously named enum and we should be explicit. @KrzysztofCwalina FYI for the `model B` scenario above only.  For now please name the enum [Class][Property] so in this case it would be `BRepeatabilityResult` if we come across one of these.

**Comment by chunyu3** [comment]
emitter will emit literal type
```
interface InputLiteralType extends InputType{
    Name: "Literal"
    ValueType: InputType
    value : any;
}
```

**Comment by archerzz** [comment]
So far, we have the following tasks:
- [ ] Emit literal value in emitter and parse it in the csharp generator (e.g. input model), according to the format we discussed above
- [ ] Update output model to support literal value, and modify model writer to generate it
- [ ] Update method model to support literal parameter value, and modify the model writer to generate it
