### ISSUE TITLE
[FeatureReq] Clean up metadata in comments for request path / operation id

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2976]
If we look an example [here for CreateOrUpdate](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/chaos/Azure.ResourceManager.Chaos/src/Generated/ExperimentCollection.cs#L59-L60) method we see that we are adding the service request path and operation id to the summary portion of the xml docs which is very helpful to relate back where the client method ends up calling.

The issue is this doesn't show up very well in VS which we get the following with everything concatenated on one line.

![image](https://user-images.githubusercontent.com/64171366/210438835-da5c611e-a6ff-4bf4-8df6-c6285a0bf409.png)

If we instead moved this to the remarks section and put it in a list it becomes much more readable

```C#
        /// <remarks>
        /// <list type="bullet">
        /// <item>
        /// <term>Request Path</term>
        /// <description>/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Chaos/experiments/{experimentName}</description>
        /// </item>
        /// <item>
        /// <term>Operation Id</term>
        /// <description>Experiments_CreateOrUpdate</description>
        /// </item>
        /// </list>
        /// </remarks>
```

It then looks like this

![image](https://user-images.githubusercontent.com/64171366/210439590-ca924374-e522-4bfb-8709-7d96ed62f38f.png)

If instead we wanted to keep it in the summary section we could use para tags to add new lines

```C#
        /// <summary>
        /// <para>
        /// Create or update a Experiment resource.
        /// </para>
        /// <para>
        /// Request Path: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Chaos/experiments/{experimentName}
        /// </para>
        /// <para>
        /// Operation Id: Experiments_CreateOrUpdate
        /// </para>
        /// </summary>
```

It then looks like

![image](https://user-images.githubusercontent.com/64171366/210440204-4aa339b3-31dc-4f52-93bb-a23b466c7448.png)

We should consider making this change or something similar to improve readability.

**Comment by archerzz** [comment]
Theoratically, using `<remarks>` should be better, since according to the [language spec](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#d312-remarks), `<remarks>` is:
> to specify extra information about a type

However, in our code model, the whole content is baked in `MethodSignature.Description` which is then printed as `<summary>`. To split them apart, code change is untrivial.

So, I'd prefer the second approach.
