### ISSUE TITLE
[dpg]: lro protocol method sample should use `WaitUntil.Started`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#2984]
## Description

Per comment here, for examples of LRO, we should pass in `WaitUntil.Completed`, and not invoke `WaitForCompletion`. This is a revert change of #2978

**Comment by lirenhe** [comment]
@archerzz , could you describe the difference between the 2 approaches?    cc @ArcturusZhang

**Comment by archerzz** [comment]
> @archerzz , could you describe the difference between the 2 approaches? cc @ArcturusZhang

- `WaitUntil.Started`: the method returns instantly after the 1st request/response. Users have to poll/update the status of the long running operation by themselves (e.g. `Operation.UpdateStatus()` or `Operation.WaitForCompletion()`).
- `WaitUntil.Completed`: the method will send the request, and poll the status of the operation until it succeeds or fails. Users can write codes to directly get the response right after the method.
