### ISSUE TITLE
How to define a correct LRO

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2988]
**1. What defines an LRO operation?**

Current implementation:
We only read `@pollingOperation`. 

Problem:
We have such definition in [cadl-samples](https://github.com/Azure/cadl-azure/blob/4511efc9694d7fa63ab270fb477f98dd42986de7/packages/cadl-samples/data-plane/language/authoring/authoring.cadl#L237), its response included a model whose property is marked as `@pollingLocation`, like this:
```
model LongRunningStatusLocation {
  @pollingLocation
  @doc("The location for monitoring the operation state.")
  @Cadl.Http.header("Operation-Location")
  operationLocation: ResourceLocation<OperationStatus>;
}
```

**2. Do we consider the polling location?**

Current implementation:
We don't care about how user defines. We look for the header in order "Operation-Location, Azure-AsyncOperation, Location" [here](https://github.com/Azure/autorest.csharp/blob/a24ca3c4c5b47d9e6576bc3b64bd5826fb4ac248/src/assets/Generator.Shared/NextLinkOperationImplementation.cs#L356-L385).

Problem:
So we should ignore the decorator `@pollingLocation` above?

**3. Do we consider the final location?**

Current implementation:
We only care about some specific final-state-via with complicate logic [here](https://github.com/Azure/autorest.csharp/blob/a24ca3c4c5b47d9e6576bc3b64bd5826fb4ac248/src/assets/Generator.Shared/NextLinkOperationImplementation.cs#L214-L258).

Problem:
Shall we repect the `@finalLocation` decorator like this?
```
model LocationOfCreatedResourceResponse<T extends object> is Cadl.Http.CreatedResponse {
  @finalLocation
  @Cadl.Http.header("Location")
  location: ResourceLocation<T>;
}
```
What if there is no `@finalLocation` decorated? Example:
```
@Azure.Core.pollingOperation(Authoring.createProjectStatusMonitor)
op updateProject is Azure.Core.LongRunningResourceCreateOrReplace<Project, Project>;
```

**Comment by mikekistler** [comment]
Long running operations should be defined in Cadl using the Cadl Azure Core "LongRunning*" operation templates. See the docs at:

https://azure.github.io/cadl-azure/docs/libraries/azure-core/reference

If these templates are not sufficient please open an issue on Cad Azure Core.

**Comment by archerzz** [comment]
https://github.com/Azure/typespec-azure/pull/2581 should help to mitigate the issue regarding how to fetch LRO metadata.

**Comment by archerzz** [comment]
I believe we will change to use `getLroMetadata()` method and `LroMetadata` to get the LRO definition: https://github.com/Azure/typespec-azure/pull/2581/files#diff-d6c989af71b662f005835f512aed3e6347892fc11652196034c1b737ececd135R268-R277

```typescript
export interface LroMetadata {
  operation: Operation;
  logicalResult: Model;
  finalStateVia: finalStateValue;

  // custom polling information
  steps: OperationStep[];
}

export function getLroMetadata(program: Program, operation: Operation): LroMetadata | undefined {
```

**Comment by chunyu3** [comment]
We will implement LRO via LroHelper. List all the scenarios which is supported, and the ones not-supported.

**Comment by archerzz** [comment]
This is blocked by https://github.com/Azure/typespec-azure/issues/3109

**Comment by archerzz** [comment]
Reopen. `healthinsights` has a custom LRO definition. Our adoption of `getLroMetadata` will break the generated codes: https://github.com/Azure/azure-rest-api-specs/blob/c2ca67f61d62f966ffe8327720e9bd5bd7838ee5/specification/cognitiveservices/HealthInsights/healthinsights.oncophenotype/route.oncophenotype.tsp

See the regen PR: https://github.com/Azure/azure-sdk-for-net/pull/37330

**Comment by archerzz** [comment]
Depending on issue(https://github.com/Azure/typespec-azure/issues/3245) to be fixed.

**Comment by archerzz** [comment]
This is blocked by problematic LRO template in healthinsights, which is being fixed in the following two PRs:
- https://github.com/Azure/azure-rest-api-specs/pull/24960
- https://github.com/Azure/azure-rest-api-specs/pull/24671
