### ISSUE TITLE
InvalidOperationException while declaring miltiple clients  

### ISSUE THREAD

**Issue by asaflevi-ms** [Azure/autorest.csharp#2991]
**Describe the issue or request**
After upgrading to Cadl 0.38.0, 
Unhandled exception. System.InvalidOperationException: Declaration already initialized
   at AutoRest.CSharp.Generation.Writers.CodeWriterDeclaration.SetActualName(String actualName)
  
 Is thrown while using csharp emitter.
   
Cadl code: https://github.com/Azure/azure-rest-api-specs-pr/tree/asaflevi/feature/health-decision-support-cadl/specification/cognitiveservices/data-plane/HealthDecisionSupport/cadl

HealthDecisionSupport service is a health service that is hosting multiple clinical decision models.
We would like to have SDK client for each model.
Currently two models are supported, TrialMatcher and OncoPhenotype .

**Comment by chunyu3** [comment]
The root cause is related the convenience method generation. The lifecycle of 'DefaultRequestContext' is not correct.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/10458143/211705487-b2cc1ef1-a10f-4c98-b1bb-8e68a9f54df5.png)

**Comment by pshao25** [comment]
Already fix in the latest code, so close.
