### ISSUE TITLE
[Bug] when the query parameter is array, the generated code build failed

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#2999]
When we define an array as query parameter, the generated code build failed.

Sample cadl:  https://github.com/openapi-env-test/azure-rest-api-specs/pull/3625

Generated .Net PR: https://github.com/openapi-env-test/azure-sdk-for-net/pull/1439

root cause:
When the parameter is array, the `Delimiter` should be set
https://github.com/Azure/autorest.csharp/blob/6d9ad9f954b6f1c928b3139066b5479ea328c858/src/AutoRest.CSharp/Common/Generation/Writers/RequestWriterHelpers.cs#L352-L353

**Comment by lirenhe** [comment]
@chunyu3, in https://github.com/openapi-env-test/azure-rest-api-specs/pull/3625, could you share the line of the code that cause this problem?

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3114
