### ISSUE TITLE
[Bug] LRO return response<T> when the final response is 204-no content

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3000]
We defined an LRO operation which contains both 202 and 204 response. the generated LRO method return Response<T>, actually it should be Response, no content.

expected to return no content
sample cadl: 
Delete LRO  https://github.com/Azure/azure-rest-api-specs-pr/pull/9634/files#diff-582563f31569daf2daae2f378f2b7444bc33cac407da4a41b74834d6d6325137R31.

The SDK generated from ADP project in this PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/9634

**Comment by lirenhe** [comment]
@chunyu3, I didn't find the generated code in https://github.com/Azure/azure-rest-api-specs-pr/pull/9634 , could you explain what is the current output and what is the expected output?  Thanks

**Comment by archerzz** [comment]
I think this is an issue in CADL: what's the expected way to determine every aspect of an LRO. There are several decorators out there, and you cannot stop people from defining the LRO operations according to their own understanding.

- If you check the customer's operation template, it defines 2 success responses.
```typescript
op CustomLongRunningResourceDelete<TResource extends object>(
  ...Foundations.ItemKeysOf<TResource>,
  ...Foundations.ApiVersionParameter,
  ...LongRunningOperationIdHeader
): (AcceptedResponse<CustomBodyWrapper<LongRunningOperationResponse>> &
  LongRunningOperationStatusLocationHeader) | NoContentResponse | CustomErrorResponse;
```
- And if you check the [template provided by CADL](https://github.com/Azure/cadl-azure/blob/c891224009d86e78525c9c33303c17833aee561e/packages/cadl-azure-core/lib/operations.cadl#L199-L206), it defines 1 success response.
```typescript
 LongRunningResourceDelete<TResource extends object, Traits = {}> is Foundations.ResourceOperation<
    TResource,
    TraitProperties<Traits & InterfaceTraits, TraitLocation.Parameters, TraitContext.Delete>,
    Foundations.AcceptedResponse<Foundations.OperationStatus &
      Foundations.LongRunningStatusLocation &
      TraitProperties<Traits & InterfaceTraits, TraitLocation.Response, TraitContext.Delete>>,
    Traits & InterfaceTraits
  >;
```

Considering other issues we met with LRO, I think we need a semantic model for LRO, not only some decorators and templates. I've filed Azure/cadl-azure#2453 to track that.

**Comment by archerzz** [comment]
This is still an issue after we adopt `getLroMetadata()` in #2988 `LroMetadata.logicalResult` will return either the final result or the final status monitor result. Currently we have a temporary handling which will set the return body `null` if it's a delete operation.

**Comment by chunyu3** [comment]
There is a issue to track all LRO definition. May close this one.

**Comment by archerzz** [comment]
LRO delete operation should have void return type now. See the generated codes from `cadl-ranch`: https://github.com/Azure/autorest.csharp/blob/3633830fe56d1f0875ea70e6aa60a651e016bd1e/test/CadlRanchProjects/azure/core/lro/standard/src/Generated/StandardClient.cs#L198
