### ISSUE TITLE
[Bug] the name in the model constructor parameter is not the same as the one to assign in the body

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3014]
In OpenAI.Inference https://github.com/Azure/azure-rest-api-specs/tree/feature/cognitiveservices/openai-cadl/specification/cognitiveservices/OpenAI.Inference

Define `Choice` model
```
@doc("Choice model within completion response")
model Choice {
    @doc("Generated text for given completion prompt")
    text?: string;
    @doc("Index")
    index?: int32;
    @doc("Log Prob Model")
    logprobs?: CompletionsLogProbsModel;
    @doc("Reason for finishing")
    finish_reason?: string;
}
```

generated SDK code:
```
internal Choice(string text, int? index, CompletionsLogProbsModel logprobs, string finish_reason)
        {
            Text = text;
            Index = index;
            Logprobs = logprobs;
            Finish_reason = finishReason;
        }
```

The variable name in constructor signature is `finish_reason`, but in the assignment it use `finishReason`.

**Comment by archerzz** [comment]
This looks like a clean name issue. Thanks @chunyu3 for finding it.

**Comment by chunyu3** [comment]
We may also need to apply right naming conversion for the model Field name. 'Finish_reason' is not complied with the convension.

**Comment by chunyu3** [comment]
> This looks like a clean name issue. Thanks @chunyu3 for finding it.

It is the inconsistent issue. in constructor method signature, the parameter has applied the `toVariableName()` convention, but in the constructor body, when assignment, it does not, and use the origin name.
