### ISSUE TITLE
refactor(common): clean up null check in generated deserialization codes

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#3038]
## Description

We have excessive null check in the generated deserialization codes, which causes the error in test/debug if backend responses do not strictly follow the API spec.

We should remove unnecessary null checks. We should check null only when:
- `IsRequired: true`, but the value isn't in the response.
  - If a property is required, we don't accept null value.
- The type is a non-nullable value type and the value isn't in the response.
  - For reference types, we accept null value, e.g. a string.
  - For value types, we don't accept null value, even we declare it as `int?`.

**Comment by archerzz** [comment]
move back to 2.0 GA, because of #3170

**Comment by chunyu3** [comment]
resolved in PR https://github.com/Azure/autorest.csharp/pull/3029. close it.
