### ISSUE TITLE
refactor(cadl): clean up how we define constant parameters

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#3040]
## Description

There is duplicated information about constant parameters in our code gen.
https://github.com/Azure/autorest.csharp/blob/80418efe80837f8748227f19ccf32871c12e7391/src/CADL.Extension/Emitter.Csharp/src/emitter.ts#L596-L616

There are 3 places related to a constant: `Type`, `Kind` and `DefaultValue`.

I think we can remove the constant value assignment in `DefaultValue` which should be reserved for optional parameters (if we support in the future). We can assign `InputLiteralType` to `Type`, so that we can fetch the constant value from `InputLiteralType`.

**Comment by chunyu3** [comment]
duplicate https://github.com/Azure/autorest.csharp/issues/3039
