### ISSUE TITLE
Migrate CADL Emitter to use the latest version of CADL Core and CADL Azure.

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3043]
"@cadl-lang/compiler": "0.39.0",
@azure-tools/cadl-azure-core: 0.25.0
@azure-tools/cadl-autorest: 0.25.0
@azure-tools/cadl-dpg: 0.25.0

cadl-core release notes: https://microsoft.github.io/cadl/release-notes/release-2023-01-12
cadl azure release notes: https://azure.github.io/cadl-azure/docs/release-notes/release-2023-01-12

**Comment by lirenhe** [comment]
@cadl-lang/compiler": "0.40.0"

Please work on this with high priority, thanks
