### ISSUE TITLE
Support @projectedName for CADL+DPG

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#3057]
There is a feedback from archboard review meeting to rename a model in OpenAI.
We need to enable to support for @projectedName to handle this requirement.

Please check https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/projection/main.cadl for the test project.

CADL-dpg support is already done in https://github.com/Azure/cadl-azure/pull/2462.

**Comment by ArcturusZhang** [comment]
Some useful document: https://microsoft.github.io/cadl/standard-library/projected-names

**Comment by pshao25** [comment]
Please add tests by:
1. Add "projection" to `$cadlRanchProjectPaths` in `eng\generated.ps1` and generate the SDK.
2. Add corresponding E2E tests under test\CadlRanchProjects.Tests.
