### ISSUE TITLE
Handle MatchConditions: via header parameters for CADL+DPG 

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#3065]
We need to decide how the generated SDK would look like for

`op read(@path petId: int32, @header ifMatch?: string): {
     @statusCode statusCode: 200;
     @header eTag: string;
     @body pet: Pet;
} | {
      @statusCode statusCode: 404;
};`

The generated code should be parity with DPG 1.0:  https://github.com/Azure/autorest.csharp/pull/1669

Mgmt. SDK seems to convert covert ifMatch to Azure.Etag.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/src/Generated/ImmutabilityPolicyResource.cs#L171

Set the milestone to GA as this may cause breaking change.

**Comment by chunyu3** [comment]
DPG already support this.
