### ISSUE TITLE
Support multiple discriminators

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3081]
Sample cadl:
https://github.com/Azure/cadl-ranch/blob/68ac3ccc553645284f39254c558bc0e4f24c85c8/packages/cadl-ranch-specs/http/models/inheritance/main.cadl

We could support this like HLC, I have a trial here: https://github.com/pshao25/autorest.csharp/tree/inheritance/test/TestProjects/AdditionalPropertiesEx/Generated

**Comment by pshao25** [comment]
Needs decision on https://github.com/Azure/cadl-azure/issues/2430

**Comment by archerzz** [comment]
filed #3099 3099 for follow up
