### ISSUE TITLE
Support for `nullable` primitive type array

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/autorest.csharp#3084]
**Describe the issue or request**
We have JSON that is a list of floats that may or may not contain a `null` item. Roughly speaking, something that looks like `[null, 0.1, 0.2, ...]`. It seems like it is not possible to have an array of nullable primitive types at the moment. 

We would like to have C# generated from this sort of cadl:

```cadl
alias nullableFloat = float32 | null;

model MyModel {
  listOfFloats?: nullableFloat[];   
}
```

**Comment by nguerrera** [comment]
The code you have there should work.

OpenAPI emitter has some issues (*) with it and the getTypeName is omitting parens when it shouldn't but there should actually be the right structure in the type graph for an emitter to do what you want here (**), which is also the correct interpretation. You can also express this without the alias using `(float32 | null)[]`

(*) https://github.com/microsoft/cadl/issues/356#issuecomment-1287278240
(**) verifying this now to be sure

**Comment by nguerrera** [comment]
Oh sorry, I thought this was filed against Cadl itself.

**Comment by chunyu3** [comment]
We will set the nullable and optional as following:
```
name? : type
    - if type is Model
        - optional: true
        - nullable: true
    - if type is primitive
        - optional: true
        - nullable: true
name? : type | null
    - if type is Model
        - optional: true
        - nullable: true
    - if type is primitive
        - optional: true
        - nullable: true
name : type
    - if type is Model
        - optional: false
        - nullable: true
    - if type is primitive
        - optional: false
        - nullable: false
name : type | null
    - if type is Model
        - optional: false
        - nullable: true
    - if type is primitive
        - optional: false
        - nullable: true
 ```

Generate code:
```
if primitive && nullable
    - primitivate? i.e. int? bool?
```
serialization logic
```
if readonly
    - don't write the serailize line
if null
    - skip serialize at runtime
 ```
