### ISSUE TITLE
Retire build target `GenerateTest` and create new as `GenerateTests`

### ISSUE THREAD

**Issue by changlong-liu** [Azure/autorest.csharp#3086]
Now we have building target `GenerateTest` in autorest.csharp and `GenerateTests` in azure-sdk-for-net.

As discussed in https://github.com/Azure/azure-sdk-for-net/pull/33940, we want to have consistent name for test/sample generation in autorest.csharp and azure-sdk-for-net. And the `GenerateTests` is more suitable name than `GenerateTest`.

I plan to follow below steps to retire `GenerateTest`:
1. create target `dotnet build \t:GenerateTests` in autorest.csharp.
2. use autorest GenerateTests  in azure-sdk-for-net (currently our sdk repo `GenerateTests` is based on autorest `GenerateTest`)
3. remove GenerateTest in autorest.csharp

**Comment by changlong-liu** [comment]
Adding @m-nash , @archerzz , @ArcturusZhang, @ArthurMa1978  for awareness in case this is not the right direction or approach.

**Comment by raych1** [comment]
@changlong-liu confirmed this task was done.
