### ISSUE TITLE
`format-by-name-rules` does not set the deserialization format string for datetime

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#3090]
In `OperationalInsights`, using below config:
```
format-by-name-rules:
   'lastSkuUpdatedOn': 'datetime'
```

**Actual behavior:**
The generated deserialization code will use:
`lastSkuUpdate = property.Value.GetDateTimeOffset();`

This calls the `JsonElement.GetDateTimeOffset()` method that only supports ISO 8601 format.

This caused issue: https://github.com/Azure/azure-sdk-for-net/issues/33536

**Expected behavior:**
The generated code should have a datetime format string:
`lastSkuUpdate = property.Value.GetDateTimeOffset("O");`

This calls an extension method: https://github.com/Azure/autorest.csharp/blob/c8280c0cacac4c06c7bdcd4414438a517db41eab/src/assets/Generator.Shared/JsonElementExtensions.cs#L66-L71
It treats the `JsonElement` as Int64 (Unix Timestamp) or string and the string case can support multiple formats despite the "O" format (`ISO8601`) being passed in.https://github.com/Azure/autorest.csharp/blob/c8280c0cacac4c06c7bdcd4414438a517db41eab/src/assets/Generator.Shared/TypeFormatters.cs#L125-L132

**Comment by ArthurMa1978** [comment]
Have another issue https://github.com/Azure/autorest.csharp/issues/2524 opened to track all unsupported format.
