### ISSUE TITLE
Emitter is adding an AcceptedResponse model even though the service CADL doesnt define one

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest.csharp#3092]
**Describe the issue or request**
During the Health Decision Support arch board the review showed an extra AcceptedResponse model was generated. Seems like this might be a bug. 

Link to APIView (comment is currently on line 34): https://apiview.dev/Assemblies/Review/8752b674208144f0b7ccb3c13343099c 
Link to CADL spec PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/10411

**Describe your ideas for solutions**
Seems like AcceptedResponse shouldn't be generated even if it's part of the operation template. I believe the fix for this issue may be related to: https://github.com/Azure/cadl-azure/issues/2505

**Comment by catalinaperalta** [comment]
cc @m-nash

**Comment by m-nash** [comment]
@pshao25 this is part of the work you are doing for `Response` type with templates can we link this with the original issue and close if its a duplicate?

**Comment by pshao25** [comment]
> @pshao25 this is part of the work you are doing for `Response` type with templates can we link this with the original issue and close if its a duplicate?

If they are not using cadl 0.39, then it is the root cause. They could update to the lastest one to resolve this. But it seems not the case. Need @archerzz to confirm. If they are using the latest code, then there is another root cause.

**Comment by archerzz** [comment]
Thanks @pshao25 Confirmed on my local build.

@catalinaperalta I tried the latest csharp emitter which cooperate with cadl `0.39`, and `AcceptedResponse` is not generated. Could you have a try? Thanks.

![image](https://user-images.githubusercontent.com/4516/218384342-749b5b1a-509b-4915-9be8-12739e24056f.png)

**Comment by m-nash** [comment]
@catalinaperalta this appears to again be related to not generating from the language repo?  In the language repo all the dependencies of the csharp emitter are fixed so that we know it will all work as expected.  `Generating from the spec repo is not supported`.
