### ISSUE TITLE
Handle non-model return type

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3110]
Cadl:
```
op world(): string;
```

It returns a string. Generated convenience method:
```C#
public virtual async Task<Response<string>> WorldValueAsync(CancellationToken cancellationToken = default)
{
    ...
    RequestContext context = FromCancellationToken(cancellationToken);
    Response response = await WorldAsync(context).ConfigureAwait(false);
    return Response.FromValue(string.FromResponse(response), response);
}
```

Option1: add a linter to avoid return non-model type.
Option2: we change the last line of our convenience method to 
```C#
return Response.FromValue((string)JsonData.FromBytes(response.Content.ToMemory()), response);
```

**Comment by m-nash** [comment]
I do think a linter rule here would be good, however a warning won't stop anyone and right now all linter rules are going in as warning.

I am pretty sure JsonData is still in experimental so we can't take a dependency on that.  We would need to deserialize the single value for most primitives we can use `response.Content.ToObjectFromJson<[theTypeWeWant]>()`
