### ISSUE TITLE
[TypeSpec] Support array format for query/header

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#3114]
By default, TypeSpec means `multi` (a=1&b=2)

You can specify an option by query option:
https://microsoft.github.io/cadl/standard-library/rest/reference/decorators#@Cadl.Http.query
https://microsoft.github.io/cadl/standard-library/rest/reference/js-api/interfaces/http.QueryParameterOptions

For instance, this means csv:
```
  @get list(@query({format: "csv"}) option?: string[]): Widget[] | Error;
```

We should at least make the default `multi` work as this is blocking for translator team

**Comment by chunyu3** [comment]
split to two subitem: query and head
 @ArcturusZhang  will work on head
@chunyu3  will work on query.
