### ISSUE TITLE
Same discriminator for inheritance models

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3121]
We cannot support this cadl:
```
@discriminator("model.kind")
model BaseModel {}

@discriminator("model.kind")
model DerivedModel extends BaseModel {
  "model.kind": "derived";
  "derived.name": string;
  for: string;
}
```
Error from codegen: An item with the same key has already been added. Key: model.kind

Repro steps: enable cadl-ranch project of 'special-words'.

**Comment by archerzz** [comment]
I don't think this is a valid case. Cadl should report error on this. The `@discriminator` has ambiguous meaning here. What does it mean if there is a such decorator?
- the decorated model has a discriminator property
- or the decorated model and its parents have a discriminator property

**Comment by ArcturusZhang** [comment]
First look at this cadl gives me the impression that this cadl is wrong. We should never have the `@discriminator` attribute on `DerivedModel`.
We should confirm the expected results with the cadl team or cadl ranch team.

**Comment by chunyu3** [comment]
I think it may describe the scenario in `body-complex` test-server test.
In this there are inheritance chain:  Fish-> shark->sawShark
They all use the same discriminator `FishType`, but it describe the multiple-level inheritances, and in `shark` deserialization will handle the deserialize `swwShark`

**Comment by pshao25** [comment]
@archerzz could you confirm with the owners. If it is invalid we will modify cadl-ranch.

**Comment by chunyu3** [comment]
Need cadl to clarify the behavior of same discriminator in multiple hierarchy levels.

**Comment by archerzz** [comment]
Mark has confirmed that it's a bug. I've raised a PR to fix it: https://github.com/Azure/cadl-ranch/pull/218
