### ISSUE TITLE
[Feature] How to generate non-explicit body parameter

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3129]
Cadl
```
@convenientAPI(true)
op hello(parameter: Thing): void;
```
it should be equivalent to
```
@convenientAPI(true)
op hello(@body parameter: Thing): void;
```

Actual:
```C#
public virtual Response Hello(Thing parameter, CancellationToken cancellationToken = default)
{
    Argument.AssertNotNull(parameter, nameof(parameter));

    HelloRequest helloRequest = new HelloRequest(parameter);
    RequestContext context = FromCancellationToken(cancellationToken);
    Response response = Hello(helloRequest.ToRequestContent(), context);
    return response;
}
```

Expected:
We should not generate model `HelloRequest`.

**Comment by chunyu3** [comment]
cadl compiler will return an anonymous model 
{
parametre: Thing;
} as body.

**Comment by chunyu3** [comment]
If there is no @body decorator, the parameter: Thing is the property of body parameter, so the payload is {parameter:{ }}, so we design an internal model `{operation}Request` to serialize as we did for spread alias.

**Comment by chunyu3** [comment]
It is by-design.

**Comment by pshao25** [comment]
@chunyu3 Could add the reference or quote like who confirmed this is by design?

**Comment by chunyu3** [comment]
The behavior is the same as we handle spread.

**Comment by chunyu3** [comment]
Maintain current implementation as it is.

**Comment by chunyu3** [comment]
The documentation describe the behavior of explicit and non-explicit @boady decorator.  If the @body is present then no anon model if it isn't then there is an anon model. https://gist.github.com/srnagar/feceb0310cbf3335385eada1e5fe1a86
