### ISSUE TITLE
Support the invalid model property names

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3143]
Example:
```
model DerivedModel {
  "model.kind": "derived";
  "derived.name": string;
  for: string;
}
```
"model.kind" and "derived.name" are not valid.

Solution 1:
Add lineter to compiler. I don't think cadl team will agree.

Solution 2:
Add linter in emiter and let compiler call it.

Solution 3:
Codegen remove the invalid character and make it camelcase.

I prefer solution 2.

**Comment by chunyu3** [comment]
What's the name will be in the json payload?

**Comment by chunyu3** [comment]
Those invalid model should be supported. Apply naming conversion in autorest.csharp/common, and apply to all targets(mgmt, hlc, dpg).

For keyword, (e.g.  for: string;), we will add waring in apiview and ask arch board to review this. If they don't accept, we may add @projectName to override.
