### ISSUE TITLE
support different authentication defined in cadl

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3168]
The supported authentication types are defined in https://microsoft.github.io/cadl/standard-library/rest/authentication

Today, we only support ApiKeyAuth and OAuth2Auth.

We need to figure out how to support other authentication types.

Note:

We don't need to generate everything, some kind of the custom code is acceptable and we need to make our framework ready.
We should not let codegen to crash for the cadl defined authentication types.

**Comment by chunyu3** [comment]
We have four kinds of auth supported in Cadl

BasicAuth, not supported, may not happen as a real cae
BearerAuth, not supported, may happen
ApiKeyAuth, supported
OAuth2Auth, supported
I think we could support BearerAuth with necessary change in our codegen or core.

see discussion here: https://teams.microsoft.com/l/message/19:4844af8fce9742a98d06e1debf60bab2@thread.skype/1675303249190?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1675303249190&teamName=Azure%20SDK&channelName=DPG%20Support&createdTime=1675303249190&allowXTenantAccess=false

**Comment by lirenhe** [comment]
@chunyu3, could you reuse this one?  https://github.com/Azure/autorest.csharp/issues/3074

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3074
