### ISSUE TITLE
The internal constructors for a model in DPG and mgmt/HLC are different

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3178]
The difference happens when the model has a discriminator.
In mgmt/HLC, the discriminator property will show up as a parameter in the internal constructor, for example:
https://github.com/Azure/autorest.csharp/blob/9151a2ec37f140ffbc53c8a5acda3e3280314afd/test/TestProjects/MgmtDiscriminator/Generated/Models/DeliveryRuleQueryStringCondition.cs#L31
In DPG, the discriminator property will not show up as parameter in the internal constructor, for example:
https://github.com/Azure/autorest.csharp/blob/9151a2ec37f140ffbc53c8a5acda3e3280314afd/test/CadlRanchProjects/inheritance/Generated/Models/Salmon.cs#L30

We should align the behavior considering that we cannot quickly align the implementation.

**Comment by ArcturusZhang** [comment]
We are going to align the behavior in mgmt/HLC to the way in DPG by not exposing the discriminator property in their internal constructors.

**Comment by ArcturusZhang** [comment]
Another inconsistency: DPG models will put the discriminator property in their protected constructor, but mgmt does not.
Mgmt (discriminator property is `name`):
https://github.com/Azure/autorest.csharp/blob/8ee2ca051a2ac5f4f79fb2d82209bfa076f93cbd/test/TestProjects/MgmtDiscriminator/Generated/Models/DeliveryRuleAction.cs#L18
DPG (discriminator property is `discriminatorProperty`):
https://github.com/Azure/autorest.csharp/blob/8ee2ca051a2ac5f4f79fb2d82209bfa076f93cbd/test/TestProjects/Models-Typespec/Generated/Models/BaseModelWithDiscriminator.cs#L20

**Comment by ArcturusZhang** [comment]
Differences between the discriminator in mgmt/HLC and DPG:

| category | mgmt/HLC | DPG |
| :-- | :-- | :-- |
| accessibility | internal | public |
| has setter? | no | yes |
| type | wrapped in extensible enum | always string |
| show up in internal ctor of base? | yes | no |
| show up in public ctor of base? | Always no | Always yes |
| show up in internal ctor of derived? | yes | no |
| show up in public ctor of derived? | Always no | Always no |

**Comment by ArcturusZhang** [comment]
My proposal is like this:

1. We do not expose the discriminator on the public/protected ctor.
2. We make the discriminator property internal (and the related extensible enum if any).
3. We add an `init` or `internal set` on discriminator property.
4. We set the property directly in public ctor of derived types (because base ctor no longer expose this property).
5. We put the discriminator on the internal ctor only on base.
6. We do not put the discriminator on the internal ctor for derived types, we assign it when calling base

Therefore it should look like this
```csharp
public abstract class BaseModel
{
protected BaseModel(string requiredProperty)
{
    RequiredProperty = requiredProperty;
}

internal BaseModel(string discriminatorProperty, string requiredProperty, string otherProperty)
{
    DiscriminatorProperty = discriminatorProperty;
    RequiredProperty = requiredProperty;
    OtherProperty = otherProperty;
}

internal string DiscriminatorProperty { get; init; } // internal set is also OK

public string RequierdProperty {get;set;}

public string OtherProperty {get; set;}
}

public class ModelA
{
public ModelA(string requiredProperty, int requiredInt) : base(requiredProperty)
{
    DiscriminatorProperty = "A"; // this requires the `init` indexer of internal set indexer
}

internal ModelA(string requiredProperty, string otherProperty, int requiredInt): base("A", requiredString, otherProperty)
{
    RequiredInt = requiredInt;
}

public int RequiredInt { get; set; }
}
```

**Comment by ArcturusZhang** [comment]
The other way around:
```csharp
public abstract class BaseModel
{
protected BaseModel(string requiredProperty)
{
    RequiredProperty = requiredProperty;
}

internal BaseModel(string discriminatorProperty, string requiredProperty, string otherProperty)
{
    DiscriminatorProperty = discriminatorProperty;
    RequiredProperty = requiredProperty;
    OtherProperty = otherProperty;
}

public string DiscriminatorProperty { get; protected internal set; }

// or if it is internal
// internal string DiscriminatorProperty { get; protected set; }

public string RequierdProperty {get;set;}

public string OtherProperty {get; set;}
}

public class ModelA
{
public ModelA(string requiredProperty, int requiredInt) : base(requiredProperty)
{
    DiscriminatorProperty = "A"; // this requires the `init` or `set` on the property
}

internal ModelA(string requiredProperty, string otherProperty, int requiredInt): base("A", requiredString, otherProperty)
{
    RequiredInt = requiredInt;
}

public int RequiredInt { get; set; }
}
```

**Comment by m-nash** [comment]
Last night we discussed removing the discriminator from the base serialization ctor since it is abstract we will alwyas construct a derived class even in the unknown case and that derived class will always set its value in both of its ctors.

The only place the discriminator should show up on the as a parameter is the model factory for the base type and the serialization ctor for the unknown derivation.

**Comment by ArcturusZhang** [comment]
Since our current code is following the pattern that I build the parameters from my own properties (`ModelTypeProviderFields`) and then putting them together to get the constructors (`ModelTypeProvider`), it is the most convenient that we keep the discriminator in the internal constructor. Because the unknown model is the only one that needs the discriminator as parameter in our previous design, therefore to get the parameter, we will have to get it from my base model and build it again in `ModelTypeProvider`, since it never passes along through the constructors.
Based on above reasons, I prefer that we keep the discriminator in the base and unknown model's constructor so that we could easily get the parameter of the discriminator. Other version of derived constructors will not have this parameter.

**Comment by ArcturusZhang** [comment]
This issue has been fixed by https://github.com/Azure/autorest.csharp/pull/3207

Because during the development of this alignment, we realized that the way in mgmt/HLC of implementing discriminator related model hierarchies is always correct, therefore the thing we need to do for this issue is only to change the way DPG is doing, and this has been done by https://github.com/Azure/autorest.csharp/pull/3207

Closing this issue
