### ISSUE TITLE
The generator is not generating ModelFactory methods for some of the models

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3181]
Related example and occurrence of this issue see this comment: https://github.com/Azure/azure-sdk-for-net/pull/33110#discussion_r1121266069

**Comment by apattath** [comment]
@ArcturusZhang, @m-nash - is anyone looking into this issue? The issue was originally raised from our PR (linked above) for Release candidate SDK. We're now planning to make our SDK release for GA (GA is at the end of March)

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang, @m-nash - is anyone looking into this issue? The issue was originally raised from our PR (linked above) for Release candidate SDK. We're now planning to make our SDK release for GA (GA is at the end of March)

this is not a blocker for your GA. We could always add the missing entries back using customization code.
If you believe some of them are needed in model factory, please add them in customization code.

**Comment by m-nash** [comment]
@ArcturusZhang that is true if this is purely a "missing models" issue.  If that is just the tip of the iceberg and some of the items that are there are not correct then it could have a breaking change post GA.  I would like us to do this investigation for root cause so we know the answer to this before they GA if possible.

**Comment by ArcturusZhang** [comment]
@m-nash I just debugged into this library to see what is happening for those public models.
EmailSendResult: internal property.
EmailMessage: its `IncludeDeserialize` is false (currently by design)
EmailContent: same as above
EmailRecipients: same as above
EmailAddress: same as above
EmailAttachment: same as above
Above are all the public models we have in this RP (others are internal)

Let me know if you would like to loose the constraint. We are doing bunch of checks before we generate an entry for a model: https://github.com/Azure/autorest.csharp/blob/524aa32ab8bb4196da1c9800cae9c839603d0ba5/src/AutoRest.CSharp/Common/Output/Models/Types/ModelFactoryTypeProvider.cs#L217
1. it must be public
2. it must have a deserializer (usage contains output)
3. it must not be abstract unless it has a discriminator
4. it must not have internal properties except for the safe flattened properties
5. it must at least have one readonly property (exclude IList and IDictionary)
6. its internal constructor must not have a parameter with internal type

We are doing the extra checks to minimize the size of our model factory. Let me know if any of these checks do not make sense, so that we could change them.
Some of them exist before I change anything on the model factories.

**Comment by m-nash** [comment]
I think we should remove check 2.

I am not sure I understand 4.  Are we saying if I have 1 public readonly property and one internal property that isn't a safe flatten then we won't generate the model factory?  This seems wrong I still would need to be able to mock the public property that is readonly.

I am not sure why 6 excludes the factory can't we just omit the internal type from the public factory surface and default it when calling the internal ctor?

**Comment by ArcturusZhang** [comment]
@m-nash 
thank you! I will soon remove the check 2. And this is one of the reason that every model should have an internal ctor.

About 4, we will never generate internal properties other than discriminator or safe flattened properties. We have internal properties usually because they are added using customization code and the generator will never know how to deal with it. And usually when they are adding those properties, they will remove our generated internal ctor and write their own, therefore it is not very likely that our generator could generate code that could compile. Therefore we have this condition - indicating that you are customizing this model too much and you will have to maintain the model factory entry for this model by yourself.

6 usually comes along with 4.

**Comment by ArcturusZhang** [comment]
@m-nash it makes sense.
I am planning to do this step by step, let us first loose the constraint 2. I will create another issue to track other checks (like 4 and 6) so that we do not have to deal with a lot of changes in one PR.
