### ISSUE TITLE
Verify whether dotnet DPG could generate stream API correctly

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#3197]
@Header contentType: "application/octet-stream";
@Body content: bytes;

Sample of issue:
https://github.com/wiboris/BatchFileIssue

Please check https://github.com/Azure/autorest.python/issues/1769 for more detailed information

**Comment by pshao25** [comment]
Tried this https://github.com/Azure/autorest.testserver/blob/0b506ec5426d50d8e439141cd3aa21eb0c32ecee/swagger/body-formdata.json#L52-L83, E2E works for protocol methods.

But we don't have convenience method. We could wrap the convenience method similar like this:
```C#
var stream = MakeStream("Test data stream");
var output = await client.UploadFileViaBodyAsync(RequestContent.Create(stream));
string result = new StreamReader(output.ContentStream).ReadToEnd();
Assert.AreEqual("Test data stream", result);
```

**Comment by lirenhe** [comment]
Let's make sure we have protocal method and convenience API generated from typespec input for this case.
As this would impact batch service team, please treat this with high priority.  thanks

**Comment by pshao25** [comment]
I just realized we already supported as tested in https://github.com/Azure/autorest.csharp/blob/68d87b329d4f4bedf1e1598ca9a49bdb560998b0/test/TestProjects/MediaTypes-Typespec/MediaTypes-Typespec.tsp#L30

So close it.
