### ISSUE TITLE
[DPG] The derived models with all required properties do not have proper internal constructor

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3206]
For this typespec:
```
@discriminator("name")
@doc("Base model with discriminator property.")
model DeliveryRuleAction {
    foo?: string;
}

@doc("Deriver model with discriminator property.")
model DeliveryRuleCacheExpirationAction extends DeliveryRuleAction {
    name: "A";

  @doc("Required parameters.")
  parameters: CacheExpirationActionParameters;
}

model CacheExpirationActionParameters {
    foo: string;
    bar?: int32;
}
```
Now on the latest commit e07e879768792aea9b30c2a8b65abf8f3d596616 generates the code like this for class `DeliveryRuleCacheExpirationAction`:
```csharp
    /// <summary> Deriver model with discriminator property. </summary>
    public partial class DeliveryRuleCacheExpirationAction : DeliveryRuleAction
    {
        /// <summary> Initializes a new instance of DeliveryRuleCacheExpirationAction. </summary>
        /// <param name="parameters"> Required parameters. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="parameters"/> is null. </exception>
        public DeliveryRuleCacheExpirationAction(CacheExpirationActionParameters parameters) : base("A")
        {
            Argument.AssertNotNull(parameters, nameof(parameters));

            Parameters = parameters;
        }

        /// <summary> Required parameters. </summary>
        public CacheExpirationActionParameters Parameters { get; set; }
    }
```
and corresponding deserialization looks like this:
```csharp
        internal static DeliveryRuleCacheExpirationAction DeserializeDeliveryRuleCacheExpirationAction(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            CacheExpirationActionParameters parameters = default;
            string name = default;
            Optional<string> foo = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("parameters"u8))
                {
                    parameters = CacheExpirationActionParameters.DeserializeCacheExpirationActionParameters(property.Value);
                    continue;
                }
                if (property.NameEquals("name"u8))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("foo"u8))
                {
                    foo = property.Value.GetString();
                    continue;
                }
            }
            return new DeliveryRuleCacheExpirationAction(parameters);
        }
```
The optional property on the base class `foo` just disappears during the deserialization and it is not correct.

**Comment by ArcturusZhang** [comment]
Root cause is here: https://github.com/Azure/autorest.csharp/blob/e07e879768792aea9b30c2a8b65abf8f3d596616/src/AutoRest.CSharp/Common/Output/Models/Types/ModelTypeProvider.cs#L186
In the above case, `publicParameters` and `serializationParameters` happens to have the same content, therefore the serialization constructor has been skipped.
The public parameters and serialization parameters will always have the same content if all the properties on this model are required, but it breaks when it has a base class - properties can be optional on the base model therefore in this case we cannot skip the serialization constructor.

**Comment by chunyu3** [comment]
> Root cause is here:
> 
> https://github.com/Azure/autorest.csharp/blob/e07e879768792aea9b30c2a8b65abf8f3d596616/src/AutoRest.CSharp/Common/Output/Models/Types/ModelTypeProvider.cs#L186
> 
> 
> In the above case, `publicParameters` and `serializationParameters` happens to have the same content, therefore the serialization constructor has been skipped.
> The public parameters and serialization parameters will always have the same content if all the properties on this model are required, but it breaks when it has a base class - properties can be optional on the base model therefore in this case we cannot skip the serialization constructor.

The `publicParameters` and `serializationParameter` should not the same in that case. Maybe that the `serializationParameters` is not correct.

**Comment by ArcturusZhang** [comment]
> > Root cause is here:
> > https://github.com/Azure/autorest.csharp/blob/e07e879768792aea9b30c2a8b65abf8f3d596616/src/AutoRest.CSharp/Common/Output/Models/Types/ModelTypeProvider.cs#L186
> > 
> > In the above case, `publicParameters` and `serializationParameters` happens to have the same content, therefore the serialization constructor has been skipped.
> > The public parameters and serialization parameters will always have the same content if all the properties on this model are required, but it breaks when it has a base class - properties can be optional on the base model therefore in this case we cannot skip the serialization constructor.
> 
> The `publicParameters` and `serializationParameter` should not the same in that case. Maybe that the `serializationParameters` is not correct.

These two list of parameters stands for "the parameters coming from my own properties", therefore:
PublicParameters: parameters coming from the required properties of my own
SerializationParameters: parameters coming from all the properties of my own
Because this model only have required parameters, they are the same.
This part is correct. Issue is on "we should not skip the serialization constructor when these lists are the same" because they are not all the parameters.
Details please check my PR.
