### ISSUE TITLE
Make auto regen PR pass the ci build triggered from SDK repo

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3216]
We have this pipeline to help us regen PR: https://github.com/Azure/autorest.csharp/pull/3171

These are sample PRs generated: 
https://github.com/Azure/azure-sdk-for-net/pull/35005
https://github.com/Azure/azure-sdk-for-net/pull/34956

These PRs cannot pass the ci triggered from azure-sdk-for-net. The remaining items are:
- Download internal packages without changing common scripts
- Regenerate APIView.

**Comment by hallipr** [comment]
AutoRest.CSharp regen preview pipeline now creates functional azure-sdk-for-net PR with appropriate API View links and alpha package restoration.
