### ISSUE TITLE
Constant Schemas/Literal Types are not consistent between mgmt and dpg

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3230]
For the equivalency between Constant Schemas and Literal Types, please refer to this comment in this issue: https://github.com/Azure/autorest.csharp/issues/3230#issuecomment-1482373167

For the details for the current inconsistency, please refer to this comment in this issue: https://github.com/Azure/autorest.csharp/issues/3230#issuecomment-1482061430

For the alignment that we are planning to apply, please refer to this comment in this issue: https://github.com/Azure/autorest.csharp/issues/3230#issuecomment-1486340259

Plan to do this in two steps:
1. Change the generator to make mgmt/HLC to align our decision
2. Change the emitter and the generator to make DPG to align our decision

**Comment by ArcturusZhang** [comment]
Related with https://github.com/Azure/autorest.csharp/issues/3178

**Comment by ArcturusZhang** [comment]
Come up with a matrix of constants/literals for mgmt and dpg when it is string/non string, property and parameter

**Comment by ArcturusZhang** [comment]
On my side, I believe the current implementation in DPG for optional literal is not correct, it is never "optional" because we always send a value for that property or parameter and the customer never has a chance to change them.

**Comment by chunyu3** [comment]
`Literal` is not the same as `Constants`. `Literal` is to define an type, more like a Fixed enum. `Constant` talk about a variable. Current we tried to map a type to a variable, there will be some gap. And I think the semantic of optional property of an literal type is not quite clear. What value of a optional property with literal type is when the property is not set?

**Comment by ArcturusZhang** [comment]
Some background knowledge:

# How is constant defined in swagger?

Swagger actually does not have a constant type. The model v4 transforms the "sealed enum with only one value" into `ConstantSchema` which is also a type, therefore this is the swagger equivalent to `LiteralType`, because it is a type as well. FYI @chunyu3 
```
"bar": {
"type": "string",
"enum": ["default"],
"x-ms-enum": {"modelAsString": false}
}
```

# How is literal types defined in typespec?

Typespec has native support for literal types
```
model Foo
{
bar: "default"; // stands for a property `bar` with the literal type of `default`
}
```

**Comment by m-nash** [comment]
@ArcturusZhang thanks a ton for putting this together.  Can you add one more column to the matrix above to explain what dataplane target does today and then schedule a sync to talk through this.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang thanks a ton for putting this together. Can you add one more column to the matrix above to explain what dataplane target does today and then schedule a sync to talk through this.

I updated the matrix.
Actually we already have a test project for various cases of the constant for HLC: https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestServerProjects/constants
Now looks like we have kind of an alignment between HLC and DPG - they did not differentiate optional and required constants or different types of the constant.
But my opinion is that our behaviour on optional constant is wrong - we never give the customer a choice of not putting the value into the request, especially when it is a query. We have got an explicit complain from the storage team which is the direct reason that we added the "extensible enum" wrapping mechanism.

**Comment by ArcturusZhang** [comment]
Actions and proposals for mgmt/hlc and dpg:

| combination | mgmt diff | hlc diff | dpg diff | proposal
| :-- | :-- | :-- | :-- | :-- |
| required string constant in model property | remove setter | remove setter | make public<br>change assignment<br>include in deserialization | public<br>extensible enum : opt<br>initializer in ctor<br>no setter<br>include in serialization<br>include in deserialization |
| optional string constant in model property | no-op | introduce extensible enum<br>remove the initialization in ctor | make public<br>introduce extensible enum<br>change assignment<br>add setter<br>include in deserialization | public<br>extensible enum: always<br>no initializer in ctor or default property assignment<br>setter<br>include in serialization<br>include in deserialization |
| required string constant in method parameter | no-op | no-op | no-op | not show up in the method<br>hardcode in request<br>no extensible enum |
| optional string constant in method parameter | no-op | add it to the method<br>no longer hardcode in request<br>add extensible enum | add it to the method<br>no longer hardcode in request<br>add extensible enum | show up in the method with default<br>extensible enum (always)<br>should not hardcode in request |

I only listed "string" constant, because I did not think non-string constant will have any difference.

**Comment by m-nash** [comment]
@ArcturusZhang thank you for all the detailed investigation here.  In your last table I am curious why we decided to have extensible enum be a generator option for a required property but when its optional its required?  Is this because we need a setter and therefore the hint on what values are known is important?

I am also curious on why we chose ctor assignment for required and property assignment for optional?

For the optional case would the default be null or the single value?

For parameters I agree with the proposal.

**Comment by ArcturusZhang** [comment]
We have an issue because mgmt and HLC diverges on this part:

1. mgmt already has the extensible enum and when it is an optional constant parameter, the default behavior is `null`, like:
```csharp
public Response Foo(ExpandType? expand = null)
```
2. HLC never has the extensible enum therefore when it is an optional constant parameter, the default behavior is "always have the value"
```csharp
public Response Foo() // the operation
// when creating the request
private CreateFooRequest()
{
builder.AppendQuery("foo", "value", false); // it always append the query
}
```

After the alignment, mgmt and HLC should have a same behavior, either default to null or default to the only value, but whichever we choose, we have a behavioral change in the other plane.

Which behavior should we take? We might need some discussion on this. @m-nash

**Comment by m-nash** [comment]
If I undserstand correctly before the constant was just hard coded in but after we swap to extensible enum the default value becomes null and we no longer pass the query param?

If so can we add a transform to add a default value so it matches the old behavior in the HLC case?

**Comment by ArcturusZhang** [comment]
Since this change will introduce breaking changes, I moved this to 2.0 GA
