### ISSUE TITLE
[DPG] Wrap the discriminator values into an extensible enum

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3234]
Details please refer this comment: https://github.com/Azure/autorest.csharp/issues/3178#issuecomment-1484533400

We need to introduce an extensible enum and make sure the discriminator use this new enum type.
Throw errors when an explicit name is not set for this discriminator type.

**Comment by chunyu3** [comment]
The wrapped extensible enum:
The usage of the enum: same as the model
The values of the enum: all existing discriminator values
The name of the enum:  Shall we add an decorator to define the enum name?

Discriminator Property:
solution: add a property in base model
