### ISSUE TITLE
Remove the SDK checks of nullability in responses

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3269]
**Describe the issue or request**

We have a few checks for the nullability of the response, and throw exceptions when a property is not expected to be null but we got null value in the response. For instance: https://github.com/Azure/autorest.csharp/blob/61a661324ea888b8c317bb67b9b5b247d5bb02dc/samples/AnomalyDetector/Generated/Models/AnomalyDetectionModel.Serialization.cs#L48
This is throwing exception when we got a response like:
```
{
    "modelInfo": null
}
```
but no exception will be thrown when the property is absent in the response. In a way of javascript, it is throwing exceptions when a property in the response JSON is null, but will not throw exception when a property in the response JSON in undefined.

The purpose of these checks is to check the service's behavior aligns with their swagger on the fact whether x-nullable is correctly honored.

But in practice this introduces more trouble than its benefits. Despite this check only works in DEBUG mode, we got quite a few complains from internal customers that gets exceptions when trying to debug their program which uses our SDK, but the fault is totally not on them at all and they do not have a simple valid solution.

This check is also taking the responsibility which the service team or some swagger tooling should catch and other language SDKs do not do this check at all.

**Describe your ideas for solutions**

We will remove all similar checks in our SDKs, and migrate the responsibility of checking violations of `x-nullable` to the live validation tool. There is an issue tracking this: https://github.com/Azure/azure-rest-api-specs/issues/23217

The live validation is a tool that checks the swagger correctness via real traffic, the `x-nullable` check falls into their responsibility perfectly because it is an issue that the service response does not align with their swagger (if x-nullable is false, null value should never be returned for that property).

**Comment by ArthurMa1978** [comment]
2 PRs fixed for both mgmt. and data plane:

- [x] https://github.com/Azure/azure-sdk-for-net/pull/35516
- [x] https://github.com/Azure/autorest.csharp/pull/3029

**Comment by ArcturusZhang** [comment]
Closing this issue since it has been fixed
