### ISSUE TITLE
Support apiverion in query and path/uri together

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3273]
Cadl-ranch: https://github.com/Azure/cadl-ranch/blob/279957d1c4b73fa5af1bbb5d9539985e40214d3b/packages/cadl-ranch-specs/http/azure/core/traits/main.tsp

This spec has two operation. One has apiversion as query parameter, the other has apiversion as path parameter(this place has another issue, I think it should be uri parameter).

We cannot support them together in the same spec.

**Comment by chunyu3** [comment]
We only support one apiversion, either path parameter or query parameter. In the cadl-ranch test, is the query apiversion parameter traited?

**Comment by chunyu3** [comment]
In this cadl-ranch test project, one operation trait out apiVersion path api-version parameter, the other not. As a result, in one client, one operation uses path apiversion, one uses query apiversion. We need to discuss if it is valid scenario that one client with mixed apiversion parameter.

**Comment by chunyu3** [comment]
apiversion in path: /2022-02-01/foo
apivesion in querey: /foo?api-version=2022-02-01

**Comment by pshao25** [comment]
Confirmed with @mikekistler, this is invalid case. Close with won't fix.
