### ISSUE TITLE
Generating from tsp does not always respect specified commit 

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#3306]
I am attempting to generate from the latest commit of https://github.com/Azure/azure-rest-api-specs/pull/23204. I've updated my [tsp-location.yaml](https://github.com/JoshLove-msft/azure-sdk-for-net/commit/5958661378437336c1456c6086cf4af7337ac89c) to reference the latest commit, [663b3482ea7d724a5204075a346d74d62e4731b3](https://github.com/Azure/azure-rest-api-specs/blob/663b3482ea7d724a5204075a346d74d62e4731b3/specification/eventgrid/Azure.Messaging.EventGrid/main.tsp). However, when I generate locally, it is using an [older commit](https://github.com/Azure/azure-rest-api-specs/blob/c879030ab8a98b4f0b37c82f8fd56b6afe13c1f4/specification/eventgrid/typespec/main.tsp). 

I've tried manually deleting the TempTypeSpec folder. I've also tried deleting the Azure.Messaging.EventGridV2 directory from here - C:\Users\jolov\src\r\Azure\sparse-spec\Azure.Messaging.EventGridV2\specification\eventgrid. 
But it still always uses an older commit. 

The interesting thing about the [old commit](https://github.com/Azure/azure-rest-api-specs/blob/c879030ab8a98b4f0b37c82f8fd56b6afe13c1f4/specification/eventgrid/typespec/main.tsp) it is using is that it was the final commit prior to us changing the directory structure so that the main.tsp was no longer under the typespec directory. However, I've updated the directory in my tsp-location.yaml to reflect the new structure:
```
repo: Azure/azure-rest-api-specs
directory: "specification/eventgrid/Azure.Messaging.EventGrid"
commit: 663b3482ea7d724a5204075a346d74d62e4731b3
```
but it doesn't seem to help.

**Comment by lmazuel** [comment]
cc @m-nash

**Comment by JoshLove-msft** [comment]
Nevermind! I had two tsp-location.yaml files defined and I was editing the one that was in the wrong location.
