### ISSUE TITLE
Array parameters not generated correctly

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#3308]
This [main.tsp](https://github.com/Azure/azure-rest-api-specs/blob/c879030ab8a98b4f0b37c82f8fd56b6afe13c1f4/specification/eventgrid/typespec/main.tsp#L161) defines an operation that takes a parameter defined as an array. When generating, the parameter is typed as `object` rather than `IEnumerable<CloudEventEvent>` as expected.

```
  public virtual async Task<Response> PublishBatchOfCloudEventsAsync(string topicName, object events, CancellationToken cancellationToken = default)
```

**Comment by pshao25** [comment]
Hi @JoshLove-msft , this is by design. A raw array cannot be body. You should wrap it in a model.

cc @m-nash

**Comment by JoshLove-msft** [comment]
This can't be wrapped in a model as it adheres to the CloudEvent spec - https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md#41-mapping-cloudevents

**Comment by lmazuel** [comment]
> Hi @JoshLove-msft , this is by design. A raw array cannot be body. You should wrap it in a model.
> 
> cc @m-nash

An array as input is a perfectly valid scenario.

**Comment by m-nash** [comment]
We should generate the following for input body types that are enumerable.  In general these shouldn't be allowed for azure services according stewardship board, but for brown field / external customers we may need to support them

- T[] => IEnumerable<T>
- byte[] => BinaryData
- Dictionary<T, U> => IDictionary<T, U>

@JoshLove-msft has the stewardship board approved the specific API here since this is an azure service?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft has the stewardship board approved the specific API here since this is an azure service?

Yes, this has been approved by the stewardship board. Are there any docs that outline the policy on using arrays for input?

**Comment by m-nash** [comment]
@tg-msft you mentioned this was something that API Stewardship Board tries to push back on do you have a link to any documentation on that?

**Comment by tg-msft** [comment]
https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#collections-response-is-object
