### ISSUE TITLE
Suppressing client methods still generates REST methods

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#3315]
When using `[CodeGenSuppress("MethodName", typeof(param1), ...)]` (and for Async) to suppress methods, which some libraries do, the generated *RestClient still has members related to creating and invoking requests e.g.,

* https://github.com/Azure/azure-sdk-for-net/blob/1aad75bd5889b95944a596fecf655bfc2b096529/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Customization/SparkSessionClient.cs#L13
* https://github.com/Azure/azure-sdk-for-net/blob/1aad75bd5889b95944a596fecf655bfc2b096529/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Generated/SparkSessionRestClient.cs#L126
* https://github.com/Azure/azure-sdk-for-net/blob/1aad75bd5889b95944a596fecf655bfc2b096529/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Generated/SparkSessionRestClient.cs#L156

They're not public, but still unnecessarily increase the size of the assembly. Low pri.

**Comment by ArcturusZhang** [comment]
I believe this is an issue for HLC instead of DPG. DPG does not generate RestClient methods.

We could add the corresponding attribute to the *RestClient to make them vanish, and I believe we should always require that attribute to remove the corresponding rest client, because the purpose of CodeGenSuppress is just removing the given member from the class with the attribute

**Comment by heaths** [comment]
> I believe this is an issue for HLC instead of DPG. DPG does not generate RestClient methods.
> 
> We could add the corresponding attribute to the *RestClient to make them vanish, and I believe we should always require that attribute to remove the corresponding rest client, because the purpose of CodeGenSuppress is just removing the given member from the class with the attribute

I think that makes sense. I hadn't considered making a partial class - since the rest client is already partial - to hide those, and this does allow for a manually written partial client class to still call them in different ways. I'll go ahead and close this. It's a good workaround - even solution - and not worth spending lots of time on HLCs right now.
