### ISSUE TITLE
[WIP] Consolidate service interaction code between DPG, MPG and Legacy Data Plane

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#3339]
This issue contains description of the differences in client generation between autorest.csharp flavors and possible ways of consolidation. **_Description will be updated_**

Clients are different not only in terms of supported features, but also in how many types of clients is generated and how responsibilities are shared between them
- DPG has only one client per endpoint. It contains all `CreateXxxRequest` methods, private response classifiers, sync and async version of the protocol methods and convenience methods that serialize request payload, call protocol methods and deserialize response (with the exception of Pageable, where convenience method calls create request method directly due to performance concerns). 
- Legacy Data Plane has internal RestClient per endpoint and may have public client that uses it. RestClient contains create request methods that serialize payload and sync/async convenience methods that handle response deserialization that may vary based in status codes. It also supports internal response header groups. Public client wraps RestClient method calls into client diagnostics scope and creates LRO instances. RestClient can have protocol methods similar to DPG, which would use their own version of create request methods.
- MPG has internal RestClient per endpoint and multiple `ArmResource`- and `ArmCollection`-derived clients. RestClient is similar to Legacy Data Plane. Clients that use it may call one and the same method but with different set of parameters and/or has additional logic to create instance of `ArmResource` client that would contain deserialized resource data.

### Summary of supported and non-supported features

|       Feature     | DPG  | Legacy Data Plane | MPG |
|          ---:     | :--- | :--- | :--- |
| Number of clients | Single public client | one internal RestClient and one public client | One internal rest client and one or more public ArmResource`- and `ArmCollection`-derived clients |
| Subclient / Resource client support | Yes | No | Yes |
| Parameter spread support | Yes | No | No |
| Parameter flattening support | No | Yes | No |
| Parameter grouping support | No | Yes | Yes |
| Request body serialization | Convenience methods | Create request methods | Create request methods |
| Multipart body support | No | Only in convenience methods | Yes |
| Multiple non-error response status code support | No | Yes | Yes |
| Response classifier support | Yes | Only in protocol methods | No |
| Header model | No | Yes | No |
| LRO types | `Operation` or `Operation<T>` | Generated LRO types, per client operation | Generated LRO types, one per client |
| LRO + Paging | No | Limited | Limited |

### Feature descriptions
- Parameter spread: request payload is represented in convenience method signature by the set of parameters, induced from the properties of the payload object. 
- Parameter flattering: request payload is represented in convenience method signature by the set of parameters, induced from the properties of the flattened model
- Parameter grouping: several elements of the request are represented in method signature as single parameter
- Header model: internal type that caches values of the response headers collection
- Request body serialization: logic that creates an instance of one of the types derived from `RequestContent`
- Response classifier: type derived from `Azure.Core.ResponseClassifier` that provides information about response. Each protocol method has default response classifier, which can be overridden by caller via `RequestContext`

#### Existing methods

Combined from all types of clients, there are 7 types of methods for non-LRO, non-paging case:
- Legacy public client method
  - Validates parameters
  - Calls convenience rest client method with matching signature, wrapped in client diagnostics scope
  - Returns result as is
- MPG public client method: 
  - Validates parameters
  - Calls convenience rest client method with matching or more generic signature, wrapped in client diagnostics scope
  - Returns instance of ArmResource that contains new resource data
- DPG convenience method
  - Validates parameters
  - Creates request content instance
  - Calls matching protocol method, wraps the call into client diagnostics scope if method name is different
  - Deserializes raw response into model
  - Returns typed response
- MPG / Legacy convenience rest client method
  - Validates parameters
  - Creates message by calling rich `CreateXxxRequest` method
  - Calls `_pipeline.Send`/`_pipeline.SendAsync` to get untyped response
  - Deserializes response based on the status code
  - Returns typed response
- DPG / Legacy protocol method
  - Validates parameters
  - Creates client diagnostic scope
  - Creates message by calling simple `CreateXxxRequest` method
  - Calls `_pipeline.ProcessMessage`/`_pipeline.ProcessMessageAsync` extension methods to get untyped response (these methods also call `ResponseClassifier.IsErrorResponse`)
  - Returns untyped response
- Rich `CreateXxxRequest` method creates `HttpMessage`, creates `RequestContent` instance, handles parameter grouping and flattening
- Simple `CreateXxxRequest` method only creates `HttpMessage` from parameters

**Comment by ArcturusZhang** [comment]
Working in https://github.com/Azure/autorest.csharp/pull/3726
