### ISSUE TITLE
No operations generated in Azure.AI.ContentSafety.netstandard2.0.cs

### ISSUE THREAD

**Issue by mengaims** [Azure/autorest.csharp#3342]
No operations generated in Azure.AI.ContentSafety.netstandard2.0.cs in https://github.com/Azure/azure-sdk-for-net/pull/34933
I've tried run eng/scripts/CodeChecks.ps1 again but nothing more generated.

**Comment by catalinaperalta** [comment]
@m-nash the discussion for this is included in the PR that Meng linked in the issue. Is there something that needs to be fixed for this?

**Comment by catalinaperalta** [comment]
Suggested solution is to run this: `.\eng\scripts\Export-API.ps1 contentsafety`

If it's still not working ping @m-nash and @chunyu3 to investigate

**Comment by catalinaperalta** [comment]
Related docs: https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md

**Comment by chunyu3** [comment]
Hello @mengaims  after we create the project template correct, this issue will not occur. @mengaims  do you have further problem?

**Comment by chunyu3** [comment]
Hello @mengaims  We will update the analyzer to resolve this issue.
As a workaround to unblock your work, you can suppress AZC0002 via adding line `<NoWarn>AZC0002</NoWarn>` in csproj file as following:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>Device Update for IoT Hub client library</AssemblyTitle>
  ...
    <NoWarn>AZC0002</NoWarn>
   ...
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" />
  </ItemGroup>

  <!-- Shared source from Azure.Core -->
 <ItemGroup>
    <Compile Include="$(AzureCoreSharedSources)ArrayBufferWriter.cs" LinkBase="Shared" />
    <Compile Include="$(AzureCoreSharedSources)AzureResourceProviderNamespaceAttribute.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
```

**Comment by mengaims** [comment]
It succeeded now, thanks all for the help! Closing this issue.
