### ISSUE TITLE
Expected date format of IfModifiedSince

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3351]
Actual:
https://github.com/Azure/autorest.csharp/blob/0d501998cca71449d49f04a171aa3db87c07220c/test/CadlRanchProjects/azure/core/traits/Generated/TraitsClient.cs#L169
We set "O" as a format, so the payload would be like: ""2022-08-26T14:38:00.0000000Z"

The expected behavior in cadl-ranch is ["Fri, 26 Aug 2022 14:38:00 GMT"](https://github.com/Azure/cadl-ranch/blob/0000ee363bfd27a34ec8b717172f3a0e610e61a4/packages/cadl-ranch-specs/http/azure/core/traits/mockapi.ts#L23)

**Comment by chunyu3** [comment]
If it(dateTime) is default:
in header:rfc7231
in body: rfc3339
