### ISSUE TITLE
[DPG] Cannot pass multiple options into the build parameter `typespecAdditionalOptions`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3362]
**Describe the issue or request**

It is documented [here](https://github.com/Azure/azure-sdk-for-net/blob/6b1372a2cbaa29e1c28b4c7c1b60c362f8a77f2e/eng/common/scripts/TypeSpec-Project-Generate.ps1#L9) that we could just this syntax:
```
option1=value1;option2=value2
```
to pass multiple typespec emitter options, but actually it does not work. The content after the semicolon will be ignored.
If we use this command in azure-sdk-for-net repo
```
dotnet build /t:GenerateCode  /p:typespecAdditionalOptions="debug=true;csharpGeneratorPath=/path/to/autorest.csharp/artifacts/bin/AutoRest.CSharp/Debug/net6.0/AutoRest.CSharp.dll"
```
the script can only get the value before semicolon and others are just ignored.

**Comment by ArcturusZhang** [comment]
it turns out that `;` does not work, such as:
```
dotnet build /t:GenerateCode /p:typespecAdditionalOptions="csharpGeneratorPath=./autorest.csharp/artifacts/bin/AutoRest.CSharp/Debug/net6.0/AutoRest.CSharp.dll;debug=true"
```
will not work. In the command executed, the script will only get the first part of the option `csharpGeneratorPath`, and `debug=true` is just thrown away.
However, it works as a charm if we escape the symbol `;` like this:
```
dotnet build /t:GenerateCode /p:typespecAdditionalOptions="csharpGeneratorPath=./autorest.csharp/artifacts/bin/AutoRest.CSharp/Debug/net6.0/AutoRest.CSharp.dll%3Bdebug=true"
```
In this way, the script will add both the options to the command.

**Comment by ArcturusZhang** [comment]
after some experiments, `dotnet build` command is the one who is responsible to the issue that the script could only receive the part before semicolon.

**Comment by chunyu3** [comment]
We will not use the Typespec-Project-Generate.ps1 to generate code. close this issue.
