### ISSUE TITLE
Is it possible to generate annotation [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)] for generating .net model using autorest?

### ISSUE THREAD

**Issue by yifan-zhou922** [Azure/autorest.csharp#3365]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

We would love to generate models with the annotation [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)] in .net and the @JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL) in java. Thanks.

**Comment by ArcturusZhang** [comment]
Could you be more specific on the scenario here?

**Comment by yifan-zhou922** [comment]
Hi @ArcturusZhang, we want to generate some models based on the swagger we defined.
Here is part of the autorest.md we used for generating 
![image](https://github.com/Azure/autorest.csharp/assets/78060542/b75dfd5d-3a50-457b-ab30-1885ef9fae6b)
Here is one of the samples.
![image](https://github.com/Azure/autorest.csharp/assets/78060542/9818743d-858e-4b08-ad97-5a737e8b83e5)
Furthermore, we want to ignore the null properties but do not know how to achieve this.

**Comment by ArcturusZhang** [comment]
After an offline discussion, this is a feature request for public serialization, therefore I will close this issue because the public serialization feature is tracked in other issues
