### ISSUE TITLE
[Sample] Define a way to select the correct client constructor in sample

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3369]
There will be manually customized client constructors together with auto-generated ones. When generate samples, we need define a way to select the correct effective client constructor to use.

By default, the customized constructor will be the first choice, but it may cause some problem,
e.g. openai add a set of customized client constructors which is target for openai endpoint, the auto-generated constructors are for azure openai. So when write samples for auto-generated method, it is not correct to use the customized client constructor.

**Comment by archerzz** [comment]
One case from `OpenAI` is that `ChatMessage` used to have `Content` property as optional and nullable. So the constructor of `ChatMessage` did not have `Content` as parameter. When custom constructor (e.g. `Content` as mandatory) is added to replace the original constructor (and make it internal), our sample generation still picks up the original constructor, which results in compilation error.

**Comment by archerzz** [comment]
> One case from `OpenAI` is that `ChatMessage` used to have `Content` property as optional and nullable. So the constructor of `ChatMessage` did not have `Content` as parameter. When custom constructor (e.g. `Content` as mandatory) is added to replace the original constructor (and make it internal), our sample generation still picks up the original constructor, which results in compilation error.

Just realized this issue is not for model constructor. So I filed https://github.com/Azure/autorest.csharp/issues/3641

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3144
