### ISSUE TITLE
BinaryData serialization issue

### ISSUE THREAD

**Issue by mengaims** [Azure/autorest.csharp#3375]
Open this issue to continue this discussion in teams channel: https://teams.microsoft.com/l/message/19:7b87fb348f224b37b6206fa9d89a105b@thread.skype/1682584135138?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1682584135138&teamName=Azure%20SDK&channelName=Language%20-%20DotNet&createdTime=1682584135138

We need to accept image input as base64 encoded string, and during the rest api review we were suggested to define it as bytes, like below:
```
model ImageData {
  @doc("Base64 encoding of image.")
  content?: bytes;
  @doc("The blob url of image.")
  blobUrl?: url;
}
```

In .NET code, I tried this:
```
            byte[] b = File.ReadAllBytes(datapath);
            BinaryData binaryData = BinaryData.FromBytes(b);
            ImageData image = new ImageData() { Content = binaryData };
```
But exception would be thrown:
System.Text.Json.JsonReaderException : '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
Stack:
ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
Utf8JsonReader.ConsumeValue(Byte marker)
Utf8JsonReader.ReadFirstToken(Byte first)
Utf8JsonReader.ReadSingleSegment()
Utf8JsonReader.Read()
JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
JsonDocument.Parse(String json, JsonDocumentOptions options)
IUtf8JsonSerializable.Write(Utf8JsonWriter writer) 行 24
Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value) 行 79
IUtf8JsonSerializable.Write(Utf8JsonWriter writer) 行 19
Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value) 行 79
AnalyzeImageOptions.ToRequestContent() 行 37
ContentSafetyClient.AnalyzeImage(AnalyzeImageOptions body, CancellationToken cancellationToken) 行 172
ContentSafetySamples.AnalyzeImage() 行 58

According to @m-nash, we should pass into base64 string instead of raw bytes of file, in this way, the sample code would look like:
`BinaryData binaryData = BinaryData.FromObjectAsJson([My Base64 string]);`
or
`BinaryData binaryData = BinaryData.FromString("\""+[My Base64 string]+"\"");`
They will work, but not straightforward to customer to understand and use. How can customer know that he should initialize 
 BinaryData from ObjectAsJson while passing a string? Or pass a string but need to add "\\" to the begin and end?
My suggestion is, passing the image binary to BinaryData and have some change on the serialization code in the SDK. Like below:
Replace the original generated code:
```
writer.WritePropertyName("content"u8);
#if NET6_0_OR_GREATER
    writer.WriteRawValue(Content);
#else
    JsonSerializer.Serialize(writer, JsonDocument.Parse(Content.ToString()).RootElement);
#endif
```
with 
```
writer.WritePropertyName("content"u8);
writer.WriteBase64StringValue(Content);
```

So that customer can read the image into bytes and call directly by:
```
BinaryData binaryData = BinaryData.FromBytes(b);
ImageData image = new ImageData() { Content = binaryData };
```
Besides, this aligns with the behavior of python package, in python sdk, the sample code would be like:
```
with open(image_path, "rb") as file: 
    my_file = file.read() 
    response = client.analyze_image(AnalyzeImageOptions(image=ImageData(content=my_file)))
```
@chunyu3 @m-nash does this make sense to you?
@heaths could you help provide your advice from the point of our scenario? 
CC @catalinaperalta

**Comment by heaths** [comment]
You don't want to use any of the `*json*` methods. That expects JSON. According to documentation, `BinaryData.FromBytes(byte[])` or even the constructor `new BinaryData(byte[])` should work. @JoshLove-msft can you help here?

**Comment by JoshLove-msft** [comment]
Sounds like the issue is that non-textual data is being included as part of a JSON object graph. One strategy to work around this is to Base64 encode the bytes so that you can include the resulting string in JSON.

I think it is a fair point that customers won't necessarily understand that they need to do this, and one potential solution would be to make the code generation handle both JSON and truly binary data that needs to be Base 64 encoded.
@m-nash is this something that code gen could handle? Essentially try what we are currently doing, and fall back to Base64 writing?

**Comment by heaths** [comment]
So is `FromBytes` expecting a `byte[]` representing JSON, then? At least from the method name, it wasn't clear. Is `BinaryData` meant for only JSON serialization, or can it handle raw binary responses/requests as well?

**Comment by JoshLove-msft** [comment]
No, FromBytes can take in any bytes. The issue is that this is a property on a model that is being serialized as JSON.

**Comment by KrzysztofCwalina** [comment]
I think our serialization logic needs the be aware that the service want the bytes to be base64 encode, and it needs to honor that.

**Comment by mengaims** [comment]
The user experience is poor when using current code: User see a class named BinaryData, but have to read in the files first, convert into base64 string, and even add the ugly double quoatation marks, to initialize this **"Binary"** Data. Put ourselves in customer's shoes, what will customer think? But in our python code, it's just read in the file, pass to constructor, done!

**Comment by heaths** [comment]
@KrzysztofCwalina or @JoshLove-msft correct me if I'm wrong, but @mengaims I think they are saying that 1) the typespec needs to document the format as needing base64 and 2) the code generator needs to do that automatically; thus, a customer could do `BinaryData.FromBytes()` and the right thing will happen.

**Comment by m-nash** [comment]
I am tracking the redesign of this TypeFactory mapping here FYI https://github.com/Azure/autorest.csharp/issues/3390.
