### ISSUE TITLE
Autorest is doing name creation for methods which we should undo

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3377]
Right now search has two methods both named get.  [Method1](https://github.com/Azure/azure-rest-api-specs-pr/blob/bc441dcec943fa48facd9531f24cc2109e9d6b4a/specification/search/serverless/indexes.tsp#L25), [Method2](https://github.com/Azure/azure-rest-api-specs-pr/blob/bc441dcec943fa48facd9531f24cc2109e9d6b4a/specification/search/serverless/documents.tsp#L29).

In our generator we are somehow coming up with new names for these so they don't collide on the same client.

This is a case where we should fall back to protocol only or have the client.tsp specify what these two methods should be called.

The [cadl.json](https://github.com/ShivangiReja/azure-sdk-for-net-pr/blob/CognitiveSearchSDK/sdk/search/Azure.Search.CognitiveSearch/src/Generated/cadl.json) output has the names as `get` so I assume the rename happens inside autorest.csharp but didn't dig further to verify.

**Comment by chunyu3** [comment]
Operation in a namespace/interface should have identical name. The operations belonging to different namespace may same names. But they will belong to different client, so it will no conflict when we adopt client-hierarchy feature.

**Comment by chunyu3** [comment]
In latest codegen, we will honor the namespace/interface, those two `get` methods will belong different sub client, so there will no conflict. close this.
