### ISSUE TITLE
[Sample]  Add contextual date times when the parameters are "start" and "end"

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3381]
In [this example](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.AI.AnomalyDetector/3.0.0-preview.7/api/Azure.AI.AnomalyDetector/Azure.AI.AnomalyDetector.AnomalyDetectorClient.html#Azure_AI_AnomalyDetector_AnomalyDetectorClient_DetectMultivariateBatchAnomaly_System_String_Azure_AI_AnomalyDetector_MultivariateBatchDetectionOptions_System_Threading_CancellationToken_) we use the same value for start and end time which works but is confusing from a sample point of view.

**Comment by chunyu3** [comment]
When there are 'start' and `end` time in the parameter list, append a hour later to `end` time.

**Comment by ArcturusZhang** [comment]
There is really no point to polish those "randomly generated sample values", therefore we are going to close this as a wont fix.
When we have the ability to generate samples from the example on the tsp file, we will get far better generated samples.
