### ISSUE TITLE
Exception for diagnostic scope is added.

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3388]
Because we are adding the scope in the protocol method if an exception happens in the convenience method no diagnostic scope is created.  In order to work with our test framework we either need to add [ForwardsClientCallsAttribute](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/ForwardsClientCallsAttribute.cs) or add the scope creation to the convenience method and conditionally add the scope in the protocol if it wasn't added in the convenience method.

**Comment by ArcturusZhang** [comment]
Hi @m-nash do we still need to do this? if so could you please provide more information on this?

**Comment by ArcturusZhang** [comment]
We did not get feedback about what this is for, therefore temporarily closed this. Feel free to reopen or open a new one if we still need to fix this in the future
