### ISSUE TITLE
Generate protocol only with required params when needed even if there is no convenience method

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3401]
In order to be able to add the convenience method later we need to generate the protocol method the same way regardless of whether its done at the same time or first by itself.

**Comment by JoshLove-msft** [comment]
This is a blocker for Event Grid V2 beta.

**Comment by pshao25** [comment]
@JoshLove-msft would you give me a link of the spec of Event Grid and which method you want this feature.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft would you give me a link of the spec of Event Grid and which method you want this feature.

Sure, https://github.com/Azure/azure-rest-api-specs/blob/feature/eventgrid/typespec/specification/eventgrid/Azure.Messaging.EventGrid/main.tsp

**Comment by chunyu3** [comment]
Protocol overload will eliminate client side defaults altogether.


A required default would become

```
public void Foo(int requiredParam)
{
  //document the default in the <param> tag but don't apply any default
}
```

An optional default would become

```
public void Foo(int? optionalParam)
{
  //document the default in the <param> tag
  //keep the value passed in even if its null
}
```

If the param can be left optional in the signature due to the presence of RequestContent then it would be the following

A required default would become (keep same ordering rules as before)
```
public void Foo(RequestContent content, int requiredParam)
{
  //document the default in the <param> tag but don't apply any default
}
```
An optional default would become
```
public void Foo(RequestContent content, int? optionalParam = default)
{
  //document the default in the <param> tag
  //keep the value passed in even if its null
}
```

**Comment by chunyu3** [comment]
File separate issue https://github.com/Azure/autorest.csharp/issues/3475 to track the eliminating client side defaults.
