### ISSUE TITLE
Road map of aligning the model generations between mgmt/HLC and DPG

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3405]
Current issues:

- https://github.com/Azure/autorest.csharp/issues/3230
- https://github.com/Azure/autorest.csharp/issues/3178
- https://github.com/Azure/autorest.csharp/issues/3406

- https://github.com/Azure/autorest.csharp/issues/3417

**Comment by ArcturusZhang** [comment]
To have the model factory (https://github.com/Azure/autorest.csharp/issues/2461), we need to resolve:
- https://github.com/Azure/autorest.csharp/issues/3178
To let the model factory include more models (https://github.com/Azure/autorest.csharp/issues/3181), we need to resolve:
- https://github.com/Azure/autorest.csharp/issues/3406

**Comment by chunyu3** [comment]
All the items Model Factory need is `GA-Required`

**Comment by ArcturusZhang** [comment]
Now our code generator has 3 layers:
1. Spec -> input models. We have two versions of this:
a. Swagger Spec -> CodeModel Schemas
b. TypeSpec -> Input types
2. Input models -> Output models. We have two versions of this:
a. CodeModel Schemas -> SchemaObjectType (or derived MgmtObjectType for mgmt plane)
b. Input types -> ModelTypeProvider (for DPG)
3. Output models -> Writers. We only have one version of this, it works for both `SchemaObjectType` and `ModelTypeProvider`.

The differences between the generated models in mgmt/HLC and DPG comes from the differences on those 3 layers. The biggest differences come from the second layer between `SchemaObjectType` and `ModelTypeProvider`. Minor differences come from the first layer.

It will be a big change if we use our `CodeModelConverter` to convert all the CodeModel Schemas to Input Types first and then we all use `ModelTypeProvider` to generate the models, because we will get differences both from the first layer and the second layer. It might be difficult to distinguish where an unexpected change comes from therefore it is harder to fix them.

I plan to fix this in two steps. We will first re-implement `SchemaObjectType` to make it mimic everything we did in `ModelTypeProvider`. For instance, `ModelTypeProvider` is getting its properties by fields from `ModelTypeProviderFields`, we will re-implement `SchemaObjectType` to get its properties by fields from `SchemaObjectTypeFields` as well, and the implementation of `SchemaObjectTypeFields` will be exactly the same to `ModelTypeProviderFields`, etc. This should be done in this PR: https://github.com/Azure/autorest.csharp/pull/3200

**Comment by ArcturusZhang** [comment]
FYI @m-nash

**Comment by ArcturusZhang** [comment]
Close in favor of https://github.com/Azure/autorest.csharp/issues/3801
