### ISSUE TITLE
Default the namespace config to the value of packageDir

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3408]
These two values will almost always be the same to eliminate verbosity we should default the namespace since packageDir will always be required.

https://github.com/Azure/azure-rest-api-specs/pull/23866/files#diff-b7e75220b6f450282cba2075cfb681c5c83cbb0090b9e5d3784ba768c55a09b5R24

**Comment by chunyu3** [comment]
Already implemented in https://github.com/Azure/azure-rest-api-specs/pull/23866
