### ISSUE TITLE
AZ0002 Analyzer

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3413]
Update Analyzer AZ0002 rule to add more check scenarios:

- [ ]  verify if the method has `cadncellationToken` or `requestContext`. if not, return failure

- [ ] Need to update the AZ0002 description to cover more scenarios

- [ ] method signature parameter and response consistence check:  (requestContent must combine with requestContext, response<BinaryData> must combine with requestContext

- void A (RequestConent content, CancellationToken callellationToken) - Invalid
- Response<BinaryData> A (CancellationToken callellationToken) - Invalid
- Response<ModelT> A (RequestContext requestContext) - Invalid
- and so on

- [ ] Sync and async method pair check: need to check each sync method coupled with an async method

**Comment by pshao25** [comment]
Duplicate with https://github.com/Azure/azure-sdk-tools/issues/6145
