### ISSUE TITLE
allow no typespec-csharp API version

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#3422]
Related to #3348, I am still unable to generate code with "@azure-tools/typespec-csharp": "0.2.0-beta.20230518.1" if there a version is not set. It should be possible to skip versioning. The error is:

```
PS C:\Users\cataggar\ms\avs\src\conveyor\ConsumptionWorker\client> tsp compile .
TypeSpec compiler v0.44.0

{"level":"info","message":"routes:1"}
{"level":"info","message":"load operation: pet, path:/pet "}
error @azure-tools/typespec-csharp/No-APIVersion: No APIVersion Provider for service Pet
```

Using this main.tsp:
```
import "@typespec/http";
// import "@typespec/versioning";

using TypeSpec.Http;
// using TypeSpec.Versioning;

@service({
  title: "Pet API",
})
// @versioned(ServiceApiVersions)
namespace Pet;

// enum ServiceApiVersions {
//   v2023_05: "2023-05",
// }

@discriminator("kind")
model Pet {
  // kind: string;
}

model Cat extends Pet {
  kind: "cat";
  meow: boolean;
}

model Dog extends Pet {
  kind: "dog";
  bark: boolean;
}

@route("/pet")
@get
op pet(): Pet;
```

**Comment by chunyu3** [comment]
Hello @cataggar  api-version is required now. Could you help to provide some context about  what scenario do we need a SDK without an api-version? Thanks

**Comment by cataggar** [comment]
TypeSpec supports defining unversioned APIs https://microsoft.github.io/typespec/standard-library/versioning/overview . Why limit it? Seems like an unnecessary check.

**Comment by chunyu3** [comment]
Hello @cataggar Yes, TypeSpec is not required apiversion, but azure SDK need api-version. Each rest api call will append the api-version.

.NET codegen will not generate SDK when there is no api-version. Same as Java.

Do you have any real scenario which has no api-version? If so, would you please provide this context? I will discuss with our archboard about this.

**Comment by cataggar** [comment]
Is typespec-csharp limited to TypeSpec specifications for Azure? If yes, go ahead and close this.

**Comment by chunyu3** [comment]
> Is typespec-csharp limited to TypeSpec specifications for Azure? If yes, go ahead and close this.

Yes. ApiVersion is needed. so close this.
