### ISSUE TITLE
x-ms-client-default value missing after implementing overloads

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3424]
After this change https://github.com/Azure/autorest.csharp/pull/3412, [the required parameter with x-ms-client-default](https://github.com/Azure/autorest.csharp/blob/f854cb109aeea2fa844d8b0b32c34e1d40b1847c/test/TestProjects/Parameters-LowLevel/src/Parameters.json#L33-L40) will lose its value.

Before:
```C#
public virtual async Task<Response> NoRequestBodyResponseBodyAsync(int id, int? top = null, int skip = 12, string status = "start", RequestContext context = null);
```

After:
```C#
public virtual async Task<Response> NoRequestBodyResponseBodyAsync(int id, int? top, int skip, string status, RequestContext context);
```

**Comment by m-nash** [comment]
We definitely need to still honor the default values in the body implementation where applicable.  We should also add the default description in the `<param>` tag if the param is required but has a default value.

**Comment by pshao25** [comment]
To simplify the discussion, let's use this example with one optional parameter and one required parameter. This is the current behavior:
```C#
public virtual async Response Method(int? optional = 7, int required = 8, RequestContext context = null);

internal HttpMessage CreateMethodRequest(int? optional, int required, RequestContext context)
{
    if (optional != null)
    {
        uri.AppendQuery("optional", optional.Value, true);
    }
    uri.AppendQuery("required", required, true);
}
```
We could see that null check is used to decide whether the parameter should be on the wire.

After change https://github.com/Azure/autorest.csharp/pull/3412, current suggestion is:
```C#
public virtual async Response Method(int? optional, int? required, RequestContext context);

internal HttpMessage CreateMethodRequest(int? optional, int? required, RequestContext context)
{
    if (optional != null)
    {
        uri.AppendQuery("optional", optional.Value, true);
    }
    uri.AppendQuery("required", required?.Value ?? 8, true); // If required is null, then we give it 8
}
```

**Comment by m-nash** [comment]
To directly answer the question no we should not default the optional parameter to 7 when we receive null.

We need to make sure we don't confuse `nullable` from a spec perspective and `nullable` from a type perspective.  Similarly `optional` from a spec perspective is different from `nullable` from a type perspective.

Think of a customer passing in `null` as them saying `I don't care` or `I don't want a value`.  We should honor this except in the cases where the service requires a default value.  In that case even if the customer `doesn't care` the service will use the default value.

**Comment by pshao25** [comment]
Fixed in https://github.com/Azure/autorest.csharp/pull/3479
