### ISSUE TITLE
Add a option to enable options bag for some methods

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3428]
In swagger we won't have the client.tsp capabilities and since we don't want an automatic decision to convert to options bag based on threshold, so we will add a configuration to configure which methods will apply options bag.

**Comment by archerzz** [comment]
More details:
- This is only for swagger-based definition, so we should provide a property in `autorest.md`
- This is only for protocol methods.

**Comment by archerzz** [comment]
## Design of the property

`group-parameters` which will accept a single or an array of operation IDs. In the generated methods of each ID, the parameters will be grouped except for `RequestContext`.

### Example

```markdown
group-parameters:
- ResourceGroups_Get
- Roles_Update
```

**Comment by chunyu3** [comment]
Protocol method should has the consistence signature with the operation definition. So don't need to add options bag for protocol method. @m-nash  
close this.
