### ISSUE TITLE
feat(typespec): upgrade to typespec 0.45.0

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#3477]
## Description

See release notes:
- TypeSpec Core release notes: [June 2023 | TypeSpec (microsoft.github.io)](https://microsoft.github.io/typespec/release-notes/release-2023-06-06)
- TypeSpec Azure release notes: [June 2023 | TypeSpec Azure](https://azure.github.io/typespec-azure/docs/release-notes/release-2023-06-06)

This is a blocker for some of our work items, like #2988

**Comment by lirenhe** [comment]
Do we plan to move to PeerDependency?   From Python experience, this would solve a lot of effort for version upgrade.  @chunyu3
