### ISSUE TITLE
The Generated code has ambiguity with the customized code 

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3489]
In [synaps sdk](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/synapse/Azure.Analytics.Synapse.AccessContro) , the generated code has ambiguity with the customized code https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.AccessControl/src/RoleAssignmentsClient.cs#L17 and https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.AccessControl/src/Generated/RoleAssignmentsClient.cs#L329

We shall include the customized code and resolve ambiguity when generate code.

**Comment by lirenhe** [comment]
@pshao25, as we generate HLC for all synapse libraries instead of using DPG, do you know why Synapse.AccessControl contains the public protocol methods?

**Comment by pshao25** [comment]
@lirenhe AccessControl is DPG.

**Comment by pshao25** [comment]
We removed customization code in https://github.com/Azure/azure-sdk-for-net/pull/31126. So close it.
