### ISSUE TITLE
Incorrect key for apiversion

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3513]
Actual:
https://github.com/Azure/autorest.csharp/blob/77a8ee63ad51e7cd373eee1292da67fb1eac530d/test/TestProjects/MixAPIVersion-TypeSpec/src/Generated/MixApiVersionClient.cs#L337

Expected:
`uri.AppendQuery("api-version", "2022-07-09", true);`

**Comment by chunyu3** [comment]
In the typespec, the query parameter is defined as `@query apiVersion: "2022-07-09"`, the query name is `apiVersion`, so codegen generate according to the spec definition. It is by-design.

If it want to change the query name, it need to specify in the `@query` decorator as `@query("api-version)"`.
