### ISSUE TITLE
CodeGen doesn't support common types in v4 & v5

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#3537]
For the new common types [v4](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json) and [v5](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json), some properties were specified the format, which caused the CodeGen can't indicate these types as common types.

**Comment by ArthurMa1978** [comment]
Here is a sample https://github.com/Azure/azure-sdk-for-net/pull/37213 which have to use directive to mitigate

**Comment by live1206** [comment]
Done
