### ISSUE TITLE
DPG clients for services which utilize http redirects require use of new Azure.Core options

### ISSUE THREAD

**Issue by christothes** [Azure/autorest.csharp#3550]
As of Azure.Core version 1.33.0, http client redirects are disabled by default. For DPG clients that require redirects for their service, generated code must enable redirects explicitly.

This can be done 2 ways:

## Enable redirects globally
If a client requires redirects to be enabled globally for the pipeline, the `HttpPipelineTransportOptions.IsClientRedirectEnabled` property must be set to true on the transport options passed to `HttpPipelineBuilder.Build`.

## Enable redirects only for specific operations
Clients that require redirects to be enabled only for certain operations can do so per HttpMessage by calling the `SetAllowAutoRedirect` static method on `RedirectPolicy`:

https://github.com/Azure/azure-sdk-for-net/blob/5908df790e4e2efde91619bc9e5c873576f65a9a/sdk/core/Azure.Core/src/Pipeline/RedirectPolicy.cs#L37

**Comment by archerzz** [comment]
After discussion, we think we should **enable redirects per operation** so as to follow minimal privilege principle. We will:
- add an option in `autorest.md` to accept a list of operations which should enable redirect
- enable redirects for operations we find. There is no inventory about which rest API returns HTTP redirect. We have to search the specs/codes/test recordings to find them as many as possible. There could be missing pieces which should be easy to fix.

**Comment by archerzz** [comment]
For typespec, if no service returns HTTP redirects, we can implement the option later. Ideally it should be a decorator in `client.tsp` and supported in TCGC, but that requires time to implement. A work-around is providing such option in `tspConfig.yml`. If we could avoid temporary solution, decorator is the way to go.
