### ISSUE TITLE
Burkor feature request

### ISSUE THREAD

**Issue by Aparnex** [Azure/autorest.csharp#3552]
**Describe the issue or request**
Please describe the issue or feature request.

**Describe your ideas for solutions**
Please describe how you think a change or changes might work. Consider
how these changes might work for multiple services.

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by lirenhe** [comment]
@Aparnex,  could you provide more information about this feature request?  Seems all the above description are from the issue template.

**Comment by Aparnex** [comment]
Ok no problem I will work on it

**Comment by Aparnex** [comment]
I am sorry for for my let response
The problem is that I lost my mom 
Pls I need more time

**Comment by Aparnex** [comment]
Pls I need more time,I lost my mom please add more time for me
  
  
  
  
  
  
  

  
  
>

**Comment by Aparnex** [comment]
Pls add more time for me   
  
The problem is that I lost my mom
  
  
  
  
  
  
  

  
  
>

**Comment by Aparnex** [comment]
Please I need mor time because I lost my mom
  
  
  
  
  
  
  

  
  
>
