### ISSUE TITLE
Ability to generate a client with redirects enabled

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#3554]
As of https://github.com/Azure/azure-sdk-for-net/pull/34645, redirects are disabled by default in Azure Core. There are some TestServer tests that needed to be ignored in https://github.com/Azure/autorest.csharp/pull/3553/ in order to upgrade to Azure.Core 1.33.0. Apart from evaluating whether the tests should be removed or updated in some way, we should evaluate whether we need the ability to generate a protocol client with redirects enabled. Currently, the only libraries that need redirects are enabling it through the customization layer.

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3550

**Comment by archerzz** [comment]
It's a duplicate of #3550 and it's fixed by #3570
