### ISSUE TITLE
Make generator and analyzer consistent on protocol method

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3571]
**Spec (and swagger as well):** 

The point is it doesn't have return model and all the parameters are not models.
```
op delete(string id): void;
```

**Current behavior of generator:**

We don't generate convenience method even user set `@convenientAPI`. Reason: imagine what the convenience method looks like:
```C#
public virtual Response Delete(string id, CancellationToken cancellationToken = default) {}
public virtual Response Delete(string id, RequestContext context = null) {}
```
There is no benefit we could gain from the convenience method, so generator will not generate the convenience. As a result, the protocol method will keep the `RequestContext` optional since there will be no ambiguity.
```C#
public virtual Response Delete(string id, RequestContext context = null) {}
```

**Current behavior of analyzer:**

This method fails because analyzer thinks the `RequestContext` should be required. It conflicts with generator's behavior.

The challenge here is whether generator generates convenience method depends on whether there is a return type, but analyzer doesn't have this information.

**Solutions:**

This blocks us from updating to the latest analyzer. So I would suggest we remove all the check "if there is no RequestContent, then the RequestContext should be required" from analyzer, i.e. remove all these [line](https://github.com/Azure/azure-sdk-tools/blob/c6a88f70973aff7b0df2c88ea60ccd1f055e710a/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs#L187-L194), because it is not doable.

**Comment by lirenhe** [comment]
cc @m-nash

**Comment by pshao25** [comment]
If there is no convenience method, we will not check such protocol methods. But if there is a corresponding convenience method, we will make sure the RequestContext is required.

**Comment by m-nash** [comment]
@pshao25 not sure I follow that last comment.  We should always check that the protocol method is written correct such that we can have an overload with the convenience method at a later time.

**Comment by pshao25** [comment]
@m-nash we already discussed in the sync meeting that if there is no convenience method there is no way we could know whether the `context` should be required. And you decided to only check `context` when there is a convenience method.

**Comment by chunyu3** [comment]
Already implemented. close it.
