### ISSUE TITLE
Optimize package installation

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3575]
**Performance:**
Look at this performance data to have an intuition of how `npm install` costs during `dotnet build /t:GenerateCode`. Take `dotnet build /t:GenerateCode .\sdk\anomalydetector\Azure.AI.AnomalyDetector\src\` as an example:
- Total duration: 1.67min
- `npm install`: 1.11min
- emitter (dotnet generator inclusive): 14.59sec

`npm install` takes 1.11 out of 1.67 min, and I haven't included the spec copy process from sparse location to project location.

**Problem:**
Currently `npm install` happens every time when user builds SDK and every time pipeline tries to regen SDK for every project. There is a lot of duplicate installation.

**Solution:**
The solution in this [PR](https://github.com/Azure/azure-sdk-tools/pull/5690) is moving `npm install` from each project to the root folder so that 
- For pipeline, it only needs to happen once.
- For end user, it only installs when emitter upgrades.

**Remaining issue:**
In pipeline, we run `dotnet build /t:GenerateCode` in parallel. Therefore, there is a chance `npm install` is called from different processes simultaneously. 

Solutions to this remaining issue are:
- Add a file lock to protect `npm install`. But this solution is not recommended by engineer team.
- Add a parameter like `dotnet build /t:GenerateCode /p:InstallDependency`. In pipeline, we install dependency at the begging and set `InstallDependency` false. In user case, `InstallDependency` is default to true.

**Comment by lirenhe** [comment]
@pshao25, did you see any pipeline failure as a result of this remaining issue?
I am trying to understand the importance of this task.

**Comment by pshao25** [comment]
> @pshao25, did you see any pipeline failure as a result of this remaining issue? I am trying to understand the importance of this task.

This issue happens in multi-process scenario. So it is a random issue. But considering such long `npm install` takes, it is very likely to happen.

We currently don't have any pipeline fails because we haven't got https://github.com/Azure/azure-sdk-tools/pull/5690 merged.

It takes more than 1 min to install! Our generator only takes 15 secs from end to end! Why not important?
