### ISSUE TITLE
Ambiguous call under spread scenarios

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3585]
**Typespec:**
```
alias ThingAlias = {
  @doc("age of the Thing")
  age?: int32;
  @doc("name of the Thing")
  name?: string;
};
op spreadAlias( ...ThingAlias ): void;
```

**Actual:**
```C#
public virtual async Task<Response> SpreadAliasAsync(int? age = null, string name = null, CancellationToken cancellationToken = default);
public virtual async Task<Response> SpreadAliasAsync(RequestContent content, RequestContext context = null)
{
    Argument.AssertNotNull(content, nameof(content));
}
```
This call is an ambiguity: `SpreadAliasAsync(null)`. This will not happen to `string`, see details in https://github.com/Azure/autorest.csharp/issues/3587.

**Expected:**
In the normal case like 
```C#
public virtual async Task<Response> SpreadAliasAsync(Model model, CancellationToken cancellationToken = default)
{
    Argument.AssertNotNull(model, nameof(model));
}
public virtual async Task<Response> SpreadAliasAsync(RequestContent content, RequestContext context = null)
{
    Argument.AssertNotNull(content, nameof(content));
}
```
Even there is an ambiguous call `SpreadAliasAsync(null)`, we still leave `RequestContext` optional, because `SpreadAliasAsync(null)` makes no sense.

What makes this scenario special from others is `SpreadAliasAsync(null)` makes sense to convenience method. So I think the protocol method should change when the first parameter in convenience method is not string.

**Solution:**
```C#
public virtual async Task<Response> SpreadAliasAsync(RequestContent content, RequestContext context)
{
    Argument.AssertNotNull(content, nameof(content));
}
```

**Update:**

According to https://github.com/Azure/autorest.csharp/issues/3587#issuecomment-1639102482, we don't take `SpreadAliasAsync(null)` into consideration, so leave `RequestContext context = null`.

**Comment by AlexanderSher** [comment]
> This will not happen to string, see details in https://github.com/Azure/autorest.csharp/issues/3587.

`RequestContent` has an implicit cast from `string`, but no implicit cast to `string`, so during cast resolution `string` parameter wins.

**Comment by pshao25** [comment]
In the update section of description, this is by design.
