### ISSUE TITLE
No ambiguity exists when a type has an implicit conversion to RequestContent

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3587]
**Background:**

We will make protocol method an overload (make the `RequestContext` required) if the input body is optional to avoid ambiguous call. For example:
```
op get(@body optional?: Model) : void;
```
We will generate
```C#
public virtual Response Get(Model optional = null, CancellationToken cancellationToken = default);
public virtual Response Get(RequestContent content, RequestContext context);
```
The `RequestContext` is required otherwise there will be ambiguous call `Get(null)`.

**Problem:**

We are introducing such kind of implicit conversion from `Model` to `RequestContent`:
```C#
public static implicit operator RequestContent(Model model)
{
    // Some logic
}
```

After this change, below code has no ambiguity (attention: `RequestContext` is back to optional). We could call `Get(null)` and it goes to convenience method.
```C#
public virtual Response Get(Model optional = null, CancellationToken cancellationToken = default);
public virtual Response Get(RequestContent content, RequestContext context = null);
```

From [this document](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12645-better-conversion-from-expression), 

> Given an implicit conversion C₁ that converts from an expression E to a type T₁, and an implicit conversion C₂ that converts from an expression E to a type T₂, C₁ is a better conversion than C₂ if one of the following holds:
> E exactly matches both or neither of T₁ and T₂, and T₁ is a better conversion target than T₂ ([§12.6.4.7](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12647-better-conversion-target))

and [this document](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12647-better-conversion-target),

> Given two types T₁ and T₂, T₁ is a better conversion target than T₂ if one of the following holds:
> An implicit conversion from T₁ to T₂ exists and no implicit conversion from T₂ to T₁ exists

It seems to be expected. Try code [here](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMA6AFQFMAPYPAKQGcB7KAbgFgAoVAJhxY23wIAswRAIZwAllADmTZlwDM2NpgDKNALZEAwgBshVKiwDeLTCezz2mALI04RLcdNHmpl2Z4A2TKNUAHLaIBjUWBMGh8iMCFgGjBMACUiAEcIIipgDTpgIihgAAprWy1MAMzs4ABKB1dMJ2rq1AB2TCgiAHd4pJS0jJyy3PLpOswAXyqRsbHUc0UE5NT00pyasZcpjy9ffyCQsIiomI657sW83CwS3pzyzABeAD5mtsOuhcu8gbHR51NJ6ef5npZMg1cbfEy/bAAFkwAHEiHkCnYAPyYVQ2Oy3ZoQLRaGCYDRCKABOw6YCiOgEGgAa2yxUJxJxUXJUEpNKgmNsADMhNiKpgxrU6rgAJy5ABEQjFHzBoJcENQ0LheVmL0BZRRFyySxuWJxeJVANKZA1RpCOqg2K01wFQxWphF4oARlLBqYvnKZew2AK7SYWu0VOptLoqP08ErchacdKXF8viwgA==).

Pay attention to that we already have implicit conversion from `string/BinaryData/DynamicData` to `RequestContent`. So same logic applies to these types.

**Action:**

We might revert the previous logic because we don't need to generate overload for an optional body after that change.

**Comment by pshao25** [comment]
I think we should be clear about the principles of when to make a protocol method overload. Should we keep `RequestContext context = null` as possible as we can (in this case we should revert previous logic), or as long as there is no ambiguous call we could do either way (in this case we could keep current behavior).

> whether this is obvious from end users' prospective.

Of course, we change the signature.

> To avoid the misuse of Get(null), is it better to keep them separate?

Why would Get(null) a misuse? I think it totally makes sense.

**Comment by lirenhe** [comment]
> I think we should be clear about the principles of when to make a protocol method overload. Should we keep `RequestContext context = null` as possible as we can (in this case we should revert previous logic), or as long as there is no ambiguous call we could do either way (in this case we could keep current behavior).
> 
> > whether this is obvious from end users' prospective.
> 
> Of course, we change the signature.
> 
> > To avoid the misuse of Get(null), is it better to keep them separate?
> 
> Why would Get(null) a misuse? I think it totally makes sense.

From our guideline:


Approachable

-   We are experts in the supported technologies so our customers, the developers, don’t have to be.

**Comment by pshao25** [comment]
Test: If only the required parameters are set, leave optional parameters empty.
