### ISSUE TITLE
RequestContext changed from optional to required

### ISSUE THREAD

**Issue by MattCosturos** [Azure/autorest.csharp#3589]
**Describe the bug**
As of version @autorest/csharp@3.0.0-beta.20230706.2 the `RequestContext` parameter was changed from optional to required.

This means all of our code using the generated client is now broken.

Generation command
`autorest --version:3.9.3 --input-file=$1 --csharp --output-folder=$2 --use=@autorest/csharp@3.0.0-beta.20230706.2 --verbose`

Generated a method signuature
`public virtual async Task<Response> CustomersIdAsync(Guid id, RequestContext context)`

Version 0706.1, and earlier generate the following method signature
`public virtual async Task<Response> CustomersIdAsync(Guid id, RequestContext context = null)`       

**Expected behavior**
Is this breaking change expected?

**Comment by pshao25** [comment]
This is expected. I believe you have another method generated as `public virtual async Task<Response> CustomersIdAsync(Guid id, CancellationToken cancellationToken = default);` If we don't make RequestContext required, compilation will fail when call CustomersIdAsync(<some guid>);

**Comment by MattCosturos** [comment]
What you are saying makes sense, however none of the generated methods in our clients accept a cancellationToken.
We only end up with the single `public virtual async Task<Response> CustomersIdAsync(Guid id, RequestContext context)`

Trying this
`autorest --version:3.9.6 --input-file=https://mc-factory-dev.eastus2.cloudapp.azure.com/ea/api/swagger/v1/swagger.json --csharp --output-folder=generated --verbose`

results in a single method for each endpoint, none of which accept a cancellationToken.

**Comment by pshao25** [comment]
Yeah, you don't have a method ending with CancellationToken because you have a swagger spec. If you try out typespec spec, then there will be that method.

As long as there is a possibility that one day you add that convenience method, we will make RequestContext required even now you don't have it.

**Comment by MattCosturos** [comment]
Thanks for the information.
Last question then, is there a change-log or release notes or any type of discussion anywhere regarding auto-rest changes?

I will need to lock into specific versions from now on, to avoid sudden breaking changes.

**Comment by pshao25** [comment]
Unfortunately not. We are in beta version which is released several times per day. We are a plugin of autorest so even we have a changelog it will not show up in the autorest repo. We would consider add changelog to autorest.csharp repo after GA or maybe some important beta milestone.

**Comment by KrzysztofCwalina** [comment]
> This is expected. 

@pshao25, is this really expected? The return type of the convenience method (the one taking `CancellationToken`) has changed from `Response` to `Response<T>`. This means it's a source breaking change. 

For context, this is an example of an method and its changes:

```csharp
// V1
public virtual Response GetDevice(string deviceId, RequestContext context = null);

V2
public virtual Response GetDevice(string deviceId, RequestContext context);
public virtual Response<Device> GetDevice(string deviceId, CancellationToken cancellationToken = default);
```

I might be misremembering the rules we agreed on, but my mental model is that we wanted to generate required RequestContext parameter in V1 if the method does not have an input model (RequestContent)

cc: @annelo-msft, @m-nash

**Comment by pshao25** [comment]
@KrzysztofCwalina Your memory is correct: we want to generate required `RequestContext` in v1 (swagger). It is optional now because it is GAed so we added a flag `keep-non-overloadable-protocol-signature`. In v2 (TypeSpec) customer could still use this flag to make `RequestContext` optional.  I apologize I didn't realize this library is GAed whan I said "it is expected".

For the document, we have this [PR](https://github.com/Azure/azure-sdk-for-net/pull/37795) on going.
