### ISSUE TITLE
[Feature] Overload function to allow method signature change for Model Factory - parameter

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#3596]
Swagger may introduce non-breaking changes by adding / removing optional parameters, which currently is breaking changes for .Net SDK.
CodeGen should generate overload function to make it non-breaking change automatically instead of handwriting manual code now.

**Comment by ArcturusZhang** [comment]
Reopen since last time the PR resolved this has been reverted because of some accidents.
