### ISSUE TITLE
Handle Anonymous models

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3623]
Initial problem comes from https://github.com/Azure/autorest.csharp/issues/3592#issuecomment-1649195720. User wants to define invalid spec like 
```
op postClusterScale(): {
  @body body: ClusterScale;
};
```
Two errors here:
1. The return type is an anonymous type.
2. There is a body decorator in return type. Cannot believe typespec compiler even allows it pass!

We should properly handle the anonymous type.

**Scenario 1: return type is an anonymous body type**
```
op postClusterScale(): {
  @body property: ClusterScale;
};
```
Actual: Successfully generate the model `ClusterScale` with **internal** constructor. Interesting...
Expected.

**Scenario 2: return type is an anonymous normal type**
```
op postClusterScale(): {
  property: ClusterScale;
};
```
Actual: models with empty name
![image](https://github.com/Azure/autorest.csharp/assets/97225342/9df6440a-0e7e-48c2-9ad1-c55bd6a8c1e0)
Expected:
1. Fail because it is anonymous.
**2. Make it `low confident`.** issue to tyspec

**Scenario 3: return type is an empty return type**
```
op postClusterScale(): {}
```
Actual: models with empty name
![image](https://github.com/Azure/autorest.csharp/assets/97225342/9df6440a-0e7e-48c2-9ad1-c55bd6a8c1e0)
Expected:
Regard `{}` as a `object` => Record<unknown>.

**Scenario 4: Input type is an anonymous type**
```
model Input {
  @path
  id: string;
  detail: {
    info: string;
    type: string;
  }
};
op operation(...Input): void;
```
Actual: models with empty name
![image](https://github.com/Azure/autorest.csharp/assets/97225342/97bc3532-27be-492c-a7d3-4cae55ed8aff)
Expected: Fail or make it `low confident`.

**Scenario 5: Input type is an alias with anonymous type**
```
alias Input = {
  @path
  id: string;
  @body
  detail: {
    info: string;
    type: string;
  }
};
op operation(...Input): void;
```
Actual: models with empty name
![image](https://github.com/Azure/autorest.csharp/assets/97225342/97bc3532-27be-492c-a7d3-4cae55ed8aff)
Expected: It should be the same as below. (But we cannot generate below spec, which means we have another bug with spread scenario.)
```
alias DetailAlias = {
    info: string;
    type: string;
};
alias Input = {
  @path
  id: string;
  @body
  detail: DetailAlias;
};
op operation(...Input): void;
```
```C#
Response Operation(string id, string info, string type, CancellationToken cancellationToken);
Response Operation(string id, RequestContent content, CancellationToken cancellationToken);
```

**Comment by lirenhe** [comment]
@pshao25, could you provide more information about this case like the input typespec, the expected behavior and the actual result.
What is the anonymous model in this case?

**Comment by pshao25** [comment]
> @pshao25, could you provide more information about this case like the input typespec, the expected behavior and the actual result. What is the anonymous model in this case?

Updated the description

**Comment by ArcturusZhang** [comment]
Current solution is that whenever we have an anonymous model, we will remove the corresponding convenience method (by making it low confident).
