### ISSUE TITLE
Sample generator should not throw exception when hit example errors

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#3630]
For example, a property is required but not given a value in the example, the sample generator can handle this by providing a default value and adding a comment that says this property needs a value, and mentions the example in swagger should be fixed.

**Comment by ArcturusZhang** [comment]
FYI the related implementation could be found here: https://github.com/Azure/autorest.csharp/blob/0220ddc134d4e799b838c7e9e6d8783aaf45abd8/src/AutoRest.CSharp/MgmtTest/Models/MockTestCase.cs#L105
