### ISSUE TITLE
list operations named as Get methods

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#3638]
I'm switching over an internal API from Swagger to TypeSpec in this [internal PR](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/8554320). The DPG code generator is unfortunately naming of the `list` operations as `Get` functions. The previous generator did not do this renaming. I don't think it should be done.

Previously the `listPods` operation would result in a `ListPodsAsync`  method. Now it is `GetPodsAsync`. Please revert this renaming or allow a way to disable it.

**Comment by archerzz** [comment]
I also met this problem in the `Batch` typespec transformation. This looks like a regression when we refactoring codes?

**Comment by archerzz** [comment]
@cataggar This is by design. Was the SDK officially released before?

**Comment by cataggar** [comment]
It is an internal client. I don't understand that design decision. Is this just C# or any AutoRest client?

**Comment by cataggar** [comment]
@archerzz, can you point me to the design on this. Developers are tripping up on this change.

**Comment by m-nash** [comment]
Using Get[Noun]s is the idiomatic way to name list methods.  For reference the guideline can be found here https://azure.github.io/azure-sdk/general_design.html#general-client-standardize-verbs.

**Comment by cataggar** [comment]
Thanks for the link! I do not like the choice, but will live with it.

![image](https://github.com/Azure/autorest.csharp/assets/87583576/b456817a-d4a1-4db9-9315-580d61f17d27)
