### ISSUE TITLE
[sample] pick up custom model constructor

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#3641]
## Description

Sometimes, service team will write custom model constructors and make existing generated constructors internal or even deleted. Our current sample generation logic will still pick up the constructors being generated and thus could:
- cause compilation error if the signature not compatible
- not the best option for samples

We need to figure out a way to adopt custom constructor in the sample generation.

One example is `OpenAI`. Its `ChatMessage` used to have a constructor not having `Content` which used to be optional. That constructor was replaced by a custom constructor which had `Content` as mandatory parameter.

**Comment by chunyu3** [comment]
duplicated
