### ISSUE TITLE
Provide more information in the API doc for operations

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#3650]
- [x]  Add verbose information.
- [x]  Add ResourceType information, this will help on `SetApiVersion`, here is a [sample](https://github.com/Azure/azure-sdk-for-net/issues/35152).
- [x]  Update SetApiVersion comment about how to use these added information

**Comment by RodgeFu** [comment]
Reopen because we also need to update Set-ApiVersion's comments to let user know how to figure out the ResourceType from the Operation's tooltip after the Resource information are available in most major SDK.
