### ISSUE TITLE
First letter of model name should be capitalized when spec is lower case

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3669]
Spec:
```
model thisIsAModel {}
```
Actual:
```C#
public partial class thisIsAModel {}
```
Expected:
```C#
public partial class ThisIsAModel {}
```
We should change `t` to `T`.

**Comment by lirenhe** [comment]
What is the existing practice when facing this naming?  Do we use customization to modify the name or leverage codegen to auto handle it?

**Comment by pshao25** [comment]
I'm not sure if customization could handle this. Maybe it is case insensitive. We should fix in codegen side I think.

**Comment by lirenhe** [comment]
TypeSpec already has the rule of 'The names of Model types must use PascalCase' but it reports warning only.   https://github.com/Azure/typespec-azure/blob/420260abedbb248c1a1fb74d27ccdd29651faf73/packages/typespec-azure-core/test/rules/casing.test.ts#L45

If this is an invalid case, can we update or create a linter rule in TCGC to report error for this?

**Comment by chunyu3** [comment]
Codegen may need to generate according to the spec.
