### ISSUE TITLE
[.NET]: Codebase Unification for DPG and mgmt. SDK

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#3689]
**Describe the issue or request**
Follow https://github.com/Azure/typespec-azure/issues/3424

**Describe your ideas for solutions**

This is the step to ensure we could use typespec codeGen to also generate typespecs from mgmt. SDK
This includes:
- Unified the behavior of the generated SDK for models, operation, etc.
- Unified the CodeGen for APIs & models generation.

**Comment by ArthurMa1978** [comment]
dup with:
https://github.com/Azure/autorest.csharp/issues/3801
https://github.com/Azure/autorest.csharp/issues/3802
https://github.com/Azure/autorest.csharp/issues/3803
https://github.com/Azure/autorest.csharp/issues/3804
https://github.com/Azure/autorest.csharp/issues/3805
