### ISSUE TITLE
Our generator creates client libraries which violate AZC0006 and AZC0007

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3706]
We should update our generator so that these two analyzer rules are not violated for azure sdks

**Comment by chunyu3** [comment]
Hello @m-nash  Does this occur in MPG, DPG or both?

**Comment by pshao25** [comment]
**Current HLC behavior:**
One constructor with optional `options` like
```C#
public AClient(Uri endpoint, AClientOptions options = null) {}
```

**Current DPG behavior:**
Two constructors, one with all parameters and the other with only required parameters. All the parameters will be changed to required.
```C#
public AClient(Uri endpoint): this(endpoint, new AClientOptions()){}
public AClient(Uri endpoint, AClientOptions options){}
```
When there is only one optional parameter (e.g. this case only have one optional `AClientOptions`), this scenario actually not violates analyzer.

However, when there are more than one optional parameter, it violates analyzer, like
```C#
public AClient(AzureKeyCredential credential): this(credential, new Uri("http://localhost:3000"), new AClientOptions()){}
public AClient(AzureKeyCredential credential, Uri endpoint, AClientOptions options){}
```

**Comment by pshao25** [comment]
So, we will put all the optional parameters except endpoint into options 

1. `public AClient(string required, string optional ="optional", AClientOptions options = null)` becomes
```C#
public AClient(string required): this(required, new AClientOptions()){}
public AClient(string required, AClientOptions options)
{
  _optional = options.Optional; // Client parameter
}

public partial class ArrayClientOptions : ClientOptions
{
    internal string Optional { get;}

    /// <summary> Initializes new instance of ArrayClientOptions. </summary>
    public ArrayClientOptions(ServiceVersion version = LatestVersion, string optional = "optional")
    {
        Version = version switch
        {
            ServiceVersion.V1_0_0 => "1.0.0",
            _ => throw new NotSupportedException()
        };

        Optional = optional;
    }
}
```

2. `public AClient(string required, Uri endpoint = new Uri("http://localhost:3000"), AClientOptions options = null)` becomes
```C#
public AClient(string required): this(new Uri("http://localhost:3000/"), required, new AClientOptions()){}
public AClient(Uri endpoint, string required, AClientOptions options){}
```

**Comment by tg-msft** [comment]
I'd clarify

> So, we will put all the optional parameters except endpoint into options

slightly to 

- We'll default to adding optional parameters in `ClientOptions`
- Some special optional parameters (just `endpoint` for now) will be included as .ctor params by default
- We'll occasionally move other optional parameters to .ctor params manually on a case by case basis

**Comment by pshao25** [comment]
As suggested in this PR https://github.com/Azure/azure-sdk-tools/pull/8478, customers should suppress themselves if they have an optional endpoint. Therefore, all the pieces of this issue have been done.
