### ISSUE TITLE
Investigate why AD0001 fails for ConvenienceUpdate-TypeSpec

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3708]
Currently this following projects fail with the following error if we don't suppress AD0001.

```
CSC : error AD0001: Analyzer 'Azure.ClientSdk.Analyzers.ClientConstructorAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains more than one matching element'. [...\autorest.csharp\test\TestProjects\ConvenienceUpdate-TypeSpec\src\ConvenienceInCadl.csproj::TargetFramework=netstandard2.0]
```

- `ConvenienceUpdate-TypeSpec`
- `Parameter-TypeSpec`
- `Customization-TypeSpec`

**Comment by pshao25** [comment]
We generate static properties in clients, so there will be a static constructor without any parameters implicitly added.
