### ISSUE TITLE
Consolidate generation of DPG and MPG models

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#3770]
After https://github.com/Azure/autorest.csharp/issues/3769, do similar thing for MPG models, including MPG-specific logic that modifies schemas before they are used for model generation

**Comment by ArcturusZhang** [comment]
MPG differences:
1. Transformations with schemas
2. Replacement after the creation of type provider

**Comment by ArthurMa1978** [comment]
Following works are tracked by https://github.com/Azure/autorest.csharp/issues/4415
