### ISSUE TITLE
SDK for service with @useAuth(ApiKeyAuth<ApiKeyLocation.header, "Ocp-Apim-Subscription-Key">) doesn't compile.

### ISSUE THREAD

**Issue by rhurey** [Azure/autorest.csharp#3773]
**Describe the issue or request**
Have typespec using

``` TypeScript
@useAuth(ApiKeyAuth<ApiKeyLocation.header, "Ocp-Apim-Subscription-Key">)
@useAuth(BearerAuth)
@server(
    "{endpoint}/computervision",
    "Analyze an image to generate a description of its content.",
    {
      @doc("""
  Supported Cognitive Services endpoints (protocol and hostname, for example:
  https://<resource-name>.cognitiveservices.azure.com).
  """)
      endpoint: url,
    }
  )
```

And the generated SDK for it doesn't build because it tries to use an AzureKeyCredentialPolicy that is marked internal:
``` C#
_pipeline = HttpPipelineBuilder.Build(options, Array.Empty<HttpPipelinePolicy>(), new HttpPipelinePolicy[] { new AzureKeyCredentialPolicy(_keyCredential, AuthorizationHeader) }, new ResponseClassifier());
```
            
**Describe your ideas for solutions**
Looking at other generated code in the repro, it appears that the .csproj file needs to have a link to the AzureKeyCredential file added:
``` xml
<Compile Include="$(AzureCoreSharedSources)AzureKeyCredentialPolicy.cs" LinkBase="Shared" />
```

(Reference source: https://github.com/Azure/azure-sdk-for-net/blob/b1b123c1dcb1ba0fbe206fcbd3a1f8280d4410ce/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/Azure.AI.AnomalyDetector.csproj#L21C21-L21C21)

Trivially worked around by manually adding the reference to the project, but took time to track down.

**Comment by chunyu3** [comment]
The same issue as https://github.com/Azure/autorest.csharp/issues/3569
