### ISSUE TITLE
Convenience methods calling protocol methods should Dispose RequestContent?

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#3788]
Feel free to double check me, but I believe we should be calling Dispose on RequestContent instances we create in the convenience layer of DPG libraries.

Here is my thinking:

- RequestContent is IDisposable
- For protocol methods, the caller owns the RequestContent and is responsible for disposing it
    - Do/should we show this in generated samples?
- For convenience methods, we create the RequestContent in the model's serialization routine in the convenience method
    - Since we created the RequestContent, we're responsible for calling Dispose on it
- It doesn't look like we're putting the value returned from ToRequestContent in `using` statements:
    - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/src/Custom/OpenAIClient.cs#L155
    - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/src/Generated/OpenAIClient.cs#L51

If we agree with the above, the action items here would be:
- [ ] Show RequestContent in protocol method generated samples with `using` statement
- [ ] Add `using` statement to RequestContent created in convenience methods that call protocol methods

**Comment by pshao25** [comment]
@annelo-msft sounds reasonable and tests don't complain.
