### ISSUE TITLE
Change Response.FromValue emit based on content-type for current operation

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3816]
Originally reported here 
https://github.com/microsoft/typespec/discussions/2557

**Comment by pshao25** [comment]
@m-nash Where should we maintain the mapping, like "application/json" should be taken as "json" which "text/plain" should be taken as "text, similar to this function in M4. https://github.com/Azure/autorest.csharp/issues/3056#issuecomment-1429403557

**Comment by pshao25** [comment]
The original reported issue has been fixed. Other cases we will handle one by one and summarize in https://github.com/Azure/autorest.csharp/issues/3932
