### ISSUE TITLE
Need to handle the deserialization if we use getLroMetadata.LogicalResult

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3837]
The envelope type is what we will need to deserialize and pull the logic result out of the envelope.

I have a custom work around for openai for now.

https://github.com/Azure/azure-sdk-for-net/pull/39275/commits/7e86a998ebf5fbeceb65b52401cafaba6ea47e76

**Comment by archerzz** [comment]
This is a priority since we leave a gap in the implementation of LRO.
