### ISSUE TITLE
Autorest.csharp onboarding bug

### ISSUE THREAD

**Issue by pallavit** [Azure/autorest.csharp#3841]
1. Update the Summary comments for clients [autorest.csharp/src/AutoRest.CSharp/LowLevel/Generation/DpgClientWriter.cs at feature/v3 · Azure/autorest.csharp (github.com)](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/LowLevel/Generation/DpgClientWriter.cs#L60) to include a new line "Hello World"

2. Push a draft PR to autorest.csharp
This will require to [Build](https://github.com/Azure/autorest.csharp/tree/feature/v3#build) and [Test](https://github.com/Azure/autorest.csharp/tree/feature/v3#test) the changes locally first.

3. Run the regen pipeline here https://dev.azure.com/azure-sdk/internal/_build?definitionId=5990&_a=summary against your pr number refs/pull/####/head

4. Validate the changes in the draft PR created in azure-sdk-for-net

5. Cancel both PRs

**Comment by jorgerangel-msft** [comment]
Generator PR: [here](https://github.com/Azure/autorest.csharp/pull/3863)
