### ISSUE TITLE
Enhance the description of union types

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3850]
**Describe the issue or request**

Now the union types are modeled as `BinaryData` in our generated code. But those properties are still using the default description for `BinaryData` type which is quite misleading.

We need to enhance it to include the information about what kind of types this union property could accept

**Comment by m-nash** [comment]
In this api here https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Platform-OpenAI-TypeSpec/completions/models.tsp#L171 we have a model that takes in either a string literal of 2 values OR a model of type ChatCompletionFunctionCallOption.

We can see the generated model converts this into a BinaryData https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Platform-OpenAI-TypeSpec/src/Generated/Models/CreateChatCompletionRequest.cs#L173 and we lose the context for the customer of what can go into this BinaryData.  We want to provide help in the summary docs to let customers know what types of values are expected.
