### ISSUE TITLE
TypeFactory can't resolve anonymous types for method return

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#3853]
In `FirstTest-TypeSpec` test, `FirstTestTypeSpecClient.ReturnsAnonymousModel` method returns `Response<object>`:
https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/FirstTest-TypeSpec/src/Generated/FirstTestTypeSpecClient.cs#L824

It expected to return `Response<ReturnsAnonymousModel_101>`

**Comment by ArcturusZhang** [comment]
This has been fixed in [this PR](https://github.com/Azure/autorest.csharp/pull/4091)
