### ISSUE TITLE
api-version parameter gets added even in not declared.

### ISSUE THREAD

**Issue by glecaros** [Azure/autorest.csharp#3856]
I'm trying to generate a client from TypeSpec and I none of my operations declare an `api-version` parameter, but when I generate the C# client, the parameter always gets added (I'm using `@versioned` mostly for book keeping, and if I remove it the emitter errors out).

The following is a small repro I created:
```typescript
import "@typespec/rest";
import "@typespec/http";
import "@typespec/versioning";

using TypeSpec.Http;
using TypeSpec.Versioning;

@service({
  title: "<placeholder>",
})
@server(
  "{endpoint}",
  "<placeholder>",
  {
    endpoint: string,
  }
)
@versioned(APIVersion)
namespace Example;


enum APIVersion {  
  v20231001Preview: "2023-10-01-preview",
}

interface API {
    @route("/foo")
    @post
    op foo(bar: string, baz: safeint): string;
}
```
This results in a client with the following create request member function:
```csharp
internal HttpMessage CreateFooRequest(RequestContent content, RequestContext context)
{
    var message = _pipeline.CreateMessage(context, ResponseClassifier200);
    var request = message.Request;
    request.Method = RequestMethod.Post;
    var uri = new RawRequestUriBuilder();
    uri.Reset(_endpoint);
    uri.AppendPath("/foo", false);
    uri.AppendQuery("api-version", _apiVersion, true);
    request.Uri = uri;
    request.Headers.Add("Accept", "application/json");
    request.Headers.Add("Content-Type", "application/json");
    request.Content = content;
    return message;
}
```

**Comment by pshao25** [comment]
Pay attention to the name of package you are using: `@azure-tools/typespec-csharp`. It is by design to have an `api-version`. For non-azure-exclusive package, please stay tuned.

**Comment by glecaros** [comment]
@pshao25, I'm actually hitting this issue when creating an azure client library that by design has no api-version

**Comment by pshao25** [comment]
How could an azure client not have an api-version? Check out guidelines here: https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#api-versioning.

Have you passed api review for such kind of api?

**Comment by pshao25** [comment]
@glecaros Are you in azure-sdk-for-net? If so, what is your service name?

**Comment by glecaros** [comment]
hey @pshao25, the spec we are working on is for a chat-protocol that will be exposed by some azure services, and that we will also allow customers to implement in their own middle-tiers.
Right now, we have a PR in the specs repo (the removal of `api-version` was actually feedback from the review), and we have PRs for the tier1 languages repos based on the head commit of the PR branch. We are waiting to merge the spec before we get the mono repos reviewed.

**Comment by lirenhe** [comment]
@glecaros,  are you talking about this PR?  https://github.com/Azure/azure-rest-api-specs/pull/26038

But from sample in this PR: https://github.com/Azure/azure-rest-api-specs/blob/a11385a85f3c1f9dd86f8cf517928825890922bb/specification/machinelearning/data-plane/Azure.AI.ChatProtocol/preview/2023-10-01-preview/examples/create.json,

  I find there is still a parameter of 'api-version'.  So I would like to confirm what your expected behavior for this.  Thanks

**Comment by mikekistler** [comment]
For Azure services, the TypeSpec must have an api-version parameter, so there is no need to add it. And for non-Azure services, we should not impose our API Guidelines on them. So in both cases we should not add an api-version if it is not defined in the TypeSpec.

**Comment by lmazuel** [comment]
+1 with @mikekistler and @johanste FWIW. TypeSpec is the only source of truth about deciding to add api-version or not. Let's not get Azure biased, and build a codegen that would make the unbranding story unnecessarily complicated.

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3939
