### ISSUE TITLE
Fix duplicates in the list of derived models or remove the list

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#3876]
C# TypeSpec emitter produces duplicates when fills in derived models list.

Here is an example of the same model presented twice.
- as a item in the DerivedModels array: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/ConfidentLevels-TypeSpec/src/Generated/tspCodeModel.json#L719-L745
- as a separate model: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/ConfidentLevels-TypeSpec/src/Generated/tspCodeModel.json#L793-L819
Both point to the same base model id ref85.

Possible solutions:
- Fix emitter output.
- Remove `DerivedTypes` from protocol, assign them during deserialization or in a separate visitor.
- Remove `DerivedTypes` completely.

**Comment by chunyu3** [comment]
When there is a `BaseModel` and a derived model `DerivedModel`, in the emitted json, `BaseModel` has a reference to `DerivedModel` and `DerivedModel` also has a reference to `BaseModel`. If both use the `$ref`, there will be a circle, and it will throw exception when deserailize this json, so we duplicate the derived model to break the circle.

The possible solution is remove one reference, either from `BaseModel` or `DerivedModel` from emitted json, and then need to calculate the relationship in codegen runtime.

**Comment by AlexanderSher** [comment]
Fixed in https://github.com/Azure/autorest.csharp/pull/3967
