### ISSUE TITLE
NRE when input body of convenience method is null

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3878]
```C#
internal virtual async Task<Response> ReclassifyJobAsync(string id, IDictionary<string, string> reclassifyJobRequest = null, CancellationToken cancellationToken = default)
{
using RequestContent content = RequestContentHelper.FromDictionary(reclassifyJobRequest);
}
```

When passing `null` to reclassifyJobRequest, `RequestContentHelper.FromDictionary` throws NRE.

Solution 1:
In `RequestContentHelper.FromDictionary` we add:
```C#
if (dictionary == null)
    return null;
```

Solution 2:
In convenience method, we add:
```C#
if (reclassifyJobRequest == null)
{
    return await ReclassifyJobAsync(id, (RequestContent)null, cancellationToken).ConfigureAwait(false);
}
```

**Comment by AlexanderSher** [comment]
Another option:
```cs
using RequestContent content = reclassifyJobRequest != null ? RequestContentHelper.FromDictionary(reclassifyJobRequest) : null;
```

**Comment by ArcturusZhang** [comment]
> Another option:
> 
> ```cs
> using RequestContent content = reclassifyJobRequest != null ? RequestContentHelper.FromDictionary(reclassifyJobRequest) : null;
> ```

This is really cumbersome, I prefer the simplest solution, change the helper method so that it just returns null when input is null and we do not have to change anything other than this.

**Comment by jsquire** [comment]
> > Another option:
> > ```cs
> > using RequestContent content = reclassifyJobRequest != null ? RequestContentHelper.FromDictionary(reclassifyJobRequest) : null;
> > ```
> 
> This is really cumbersome, I prefer the simplest solution, change the helper method so that it just returns null when input is null and we do not have to change anything other than this.

Alex's suggestion is the right approach.  The proposed change to the class does not align with its design and fundamentally changes the contract for callers.  

In the current contract, callers of that method are guaranteed that either a valid object is returned, or an exception is surfaced.  The proposed change shifts the burden from "the generator should check for null before calling" to "all callers of the method must check the return value to guard against null".  

That's not a change that I believe will be accepted for Core.
