### ISSUE TITLE
Unable to compile generated code:  'HttpPipeline' does not contain a definition for 'ProcessMessageAsync'

### ISSUE THREAD

**Issue by mateid** [Azure/autorest.csharp#3907]
I am unable to compile Autorest CSharp generated code. I have already applied the fixes described [in this Stackoverflow answer](https://stackoverflow.com/questions/66508254/error-compiling-autorest-generated-client) however I am stuck on this error:   

```
'HttpPipeline' does not contain a definition for 'ProcessMessageAsync' and no accessible extension method 'ProcessMessageAsync' accepting a first argument of type 'HttpPipeline' could be found (are you missing a using directive or an assembly reference?)
```

Not sure if I am missing a reference or something like that. I feel like this should just work out of the box without having to implement the fixes described in the answer mentioned above. Is there a gap in the documentation perhaps?

**Comment by chunyu3** [comment]
Hello @mateid When you use .NET codegen to generate project file (.csproj), the auto-generated project files will contain all the needed compile dependency and can compile successfully under azure-sdk-for-net.
You can specify `--new-project=true` to let codegen generate a project file.

**Comment by mateid** [comment]
@chunyu3 that worked, thank you very much!
