### ISSUE TITLE
[Feature Request] Add a "target branch" on the regen pipeline

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3914]
**Describe the issue or request**

Now the regen pipeline will always run against main branch of azure-sdk-for-net, could we make it configurable? Sometimes we might need some modifications to make sure the generator could generate the code properly, and the modifications may not make sense before the generator version gets bumped. When this happens, we could create a branch which contains the necessary changes to let the generator does its job correctly, and set the branch to be the target branch of the regen pipeline to see the generation result properly.

**Comment by pshao25** [comment]
I think this feature already added back. Have you tried the steps here: https://github.com/Azure/azure-sdk-for-net/issues/37033#issue-1758130494?

**Comment by ArcturusZhang** [comment]
@pshao25 thank you! Good to know, this works like a charm
