### ISSUE TITLE
Investigate two generated extensions without compile error

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#3926]
Currently we have two `ParametersLowLevelClientBuilderExtensions.cs` at feature/v3 https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/Parameters-LowLevel/src/Generated
![image](https://github.com/Azure/autorest.csharp/assets/97225342/4a9d4866-b38e-4da3-b8e5-8e711ccaaa04)

How could this happen and why compile succeed?

**Comment by chunyu3** [comment]
A new `ParametersLowLevelClientBuilderExtension.cs` was added in https://github.com/Azure/autorest.csharp/pull/3676. Maybe the windows/linux different behavior to handle the name, windows case-insensitive

**Comment by pshao25** [comment]
Only one left now.
