### ISSUE TITLE
[Microsoft Generator CSharp] Add support for parsing source input file

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#3998]
The generator executable should support parsing a  TypeSpec code model JSON file ie. (`tspCodeModel.json`) as input and deserializing it into an object/model that can be consumed by the generator. We should use similar parsing and deserialization done in [autorest](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/AutoRest/Communication/StandaloneGeneratorRunner.cs).

**Comment by lirenhe** [comment]
@jorgerangel-msft, could you provide more information for this task?  I believe today the c# code generator would consume that file and deserialize it.   Is there any missing functions here? Thanks

**Comment by chunyu3** [comment]
hello @jorgerangel-msft So will there be two separated generator: branded generator and unbranded generator? I am curious about the current architecture of .NET codegen.

**Comment by m-nash** [comment]
@chunyu3 There will only be 1 generator but there will be 2 plugins to the generator.  The base plugin will be the SCM plugin and the azure plugin will override / extend a few things on top of that so will not be a complete rewrite.
