### ISSUE TITLE
How to use new extension mocking to mock methods on resourcegroupresource

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/autorest.csharp#4007]
**Describe the issue or request**
We used the beta versions of some of the extension mocking support and that required we setup GetCachedClient method to mock the sdk in our method under test.

<img width="600" alt="Screenshot 2023-12-04 084617" src="https://github.com/Azure/autorest.csharp/assets/11986860/c79df9f6-840b-42c9-900c-594227a1aa8d">

With the release versions of Azure.ResourceManager.Network (1.6.0) and Azure.ResourceManager (1.9.0) it doesn't appear that GetCachedClient is the way to go anymore as I can't find NetworkResourceGroupMockingExtension.  **Given the below method, how would I mock the extension method GetVirtualHubs?**

<img width="577" alt="Screenshot 2023-12-04 081905" src="https://github.com/Azure/autorest.csharp/assets/11986860/974a6b79-d6a6-47f4-89db-cf6982979c62">

**Describe your ideas for solutions**
Please describe how you think a change or changes might work. Consider
how these changes might work for multiple services.

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by ArcturusZhang** [comment]
Thank you for reporting this.
Comparing with the beta version we previously release for gathering feedbacks, there is a naming change from `XXXMockingExtension` to `MockableXXXResource`
Therefore to make things work, you just need to rename your `NetworkResourceGroupMockingExtension` to `MockableNetworkResourceGroupResource`
and everything should work fine
