### ISSUE TITLE
[MPG] Add a xml doc paragraph to explicitly document how to override the api-version for one method

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4014]
**Describe the issue or request**

MPG libraries provide the functionality of overriding the api-version, but it works by a key of resource type.
Our SDK users might get lost when using an operation because which resource type to use to override the api-version is actually undocumented.

We could add a paragraph to document it.

**Comment by RodgeFu** [comment]
fixed by https://github.com/Azure/azure-sdk-for-net/pull/43062
