### ISSUE TITLE
How to mock extension method GetResourceClient

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/autorest.csharp#4028]
**Describe the issue or request**
I am trying to test one of our methods that calls the method GetDataCollectionRuleAssociations in Azure.ResourceManager.Monitor.  

<img width="521" alt="image" src="https://github.com/Azure/autorest.csharp/assets/11986860/f7af51af-1de2-4677-8530-79f853f45721">

I see in the definition of this methods it calls GetARmResourceExtensionClient which calls ArmClient.GetResourceClient.  I tried to mock this method similar to GetCachedClient but I think maybe I just have the wrong type in my setup.  What should it be?  Is there an example for how to set this up correctly?

<img width="288" alt="image" src="https://github.com/Azure/autorest.csharp/assets/11986860/0fd0a218-0f43-41dc-ad17-0dc424616571">

**Describe your ideas for solutions**
Please describe how you think a change or changes might work. Consider
how these changes might work for multiple services.

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by ArcturusZhang** [comment]
Hi @rguthriemsft the latest version 1.3.0 of Azure.ResourceManager.Monitor should have changed it to GetCachedClient.
Please try to update your version to the latest and use `GetCachedClient` to mock an extension method.

**Comment by ArcturusZhang** [comment]
I believe this issue has been resolved per offline discussion. Close this issue
