### ISSUE TITLE
Set up local NuGet package for testing

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4064]
There is some test-only fallback logic in production code in this [PR](https://github.com/Azure/autorest.csharp/pull/4026/files#diff-a0fe4c346798a56a7b209bfd77e4a6ef669c20846246235bc3fa3deb25466bb7)
We would like to set up a local NuGet package to avoid this fallback.
- dotnet pack [the current test project](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/MgmtCustomizations) as baseline contract with version 1.0.0
- put the generated .nupkg into [BaselineContract](https://github.com/Azure/autorest.csharp/pull/4026/files#diff-8a2bf525b36a645f298c123c93ff9189cf89c10055da8e74392680d7c45df41f) instead of the existing DLL
- Update Generate.ps1 to update Nuget.Config adding another feed pointing to the above `BaelineContract` folder, run the tests and remove the added feed after the test run in the end
- Add `<ApiCompatVersion>1.0.0</ApiCompatVersion>` to MgmtCustomizations.csproj to consume the local package

**Comment by RodgeFu** [comment]
resolved with PR https://github.com/live1206/autorest.csharp/pull/2
