### ISSUE TITLE
[BUG] Strings with the `date-time` format follow RFC3339 in the generated client

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4070]
### Library name and version

Any

### Describe the bug

When using the [Data Plane Generation Quickstart Tutorial](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/Data%20Plane%20Code%20Generation/AzureSDKCodeGeneration_DataPlane_Quickstart.md), the generated LLC takes definitions with string properties that have `"format": "date-time"` in the swagger spec and documents them claiming that they follow the "ISO 8601 Format". This appears in the comments of methods that use said definitions as parameters. The latest [Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#json) indicate that dates should use RFC3339 instead.

### Expected behavior

No mention of the ISO 8601 format, and ideally mentioning the RFC3339 format instead.

### Actual behavior

Generated methods come with generated comments that mention ISO 8601.

### Reproduction Steps

1. Get a swagger spec that has a definition with a property marked as a string that uses the `date-time` format.
2. Follow the [Data Plane Generation Quickstart Tutorial](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/Data%20Plane%20Code%20Generation/AzureSDKCodeGeneration_DataPlane_Quickstart.md) using that swagger spec.
3. Observe the generated client.

**Comment by lirenhe** [comment]
Move to autorest.csharp repo as this is an issue for the CodeGen.

**Comment by archerzz** [comment]
We're still setting to `ISO8601` if the format is not specified. See: https://github.com/Azure/autorest.csharp/blob/74938fddeede57bd4758720b05ea355eabd29645/src/AutoRest.CSharp/Common/Output/Builders/SerializationBuilder.cs#L53-L54

However, when serializing the date, both `ISO8601` and `RFC3339` use the same format. See: https://github.com/Azure/autorest.csharp/blob/74938fddeede57bd4758720b05ea355eabd29645/src/AutoRest.CSharp/Common/Output/Models/Serialization/SerializationFormatExtensions.cs#L11-L13
And https://github.com/Azure/autorest.csharp/blob/74938fddeede57bd4758720b05ea355eabd29645/src/assets/Azure.Core.Shared/TypeFormatters.cs#L30
https://github.com/Azure/autorest.csharp/blob/74938fddeede57bd4758720b05ea355eabd29645/src/assets/Azure.Core.Shared/TypeFormatters.cs#L15

---

`yyyy-MM-ddTHH:mm:ss.fffffffZ` is a compatible format recognized by both `ISO8601` and `RFC3339`. See the Q&A on Stackoverflow: https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats. `ISO8601` might be still used by some existing services. So, we should remove the generated document describing it, though we actually use a compatibile serialization format.
