### ISSUE TITLE
Allow specifying the model namespace to use

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#4087]
In c-sharp emitter options defined in tspconfig.yaml, it is possible to say whether or not to use a model namespace, e.g. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/Azure.Messaging.EventGrid/tspconfig.yaml#L28

It would be helpful to allow the model namespace to be configurable. This is a requirement for migrating the Event Grid system events to TypeSpec.

**Comment by pshao25** [comment]
@JoshLove-msft sounds like if we take the namespace defined for model could solve your problem? Currently we don't read any model namespace from spec.

Could you give me an example what namespace you want to change to?

**Comment by pshao25** [comment]
@m-nash would you triage this request? My understanding is we do not allow arbitrary namespace for models.

**Comment by chunyu3** [comment]
Hello @JoshLove-msft Would you please describe why `EventGrid` want customize the model namespace, and what namespace hierarchy they want?  We will justify if we need to provide customized model namespace. Thanks

**Comment by JoshLove-msft** [comment]
This is no longer required as the system events are now in a separate library and do not use model namespaces.
