### ISSUE TITLE
Generate constructors taking custom scopes for TokenCredential

### ISSUE THREAD

**Issue by yufeih** [Azure/autorest.csharp#4101]
**Describe the issue or request**

`@azure-tools/typespec-csharp`: 0.2.0-beta.20231212.1

When `OAuth2Auth` is used for auth in TypeSpec, autorest generates the following constructor overloads that takes `TokenCredential`. But the authentication scope is hardcoded and cannot be modified by caller. In some cases, caller wants to send request against a different URL with a different authentication scope such as request against a testing environment.

```csharp
public class MyClient
{
    public MyClient(Azure.Core.TokenCredential credential) { }
    public MyClient(System.Uri endpoint, Azure.Core.TokenCredential credential, Microsoft.Learn.MyClientOptions options) { }
}
```

**Describe your ideas for solutions**

Generate an additional constructor that takes a `scope` parameter, or add the `scope` parameter to `ClientOptions`

```csharp
public class MyClient
{
    public MyClient(Azure.Core.TokenCredential credential) { }
    public MyClient(System.Uri endpoint, Azure.Core.TokenCredential credential, Microsoft.Learn.MyClientOptions options) { }
    public MyClient(System.Uri endpoint, Azure.Core.TokenCredential credential, string[] scopes, Microsoft.Learn.MyClientOptions options) { }
}
```

**Additional info**

scopes are customizable in `autorest.typescript` with: 

```ts
    const client = MyClient(new DefaultAzureCredential(), {
        credentials: {
            scopes: ['foo/.default']
        }
    })
```

**Comment by chunyu3** [comment]
Duplicated with https://github.com/Azure/autorest.csharp/issues/3432

**Comment by ArthurMa1978** [comment]
Close as duplicate.
