### ISSUE TITLE
[Microsoft Generator CSharp] Create extensibility point on TypeFactory

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4108]
Create an extensibility point on the [TypeFactory](https://github.com/Azure/autorest.csharp/blob/28002ce063e18e1fbb999abe7d30a56dad9c21a0/src/AutoRest.CSharp/Common/Generation/Types/TypeFactory.cs). The extensibility point should exist in the core generator library and should be extensible via a plugin.

The following are the known extensibility points that need to be implemented in the TypeFactory:
- A CreateType() function to allow converting an [input type](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Input/InputTypes/InputType.cs) to an output type of [CSharpType](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Types/CSharpType.cs).

References:
- [Existing TypeFactory class](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Types/TypeFactory.cs).

Unit tests should be added to test the added functionality.

**Comment by ArcturusZhang** [comment]
Is any one working on this? and do we have a proposal or design? Please share that somewhere

**Comment by jorgerangel-msft** [comment]
@ArcturusZhang - I'll be working on this and once I have a proposal/design I'll share it with the team.
