### ISSUE TITLE
Generator changed type of subscriptionId from string to Guid

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/autorest.csharp#4121]
The latest generator updates have changed the type of subscriptionId from string to Guid. 
![image](https://github.com/Azure/autorest.csharp/assets/67986960/26857581-2864-4e2d-95e3-4c488e635420)

.Net uses strings to represent Guid types so I believe this is a bug.
This problem can be resolved with autorest transforms but we should update the generator to output the correct type.

**Comment by ArcturusZhang** [comment]
Generator never changes types from nowhere. Please double confirm if something has changed in your swagger.
If possible, please share a PR link of your SDK changes so that we could take a look to see where the change comes from.
