### ISSUE TITLE
[Bug][TypeSpec] Cannot resolve reference when derived model is defined in base model

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#4136]
## Problem

Currently we never define `DerivedModels` because that will cause resolving reference error like below:
> Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to AutoRest.CSharp.Common.Input.InputModelType. Path: $.Models[9] | LineNumber: 579 | BytePositionInLine: 15.

The problem is that if we define `DerivedModels`, the JSON model structure is different. Let's take `Confidents-Typespec` as an example: https://github.com/Azure/autorest.csharp/blob/71dcac37a8853b00e81ec2f1892798f72ca4da8a/test/TestProjects/ConfidentLevels-TypeSpec/ConfidentLevels-TypeSpec.tsp#L124-L141

The current JSON document is like below:
```json
{
  "$id": "58"
  "Name": "Pet"
  ...
},
{
  "$id": "59"
  "Name": "Cat"
  "BaseModel": {
    "$ref": "58"
  },
...
}
```

If I we define `DerivedModels`, the JSON document is changed as:
```json
{
  "$id": "58"
  "Name": "Pet"
  "DerivedModels": [
  {
    "$id": "59"
    "Name": "Cat"
    "BaseModel": {
      "$ref": "58"
    },
  ...
  }
  ],
  ...
},
{
  "$ref": "59"
}

```

The 2nd JSON document is legal. We just need to figure out how we can correctly resolve the references like that. TCGC has done a lot of calculation for us. There is no need to re-calculate those values in csharp.

**Comment by ArcturusZhang** [comment]
For exactly the same reason, we removed the `DerivedModels` property in our emitter, and let the generator figure it out when deserializing the types.
I do not think it is necessary we have to invent that again.
