### ISSUE TITLE
[Microsoft Generator CSharp] Create base implementation & extensibility point on CodeWriter

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4153]
Create an extensibility point on the [CodeWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriter.cs) to allow writing custom Method's and their respective expressions & method body statements. The base implementation should exist in the core generator library and should be extensible via a plugin.

Known extensibility points:
- [WriteMethodBodyStatement](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.Methods.cs#L21)
- [WriteValueExpression](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.Methods.cs#L269)
- `WriteMethod`. This will be a new method that doesn't exist today.

Unit tests should be added to test the added functionality.

**Comment by m-nash** [comment]
Convers just the WriteValueExpression portion which is done
