### ISSUE TITLE
[Microsoft Generator CSharp] Create Client Model Plugin Implementation of Code Writer

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4167]
As part of supporting custom system based statements, expressions , and method bodies, the plugin should contain an implementation of the [CodeWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriter.cs). This should contain implementations for [WriteMethodBodyStatement](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.Methods.cs#L21) & [WriteValueExpression](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.Methods.cs#L269) to handle writing custom system statements, expressions, and method bodies.

**Comment by m-nash** [comment]
This most likely is obsolete once we pull in the latest expression / statements from autorest.csharp.
