### ISSUE TITLE
Support @clientName and @encodedName in dotnet CodeGen

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#4168]
As encodedName is introduced in 0.52 of TypeSpec. 
```
model Widget {
  @key id: string;

  @encodedName("application/json", "WidgetWeight")
  weight: int32;
  
  color: "red" | "blue";
  @added(Versions.v2) name: string;
}
```
And @clientName is introduced in this PR https://github.com/Azure/typespec-azure/pull/127/files.

Please support them in the CodeGen.

**Comment by timotheeguerin** [comment]
Tcgc abstract that away from you and should have just worked. Call getLibraryName

**Comment by lirenhe** [comment]
The adoption of TCGC is still in progress.  https://github.com/Azure/autorest.csharp/pull/4185
We may implement that separately to unblock customer and then move to using TCGC.  cc @m-nash

**Comment by timotheeguerin** [comment]
any progress on this? are we still blocked on doing this migration?

**Comment by pshao25** [comment]
> any progress on this? are we still blocked on doing this migration?

I'm blocked by https://github.com/Azure/autorest.csharp/pull/4212
