### ISSUE TITLE
[Microsoft Generator CSharp] Properly Dispose of Custom Assembly Resolve Event

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4178]
As part of https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/4, the nuget catalog now contains a custom assembly resolve event to handle resolving a plugin's dependencies dynamically. If the event is removed from the app context, the app will hold a reference to it throughout the lifecycle of the app. The event should be properly disposed of when it is no longer needed, preferably within the implementation of the NugetCatalog.

**Comment by m-nash** [comment]
closed due to using npm packaging instead
