### ISSUE TITLE
[Csharp Typespec Emitter] @usage @access acting transitively?

### ISSUE THREAD

**Issue by l0lawrence** [Azure/autorest.csharp#4182]
In typespec for EventGrid SystemEvents we have models that are not used within operations. In order to get them to show we use @access and @usage. 

In the following scenario -- where `MyModel` is not used within an operation:
                
                main.tsp ----
                
                ```
               op dummyOperation(): void;

                model MyModel {
                    someEnum: myEnum;
                }
                
                enum myEnum {
                   Yes,
                    No,
                   Maybe,
                }
                ```
                
                client.tsp ----
                
                ```
                @@access(namespace.MyModel, access.public)
                @@usage(namespace.MyModel, usage.input | usage.output)
                
                ```

Within the python emitter, I would get both `MyModel` and `myEnum` publicly exposed as the @access and @usage decorators are treated transitively -- applying to the enum within the model. 

Is there going to be support for this within the C# emitter?

**Comment by lirenhe** [comment]
@l0lawrence,  the dotnet work should also be completed. https://github.com/Azure/autorest.csharp/pull/3671  

Did you find any unexpected behavior from dotnet emitter?

**Comment by l0lawrence** [comment]
Hello! 

Yes, I would expect that the use of these decorators on a Model would apply to any models/enums that are used within that model. 

If you generate off of the typespec outlined above `myEnum` is not generated by the .NET emitter. I would expect it to be because it is used within `MyModel` which has @access public and @usage Input/output

**Comment by lirenhe** [comment]
The design decision for @access and @usage is that 'This decorator will not have any propagation'.
Not sure why Python implemented the other way.  @tadelesh, could you confirm the behavior?

**Comment by tadelesh** [comment]
`@access` and `@usage` do not have any propagation. Python emitter's behavior is when generating `MyModel`, it will get a property with type `myEnum` and it will generate that enum though it is not generated in the phase of `getAllModels`. I strongly recommend to add `@access` and `@usage` to all the property types.

**Comment by jhendrixMSFT** [comment]
What's the reasoning behind not propagating `@usage`?

**Comment by tadelesh** [comment]
> What's the reasoning behind not propagating `@usage`?

We don't want to introduce complicated rules for combining several usage values from propagated usage and default calculated usage. So, we decide to let author to be fully responsible for the model usage if they want to do any customization.

**Comment by jhendrixMSFT** [comment]
Seems reasonable.

Will there be some enforcement at the TCGC level then? What I've observed is that you can end up with a model type referencing e.g. an enum type that doesn't actually exist due to the dependent enum type not having the same usage.

**Comment by tadelesh** [comment]
The models and enums returned by `getAllModels` will not contain models or enums without usage. But that does not mean models or enums without usage are missing, they are just be filtered, and if a model property is a model or enum without usage, you will get that model or enum from the property type.
