### ISSUE TITLE
[CDK] Add custom serialization hooks

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#4184]
Similar to how JSON allows customizing the serialization code, we need to do the same for Bicep so that types that are entirely customized can still be used with CDK. The Bicep for [such types](add custom serialization hooks) will need to be hand-written.

**Comment by ArcturusZhang** [comment]
FYI I am changing how the existing attribute works, see PR here: https://github.com/Azure/autorest.csharp/pull/4159
