### ISSUE TITLE
[Bug] Serialization of nested models are not entirely correct

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4193]
**Describe the issue or request**

When a model contains a property of another model, this is how we are doing to write it:
https://github.com/Azure/autorest.csharp/blob/d72fed646c36e24cc899f499954ac1eef6f215f9/test/TestProjects/FirstTest-TypeSpec/src/Generated/Models/RoundTripModel.Serialization.cs#L244
This is using `writer.WriteObjectValue` which is an extension method:
https://github.com/Azure/autorest.csharp/blob/d72fed646c36e24cc899f499954ac1eef6f215f9/src/assets/Azure.Core.Shared/Utf8JsonWriterExtensions.cs#L71
But this method does not take an `options` parameter, therefore the option is missing when serializing this (and possible nested models this would also have)
We should fix this.

There are a few approaches of doing this:
1. Update the method in shared code to make it accept an optional options
2. Update our generator code, to make our generator know of when a case of model happens, it uses `ModelReaderWriter.Write` and then writes the `BinaryData` into the writer. For other cases, we still use `writer.WriteObjectValue` because this method is meant to be writing values with unknown types (`object`)

In fact, approach 1 might not be acceptable because shared code locates in `Azure.Core`, adding a new parameter creates a dependency to `System.ClientModel` in our shared code - which would be a nightmare because there is no dependency of System.ClientModel for the libraries that are not enabled with MRW.

**Comment by live1206** [comment]
We are adding `System.ClientModel` as package reference to `Azure.Core` in https://github.com/Azure/azure-sdk-for-net/pull/41655/files#diff-e9213ad79eedc5d615c9c6f35698e02f01cb9644614ee8cdf2eed9f62f4d12e4 .
So, maybe option 1 is not acceptable?

**Comment by ArcturusZhang** [comment]
We need to resolve https://github.com/Azure/autorest.csharp/issues/4246 first before we resolve this issue

**Comment by ArcturusZhang** [comment]
Fixed in https://github.com/Azure/autorest.csharp/pull/4447
