### ISSUE TITLE
[Microsoft Generator CSharp] Should we introduce abilities to mock types like `TypeFactory`, `CSharpType`, etc?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4195]
**Describe the issue or request**

I believe as the basic component of a public library, these types `TypeFactory`, `CSharpType`, etc should have the ability to mock.
We could simply enable this by adding virtual keyword to all the properties and methods they have.

**Comment by ArcturusZhang** [comment]
@m-nash what do you think?

**Comment by m-nash** [comment]
@ArcturusZhang  can you come up with a scenario where we would need to mock these?  The way I think about it now is that we will want to assert that the factory creates the right conversion from input type to csharptype but mocking this I don't know of a use case.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang can you come up with a scenario where we would need to mock these? The way I think about it now is that we will want to assert that the factory creates the right conversion from input type to csharptype but mocking this I don't know of a use case.

it may happen when some one is writing a plugin of our generator, and it is happening now because we have a test case mocking them here: https://github.com/Azure/autorest.csharp/blob/073494b8215c2c7ab825835263f2a574796f2a43/test/AutoRest.CSharp.UnitTests/Common/Output/Models/Shared/ParameterTests.cs#L25

**Comment by m-nash** [comment]
Since TypeFactory is an abstract class I believe you can mock it and override any virtual / abstract methods.  Is there additional functionality you think we need here @ArcturusZhang ?
