### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Input Classes

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4197]
The [Input classes](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/AutoRest.CSharp/Common/Input) should be migrated to the new generator. Any references to brands should be removed as part of the migration, and access modifiers for these classes should be adjusted if necessary.

**Comment by m-nash** [comment]
Handing off to Jorge wip branch https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/tree/mnash-4197
