### ISSUE TITLE
Internal: Prettier find ways too many files to format due to line ending issue on OSX

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest.csharp#4204]
**Describe the issue or request**
When running `npm run prettier` in the typespec emitter package it reports an issue for every single ts file which seems to only be about line endings.

**Describe your ideas for solutions**
Configure prettier line endings or set git attributes to use `LF` for ts files

**Comment by lirenhe** [comment]
Consider updating https://github.com/Azure/autorest.csharp/blob/feature/v3/.gitattributes to make the line ending consistent with https://github.com/Azure/autorest.csharp/blob/feature/v3/src/TypeSpec.Extension/Emitter.Csharp/.prettierrc.json

**Comment by timotheeguerin** [comment]
Seeing it is forced to `crlf` for prettier it would be better to change prettier too as this is not very cross platform.
