### ISSUE TITLE
[Microsoft Generator CSharp] Explore having an abstract method on ValueExpression

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4215]
Originally discussed in https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/9#discussion_r1486474009. We should explore having an abstract method in the [ValueExpression](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/blob/main/Microsoft.Generator.CSharp/src/ValueExpression.cs) class to support writing the value expression to the writer. A possible implementation: `public abstract void Write(CodeWriter writer)`. This will avoid having to have a long conditional in the code writer extension methods for each value expression.

**Comment by ShivangiReja** [comment]
We discussed implementing the writing of expressions and statements next to the respective expression and statement itself, rather than using a massive switch statement. We will make this change in the autorest.csharp repository and then migrate the changes into MGC.

**Comment by m-nash** [comment]
Fixed by https://github.com/Azure/autorest.csharp/pull/4494
