### ISSUE TITLE
[Microsoft Generator CSharp] Simplify MethodBodyStatement and MethodBodyStatements types

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4218]
Refactor `MethodBodyStatement` to represent a singular type, and `MethodBodyStatements` as a collection of `MethodBodyStatement` by implementing `IEnumerable<MethodBodyStatement>`.

Currently [MethodBodyStatements](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatements.cs#L8) implements [MethodBodyStatement](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatement.cs#L13-L14), which has implicit operators that allow you to create a MethodBodyStatements instance from either an array or a list of MethodBodyStatement objects.

For additional context, please see the discussion here: [Link to the discussion](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/10#discussion_r1486721622).

**Comment by AlexanderSher** [comment]
Following the [discussion](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/10#discussion_r1486721622): `MethodBodyStatements` is used inside [CodeWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.Methods.cs#L235-L241), so it can't be private - only internal.

**Comment by ShivangiReja** [comment]
Since Microsoft.Generator.CSharp repo is private, moving the discussion here:

```csharp
namespace Microsoft.Generator.CSharp.Expressions
{
    [DebuggerDisplay("{GetDebuggerDisplay(),nq}")]
    public record MethodBodyStatement
    {
        public static implicit operator MethodBodyStatement(MethodBodyStatement[] statements) => new MethodBodyStatements(Statements: statements);
        public static implicit operator MethodBodyStatement(List<MethodBodyStatement> statements) => new MethodBodyStatements(Statements: statements);

        private string GetDebuggerDisplay()
        {
            using var writer = new DebuggerCodeWriter();
            writer.WriteMethodBodyStatement(this);
            return writer.ToString();
        }
    }
}
```

```csharp
namespace Microsoft.Generator.CSharp.Expressions
{
    public record MethodBodyStatements(IReadOnlyList<MethodBodyStatement> Statements) : MethodBodyStatement;
}
```

@m-nash -
Is there any reason `MethodBodyStatements` doesn't implement `IEnumerable<MethodBodyStatement>`. Inheriting from the singular seems very strange here.

@ShivangiReja -
I'm following the existing pattern for the [MethodBodyStatements](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatements.cs#L8) and [MethodBodyStatement](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatement.cs#L11) classes.

The reason why `MethodBodyStatements` doesn't implement `IEnumerable<MethodBodyStatement>` might be because there are [static implicit operators](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatement.cs#L13-L14) defined in the `MethodBodyStatement` class. These operators allow to create `MethodBodyStatements` instance from either an array or a list of `MethodBodyStatement` objects. This design also enables flexibility in usage, such as [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/IfStatement.cs#L12-L13).

@m-nash -
I guess I am confused why the If statement in your example would not simply have a MethodBodyStatements as its _body type. Can we open a tracking issue for this to address before we GA.

@ShivangiReja -
The reason is that [MethodBodyStatements](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatements.cs#L8) does not implement `IEnumerable<MethodBodyStatement>`, and therefore, we cannot call the `Add` method [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/IfStatement.cs#L15).

[MethodBodyStatements](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatements.cs#L8) does, however, implement [MethodBodyStatement](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions/Statements/MethodBodyStatement.cs#L13-L14), which has implicit operators that allow you to create a MethodBodyStatements instance from either an array or a list of MethodBodyStatement objects.

@ShivangiReja -
@AlexanderSher could you please provide clarification on why `MethodBodyStatements` and `MethodBodyStatement` are implemented the way they are in code gen? why didn't we simplified it by defining `MethodBodyStatement`  as a single type and `MethodBodyStatements` as a collection of MethodBodyStatement by implementing `IEnumerable<MethodBodyStatement>`?

@AlexanderSher -
I'm not sure I understand the question.

`MethodBodyStatements` represents multiple statements going one after another. No other `MethodBodyStatement` is written like this.
 
Multiple statements going one after another form a statement, but not other way around. For example: 
- `AssignValueStatement`, `InvokeStaticMethodStatement` or `KeywordStatement` have no other statements inside them
- `IfStatement` has only one inner statement
- `ForeachStatement` has several inner statements

@AlexanderSher -
The reason why _some_ statements implement `IEnumerable<MethodBodyStatement>` is to support [collection initializers](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers), which require type to implement `IEnumerable<T>` and have `Add(T)` method, e.g.:
```cs
new ForeachStatement("item", collection, out var item)
{
    Declare(...),
    Assign(...),
    ...
}
```

@ArcturusZhang -
I agree with the part of `IEnumerable<MethodBodyStatement>`.
But to me, the existence of this type `MethodBodyStatements` is to provide an implicit conversion from a collection of `MethodBodyStatement`s to one big statement, and one should never use this `MethodBodyStatements` directly
If this is its only purpose, maybe we could make this record private inside the `MethodBodyStatement` to reduce the confusion.
Is this valid? @AlexanderSher 

@ArcturusZhang -
well on the other hand making `MethodBodyStatements` private might cause our user to lose the ability to construct a sequence of statements other than casting which might be bad practice.
