### ISSUE TITLE
[Microsoft Generator CSharp] Review and Finalize Expression and Statement namespace

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4222]
Currently, all statements and expressions are in the `Microsoft.Generator.CSharp.Expressions` namespace. The team proposes restructuring for better organization. Proposed options include:
- **Option-1** -  Moving statements to `Microsoft.Generator.CSharp.Statements` and expressions to `Microsoft.Generator.CSharp.Expressions`.
- **Option-2** - Preserving existing structure with subcategories like `Expressions.KnownExpressions`
`Expressions.Statements`, `Expressions.ValueExpressions`.
- **Option-3** - Treating statements as special expressions within `Expressions`, leading to a structure like `Expressions.KnownExpressions`, `Expressions.ValueExpressions`, and `Expressions.ValueExpressions.Statements`.

For more details, refer to the conversation thread [here](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/10#discussion_r1486722593).

**Comment by ArcturusZhang** [comment]
I vote for option 3
