### ISSUE TITLE
[MPG][.Net] Pass along renaming information from .NET SDK generation to TypeSpec

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4236]
We have some type/property/method renaming in .NET SDK generation, we need to pass along the renaming information to TSP during TSP conversion.

An idea is to get the renaming information from the generation output report.

**Comment by RodgeFu** [comment]
fixed by https://github.com/Azure/autorest/pull/4907 
https://github.com/Azure/autorest.csharp/pull/4380
