### ISSUE TITLE
Enable the new cancellation token pattern in the debranded generator

### ISSUE THREAD

**Issue by pallavit** [Azure/autorest.csharp#4243]
More information of the pattern can be found at - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/ProtocolMethods.md

Also, given this change will be a breaking change it is something we will have to absorb before we GA a debranded SDK.

Scope unclear at the moment.

**Comment by annelo-msft** [comment]
The pattern for CancellationTokens in unbranded clients is variously documented here:
- https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/System.ClientModel#customizing-http-requests
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/System.ClientModel/samples/ClientImplementation.md#implementing-protocol-methods
- https://github.com/annelo-msft/gists/blob/main/clientmodel-client/readme.md#client-apis

A short summary is:
- Convenience methods don't take CancellationTokens
- In unbranded clients, passing a CancellationToken is considered an "advanced scenario" -- users who want to do this must set the `CancellationToken` property on `RequestOptions` and call the protocol method.
