### ISSUE TITLE
FormattableStringExpression issues

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#4253]
The same token cannot be specified multiple times which is unlike the behavior of string.Format or string interpolation in C#:

```c#
new FormattableStringExpression("{0}{0}", foo)
```
throws an IndexOutOfRangeException
```
The count of arguments in format {0}{0} does not match with the arguments provided"
```

This is easy to workaround by just specifying multiple arguments.

Another issue is that I can't use type references within a FormattableString,

new FormattableStringExpression(
    "{{{{{0}}}}}{1}",
    new TypeReference(typeof(Environment)).Property(nameof(Environment.NewLine)),
    new TypeReference(typeof(Environment)).Property(nameof(Environment.NewLine)))))))

produces the following:

![image](https://github.com/Azure/autorest.csharp/assets/54595583/0f18229e-648d-4c06-8152-c175db9f2979)

**Comment by JoshLove-msft** [comment]
Ran into these while working on https://github.com/Azure/autorest.csharp/pull/4252/

**Comment by ArcturusZhang** [comment]
@JoshLove-msft the first issue is by-design.
FormattableString works differently from `string.Format`.
For example:
![image](https://github.com/Azure/autorest.csharp/assets/10554446/b7335eb5-c33f-44f1-9bc9-980839bfcc2b)
which will output:
![image](https://github.com/Azure/autorest.csharp/assets/10554446/cff6f6de-fbe2-49f6-b3d5-afa7e15ae8a3)
Therefore you should multiply the same arguments.

The second issue does not really come from the `FormattableStringExpression`, it should come from how compiler works.
We always write the full type name `global::Namespace.Name`, but it looks like, in some cases, the module name should not be specified.
