### ISSUE TITLE
[Microsoft Generator CSharp] Add Flag or Indicator to Method Type to Prevent Generating the Method

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4286]
Original discussion: https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/14#issuecomment-1961748973.

> There are conditions when some of the methods aren't generated: existing implementation in partical class, configuration flags, etc. Should we return null instead or indicate the issue somehow? Keep in mind that there are cases when we need to know signature of the method but don't want to generate method (e.g.: protocol method exists in partial class, convenience method that calls it is generated).

Since there are cases where a `Method` may not need to be generated / written, we should update the `Method` class to have some sort of flag, or make it nullable, to prevent the code writer from generating the class during generation.

**Comment by m-nash** [comment]
I think the way we want to go here is to have the response type of GetMethod be nullable so a plugin can indicate for a given InputOperation there should be no method created.
