### ISSUE TITLE
Invalid word "Acces" gets generated in the method name though the swagger api specs doesn't have them

### ISSUE THREAD

**Issue by DeepikaNMS** [Azure/autorest.csharp#4291]
**Describe the issue or request**

sdk\confluent\Azure.ResourceManager.Confluent\api\Azure.ResourceManager.Confluent.netstandard2.0.cs has the invalid method names that fails the spell check step of the build process. 

Running the below commands generates the file 
dotnet build /t:GenerateCode 
\eng\scripts\Export-API.ps1 confluent

and overriding the method names manually doesn't seem to work

Build failure:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3536466&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f&l=89

Commit where the file is overridden: 
https://github.com/Azure/azure-sdk-for-net/pull/42077/commits/2475155a3b17284e9069c20e166e1629f894bd91#diff-151ba45869bc86940d1eccbf306b257c57b5f5b5a3889e62b1ea798d082ab50b

Swagger API specs reference :
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/confluent/resource-manager/Microsoft.Confluent/stable/2024-02-13

**Describe your ideas for solutions**
Please describe how you think a change or changes might work. Consider
how these changes might work for multiple services.

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by live1206** [comment]
resolved
