### ISSUE TITLE
Nullable `DateTimeOffset` is not parsed from Unix timestamp

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4296]
I need a nullable `utcDateTime` property in TypeSpec, so I defined it like this:

```text
/** The Unix timestamp (in seconds) for when the run was started. */
@encode("unixTimestamp", int32)
started_at: utcDateTime | null;
```

The generated property does correspond to a nullable `DateTimeOffset`, which is great:
```csharp
public DateTimeOffset? StartedAt { get; }
```

But then, in the generated Deserialize method, I get the following:
```csharp
if (property.NameEquals("started_at"u8))
{
    if (property.Value.ValueKind == JsonValueKind.Null)
    {
        startedAt = null;
        continue;
    }
    startedAt = property.Value.GetDateTimeOffset("O");
    continue;
}
```
Notice how there is no conversion from Unix timestamp. In other words, instead of:
```csharp
startedAt = property.Value.GetDateTimeOffset("O");
```

it should be this:
```csharp
startedAt = DateTimeOffset.FromUnixTimeSeconds(property.Value.GetInt64());
```

Interestingly, if I remove the union with null in the TypeSpec, it does correctly generate the call to `DateTimeOffset.FromUnixTimeSeconds` (but understandably I lose the nullability of the `DateTimeOffset` that I need).

**Comment by joseharriaga** [comment]
The `Write` method might have a similar issue.

**Comment by chunyu3** [comment]
The encoding information missing when @encode on a property whose type is Union.
File issue https://github.com/microsoft/typespec/issues/2969 for typespec

**Comment by joseharriaga** [comment]
I have found an issue that sounds similar, but I am not sure if it is actually related:
🔗 https://github.com/Azure/autorest.csharp/issues/4677

**Comment by chunyu3** [comment]
After adopt tcgc, this issue is resolved.
