### ISSUE TITLE
Model with discriminator that defined with 'is' operator - not generated.

### ISSUE THREAD

**Issue by asaflevi-ms** [Azure/autorest.csharp#4304]
(A)
**@discriminator("kind")**
model RadiologyInsightsInference **is** Fhir.R4.Extendible;

All models that extends from RadiologyInsightsInference not generated (only csharp emitter) 

(B)
**@discriminator("kind")**
model RadiologyInsightsInference {
  ...Fhir.R4.Extendible;
}

Models are generated!.

See long thread: https://teams.microsoft.com/l/message/19:acbd512e57bd475198ea6bf4564599e3@thread.skype/1707746708507?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1707412749502&teamName=Azure%20SDK&channelName=AutoRest%20-%20CSharp&createdTime=1707746708507

**Comment by lirenhe** [comment]
@archerzz, I expect this problem will be auto resolved after we apply TCGC in emitter, could you help to confirm?
