### ISSUE TITLE
Finalize on design for Generate.ps1 for mgc

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#4330]
We don't want an exact copy of Generate.ps1, but we should have something that works similarly.

One of the things I would like to do in the new world is have a consistent generation structure

outputfolder
 - project.sln
 - src
   - project.csproj
 - test
   - project.tests.csproj

**Comment by jorgerangel-msft** [comment]
Some other things we should consider:
- We can automate clearing the packages from cache & the plugin's folder until https://github.com/Azure/autorest.csharp/issues/4450 is completed.
- The script should also automate packing the projects.

**Comment by m-nash** [comment]
Punting the folder scaffolding generation to this item https://github.com/Azure/autorest.csharp/issues/4463

**Comment by m-nash** [comment]
for now generate.ps1 will invoke mgc.exe until this item is finished https://github.com/Azure/autorest.csharp/issues/4464

**Comment by m-nash** [comment]
Punting the auto discovery to this item https://github.com/Azure/autorest.csharp/issues/4466
