### ISSUE TITLE
[Microsoft Generator CSharp] Migrate All Unbranded Test Projects

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4333]
As a follow up to https://github.com/Azure/autorest.csharp/issues/4200, all of the remaining [unbranded test projects](https://github.com/Azure/autorest.csharp/tree/feature/v3/test/UnbrandedProjects) should be migrated to the new generator and should serve as the validation when making changes to the generator code.

**Comment by m-nash** [comment]
I want to consider the trade offs with only having cadl-ranch tests with very few exceptions.
