### ISSUE TITLE
[Microsoft Generator CSharp] Convert raw string to expression in writers

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4335]
We should rewrite the logic in writers to use [Expressions](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/AutoRest.CSharp/Common/Output/Expressions) instead of raw string.
For instance: [RequestWriterHelpers](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/RequestWriterHelpers.cs)

**Comment by m-nash** [comment]
Agree with the direction but closing the task as we should review all PRs going into the new generator to replace string with expressions as items move.
