### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: CSProjWriter

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4341]
The [CSProjWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CSProjWriter.cs) class should be migrated and stripped of any branding.

**Comment by m-nash** [comment]
close in favor of https://github.com/Azure/autorest.csharp/issues/4463
