### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: Client Writers

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4342]
The client writer classes should be migrated to the generator. For target specific writers ([DpgClientWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/LowLevel/Generation/DpgClientWriter.cs) + [DataPlaneClientWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/DataPlane/Generation/DataPlaneClientWriter.cs)), we should explore if these classes need to be consolidated into a single common class that exists in the base generator library, or if the ClientWriter base class should be made extensible to plugins to create their own client writers.

Classes:
- [ClientOptionsWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ClientOptionsWriter.cs)
- [ClientWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ClientWriter.cs)
- [RestClientWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/RestClientWriter.cs)

**Comment by m-nash** [comment]
I want to avoid special writers and try to use https://github.com/Azure/autorest.csharp/issues/4346 as our sole writer class.
