### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: Code Writers

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4343]
The code writer classes should be migrated to the generator. If possible, we should explore consolidating any extension methods into the base CodeWriter class.

Classes to migrate:
- [CodeWriterDeclaration](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterDeclaration.cs)
- [CodeWriterExtensions.Methods.cs](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.Methods.cs)
- [CodeWriterExtensions](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.cs)
- [CodeWriterScopeDeclarations](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterScopeDeclarations.cs)
- [DebuggerCodeWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/DebuggerCodeWriter.cs)
- [JsonCodeWriterExtensions](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs)

**Comment by m-nash** [comment]
closing in favor of https://github.com/Azure/autorest.csharp/issues/4346
