### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: Operation Writers

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4348]
We should investigate if the method / operation writer classes should be migrated and stripped of any branding.

Classes to migrate:
- [LongRunningOperationWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/LongRunningOperationWriter.cs)
- [PageableMethodsWriterExtensions](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/PageableMethodsWriterExtensions.cs)

**Comment by m-nash** [comment]
closed in favor of https://github.com/Azure/autorest.csharp/issues/4346
