### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: Model Writers

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4349]
We should investigate if the model related writer classes should be migrated and stripped of any branding.

Classes to migrate:
- [ModelFactoryWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ModelFactoryWriter.cs)
- [ModelWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/ModelWriter.cs)

**Comment by m-nash** [comment]
closed in favor of https://github.com/Azure/autorest.csharp/issues/4346
