### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: PropertyInitializer

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4350]
The [PropertyInitializer](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/PropertyInitializer.cs) class should be migrated and stripped of any branding.

**Comment by m-nash** [comment]
Won't be needed with ValueExpression being used as the new initializer syntax
