### ISSUE TITLE
[Microsoft Generator CSharp] Migrate Writers: SerializationWriter

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4351]
The [SerializationWriter](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/Generation/Writers/SerializationWriter.cs) class should be migrated and stripped of any branding.

**Comment by m-nash** [comment]
closed in favor of https://github.com/Azure/autorest.csharp/issues/4346
