### ISSUE TITLE
[Microsoft Generator CSharp] Remove SourceInputModel._existingCompilation property

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4354]
Remove `SourceInputModel._existingCompilation` property as it is a duplicate of the `Customization` and `PreviousContract` properties in this class.

Please refer [this](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/20#discussion_r1513767292) for more details.

**Comment by m-nash** [comment]
The goal here is to have one object representing the previous contract and one object representing the cusotmizations.  We want to use those to not emit things that would have been removed by the current prost processing thereby getting a perf boost.
