### ISSUE TITLE
Fix File Input Parsing

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4443]
There is a bug in the file input parsing of configuration.json and the codemodel.json files. The path given as a positional argument to mgc should be able to construct the `src/Generated` sub-directory to find the files in the case that the supplied path doesn't contain the input files. ie. `mgc ./path1/` where `./path1/src/Generated` contains the configuration and codemodel.json files should work fine and not result in a file not found error.

**Comment by m-nash** [comment]
@jorgerangel-msft can you mark this as fixed with your current configuration pr
