### ISSUE TITLE
Convert Plugin Extensibility Code into a Writer

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4451]
We have [code](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/blob/main/Microsoft.Generator.CSharp/src/CSharpGen.cs#L73) in the generator that was added to demonstrate the extensibility of a plugin, and call it's extension methods to write expressions + statements. This should be converted into its own Writer class.

**Comment by m-nash** [comment]
I think we have made it to a point where the plugins do their own demonstration and we can remove this.
