### ISSUE TITLE
[Microsoft Generator CSharp] Generate Methods for Model types

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4476]
Generate methods for model types. As part of this task, relocate the necessary Output types from [this location](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/AutoRest.CSharp/Common/Output) as required, and generate methods for model classes in the [Unbranded-TypeSpec](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/tree/main/Microsoft.Generator.CSharp.ClientModel.TestProjects/Unbranded-TypeSpec) project.

**Comment by jorgerangel-msft** [comment]
Follow up changes will be covered in https://github.com/microsoft/typespec/issues/3329.
