### ISSUE TITLE
[ClientModel-based clients] Remove remaining "Azure" references from unbranded clients.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#4481]
"Azure" still appears a few places in refdocs and exception messages.

**Comment by m-nash** [comment]
https://github.com/annelo-msft/openai-in-typespec/pull/1#discussion_r1539944972

**Comment by m-nash** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/System.ClientModel/samples/ClientImplementation.md
