### ISSUE TITLE
[FEATURE REQ] Add support to @azure-tools/typespec-autorest

### ISSUE THREAD

**Issue by quentinRobinson** [Azure/autorest.csharp#4495]
## Library name
azure-tools/typespec-autorest

## Please describe the feature.
I've added a decorator `@example` in my typespec described in [typespec-autorest](https://azure.github.io/typespec-azure/docs/emitters/typespec-autorest/reference/decorators), but dotnet code generation fails with `error import-not-found: Couldn't resolve import "@azure-tools/typespec-
  autorest`. Want to have this package added to the [emitter-package.json](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/emitter-package.json)

**Comment by aurghob** [comment]
Hi, We cannot test our may preview and GA typespec changes properly in https://github.com/quentinRobinson/azure-rest-api-specs/pull/1 until this issue is addressed

**Comment by pshao25** [comment]
`@azure-tools/typespec-autorest` is not a requirement to call `@azure-tools/typespec-csharp`, therefore we can not add it. You could install it yourself by running `npm install`.
