### ISSUE TITLE
Add support for generating structs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#452]
`GenerateCode` currently only generates classes, not structs.  I'll need to be able to generate stucts to sidestep performance issues.

**Comment by heaths** [comment]
One way of achieving this (not yet supported) would be to use the `CodeGenSchemaAttribute`, like so:
```csharp
using Azure.Core;

namespace Azure.Search.Models
{
    [CodeGenSchema("ListDataSourcesResult")]
    internal partial struct ListDataSourcesResult
    {
    }
}
```
