### ISSUE TITLE
Method signature (alias / spread) Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#4543]

**Comment by archerzz** [comment]
This task depends on adoption of TCGC `getAllOperations()` #3994 . And if we're luck, we don't need to do extra work here.

**Comment by archerzz** [comment]
There is a way to not rely on TCGC. Check the PR #4778. The concerns are the breaking changes most of which should be resolved by https://github.com/Azure/typespec-azure/issues/771
