### ISSUE TITLE
[ClientModel-based clients] Setting `unreferenced-types-handling: keepAll` in tspconfig.yaml results in build error

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4553]
If I set `unreferenced-types-handling: keepAll` in the tspconfig.yaml and re-generate, two internal files are added:
- src/Generated/Internal/RequestContentHelper.cs
- src/Generated/Internal/Utf8JsonRequestBody.cs

These files are not actually used, but the `Utf8JsonRequestBody` class causes a build error. More specifically, the problem is the following line in the constructor:
`_content = Create(_stream);` 

This is because the `Create` method that takes a `MemoryStream` does not exist.

**Comment by ArcturusZhang** [comment]
Thank you for the feedback @joseharriaga .
This is caused by the API changes in System.ClientModel.
We will change the generator to let it no longer generate these two classes.
