### ISSUE TITLE
Create CreateMessage method for an input operation

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4583]
As a follow up of creating the initial MethodCollection, a CreateMessage/CreateRequest method should be constructed that constructs a request for a protocol method and should be added to the method collection for an input operation. Generated sample in the unbranded test project: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Unbranded-TypeSpec/src/Generated/UnbrandedTypeSpecClient.cs#L1260

**Comment by m-nash** [comment]
closing in favor of https://github.com/Azure/autorest.csharp/issues/4561
