### ISSUE TITLE
We should pre-encode property names we write to JsonWriter

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#460]
When we write property names to a `JsonWriter`, it's more efficient to pre-encode them like we did for Key Vault since, for example. `WritePropertyName` is going to do it each time anyway:
```csharp
        private static readonly JsonEncodedText s_hsmPropertyNameBytes = JsonEncodedText.Encode(HsmPropertyName);

// ...

            if (Properties._tags != null && Properties._tags.Count > 0)
            {
                json.WriteStartObject(s_tagsPropertyNameBytes);

                foreach (KeyValuePair<string, string> kvp in Properties._tags)
                {
                    json.WriteString(kvp.Key, kvp.Value);
                }

                json.WriteEndObject();
            }
```

**Comment by heaths** [comment]
A contributor submitted a PR to this effect as well: https://github.com/Azure/azure-sdk-for-net/pull/10284

**Comment by heaths** [comment]
I wrote some simple benches using either `JsonEncodedText` or just a `string` passed to `Utf8JsonWriter.WriteString` and the results were a little surprising:

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.329 (2004/?/20H1)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.301
  [Host]     : .NET Core 2.1.19 (CoreCLR 4.6.28928.01, CoreFX 4.6.28928.04), X64 RyuJIT
  Job-FKFYJS : .NET Core 2.1.19 (CoreCLR 4.6.28928.01, CoreFX 4.6.28928.04), X64 RyuJIT
  Job-QDPPAY : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
```

|          Method |        Job |       Runtime |     Toolchain | Iterations |        Mean |     Error |    StdDev |      Median | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------- |----------- |-------------- |-------------- |----------- |------------:|----------:|----------:|------------:|------:|--------:|-------:|------:|------:|----------:|
| JsonEncodedText | Job-FKFYJS | .NET Core 2.1 | netcoreapp2.1 |          1 |    806.2 ns |  20.11 ns |  48.95 ns |    796.5 ns |  1.73 |    0.10 | 0.2174 |     - |     - |     912 B |
|          String | Job-FKFYJS | .NET Core 2.1 | netcoreapp2.1 |          1 |    468.4 ns |   8.71 ns |   8.15 ns |    466.2 ns |  1.00 |    0.00 | 0.1860 |     - |     - |     784 B |
| JsonEncodedText | Job-QDPPAY | .NET Core 3.1 | netcoreapp3.1 |          1 |    658.5 ns |   2.48 ns |   1.94 ns |    658.7 ns |  1.41 |    0.03 | 0.2136 |     - |     - |     896 B |
|          String | Job-QDPPAY | .NET Core 3.1 | netcoreapp3.1 |          1 |    342.5 ns |   7.44 ns |   9.67 ns |    344.0 ns |  0.73 |    0.03 | 0.1874 |     - |     - |     784 B |
|                 |            |               |               |            |             |           |           |             |       |         |        |       |       |           |
| JsonEncodedText | Job-FKFYJS | .NET Core 2.1 | netcoreapp2.1 |        100 | 16,457.3 ns | 323.78 ns | 513.55 ns | 16,117.3 ns |  0.77 |    0.03 | 1.6785 |     - |     - |    7096 B |
|          String | Job-FKFYJS | .NET Core 2.1 | netcoreapp2.1 |        100 | 21,683.2 ns | 262.58 ns | 219.27 ns | 21,572.8 ns |  1.00 |    0.00 | 1.6479 |     - |     - |    6968 B |
| JsonEncodedText | Job-QDPPAY | .NET Core 3.1 | netcoreapp3.1 |        100 | 12,500.8 ns | 240.50 ns | 257.33 ns | 12,573.1 ns |  0.58 |    0.01 | 1.6785 |     - |     - |    7080 B |
|          String | Job-QDPPAY | .NET Core 3.1 | netcoreapp3.1 |        100 | 14,756.0 ns | 289.97 ns | 476.43 ns | 14,840.1 ns |  0.68 |    0.03 | 1.6479 |     - |     - |    6968 B |

The single iteration result was expected - there is a one-time overhead cost - but even after a 100 iterations the improvement was negligable.

**Comment by heaths** [comment]
Per offline discussion, may only be worth opting into (via flag or something) if models are serialized a lot, like maybe in some cases for Storage, etc.

**Comment by pakrym** [comment]
Closing until we find a real need.
