### ISSUE TITLE
Else if statement

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#4615]
Is there any support for writing an if else statement like this (inlining the second if statement so that it is an else if)

```c#
if (condition) 
{
...
}
else if (condition)
{
...
}
```

I couldn't figure out how to do this using an IfElseStatement. Can this be supported?

**Comment by ArcturusZhang** [comment]
Yes we already support this. You could write this in this way:
```csharp
var statement = new IfElseStatement(
	new IfStatement(condition1)
	{
		// statements for your if
	},
	// this is the else statement
	new IfStatement(condition2)
	{
		// statements for your first else if
	})
```
If you want more `else if`, you could just use another `IfElseStatement` as the `Else` part:
```csharp
var statement = new IfElseStatement(
	new IfStatement(condition1)
	{
		// statements for your if
	},
	// this is the else statement
	new IfElseStatement(
		new IfStatement(condition2)
		{
			// statements for your first else if
		},
		new IfElseStatement(
			new IfStatement(condition3)
			{
				// statements for your second else if
			},
			new MethodBodyStatement[] {
				// statements for your else
			})));
```
this will write:
```
if (condition1)
{
		// statements for your if
}
else if (condition2)
{
			// statements for your first else if
}
else if (condition3)
{
				// statements for your second else if
}
else
{
				// statements for your else
}
```

**Comment by JoshLove-msft** [comment]
I must be doing something wrong - https://github.com/Azure/autorest.csharp/pull/4649/files#diff-e951b5dd9fe84a348c5597b47c30f38972a39dce8d6659979415eafff9ac77daR292

results in https://github.com/Azure/autorest.csharp/pull/4649/files#diff-b5885dc51aea9777fab38b62bda018e5b0fd20dd6fb9f887fd3878639c61c6c9R490-R524

**Comment by ArcturusZhang** [comment]
> I must be doing something wrong - [#4649 (files)](https://github.com/Azure/autorest.csharp/pull/4649/files#diff-e951b5dd9fe84a348c5597b47c30f38972a39dce8d6659979415eafff9ac77daR292)
> 
> results in [#4649 (files)](https://github.com/Azure/autorest.csharp/pull/4649/files#diff-b5885dc51aea9777fab38b62bda018e5b0fd20dd6fb9f887fd3878639c61c6c9R490-R524)

yes from the generated code, we are having:
```csharp
if (...)
{
	// ...
}
else
{
	if (...)
	{
		// ...
	}
}
```
which just works but it is not ideal, somewhere is wrong.

**Comment by ArcturusZhang** [comment]
Since we have moved to MGC and this has a workaround - I believe our new mechanism does  not have this issue (I assume?), I would like to close this issue
