### ISSUE TITLE
[Microsoft Generator CSharp] Exclude Setter Generation for Collection Properties

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4616]
Collection properties are currently generating setters. To address this, please add logic in the `ModelTypeProvider.BuildProperties()` method to exclude setter generation for collection properties.

**Comment by jorgerangel-msft** [comment]
Original discussion: https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/pull/51#discussion_r1575046794
