### ISSUE TITLE
The doc comment for the `ApiKeyCredential` parameter in an unbranded client constructor mentions Azure

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4619]
See here for an example here: 
🔗 https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Platform-OpenAI-TypeSpec/src/Generated/OpenAIClient.cs#L31

Maybe instead of saying: "A credential used to authenticate to an Azure Service," we can change it to simply say: "A credential used to authenticate to the service."

**Comment by ArcturusZhang** [comment]
Hi @joseharriaga I changed the description to:
```
A credential used to authenticate to the service.
```
what do you think about this?
