### ISSUE TITLE
[Microsoft CSharp Generator] Remove `Constant` from the generator

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4622]
The type `Constant` is created pre-expression era in our generator which is designed to stand for a constant value from a given object or empty values.
Since we now have the expressions which provides more flexibility to represent things like that, we do not really need the type `Constant` and its shimming layer in our expression system `ConstantExpression`.

For instance, if we want to represent a default value of literal string, there is a `StringLiteralExpression` that takes in a string value and it will write itself in a way of literal string: `"<value>"`, etc. If we want to represent `null` or `default`, we have `KeywordExpression` for that.

In nowhere do we need this `Constant` any more. Therefore we should find an opportunity to remove it and should not introduce it again in `MGC`

**Comment by m-nash** [comment]
Fixed by https://github.com/microsoft/typespec/pull/3248
