### ISSUE TITLE
Duration with `@encode("seconds", float64)` is treated as Int32

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4677]
Consider the following model with a `duration` property:

```text
model Foo {
  @encode("seconds", float64)
  duration: duration;
}
```

Both the serialization and deserialization code generated for this property treat it as int32 instead of float64:

Write method:
```csharp
writer.WriteNumberValue(Convert.ToInt32(Duration2.ToString("%s")));
```

DeserializeFoo method:
```csharp
duration = TimeSpan.FromSeconds(property.Value.GetInt32());
```

**Comment by ArcturusZhang** [comment]
Hi @joseharriaga thanks for reporting this, I will take a look and provide a fix.
