### ISSUE TITLE
refactor(typespec): clean up input primitive types

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#4681]
## Description

This is a follow-up of #4300
In [InputPrimitiveTypeKind.ts](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/TypeSpec.Extension/Emitter.Csharp/src/type/inputPrimitiveTypeKind.ts), there are several issues:
- we mix types with encoding
- there are a few types which C# doesn't support, like `Object`

We should refactor to make primitive type more specific.

**Comment by ArcturusZhang** [comment]
has been resolved in https://github.com/Azure/autorest.csharp/pull/4707
