### ISSUE TITLE
[Duration] Is it by design that our float duration always serializes into a number with 3 digits?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#4695]
**Describe the issue or request**

We are using a `s\\.fff` formatter to serialize a `TimeSpan` into payload. The `s` means we write the whole seconds, and the `fff` suffix means that we keep 3 digits after the `.`
For instance, if the duration is "1 minute and 32.4 seconds", this will write to a number: `92.400` (`fff` means we always have 3 digits, adding 0 if not enough).

Is this expected? Or cadl-ranch case happens to pass because the number they use happens to have 3 digits.

If not, we should change the specifier to `s\\.FFF` because this will not append zeroes.

**Comment by archerzz** [comment]
What's the expected standard we should follow? (like RFC3337, etc)

**Comment by ArcturusZhang** [comment]
> What's the expected standard we should follow? (like RFC3337, etc)

I do not know in the seconds case, because the result is just a number, no specific "format" in it.
