### ISSUE TITLE
Emitter needs to adopt TCGC's recent changes on `nullable`

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#4701]
TCGC will label `Nullable` on property/parameter instead of type.
Codegen emitter will adapt this:

- update emitted model, apply `Nullable` on property/parameter
- update inputModel in autorest.csharp accordingly.
- Still label `Nullable` in CsharpType, update the TypeFactory.cs to pass `Nullable` parameter when create CsharpType.

**Comment by ArcturusZhang** [comment]
we could take this opportunity to review and refine the design of our input types as well

**Comment by ArcturusZhang** [comment]
Also this should fix https://github.com/Azure/autorest.csharp/issues/4314

**Comment by archerzz** [comment]
Latest decision is to deprecate all `nullable`, and return union for nullable types in TCGC. There will be a helper function `isNullable` to help check if the type is nullable. For details, see https://github.com/Azure/typespec-azure/pull/870
