### ISSUE TITLE
bug(build): regen pipeline always failed with `error : spawn EINVAL`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#4729]
## Problem

Our [regen pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5990&_a=summary) started to fail since last Friday. And it failed at the same SDK `Azure.ResourceManager.HealthResource` (https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3802422&view=logs&j=22d114d9-e1b7-5381-70ab-ddaabfa32a9d&t=1eb743b7-6600-5425-47d2-d44920e345d6&l=2231)
```
EXEC : error   | error : spawn EINVAL [D:\a\_work\1\s\azure-sdk\sdk\resourcehealth\Azure.ResourceManager.ResourceHealth\src\Azure.ResourceManager.ResourceHealth.csproj]

```

**Comment by ArcturusZhang** [comment]
This should have been resolved by @hallipr
