### ISSUE TITLE
Enable returning different type from Pageable

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#473]
When wrapping generated types, I'd like to return the wrapper as T in Pageable<T>.  Currently, I need to copy the method from AllOperations and wrap the type myself.  Would be great to be able to do this in the C# transform

**Comment by pakrym** [comment]
This might be a too advanced of an optimization for the generator to handle.

**Comment by annelo-msft** [comment]
FYI @kinelski , @maririos
