### ISSUE TITLE
Handle "" as accepted value for NextLink in Pageables

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#474]

**Comment by MiYanni** [comment]
@annelo-msft According to the docs, if there is no nextLinkName, you are supposed to specify `null`: https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-pageable
We don't actually control this mechanism. It is AutoRest (specifically ModelerFour) that does.

**Comment by pakrym** [comment]
@miyanni this issue is about treating empty as end of enumeration here https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/PageableHelpers.cs#L87
