### ISSUE TITLE
'ClientDiagnostics' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by matteogll** [Azure/autorest.csharp#4758]
**Compile error after generating classes using AutoRest for C#**
I've just followed the basic documentation here: https://github.com/Azure/autorest/blob/main/docs/generate/readme.md
And in the generated "MyClassAPIClient.cs" I got the compiler error
`'ClientDiagnostics' is inaccessible due to its protection level`
in the row 
`internal ClientDiagnostics ClientDiagnostics { get; }`

**Describe your ideas for solutions**
Does AutoRest requires a particular vesion of Azure.Core?

**Comment by ArcturusZhang** [comment]
Hi @matteogll thank you for reporting this.

now the SDK is expecting some source code as compilation time source code from Azure.Core, therefore you need to put them somewhere in your local library and add those files into your `csproj` file using `Compile Include` clause.

You could find those files in this directory: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core/src/Shared

Previously these files are provided by the generator, therefore you just need to add the generator as a private asset of your generated library, you will automatically get those shared files, but there was a structural change a few months ago and you have to do the thing I described above.

It is inconvenient and we are also trying to find a way to decouple it as well
