### ISSUE TITLE
Remove GroupedBy from InputParameter

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4779]
**Describe the issue or request**
Please describe the issue or feature request.
[InputParameter.GroupedBy](https://github.com/Azure/autorest.csharp/blob/03d3cc83dd33cce6347227622e7a0eb4ec4ac544/src/AutoRest.CSharp/Common/Input/InputTypes/InputParameter.cs#L15) is used to hold the information of [swagger usage](https://github.com/Azure/azure-rest-api-specs/blob/c3cc9abe085093ba880ee3eeb792edb4fa789553/specification/policyinsights/resource-manager/Microsoft.PolicyInsights/stable/2021-01-01/attestations.json#L387).
Given typespec doesn't support `GroupedBy` yet, we should remove it from `InputParameter`.

**Describe your ideas for solutions**
Create the grouped type in advance in the converter, and put it in `InputParameter` for the grouped parameters.

**Comment by live1206** [comment]
Removing `Groupedby` from `InputParameter` only doesn't fix this issue completely, we need to handle the below in autorest.csharp for swagger input scenario, I will work on that part.
> Create the grouped type in advance in the converter, and put it in InputParameter for the grouped parameters.

**Comment by jorgerangel-msft** [comment]
@live1206  - I see. This was on the mgc board so we thought this was applicable only to mgc, so we went ahead and moved it into our current sprint. I have a PR open to remove the param in mgc. If it's better for tracking, I can separate this issue into two. Do let me know.
