### ISSUE TITLE
SCM ClientUriBuilder prepends an extra '?' to query strings on net481

### ISSUE THREAD

**Issue by trrwilson** [Azure/autorest.csharp#4815]
**Impact**: clients using `ClientUriBuilder` produce malformed URIs that may be rejected by their target services. Azure OpenAI is one such service and Azure.AI.OpenAI 2.0.0-beta.1, by virtue of always having an `api-version` query string parameter, is currently broken on net481.

Pre-net5.0, the lackluster `System.UriBuilder` type always auto-prepends a `?` when query string parameter information is present, irrespective of whether or not the query string information already has it; this is in contrast to net5.0+, which only auto-prepend the `?` if one isn't already present:

https://learn.microsoft.com/en-us/dotnet/api/system.uribuilder.query?view=net-8.0#remarks

> To append a value to existing query information in .NET Framework, **you must remove the leading question mark before setting the property with the new value.** This is because .NET Framework always prepends the question mark when setting the property. .NET 5 (and .NET Core) and later versions are tolerant to a leading question mark, and will only prepend one if necessary.

(Bolded emphasis mine)

`ClientUriBuilder`, per the following, *invariantly* adds a `?` the first time it appends query string information. That means, pre-net5.0, it always produces a malformed request URI with two `??` before the query string.

https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/NoTest-TypeSpec/src/Generated/Internal/ClientUriBuilder.cs

```csharp
        if (QueryBuilder.Length == 0)
        {
            QueryBuilder.Append('?');
        }
```

Here's a minimal project that demonstrates the repro; it's in an initial repro state and also includes, commented out, a speculative fix to wrap the above `Append` inside of an `#if NET` block.

[ClientUriBuilderRepro.zip](https://github.com/user-attachments/files/15795342/ClientUriBuilderRepro.zip)

Without any changes:
```
PS C:\Users\travisw\AppData\Local\Temp\netfxtest> dotnet run --framework net6.0;dotnet run --framework net481
https://www.microsoft.com/test/operation?api-version=foo
https://www.microsoft.com/test/operation??api-version=foo
```

With the speculative change:
```
PS C:\Users\travisw\AppData\Local\Temp\netfxtest> dotnet run --framework net6.0;dotnet run --framework net481
https://www.microsoft.com/test/operation?api-version=foo
https://www.microsoft.com/test/operation?api-version=foo
```

I believe this is the proper location for an actual fix:
https://github.com/Azure/autorest.csharp/blob/9f4cf3b59d18e934329ecdc9181bfff13a0d0131/src/AutoRest.CSharp/Common/Output/Models/Types/HelperTypeProviders/System/ClientUriBuilderProvider.cs#L225

**Comment by trrwilson** [comment]
@ralph-msft (whom discovered this) pointed out that a conditional compilation check like tried *will not* help in single-target netstandard2.0 libraries; without separate targeting of the impacted library, the `#if NET` path will never exist. He had favorable results trying a runtime check for `System.Environment.Version.Major < 5`.

**Comment by ArcturusZhang** [comment]
Hi @trrwilson I opened a PR that could fix this issue: https://github.com/Azure/autorest.csharp/pull/4818
As you suggested, we just need to let the `ClientUriBuilder` never adds a `?` and let the `System.UriBuilder` do all the work.

**Comment by ArcturusZhang** [comment]
@trrwilson the issue has been fix by never adding a question mark.
The latest version is [v3.0.0-beta.20240613.2](https://github.com/Azure/autorest.csharp/releases/tag/v3.0.0-beta.20240613.2)
