### ISSUE TITLE
Check the usage of readonly property type in RoundTrip model for DPG

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4820]
TSP:
```ts
  model ResultModel {
    name: string;
  }

  model RoundTripModel {
    @visibility("read")
    result: ResultModel;
  }

  @route("/modelInReadOnlyProperty")
  @put
  op modelInReadOnlyProperty(@body body: RoundTripModel): {
    @body body: RoundTripModel;
  };
```

detailed case can be found in this pr: https://github.com/Azure/cadl-ranch/pull/587

In this case, usage for `ResultModel` should be `Output` instead of `RoundTrip`, because this model is readonly.

**Comment by ArcturusZhang** [comment]
In current DPG's implementation, ResultModel is generated as a `RoundTrip` model. Therefore we need a fix

**Comment by ArcturusZhang** [comment]
Also in today's offline sync up, we kind of have an agreement on the patch convenience methods, therefore we have a way to use the usage from TCGC directly therefore we could expect a final fix for this.

**Comment by ArcturusZhang** [comment]
This should have fixed this issue despite we did not know quite well which part introduces the fix.
But from the result's perspective, this is fixed.

**Comment by live1206** [comment]
> [This](https://github.com/Azure/autorest.csharp/pull/4790) should have fixed this issue despite we did not know quite well which part introduces the fix. But from the result's perspective, this is fixed.

Are you saying csharp emitter has not consumed TCGC usage yet, but the usage still got fixed?

**Comment by ArcturusZhang** [comment]
> > [This](https://github.com/Azure/autorest.csharp/pull/4790) should have fixed this issue despite we did not know quite well which part introduces the fix. But from the result's perspective, this is fixed.
> 
> Are you saying csharp emitter has not consumed TCGC usage yet, but the usage still got fixed?

that statement is not fully correct. We converted the usage value from TCGC to ours (like [this](https://github.com/Azure/autorest.csharp/blob/c875f2eac3eaa0995ffdb0bb8f1ab77dd4d9719e/src/TypeSpec.Extension/Emitter.Csharp/src/lib/converter.ts#L114C20-L114C34)) - therefore when tcgc has the fix, we get the changes in DPG as well.

**Comment by live1206** [comment]
> > > [This](https://github.com/Azure/autorest.csharp/pull/4790) should have fixed this issue despite we did not know quite well which part introduces the fix. But from the result's perspective, this is fixed.
> > 
> > 
> > Are you saying csharp emitter has not consumed TCGC usage yet, but the usage still got fixed?
> 
> that statement is not fully correct. We converted the usage value from TCGC to ours (like [this](https://github.com/Azure/autorest.csharp/blob/c875f2eac3eaa0995ffdb0bb8f1ab77dd4d9719e/src/TypeSpec.Extension/Emitter.Csharp/src/lib/converter.ts#L114C20-L114C34)) - therefore when tcgc has the fix, we get the changes in DPG as well.

OK. Then we know the fix is from TCGC.
