### ISSUE TITLE
The custom code generated automatically for mitigating breaking changes is not accurate 

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#4826]
The case is here https://github.com/Azure/azure-sdk-for-net/pull/44467/files#diff-cc4bec63a98455b4bd465c37ca781621676bb74c253802662c77980de56aacb8
The original method is:
``` C#
public virtual ArmOperation StopProtection(WaitUntil waitUntil, CancellationToken cancellationToken = default)
```

The new version added 2 new parameters into the existing `StopProtection` method, like this
``` C#
public virtual ArmOperation StopProtection(WaitUntil waitUntil, StopProtectionContent content = null, string xMsAuthorizationAuxiliary = null, CancellationToken cancellationToken = default)
```

Then the codegen generate a new method in the custom code is:
``` C#
public virtual ArmOperation StopProtection(WaitUntil waitUntil, StopProtectionContent content = null, CancellationToken cancellationToken = default)
```
That still case ApiCompat error.

**Comment by live1206** [comment]
The codegen only handles breaking changes for Model Factory for now.
This case is tracked in https://github.com/Azure/autorest.csharp/issues/4018.
