### ISSUE TITLE
[bug]: parameter name matching should be case-insensitive

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#4906]
## Problem

In our codes, when determining the parameter name, we have the following codes: https://github.com/Azure/autorest.csharp/blob/4b09bd2b26ad50009cabd1cf469618a18f85a71e/src/AutoRest.CSharp/Common/Output/Models/Shared/Parameter.cs#L134

Apparently, that doesn't work in some cases, because a parameter name is normally with initial letter lower case, and type name is always with initial letter upper case, e.g. `modelToRename` v.s. `ModelToRename`.

For example, the `Azure.Communication.CallingServer` has an incorrect parameter name: https://github.com/Azure/azure-sdk-for-net/blob/2c14024279f0d853403d65bd02e020f8b095643a/sdk/communication/Azure.Communication.CallingServer/src/Generated/ServerCallingRestClient.cs#L40
```csharp
internal HttpMessage CreateCreateCallRequest(CreateCallRequestInternal createCallRequest)
```
The parameter should be `createCallRequestInternal` instead of `createCallRequest`. `CreateCallRequestInternal` is renamed from `CreateCallRequest`: https://github.com/Azure/azure-sdk-for-net/blob/2c14024279f0d853403d65bd02e020f8b095643a/sdk/communication/Azure.Communication.CallingServer/src/Models/TransferToParticipantRequestInternal.cs#L8-L9
So, the parameter name should follow the change.

---

Here is a list of SDKs which have incorrect parameter names:
SDK | Type | Details
-- | -- | --
Azure.Communication.CallAutomation | DPG | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/2c14024279f0d853403d65bd02e020f8b095643a/sdk/communication/Azure.Communication.CallAutomation/src/Models/CreateCallRequestInternal.cs#L8-L9
Azure.Communication.CallingServer | DPG | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/2c14024279f0d853403d65bd02e020f8b095643a/sdk/communication/Azure.Communication.CallingServer/src/Models/TransferToParticipantRequestInternal.cs#L8-L9
Azure.DigitalTwins.Core | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/digitaltwins/Azure.DigitalTwins.Core/src/Customized/Models/CreateModelsOptions.cs#L8-L9
  |   | Even with compilation error
Azure.Maps.Rendering | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/maps/Azure.Maps.Rendering/src/Models/MapTileIndex.cs#L11-L12
  |   | Even with conpilation error
Azure.Maps.Search | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/maps/Azure.Maps.Search/src/Models/BatchRequestInternal.cs#L13-L14
Azure.MixedRealtiy.Authentication | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/mixedreality/Azure.MixedReality.Authentication/src/Customizations/MixedRealityTokenRequestOptions.cs#L9-L10
Azure.Search.Documents | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L19-L20
Azure.Storage.Blobs | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/storage/Azure.Storage.Blobs/src/Models/BlobServiceProperties.cs#L12-L13
Azure.Storage.Files.Shares | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/storage/Azure.Storage.Files.Shares/src/Models/ShareFileRequestConditions.cs#L11-L12
Azure.Storage.Queues | HLC | Due to renaming by   [CodeGenModel]:   https://github.com/Azure/azure-sdk-for-net/blob/452d0e1930fdd28eb4763be70eb58f9448a045e3/sdk/storage/Azure.Storage.Queues/src/Models/QueueServiceProperties.cs#L12-L13
Azure.ResourceManager.StorageCache | MGMT | Need investigation

**Comment by ArcturusZhang** [comment]
well this is yet another "magic renaming logic" in our generator.
My opinion is that in general, we should not do it, instead we should explicitly add the `@@clientName` in tsp if the input is tsp.
If possible we should limit this piece of code to only work for HLC.
