### ISSUE TITLE
Accept request header does not include multiple content types or allow overriding default value

### ISSUE THREAD

**Issue by swathipil** [Azure/autorest.csharp#4941]
In [[this typespec](https://github.com/swathipil/azure-rest-api-specs/blob/main/specification/schemaregistry/SchemaRegistry/main.tsp)], [[this operation](https://github.com/swathipil/azure-rest-api-specs/blob/cbbe228fd422db02b65e2748f83df5f2bcad7581/specification/schemaregistry/SchemaRegistry/main.tsp#L96)] accepts [[multiple content types](https://github.com/swathipil/azure-rest-api-specs/blob/cbbe228fd422db02b65e2748f83df5f2bcad7581/specification/schemaregistry/SchemaRegistry/main.tsp#L177)] in the response. However, it seems that only one is specified by design in the generated code.

In Python, the request headers can optionally be passed in to override the default values. For example, the Accept request header by default is set to `application/json`. However, a string of multiple content types was specified instead to override the default, seen [[here](https://github.com/Azure/azure-sdk-assets/blob/a1c9d18bfdf6b1ce1c14a90c208ee6d098d7cba3/python/sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_basic%5BCustom%5D.json#L35)].

In C#, I would expect that it's possible to pass in/override the default Accept request header and provide other values.

**Comment by archerzz** [comment]
@swathipil In recent updates of generator, this issue should have been fixed. You can check the latest generated C# SDK codes: https://github.com/Azure/azure-sdk-for-net/blob/b7cbdb100c78b6ba4de45e9fc4b3d854271ef3ee/sdk/schemaregistry/Azure.Data.SchemaRegistry/src/Generated/SchemaRegistryClient.cs#L40

Now the `GetSchemaById` method has an `accept` parameter.

```csharp
internal virtual async Task<Response<BinaryData>> GetSchemaByIdAsync(string id, string accept, CancellationToken cancellationToken = default)
```
