### ISSUE TITLE
[MPG] Generate wrong property name when the property name in TSP is `url`

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#4949]
In this [example](https://github.com/Azure/azure-rest-api-specs/blob/4d8b76eb4c8bcfda28784bc429b9624e5788f564/specification/devopsinfrastructure/Microsoft.DevOpsInfrastructure.Management/main.tsp#L103), the property name in the generated .Net SDK is weird:
![image](https://github.com/user-attachments/assets/7a292848-84e4-426b-ab14-0b65c3b9066e)

This can be fixed by renaming in client.tsp
![image](https://github.com/user-attachments/assets/cffaa3f8-793d-4006-8b72-6e8f53aab850)

So guessing this is a codegen bug.

**Comment by ArcturusZhang** [comment]
This is showing up here as well: https://github.com/Azure/azure-sdk-for-net/pull/45242
![image](https://github.com/user-attachments/assets/3db4a015-b56d-4cdf-b3cc-d5148248aa99)
