### ISSUE TITLE
[defect]System.InvalidOperationException: Unable to find object property with serialized name 'value' in schema SavingsPlanModelListResult

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#4975]
When generate `billing\Azure.ResourceManager.Billing` sdk (target package: package-2024-04), the generate fail.
error:

```
fatal   | System.InvalidOperationException: Unable to find object property with serialized name 'value' in schema SavingsPlanModelListResult
     at AutoRest.CSharp.Output.Models.Types.SchemaObjectType.GetPropertyBySerializedName(String serializedName, Boolean includeParents) in D:\a\_work\1\s\autorest.
csharp\src\AutoRest.CSharp\Common\Output\Models\Types\SchemaObjectType.cs:line 679
```

**Comment by ArcturusZhang** [comment]
why this is flagged with dpg when the issue happens to a mgmt library?

**Comment by chunyu3** [comment]
> t set `includeParents=false`

Actually it is in common when handle PagingResponse, the `ModelTypeProvider` also ignore parents. DPG should also has this problem also. Need investigation.
