### ISSUE TITLE
--debug Not Forwarded to tsp-client

### ISSUE THREAD

**Issue by trangevi** [Azure/autorest.csharp#5000]
**Describe the issue or request**
When calling `dotnet build /t:GenerateCode --debug`, it seems the debug flag isn't being passed into the underlying tsp-client call. I've been having an issue attempting to run the command where the underlying tsp-client call seems to be failing, based on conversation with Catalina Peralta and Michael Nash, and providing the flag doesn't provide any additional information on what is happening.

**Describe your ideas for solutions**
I don't know the details of how the underlying command is called, but hopefully it's a simple matter to pass it through.

**Add labels**
I added the 'workaround-hard' label as I believe the only workaround would be to call the underlying commands directly, which most folks probably won't know how to do.

**Comment by ArcturusZhang** [comment]
actually there is a way to forward the debug flag to tsp-client, but not in this way.
You should do:
```
dotnet build /t:GenerateCode /p:Debug=true
```

**Comment by ArcturusZhang** [comment]
> actually there is a way to forward the debug flag to tsp-client, but not in this way. You should do:
> 
> ```
> dotnet build /t:GenerateCode /p:Debug=true
> ```
> 
> Please note this is only debugging the `tsp-client`, not debugging the generator.

therefore I think we are forwarding the `--debug` option in a "dotnet build" fashion therefore I think this should resolve your current issue unless you are seeking a way of debugging the generator.
