### ISSUE TITLE
bug(build): dependency conflict when using `TypeSpecNext`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest.csharp#5066]
## Description

All our nightly build failed. A sample is https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4130610&view=results

The root cause is the dependency conflict when running `npm ls -all`: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4130610&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=164b9cb9-850d-5194-a052-63f5151be232&l=79

Azure devops pipeline UI will remove colored output. The following screen snapshot from local experiment will make it clear:
![image](https://github.com/user-attachments/assets/0d82a72d-b8e9-4db3-b7d8-80d40eacec1d)

---

I think it's quite obvious. After moving all emitter code to `microsoft/typespec`, we have an extra upstream dependency on `@typespec/http-client-csharp`. Here we bumped all depending TypeSpec libraries to dev build, but we're using a production release of `@typespec/http-client-csharp` which is using production release of TypeSpec libraries.

We need to build a version of `@typespec/http-client-chsarp` using dev releases of TypeSpec libraries, then bump its version in `autorest.csharp`.

**Comment by pshao25** [comment]
Already fixed.
