### ISSUE TITLE
ModelWriter.WriteExtensibleEnum can generate incorrectly-typed documentation

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/autorest.csharp#5069]
See the following generator source:

https://github.com/Azure/autorest.csharp/blob/5088d5b4a3684d0b3f57e536366d8f20c86183e8/src/AutoRest.CSharp/Common/Generation/Writers/ModelWriter.cs#L432-L433

Note that even when `enumType.ValueType` is not `string`, the generated documentation still refers to a `string`. In the (rare) cases where it isn't a string, it should refer to the actual type (ideally, wrapped in a `see cref` tag.)

**Comment by archerzz** [comment]
Thanks @Arithmomaniac There are quite rare cases that enum value type is not string.
![image](https://github.com/user-attachments/assets/d197baef-9f34-4b5e-9ae3-ac03cec283e5)
