### ISSUE TITLE
InputAuth from per service to per client 

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#5075]
Currently Input auth is [per service](https://github.com/microsoft/typespec/blob/3eed29834600d02c6a1ab3dd039188edf0fb2951/packages/http-client-csharp/emitter/src/type/code-model.ts#L14). Customers have requirement to make it per client. 

For this [channel](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1726596227407?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1726596227407&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1726596227407).

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/4765
