### ISSUE TITLE
--license-header flag isnt working

### ISSUE THREAD

**Issue by gregoks** [Azure/autorest.csharp#5078]
I have tried setting --license-header=none flag to remove the MIT license header from the generated files as described here - https://github.com/Azure/autorest/blob/main/docs/generate/flags.md 

But the flag isnt working. I have tried to set other values for the header but they also dont seem to work.

This is the command line that I have used:

autorest --csharp --input-file="swagger.json" --namespace=Microsoft.My.Client --output-folder="..\Generated" --generate-sample-project=false --generation1-convenience-client --v3 --public-clients --security=AADToken --skip-csproj --license-header=none

**Comment by ArcturusZhang** [comment]
Hi @gregoks according to the document you shared, no generator has implemented this flag.
This flag looks like to have an enum value list, such as MICROSOFT_MIT_NO_VERSION and others.
I do not know the content for those enum values - therefore I will fix this in a different way.
I will itnroduce another flag, maybe `custom-header` to let you specify the content you want to put in each file.
