### ISSUE TITLE
CSharp Emitter should work correctly with no tspconfig file

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#5181]
tspconfig is an optional file, it shouldn't be necessary.  This is the required scenario for un-branded

Please ensure the following steps would not crash the emitter and generate the correct SDK:

tsp init  # Chose generic restapi
tsp install 
npm install @typespec/http-client-csharp
tsp compile . --emit @typespec/http-client-csharp

**Comment by archerzz** [comment]
Not sure if this is a good idea. I think for complex scenario it would be better to have an *anchor* to indicate a project scope. We already have customers asking for extended usage of tspconfig.json: https://github.com/microsoft/typespec/discussions/5213

**Comment by lirenhe** [comment]
I think the extended usage of tspconfig is not the conflict of what want to achieve here.
Of course, we could leverage tspconfig file to support more complex scenarios 
For some simple cases where the config file does not bring any additional value, there is no need to force people to create it with all default value and nothing new.  We never require tspconfig to run an emitter.

**Comment by m-nash** [comment]
- @lirenhe does this not work today?  If not can you paste the error?
- I assume you are doing this with mgc?  I see the issue is opened here and I don't think this is a "goal" for @azure-tools/typespec-csharp but just @typespec/http-client-csharp is this correct?

**Comment by chunyu3** [comment]
Tested and current MGC works without tspconfig file.

**Comment by lirenhe** [comment]
> * [@lirenhe](https://github.com/lirenhe) does this not work today?  If not can you paste the error?
> * I assume you are doing this with mgc?  I see the issue is opened here and I don't think this is a "goal" for @azure-tools/typespec-csharp but just @typespec/http-client-csharp is this correct?

This issue is created to let each SDK owner to verify whether this could work on a clean machine.
Yes, it is targeted for MGC,  I will create related issues in Microsoft/TypeSpec next time.  thanks for the reminder.
