### ISSUE TITLE
Unbranded CodeGen should ignore the generation of unsupported authentications

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#5185]
We should skip the generation of unsupported authentications like below:
Feel free to close this item if we didn't generate anything for them today.

```
@service({
  title: "Todo App",
})
@useAuth(BearerAuth | ApiKeyAuth<ApiKeyLocation.cookie, "session-id">)
```

```
@useAuth(NoAuth)
```

**Comment by jsquire** [comment]
Please move this to the TypeSpec repository and rescope.   We should not be tracking work here.

**Comment by lirenhe** [comment]
Close it as I recreated the issue in https://github.com/microsoft/typespec/issues/5355
