### ISSUE TITLE
Collection properties should be read-only

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#521]
Based on [.NET guidelines for collection properties](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), collection properties should be read-only. The collection may be mutable or not, but the setter should be internal at most.

> I think it's a bit more complicated than that. Some lists are nullable so we have to leave the properties settable but this is something this PR didn't try to address.
>
> _Originally posted by @pakrym in https://github.com/Azure/azure-sdk-for-net/pull/10442_

In these cases, I recommend doing what Key Vault did (I hand-coded much of the serialization): if an empty array is not expected, treat null or empty as null when serializing (though, that really only matters during deserialization, since collection properties can't actually be null).

If there are cases where a collection property should serialize to an empty array, we may need additional markup in swagger or using a class template to denote that.

**Comment by pakrym** [comment]
> In these cases, I recommend doing what Key Vault did (I hand-coded much of the serialization): if an empty array is not expected, treat null or empty as null when serializing (though, that really only matters during deserialization, since collection properties can't actually be null).

There is no way to know `if an empty array is not expected` from a swagger where collection is marked as not required.

**Comment by heaths** [comment]
It would have to be up to the client library to define the behavior, which is what I was suggesting above. .NET guidelines are pretty clear, and the potential for null collection property values are what it's trying to avoid. It would be unfortunate for the customer to have to start checking for null or empty in some libraries for Azure SDK, while not for other libraries or .NET (at least for newer APIs).

**Comment by heaths** [comment]
To note, we should also consider making this lazy using `LazyInitializer.EnsureInitialized`, though maybe that doesn't make sense everywhere. I guess purely based on generated code, it's difficult to tell (at best).

**Comment by heaths** [comment]
We could provide a hint to the serializer to treat empty and null the same, perhaps a boolean property we could set in `CodeGenSchemaMemberAttribute`.

**Comment by heaths** [comment]
This is blocking release. I can't work around this because, even though I can override the fields and make them read-only (no setter), the serialization code still only checks for null and sends an empty array, which Search does not like for fields that should be null/non-existent.

**Comment by heaths** [comment]
While I think most services probably wouldn't want an empty JSON array, I think is safe to assume empty as a default; however, both Key Vault and Search want undefined / unserialized. Since Search uses generated code, I'd like to get a chance for this because we have a lot of models and properties in violation of the .NET guidelines.

What about an attribute (either specific to this purpose, or more general options with this as a property) that can be at the assembly, class, or property level where the lower-scoped one overrides any higher-scoped assembly instance to define the correct behavior, e.g.:

```c#
[CodeGenSerialization(SuppressEmptyCollections = true)]
```

**Comment by heaths** [comment]
Or, if an attribute at any level would be too hard to grok in the generator, perhaps an autorest.md declaration - a default for all source, or can set on models and/or methods.

**Comment by heaths** [comment]
Thanks for the change, but there's still a lot of instances of this for C#. Any thoughts of doing this at the assembly level as well?

**Comment by pakrym** [comment]
I would want to figure out a way to have a better behavior by default for all collection properties that doesn't break the management plane APIs. But not plans to make attributes assembly wide yet.

**Comment by pakrym** [comment]
Requires https://github.com/Azure/autorest.csharp/issues/730

**Comment by pakrym** [comment]
This is my current plan:


# Input

## Required & not-nullable

Needs to be able to send: `[]`, `[items, ...]`

Read-only property initialized with new collection.

``` C#
public IList<int> Collection { get; }
```

## Required & nullable

Needs to be able to send: `[]`, `[items, ...]`, `null`

Read-write property initialized.

``` C#
public IList<int>? Collection { get; set; }
```

## Not-Required & not-nullable

Needs to be able to send: `undefined` (not included in JSON), `[]`, `[items, ...]`

Read-only property initialized with a special collection implementation that tracks `undefined` flag. .

``` C#
public IList<int> Collection { get; }
```

## Not-Required & nullable

Needs to be able to send: `undefined` (not included in JSON), `[]`, `[items, ...]`, `null`

Read-write property initialized with a special collection implementation that tracks `undefined` flag.

``` C#
public IList<int>? Collection { get; set; }
```

# Output

All readonly.

Nullable collections can return null, not nullable collections initialized with special collection implementation that tracks `undefined` flag if property is optional.

**Comment by heaths** [comment]
Overall, I like it. A few comments/questions:

1. For required, the constructor would still take an `IEnumerable<T>`, yes? And assert it as non-null?
2. Perhaps a separate issue/solution, but a follow-up from 1: If minLength >= 1, would you also assert input as non-empty?
3. Does this plan require that `x-nullable` work be done first, or at least enough for teams to update their swaggers (or us to transform it via autorest)?
4. I can't think of a better way (just hacky ways, like sentinel values), but we should make sure with @KrzysztofCwalina that having setters on collection properties so they can be explicitly set to null is fine.
5. How will any of this affect PATCH support, where @johanste indicating an empty collection means "clear the server version" while undefined (absent) means "no change"? Will we just expect/require that swaggers are authored correctly (or fix them up to be), or have some sort of compatibility store?

**Comment by pakrym** [comment]
> 1. For required, the constructor would still take an `IEnumerable<T>`, yes? And assert it as non-null?

Yes, this doesn't change.

> 2. Perhaps a separate issue/solution, but a follow-up from 1: If minLength >= 1, would you also assert input as non-empty?

As a separate issue, yes.

> 3. Does this plan require that `x-nullable` work be done first, or at least enough for teams to update their swaggers (or us to transform it via autorest)?

Not really, default is nullable: false so we get a good behavior by default.

> 4. I can't think of a better way (just hacky ways, like sentinel values), but we should make sure with @KrzysztofCwalina that having setters on collection properties so they can be explicitly set to null is fine.

@KrzysztofCwalina confirmed he's fine with the approach.

> 5. How will any of this affect PATCH support, where @johanste indicating an empty collection means "clear the server version" while undefined (absent) means "no change"? Will we just expect/require that swaggers are authored correctly (or fix them up to be), or have some sort of compatibility store?

I haven't worked through all the scenarios but at least this approach allows up to express all the states that PATCH might required.

**Comment by heaths** [comment]
> I haven't worked through all the scenarios but at least this approach allows up to express all the states that PATCH might required.

I think even if we warned initially, that might suffice until a better store can be created. I worry that we may inadvertently delete user data if someone didn't know or pay attention to this subtle distinction. So, at the very least, maybe keep track of which (if any) operations are "patch" in swagger, and warn if any collection properties are on input models.
