### ISSUE TITLE
Return Response<IList<T>> if response type has a single collection property

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#545]
We have a number of response models in Search that return a model with a single collection property. These are not pageable. We should flatten these when a single array property exists. This is what we do in Key Vault based on guidance from the archboard.

### Method
```json
    "/skillsets": {
      "get": {
        "responses": {
          "200": {
            "description": "The list is successfully returned.",
            "schema": {
              "$ref": "#/definitions/ListSkillsetsResult"
            }
          }
        }
      }
```

### Type

```json
    "ListSkillsetsResult": {
      "properties": {
        "value": {
          "x-ms-client-name": "Skillsets",
          "type": "array",
          "readOnly": true,
          "items": {
            "$ref": "#/definitions/Skillset"
          },
          "description": "The skillsets defined in the Search service."
        }
      },
      "required": [
        "value"
      ],
      "description": "Response from a list Skillset request. If successful, it includes the full definitions of all skillsets."
    }
```

**Comment by heaths** [comment]
I tried putting `x-ms-client-flatten: true` in both the `schema` response element and the `value` property as seen above, but it had no effect: the `ListSkillsetResult` type was still generated and used in the return (`Response<ListSkillsetResult>`) of the `List` and `ListAsync` methods. Also, shouldn't those be `Get`? .NET isn't supposed to use `List` as a prefix.

**Comment by pakrym** [comment]
I think the current guidance is against it as it reduces our ability to evolve APIs

**Comment by heaths** [comment]
That's fine. I was able to work around this by just hiding the type and transforming the results. If someone else wants this later, they can reopen.
