### ISSUE TITLE
CodeGenSchemaAttribute does not let me change class to struct

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#546]
To work around #545 I tried to change the type from a class to a struct to reduce memory overhead since I'm just going to return its sole collection property, but this didn't work:

```csharp
using Azure.Core;

namespace Azure.Search.Models
{
    [CodeGenSchema("ListDataSourcesResult")]
    internal partial struct ListDataSourcesResult
    {
    }
}
```

A `class` was still generated.

**Comment by heaths** [comment]
I think this is important for places we want to wrap models, like `Field` for Search. We don't want to expose it directly, and a `Field` instance of a class would be wasteful.

**Comment by pakrym** [comment]
Dup of https://github.com/Azure/autorest.csharp/issues/452
