### ISSUE TITLE
Discriminating properties should be hidden by default

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#552]
For types that have a discriminator, we should hide the discriminator property itself by default (serves no purpose as a public API once deserialized into an appropriate type).

> It shouldn't be exposed anywhere. `@odata.type` should be used only as a polymorphic discriminator during deserialization (and emitted during serialization).
>
> _Originally posted by @brjohnstmsft in https://github.com/Azure/azure-sdk-for-net/pull/10667_

**Comment by heaths** [comment]
Updated the description to reflect DTs are being deserialized, but we still need to hide the `ODataType` property by default.

**Comment by pakrym** [comment]
Fixed
