### ISSUE TITLE
Allow implementations to replace serialization

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#555]
We have an idea for Search that would use discriminated types for input/output models. For deserializing the type, we'd like to "override" the deserialization to properly instantiate and populate the right type instead of merely wrapping it later.

There are a couple of ways to workaround this, so not high-pri, but would be optimal eventually.

One idea would be to check first if we already implemented `IUtf8JsonSerializable` in a class attributed with `CodeGenSchemaAttribute`. Assuming that's not hard to check, that's probably the easiest to support but maybe not the most robust.

Another way is might be to call into a partial method that we could optionally implement to read properties (without advancing the reader) and return which types (or instances - probably just easier for that code to create them so we don't need factories) to use.

**Comment by allenjzhang** [comment]
I would like to add user may like to access Serialization/Deserialization methods for simpler object construction. Currently marking it internal prevents that.

**Comment by heaths** [comment]
For models we generate from swagger, or for their own models like used with Cosmos DB, Search documents, etc.? Could you clarify the scenario of why a user (did you mean consumer of our SDKs?) should be able to modify it? The ask here was for SDK devs to be able to change de/serialization for when the deafult isn't quite what we want?

**Comment by pakrym** [comment]
I think the original request here is done.
