### ISSUE TITLE
Duplicate constructor generated when customized model has one already

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#582]
I have a few customized models that define a constructor with required parameters. @pakrym recently fixed generating a constructor with required parameters, but if you define one (because, for example, I also check for empty string) one gets generated anyway.

For example, `SearchField.ctor(string name, DataType type)` was already defined by me, but the generator generated one anyway.

*But only* if I don't define a private constructor, which I also had but removed now that the generator was generating ctors with required params.

**Comment by heaths** [comment]
Because of #584 and the order of parameters putting derived types' parameters first, this would have to take order into account as well. I would think that normally devs customizing model ctors would/should keep the parameter names the same, but if for some reason they didn't want to keeping the private ctor might be a viable workaround or, perhaps, more explicit would be an attribute property on `CodeGenSchemaAttribute` to avoid generating any non-serialization ctors.

**Comment by pakrym** [comment]
This should be fixed now.
