### ISSUE TITLE
'CorsRules': member names cannot be the same as their enclosing type

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#599]
**Pavel provided the workaround**: The new generator allows you to rename types/properties change namespaces and accessibility by mapping generated types to a customization types. CodeGenSchema CodeGenSchemaMember attributes in the example above are used for that. Having a property with CodeGenSchemaMember on it instructs generator to use this name instead of the default it picks and resolves the build error

    
**[Erich]**: with previous c# generator, the generated source code could be built successfully without any customization, we prefer to follow same pattern instead of introducing extra customization (smile).

**[Pavel]**: Do you have ideas about how do we make sure someone fixes the name after SDK was generated?

**[Erich]**: 
    IMO, the name customization is nice to have instead of must to have. If it is must to have, I suggest to improve C# generator to avoid the customization. I'm not sure whether python/java generators have same issue

**Comment by allenjzhang** [comment]
@Pavel, while the full customization should be there to give override options, we should still generate out of box that works without requiring manual touch. I suggest we use **Value** suffix to the same name property.  So CorsRules will have CorsRulesValue { get; set}. It is less than Ideal name, but should be more acceptable that Value { get; set;}.
