### ISSUE TITLE
Constructor with same parameter types and names was generated

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#600]
I had a few model types - derived types from a base type in swagger, if that matters - that already had a constructor with a signature like, `public MagnitudeScoringFunction(string fieldName, double boost, MagnitudeScoringParameters parameters)`, but the generator generated one that was the same, except private (so it apparently saw mine, or it'd been public I imagine).

I had the constructor defined prior to your fix for #584 but still want it since there are strings I want to check for null *or empty*.

I'm also unable to work around this with `CodeGenSuppressAttribute` because of another bug.

**Comment by pakrym** [comment]
Fixed.
