### ISSUE TITLE
generator doesn't respect namespace specified in readme.csharp.md

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#604]
If we don't specify --namespace parameter during running autorest csharp generator, it doesn't respect namespace specified in readme.csharp.md, e.g. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.csharp.md, it generates code with namespace **Sample**

**Comment by pakrym** [comment]
You are not supposed to be running autorest directly, the GenerateCode target would take care of the namespace.

**Comment by pakrym** [comment]
Closing by design.
