### ISSUE TITLE
CSharp codegen for management plane should create single RP level client to wrap the various entity clients

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#616]
As it stands right now, each entities gets a XXXClient. The more intuitive approach is to have a single RPClient. Then call RPClient.XXEntity.CRUD(). 

Feature request, for ARM management codegen path, RPClient.cs should be generated.

**Comment by pakrym** [comment]
Done

**Comment by erich-wang** [comment]
@pakrym , I just verified and found the fixed is not in latest release 4.17.2, so I reopen this issue for track purpose, thanks.

**Comment by pakrym** [comment]
Please make sure you set `azure-arm: true` in the autorest.md
