### ISSUE TITLE
Failed to generate track 2 mgmt sdk for Compute

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#637]
EXEC : error (): Duplicate object schemas with 'InstanceViewStatus' name  detected. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]

EXEC : error (): Duplicate object schemas with 'Resource' name  detected. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]

EXEC : error (): Duplicate object schemas with 'CloudError' name  detected. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]

EXEC : error (): Duplicate object schemas with 'ApiError' name  detected. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]

EXEC : error (): Duplicate object schemas with 'ApiErrorBase' name  detected. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]

EXEC : error (): Duplicate object schemas with 'InnerError' name  detected. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]
  [71.86 s] Generation Complete
C:\AME\erich-net-sdk\eng\CodeGeneration.targets(29,5): error MSB3073: The command "npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6207/autorest-3.0.6207.tgz --version=3.0.6257 C:\AME\azure-rest-api-specs\specification\compute\resource-manager\readme.md --require=C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200402.6/autorest-csharp-v3-3.0.0-dev.20200402.6.tgz --output-folder=C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src --title=Azure.Management.Compute --namespace=Azure.Management.Compute --shared-source-folder=C:\AME\erich-net-sdk\eng\../sdk/core/Azure.Core/src/Shared/ --verbose" exited with code 6. [C:\AME\erich-net-sdk\sdk\compute\Azure.Management.Compute\src\Azure.Management.Compute.csproj]

**Comment by pakrym** [comment]
Dup: https://github.com/Azure/autorest.modelerfour/issues/241
