### ISSUE TITLE
Failed to generate track 2 mgmt sdk for Monitor

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#639]
EXEC : error (): Duplicate object schemas with 'ErrorResponse' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'Resource' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'RetentionPolicy' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'ProxyOnlyResource' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'LocalizableString' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'EventDataCollection' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'EventData' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'SenderAuthorization' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'HttpRequestInfo' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

EXEC : error (): Duplicate object schemas with 'Baseline' name  detected. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]
  [40.76 s] Generation Complete
C:\AME\erich-net-sdk\eng\CodeGeneration.targets(29,5): error MSB3073: The command "npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6207/autorest-3.0.6207.tgz --version=3.0.6257 C:\AME\azure-rest-api-specs\specification\monitor\resource-manager\readme.md --require=C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200402.6/autorest-csharp-v3-3.0.0-dev.20200402.6.tgz --output-folder=C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src --title=Azure.Management.Monitor --namespace=Azure.Management.Monitor --shared-source-folder=C:\AME\erich-net-sdk\eng\../sdk/core/Azure.Core/src/Shared/ --verbose" exited with code 10. [C:\AME\erich-net-sdk\sdk\monitor\Azure.Management.Monitor\src\Azure.Management.Monitor.csproj]

**Comment by pakrym** [comment]
Dup: https://github.com/Azure/autorest.modelerfour/issues/241
