### ISSUE TITLE
Failed to build generated track 2 mgmt sdk source code for KeyVault

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#640]
Generated\Models\AccessPolicyEntry.Serialization.cs(62,54): error CS0117: 'Permissions' does not contain a definition for 'DeserializePermissions' [C:\AME\erich-net-sdk\sdk\keyvault\Azure.Management.KeyVault\src\Azure.Management.KeyVault.csproj]

**Comment by pakrym** [comment]
Dup: https://github.com/Azure/autorest.modelerfour/issues/249
