### ISSUE TITLE
null coalescing operator ?? could not apply to struct causing compilation OR incorrect enum type generation.

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#649]
Direct error behavior is a few instances of ?? operator with struct. FirewallPolicyRuleConditionType  is a struct wraps around a string value. 

            FirewallPolicyRuleConditionType RuleConditionType = ruleConditionType ?? "NetworkRuleCondition";  // <---

        /// <summary> Initializes a new instance of FirewallPolicyRule. </summary>
        /// <param name="ruleType"> The type of the rule. </param>
        /// <param name="name"> The name of the rule. </param>
        /// <param name="priority"> Priority of the Firewall Policy Rule resource. </param>
        internal FirewallPolicyRule(FirewallPolicyRuleType ruleType, string name, int? priority)
        {
            RuleType = ruleType ?? null;   // <----
            Name = name;
            Priority = priority;
        }

However, looking at the swagger, type is really should have been enum.

        "ruleConditionType": {
          "type": "string",
          "description": "Rule Condition Type",
          "enum": [
            "ApplicationRuleCondition",
            "NetworkRuleCondition"
          ],
          "x-ms-enum": {
            "name": "FirewallPolicyRuleConditionType",
            "modelAsString": true
          }

**Comment by pakrym** [comment]
Fixed
