### ISSUE TITLE
[P1] Missing AzureResourceProviderNamespaceAttribute

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#685]
All diagnostic scopes should have 'az.namespace' attribute, make sure the assembly containing **ClientOptions type is marked with AzureResourceProviderNamespaceAttribute.

Since AzureResourceProviderNamespaceAttribute is required, suggest to generate it automatically.

**Comment by pakrym** [comment]
I don't think the correct value is defined in the swagger so the generator is not able to generate it.
