### ISSUE TITLE
[P0] Generated code should not set read-only properties using object initializer syntax

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#687]
c# generator version: 20200417.2
configuration: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/readme.md

Error	CS0200	Property or indexer 'GroupCreateParameters.MailEnabled' cannot be assigned to -- it is read only	Azure.Graph.Rbac (netstandard2.0)	C:\AME\erich-net-sdk\sdk\graphrbac\Azure.Graph.Rbac\src\Generated\Operations\GroupsRestClient.cs	365	Active
```
            var model = new GroupCreateParameters(displayName, mailNickname)
            {
                MailEnabled = mailEnabled,
                SecurityEnabled = securityEnabled
            };
```

**Comment by pakrym** [comment]
Can't repro this issue with latest generator, can you verify if it still exists?

**Comment by erich-wang** [comment]
erich to verify

**Comment by erich-wang** [comment]
Verified that this was fixed.
