### ISSUE TITLE
[P1] Incorrect DiagnosticScope for long running operation

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#691]
For long running operation, e.g.  StartCreateOrUpdateAsync -> CreateOrUpdate, the diagnostic scope is set as **CreateOrUpdate**, however the expected one in DiagnosticScopeValidatingInterceptor is **StartCreateOrUpdate**

**Comment by erich-wang** [comment]
Per Pavel, could use **TestDiagnostics = false;** to work around

**Comment by MiYanni** [comment]
@erich-wang The diagnostic scopes have been moved to the public client. So, it should be part of `Start` methods now. Let me know if this is still an issue.

**Comment by pakrym** [comment]
Should be fixed now.
