### ISSUE TITLE
Long running operation: Polling serialization (resume polling functionality)

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.csharp#697]
This allows the polling state to be serialized. Right now, we just have a placeholder for ID:
https://github.com/Azure/autorest.csharp/blob/87ebcaef03def90023718a836ff41825a2579daa/src/assets/Generator.Shared/ArmOperationHelpers.cs#L149-L150

We would have to properly construct this ID so we can resume polling.

**Comment by pakrym** [comment]
API Impact additive.

**Comment by AlexanderSher** [comment]
Closing in favor of https://github.com/Azure/autorest.csharp/issues/2158
