### ISSUE TITLE
[P1: Bug] Duplicate Enum type generated in Compute  

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#700]
Swagger: 
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/compute.json

        private const string **StandardGS4Value** = "Standard_GS4";
        private const string **StandardGS4Value** = "Standard_GS4-4";

**Comment by pakrym** [comment]
M4 bug https://github.com/Azure/autorest.modelerfour/issues/275

**Comment by MiYanni** [comment]
Retest in: https://github.com/Azure/autorest.csharp/pull/732

**Comment by pakrym** [comment]
Fixed
