### ISSUE TITLE
[P0] Name should be settable for Resource

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#718]
In the case below, the `EncrptionScope` could be used as input parameter, however there's no way to set Name as it is readonly and constructor is internal

![Encrption](https://user-images.githubusercontent.com/20198527/80697277-55497500-8b0b-11ea-852e-837b95046c99.png)

**Comment by pakrym** [comment]
Can you please give more context about this issue? At least what swagger file is this.

**Comment by pakrym** [comment]
Resource.Name is defined as readonly in swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L17 but is also not defined as required.

**Comment by pakrym** [comment]
Verified this is by design. Resource name is passed into a Create* method and resources can not be renamed.
