### ISSUE TITLE
[P0] Support multiple tags in autorest.md

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#724]
Microsoft.Resources (Resource manager) management SDK requires multiple package tags in order to build the [SDK library.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/resources/Microsoft.Azure.Management.Resource/src/generate.ps1)

While the autorest.md seems only support single tag reference in Track2 generation, how can I get autorest to support this scenario? 

Thanks

**Comment by pakrym** [comment]
We figured out how to get library generated with a single invocation.
