### ISSUE TITLE
Handle multipart/form-data

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.csharp#734]
Awaiting `multipart/form-data` implementation: https://github.com/Azure/autorest.modelerfour/issues/28

Related: https://github.com/Azure/autorest.csharp/issues/306
Related: https://github.com/Azure/autorest.csharp/issues/200
Related: https://github.com/Azure/autorest.csharp/issues/157

**Comment by pakrym** [comment]
Dup https://github.com/Azure/autorest.csharp/issues/662 ?

**Comment by MiYanni** [comment]
Yeah. That is the same issue. Currently, I'm marking all the smoke tests with this issue number, so I'll do the same for that one. There are a bunch that fail because of this.
