### ISSUE TITLE
Should we default to long for integer types?

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#744]
Spec doesn't define that integer type is int32 .

**Comment by pakrym** [comment]
Blocked by https://github.com/Azure/autorest.modelerfour/issues/288

**Comment by ShivangiReja** [comment]
From https://github.com/Azure/autorest.modelerfour/issues/288#issuecomment-649063965 -

>I just read back over the initial conversation that @pakrym linked in the issue description. It sounds like there isn't anything actionable to do in AutoRest/Modelerfour at this moment, correct?

>@johanste's proposal was mainly to add a linting rule (which @lmazuel filed a request for) and gradually get all service Swaggers to explicitly specify the format for each usage of integer. I got the impression that we want to hold off on making int64 the default for now since that might be an unexpected change for service teams (and SDK library users).
