### ISSUE TITLE
The parameter name `host` RPManagementClient.cs ctor is too generic

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#766]
With name like `host` could led someone to think that should it be just the host name. It is unclear to caller whether it is a full URL and whether it should include scheme "https://" or not. Also what if some env URL that may have segments. 

I think indicating it is an Endpoint or URL seems more fitting. What about these suggestions. 
          * Uri managementEndpoint

**Comment by pakrym** [comment]
renamed to `endpoint`

**Comment by ArthurMa1978** [comment]
After re-design this has been fixed
