### ISSUE TITLE
Per-request parameter not taken at method level depending on definition

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/autorest.csharp#771]
**Describe the issue or request**
For the autorest v3: I'm working on a swagger file that defines a per-request parameter of an if-match header, but the if-match value can only be passed to the client at constructor time, not per request. I have a zip file attached with two json files that demonstrate this issue. 

In the "swaggerFails.json", the rest client gets generated like the below

```csharp
private string host;
private string ifMatch;
private ClientDiagnostics _clientDiagnostics;
private HttpPipeline _pipeline;

public SomeOperationRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string host = "", string ifMatch = null) { //saves the ifMatch at the class level }

// The instance method doesn't take the if-match header, but does use the one provided at the constructor level
public virtual Response Delete(string id, CancellationToken cancellationToken = default)
```

With a small change to the swagger file such that the parameter isn't factored out to the parameters section, I made "swaggerWorks.json"

With this edited swagger, the rest client now looks like the below:

```csharp
private string host;
private ClientDiagnostics _clientDiagnostics;
private HttpPipeline _pipeline;

/// <summary> Initializes a new instance of SomeOperationRestClient. </summary>
public SomeOperationRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string host = "") 
{ //no ifMatch at client level }

// Per method ifMatch headers, as expected
public Response Delete(string id, string ifMatch = null, CancellationToken cancellationToken = default) { ... }
```

The only difference between the two swagger files is how the parameter is referenced, which I wouldn't expect to cause this kind of code discrepancy.

```
                "parameters": [
                    {
                        "$ref": "#/parameters/Id"
                    },
                    {
                        "name": "If-Match",
                        "in": "header",
                        "description": "Only perform the operation if the entity's etag matches one of the etags provided or * is provided.",
                        "required": false,
                        "type": "string"
                    }
                ],
```

vs

```
                "parameters": [
                    {
                        "$ref": "#/parameters/Id"
                    },
                    {
                        "$ref": "#/parameters/if-match"
                    }
                ],
```

I encountered this bug working with the track 2 code generator for Azure SDKs, but that generator uses autorest v3, from what I understand. Is this expected behavior?

[swaggerFiles.zip](https://github.com/Azure/autorest.csharp/files/4636516/swaggerFiles.zip)

**Comment by MiYanni** [comment]
@timtay-microsoft 
You are missing the `"x-ms-parameter-location": "method"` for `if-match` when you have it defined in the global parameters list. You have it there for `Id` but not for `if-match`. When a parameter is defined in the global parameters list, it defaults to `client`. See documentation here:
https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-parameter-location

Please let me know if this has resolved the problem so I can close this issue. Thank you!

**Comment by timtay-microsoft** [comment]
That does seem to do the trick! Thanks, I'll close this issue
