### ISSUE TITLE
Ignore (do not generate) operation parameters for x-ms-client-request-id

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#782]
Based on https://github.com/Azure/azure-sdk-for-net/issues/11273, if swagger contains an `x-ms-client-request-id` parameter (or maybe any parameter marked as `"x-ms-client-request-id": true` in its definition), do not generate a parameter for it since we'll just have to pass null for it anyway and time is wasted checking for it, if not making the assembly a little larger.

**Comment by pakrym** [comment]
And tracestate/traceparent
