### ISSUE TITLE
[P0] Incorrect datetime format in request

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#787]
**Describe the issue or request**
One change in [TypeFormatters.cs](https://github.com/Azure/azure-sdk-for-net/pull/11860/files#diff-3d9ef10043ed0ff2a49101184a3322c4) causes date format change and leads to error: **Values for request parameters are invalid: signedExpiry, signedStart.**

Before change which worked well:
![p1](https://user-images.githubusercontent.com/20198527/82830299-e8e24b80-9ee7-11ea-8628-dd8f8de412d5.png)
After change:
![p2](https://user-images.githubusercontent.com/20198527/82830716-1380d400-9ee9-11ea-90d7-636caff9a619.png)

**Comment by pakrym** [comment]
These are equivalent values by specification, what service is this?

**Comment by giuliohome** [comment]
Hi all.
There is still a problem, we have to use

```go
currentTime.Format("2006-01-02T03:04:05.9999999Z")
```
instead of
```go
currentTime.Format(time.RFC3339Nano)
```
because now the format shows 8 decimal digits instead of 7
