### ISSUE TITLE
Add NuGet config to the repository

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#820]
We've seen some flaky builds that fail to restore. Wes suggested adding a `nuget.config`:

Wes Haggard
> looking through the repo I don't see a nuget.config explicitly in the repo, I'd suggest adding one to the root of the repo. I'm not sure why this fails sometimes but it is interesting that you are hitting this failure while restoring your autorest projects and it is looking at our blob feed which as far as I can tell isn't configured in that repo. I wonder if the nuget.config is leaking from somewhere else. 

> As for the blob feeds I've not seen similar issues around them so I wouldn't send much time on that front esspecailly given we are moving away from them and moving to DevOps feeds for our repos. 
    
> I'd suggest removing 
> https://github.com/Azure/autorest.csharp/blob/feature/v3/Directory.Build.props#L7 as well. If you still need a dev package from the language try adding the devops feed to your nuget.config. Like https://github.com/Azure/azure-sdk-for-net/blob/master/NuGet.Config#L8

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/autorest.csharp/pull/823
