### ISSUE TITLE
Ability to generate unused model types as public

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#836]
In Event Grid, there are about 100 [public model types](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventgrid/data-plane) that define event schemas for different system events. There are no operations defined with these types, but they are meant to be exposed so that customers can deserialize into these strongly typed models. The C# generator is generating all of these as internal, apparently because they are not used. I believe we can fix this by adding a CodeGen attribute to each of these classes, but I'm not sure this is the right solution given the number of types.

**Comment by JoshLove-msft** [comment]
@kerri-lee can you give the details for the model types that `x-accessibility` doesn't work for?

**Comment by kerri-lee** [comment]
`DeviceTwinInfoProperties`, `DeviceTwinInfoX509Thumbprint`, and `WebAppServicePlanUpdatedEventDataSku` are all generated as internal types.

**Comment by pakrym** [comment]
I think we solved this particular problem in a different way.
