### ISSUE TITLE
Add ability to deserialize model types that are not used as part of any operations

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#840]
In Event Grid, there are a bunch of model types that are output only which correspond to system event payloads (the Data property of an EventGridEvent). There are no operations defined in the swagger for these types, but we want to offer code in the SDK that can deserialize these payloads into the model types. In Track 1, this [code](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Microsoft.Azure.EventGrid/src/Customization/EventGridSubscriber.cs#L173) was hand-written. One issue with doing this in Track 2, is that we can't define the JsonProperty attributes to map the Json property to the model type property, as this is a NewtonSoft.Json feature.

It would be great if the code generator were able to generate this deserialization code for us. Absent that, we will need some guidance on how to define the mapping between Json property and model type property - it seems that the Json property is always just the camelCase of the model type property, but I'm not sure if this is an assumption we want to bake into the SDK. Finally, we will need a way to be able to generate public model types for all of the models. The workaround mentioned in https://github.com/Azure/autorest.csharp/pull/837 does not work for all model types (e.g. `DeviceTwinInfoProperties`).

**Comment by ellismg** [comment]
Just to confirm my understanding, it would be expected that when decoding system events, we'd always use types from `System.Text.Json` to decode them right?  We wouldn't want to use the generalized `ObjectSerializer` stuff in this case, is that right?  Or is the expectation that if the user provides a custom object serializer that is also used to deserailize the data object, event for system events?

**Comment by JoshLove-msft** [comment]
> Just to confirm my understanding, it would be expected that when decoding system events, we'd always use types from `System.Text.Json` to decode them right? We wouldn't want to use the generalized `ObjectSerializer` stuff in this case, is that right? Or is the expectation that if the user provides a custom object serializer that is also used to deserailize the data object, event for system events?

That is my understanding as well - `ObjectSerializer` would not be used for system events. The system schemas are generally just primitive properties so I don't see much value to exposing this ability to customers. Our hope is that we will be able to generate the system event deserialization code which will be using System.Text.Json.

**Comment by kerri-lee** [comment]
[Here](https://github.com/Azure/azure-sdk-for-net/pull/13583) our current workaround for generating deserialization code.

**Comment by JoshLove-msft** [comment]
@pakrym Is there a way to get the generated models to be attributed with [JsonPropertyName](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=netcore-3.1)? This appears to be the equivalent of the NewtonSoft JsonProperty attribute.
If this works, I don't think we would need to rely on generated deserialization code.

**Comment by pakrym** [comment]
>@pakrym Is there a way to get the generated models to be attributed with JsonPropertyName? This appears to be the equivalent of the NewtonSoft JsonProperty attribute.

Nope, there is none. Because JsonSerializer features were not enough to cover swagger scenarios we've opted to fully generate our serialization code.
