### ISSUE TITLE
Autorest generated C# code validate optional properties even it's null, which make validation fail

### ISSUE THREAD

**Issue by blueww** [Azure/autorest.csharp#885]
**Describe the issue or request**
Please describe the issue or feature request.

Storage team recently have new feature have [swagger change](https://github.com/Azure/azure-rest-api-specs-pr/pull/1104) as following.
The autorest generated C# code from it with always fail in validation, when any of the optional properties is null.
Since the properties are optional, we should skip validate if it’s null.

Swagger:
```json
    "DateAfterModification": {
      "properties": {
        "daysAfterModificationGreaterThan": {
          "type": "number",
          "multipleOf": 1.0,
          "minimum": 0,
          "description": "Value indicating the age in days after last modification"
        },
          "daysAfterLastAccessTimeGreaterThan": {
            "type": "number",
            "multipleOf": 1.0,
            "minimum": 0,
            "description": "Value indicating the age in days after last blob access. This property can only be used in conjuction with last access time tracking policy"
        }
      },
      "description": "Object to define the number of days after object last modification Or last access. Properties daysAfterModificationGreaterThan and daysAfterLastAccessTimeGreaterThan are mutually exclusive"
    },
```

Generated C# code:
The generated C# code to validate this item will be following (with autorest 2.0.4413, 3.0.6306)
Please note the validation will fail when any of DaysAfterModificationGreaterThan or DaysAfterLastAccessTimeGreaterThan is null (null %1 = null, null != 0). But since both properties are optional, null should be a valid value for the 2 properties.
```c#
        public virtual void Validate()
        {
            if (DaysAfterModificationGreaterThan < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "DaysAfterModificationGreaterThan", 0);
            }
            if (DaysAfterModificationGreaterThan % 1 != 0) // ensures that the value is a multiple of 1.0
            {
                throw new ValidationException(ValidationRules.MultipleOf, "DaysAfterModificationGreaterThan", 1);
            }
            if (DaysAfterLastAccessTimeGreaterThan < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "DaysAfterLastAccessTimeGreaterThan", 0);
            }
            if (DaysAfterLastAccessTimeGreaterThan % 1 != 0)
            {
                throw new ValidationException(ValidationRules.MultipleOf, "DaysAfterLastAccessTimeGreaterThan", 1);
            }
        }
```

**Describe your ideas for solutions**
Please describe how you think a change or changes might work. Consider
how these changes might work for multiple services.

Suggested change:
Autorest generated code should first check if the value is null or not, and only do validation when it’s not null, like:
```c#
  if (DaysAfterModificationGreaterThan != null && DaysAfterModificationGreaterThan % 1 != 0) // ensures that the value is a multiple of 1
  {
    throw new ValidationException(ValidationRules.MultipleOf, "DaysAfterModificationGreaterThan", 1);
  }
```

**Add labels**
As appropriate, select a label to describe how hard the issue is to work
around or how hard it would be to do without a particular feature that
could help make it easier. These labels start with "workaround".

Not workaround now, until remove the validation from swagger.

Also select a label that describes how many instances of the workaround
you would have to do without the bug being fixed or feature implemented.
These labels start with "instances".

These labels will help priority bug fixes and feature requests.

If this bug or feature request is for older versions of autorest, please
remove the v3 label and add the v2 label as appropriate.

**Comment by ShivangiReja** [comment]
Hi @blueww, thank you so much for filing the issue. We have published a preview version [here](https://www.npmjs.com/package/@microsoft.azure/autorest.csharp/v/2.3.90) to fix this issue. Please try to generate code using `autorest --csharp --use:@microsoft.azure/autorest.csharp@2.3.90  [...] ` version and let us know if you see any issue.

**Comment by ShivangiReja** [comment]
@blueww Thank you so much for filing the issue!

We have published a preview version- [@microsoft.azure/autorest.csharp/v/2.3.90](https://www.npmjs.com/package/@microsoft.azure/autorest.csharp/v/2.3.90) with the fix for this issue. Please try to generate code using `autorest --csharp --use:@microsoft.azure/autorest.csharp@2.3.90 [...]` and let us know if you see any issue.

**Comment by blueww** [comment]
I have tried to regerante .net SDK code with the preview version autorest, and it works well, this issue is resolve in the preview version.

Would you please help to release it, and apply it to .net SDK generated in https://github.com/Azure/azure-sdk-for-net?

**Comment by ShivangiReja** [comment]
It's entirely manual. So, you would need to do the following -
* Reset the autorest versions by running `autorest --reset`  command 
* Run the generation

For more about versioning refer these docs:
* https://github.com/Azure/autorest#generators
* https://github.com/Azure/autorest/blob/master/docs/autorest-versioning.md

**Comment by ShivangiReja** [comment]
Hi @blueww, I'm closing this issue. Please open a new issue if you have any further questions or find any other bugs in the preview.
