### ISSUE TITLE
Omit "gets or sets"

### ISSUE THREAD

**Issue by deastr** [Azure/autorest.csharp#903]
Is it possible to have an option to omit "gets or sets" text from model properties? Our documentation is not in English so having "gets or sets" text with them looks weird.

**Comment by chamons** [comment]
From what I can tell, the only code generated with the text "gets or sets" is https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Mgmt/Generation/ResourceWriter.cs#L47 (There are 2 usages in CodeGenModelAttribute which is shared code and one internal to autorest.csharp).

That makes this a Mgmt bug - FYI @m-nash

**Comment by ArthurMa1978** [comment]
@deastr could you help to provide more information or samples?

**Comment by deastr** [comment]
I haven't worked with AutoRest for a while but AFAIK it was something like this: if your properties are non-English they look like "Gets<non-English-word>" when  they are generated. I was asking if it's possible to generate without the Gets/Sets prefix.

**Comment by ArthurMa1978** [comment]
The AutoRest is not intended to handle globalized text, and we expect that property / variable names will be in English.
So close this issue as by design.
