### ISSUE TITLE
Backport to PS 6 for Ubuntu 20.04 support

### ISSUE THREAD

**Issue by bquantump** [Azure/autorest.csharp#918]
**Describe the issue or request**
PS is not supported on Ubuntu 20.04 and it is not clear when this will be the case

**Describe your ideas for solutions**
Back port scripts to PS 6 or use another language for the scripts

**Comment by pakrym** [comment]
I would prefer a backport. We have other powershell scripts and I would like to avoid an extra tool requirement.

**Comment by bquantump** [comment]
> I would prefer a backport. We have other powershell scripts and I would like to avoid an extra tool requirement.

This is fine. Although, I do wonder the powershell's team commitment to Linux and canonical in the long term given the current lapse here.
