### ISSUE TITLE
Generator uses uppercase parameter name when using a field instead of a property

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#925]
@pakrym, it's not an issue, but I found this unusual with the generator. When I changed to using a field, the parameter name casing was changed to PascalCase. Still internal/private accessibility, so not a problem.

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/pull/15950#discussion_r504894819_

**Comment by AlexGhiondea** [comment]
Closing for now. We can revisit this if this continues to be an issue.
