### ISSUE TITLE
Support Swagger outside the Azure SDK for AutoRest v3

### ISSUE THREAD

**Issue by seaki-msft** [Azure/autorest.csharp#960]
**Describe the issue or request**
We are using AutoRest in our [repo](https://github.com/Azure/Connectors) to translate swagger files into c#. However, we ran into several issues running AutoRest V3 because swaggers outside the Azure SDK is not supported in AutoRest v3. We use connectors swagger files and here is the [list of swagger files](https://github.com/Azure/Connectors/tree/preview/sdk/swaggers/ms-services/released). Is there a plan to support swaggers outside the Azure SDK in v3?

**An example of error**
Input: [AzureAD swagger file](https://patip2001wus8.blob.core.windows.net/api-swagger-files/tip2/azuread.json_original?sv=2018-03-28&sr=b&sig=RFUKzWf9ZrpZPuH7PlPUhipozFoc%2BmHyhIF75kqDtOc%3D&se=2020-12-17T20%3A22%3A13Z&sp=r)
```
node.exe : FATAL: Error parsing swagger file. Unexpected character encountered while parsing value: [. Path 'components.schemas.schemas:114.default', line 1, position 82534.
At C:\Users\seaki\AppData\Roaming\npm\autorest.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/autorest/entrypoints/app.js" $ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FATAL: Error pa...position 82534.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
```

**Add labels**
v3

**Comment by pakrym** [comment]
This issue is currently being worked on 

cc @ShivangiReja

**Comment by ShivangiReja** [comment]
We have added support to use V3 generator outside of azure-sdk-for-net repo. Please refer [these](https://github.com/Azure/autorest.csharp#use-outside-of-the-azure-sdk-net-repo) docs to generate code.

We have also updated the default generator used by autorest --csharp to the new version V3, which uses @autorest/csharp package.
