### ISSUE TITLE
XML comment on Enums

### ISSUE THREAD

**Issue by deaktomi** [Azure/autorest.csharp#963]
**Describe the bug**
When I create an enum in my swagger.json, something like this:
```
"MyType": {
  "description": "My own description about the values.\r\n'value1': Description about value1\r\n'value2': Descripiton about value2",
  "enum": [
	"value1",
	"value2",
  ],
  "type": "string"
},
```
I get the following csharp XML comments for a method that has a `MyType` parameter:

> Gets or sets possible values include: 'value1', 'value2'

**Expected behavior**
I believe it should be something like this:

> Gets or Sets my own description of the values.\r\n'value1': Description about value1\r\n'value2'

Can it be achieved somehow?

**Comment by chamons** [comment]
Hey @deaktomi 

I took a look at what we generate today, and this is what I see:

[Usage](https://github.com/chamons/autorest.csharp/blob/enum_comments/test/TestProjects/Enums/Generated/EnumsClient.cs#L57-L59):

```
        /// <param name="body"> The MyType to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response Operation(MyType? body = null, CancellationToken cancellationToken = default)
        {
```

[Defination](https://github.com/chamons/autorest.csharp/blob/enum_comments/test/TestProjects/Enums/Generated/Models/MyType.cs#L13-L20)

```
    /// <summary>
    /// My own description about the values.
    /// 
    /// &apos;value1&apos;: Description about value1
    /// 
    /// &apos;value2&apos;: Descripiton about value2.
    /// </summary>
    public readonly partial struct MyType : IEquatable<MyType>
```

And this is what it looks like in the IDE autocomplete:

![image](https://user-images.githubusercontent.com/6392201/115082365-6e3d6880-9ecb-11eb-8276-37239c75e643.png)

At least in VS the autocomplete does not respect new lines:

![image](https://user-images.githubusercontent.com/6392201/115083911-beb5c580-9ecd-11eb-9c5d-ec65cbc6b1d8.png)

so I don't think adding in depth enum documentation there will be readable once you have more than 3 or 4 lines.

Thoughts?

**Comment by chamons** [comment]
It has been over 2 weeks without the needed feedback. 

Please reopen with details if this is still an issue.
