### ISSUE TITLE
How to use autorest.csharp.v3 when use Start-AutoRestCodeGeneration command?

### ISSUE THREAD

**Issue by ChenglongLiu** [Azure/autorest.csharp#974]
I'm using the Start-AutoRestCodeGeneration command to generate our services' Azure SDK. There are some params defines like below in our swagger file

```
      "allOf": [
        {
          "$ref": "#/definitions/BaseClass"
        },
        {
          "$ref": "#/definitions/SomeProperties"
        }
```

[Inheritance.json](https://github.com/Azure/autorest.csharp/blob/624d38c1c67e5205b972445dcfb061064e89ecff/test/TestProjects/Inheritance/Inheritance.json#L71)

I found the [PR](https://github.com/Azure/autorest.csharp/pull/636/files#diff-8d7ac27baa716241430369df209de3f2ea2cba6551da7d0576ba02e483e61d80) add multiple inheritance feature to V3 branch. Is it useable in Start-AutoRestCodeGeneration command?

**Comment by chamons** [comment]
Yes, [this](https://github.com/Azure/autorest.csharp/pull/636/files#diff-8d7ac27baa716241430369df209de3f2ea2cba6551da7d0576ba02e483e61d80 ) suggests that allOf would work.

However, without trying the specifics it is difficult to know for sure. 

The best way to check would to generate a swagger and then review the generated code for cases like this.
