### ISSUE TITLE
Generator ignores "required": false on stream parameters

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/autorest.csharp#989]
**Describe the issue or request**
Generator ignores "required": false on stream parameters

https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.FileStorage/preview/2020-04-08/file.json#L6099

Is generating to:

https://github.com/seanmcc-msft/azure-sdk-for-net/blob/feature/storage/migrateFilesToNewGenerator/sdk/storage/Azure.Storage.Files.Shares/src/Generated/FileRestClient.cs#L942

**Comment by pakrym** [comment]
https://github.com/Azure/autorest/issues/3798
